### ISSUE TITLE
Possibility to show / edit blob container metadata

### ISSUE THREAD

**Issue by rolandkru** [microsoft/AzureStorageExplorer#2316] opened 2019-11-22 07:57 UTC
It would be great to have a possibility to show and edit custom blob container metadata in azure storage explorer. For example an additional tab in the lower left corner.

This is possible via Azure Portal.

**Comment by MRayermannMSFT** [comment] 2019-11-25 19:07
Duplicate of  #756

**Closed by MRayermannMSFT** 2019-11-25 19:07 UTC
Labels: :bulb: feature request
