### ISSUE TITLE
There is a 'Loading all items for global sort' notification when opening one table explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7380] opened 2023-10-07 08:56 UTC
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20231007.7
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open 'Settings' -> Click 'Data Explorers' -> Make sure the 'Load All' is checked. 
2. Expand one storage account -> Tables.
3. Open one table.
4. Check there is no 'Loading all items for global sort' notification.

## Expected Experience ##
There is no 'Loading all items for global sort' notification.

## Actual Experience ##
There is a 'Loading all items for global sort' notification.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/539d133d-5be8-45d6-8a86-6ec6b404360f)

**Comment by craxal** [comment] 2023-10-09 16:45
The notification should be shown. We should just reword the message.

**Comment by craxal** [comment] 2023-10-11 21:41
Merged a fix for tables as well as files. We needed to update some telemetry as well.

**Comment by v-xianya** [comment] 2023-10-12 02:50
@craxal 
Verified this issue on the main build 20231012.2. The notification has been updated to (Load all items).  

With setting 'Load All' enabled:

1. For blob and file explorer, the notification 'Load all items....' will show if clicking 'Load more'.
2. For tables, the notification 'Load all items....' will show once the table opens. even for one empty table.
Could you help to take a look?

**Comment by craxal** [comment] 2023-10-12 17:04
Both of those sound like that is expected behavior, because the explorer is trying to load all items. Does something seem odd about that?

**Comment by v-xianya** [comment] 2023-10-13 01:56
@craxal 
For table explorer.
If disable 'Load All', open one table, it loads 1000 cached items, clicking 'Load more' will load next batch.
If enabled 'Load All', open one table, it tries to load all available items even if not click 'Load more'. In this case I think it should only try to load all available items after clicking "Load more".

**Comment by craxal** [comment] 2023-10-13 18:46
@v-xianya I think you're right, only the first batch should show when the table opens. I have a fix for that already in the works.

**Closed** 2023-10-14 00:23 UTC
Labels: :heavy_check_mark: merged, 🧪 testing, :gear: tables

**Comment by v-xianya** [comment] 2023-10-16 02:49
Verified this issue on rel build 20231014.5. Fixed.
The notification 'Load all items' will only show after clicking "Load more" with 'Load All' enabled.
