### ISSUE TITLE
Add the word 'a' to the log message 'Successfully added new connection'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1860] opened 2019-09-17 09:53 UTC
**Storage Explorer Version:** 1.10.0
**Build:** [20190916.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3055553)
**Branch:** master
**Platform/OS:** Windows 10/ Centos Linux release_7.6.1810(core)/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Attach one storage account using name and key.
2. Check the log message on the Activities panel after attached successfully.

**Expect Experience:**
Show 'Successfully added **a** new connection.' on the Activities panel.

**Actual Experience:**
Show 'Successfully added new connection.' on the Activities panel.
![image](https://user-images.githubusercontent.com/41351993/65031031-1b0fd680-d973-11e9-9725-c5f0a6f2c4c2.png)

**More Info:**
This issue also reproduces when using SAS to attach items.

**Comment by craxal** [comment] 2019-09-17 15:54
@v-xianya Closing as by design. We intentionally left the article out for a compact, abbreviated style. Are there inconsistencies anywhere?

**Closed by craxal** 2019-09-17 15:54 UTC
Labels: :gear: attach, :heavy_check_mark: by design, 🧪 testing

**Comment by v-xianya** [comment] 2019-09-18 01:12
Hi @craxal Thanks for your clarification.
It is consistent in all the attached log messages.
