### ISSUE TITLE
Navigate by URL to a nested resource in a storage account

### ISSUE THREAD

**Issue by munael** [microsoft/AzureStorageExplorer#3279] opened 2020-07-21 14:16 UTC
**Is your feature request related to a problem? Please describe.**
It's cumbersome to navigate back to a nested resource directory after restarting the app as you have to do it all the way down.
Same with navigating to a position shared with you by colleagues.

**Describe the solution you'd like**
- Some way to quick open a nested resource by providing a partial URL.
- Optional: detect if the URL points to a valid binary resource and instead navigate to its logical parent.

**Describe alternatives you've considered**
I'd like to see them as well, as their UX is different. But they apply to the same issue.
- Session restore. On app start, automatically open the last opened tabs and navigate to last path open in each.
- The breadcrumbs bar becomes editable as text. This can be made to accept the URL as well.

**Additional context**
N/A

**Comment by MRayermannMSFT** [comment] 2020-07-27 18:22
@narfanar

- Restoring tabs on restart is an existing issue: https://github.com/microsoft/AzureStorageExplorer/issues/1504
- We're making the breadcrumbs editable in version 1.15! This is our next release.

As for your main request at the top, we'll try to consider something like that in the future.

**Comment by emjotde** [comment] 2021-08-03 19:41
This would be super useful to have. It's a bit weird that you can generate a URL via "Copy URL", but there is no way to actually consume it. Also interop with azcopy etc. would be vastly improved.

**Comment by Ssloto** [comment] 2021-08-03 19:55
This definitely would cut down on a lot of existing pain points when using AzureStorage tooling.

**Comment by aaronpburke** [comment] 2021-08-03 20:01
> This would be super useful to have. It's a bit weird that you can generate a URL via "Copy URL", but there is no way to actually consume it. Also interop with azcopy etc. would be vastly improved.

This. I always thought I was doing something wrong... I regularly "Copy URL" to give a link to someone for Azure Storage, but it's pretty useless since it just opens in my web browser with a 404 (because it lacks security context).

**Comment by anthonyaue** [comment] 2021-08-03 20:12
Yes please!

**Comment by vrnmthr** [comment] 2021-08-03 20:30
+1 to copy and share URL, it would make my life much easier as well... seems like basic functionality that is lacking currently

**Comment by rjai** [comment] 2021-08-03 20:56
Agreed! It would tremendously simplify using the explorer interface if we could use the URL scheme effectively instead of having to copy bits of it into the interface.

**Comment by spencerrarrick** [comment] 2021-08-03 21:56
Agreed, this is urgently needed and would improve usability immensely.

**Comment by mjpost** [comment] 2021-08-03 22:55
Very strongly seconded! The fact that I can't paste in a URL severely limits the utility of the Storage Explorer. Every user of the tool I talk to is surprised when they encounter this inability.

**Comment by anoopkunchukuttan** [comment] 2021-08-04 02:47
+1 
Yes, this is a big pain point. It would make Storage Explorer so much more useful and productive if we had this simple feature of navigating using URLs

**Comment by funtion** [comment] 2021-08-04 06:06
+1
It will be a very important and useful feature.

**Comment by snukky** [comment] 2021-08-04 16:37
+1 That would be very useful to have!

**Comment by JasonYeMSFT** [comment] 2021-11-04 21:43
Thanks for voting for the feature request. We will definitely revisit this in our next milestone and consider adding it.

**Comment by JasonYeMSFT** [comment] 2021-11-04 21:56
To help us better understand how "navigate by url" works: 

Are you expecting to use a url (e.g. https://stgacct.blob.core.window.net/container) to navigate to a resource you already own, as opposed to manually navigate through subscriptions -> storage accounts ...? We have a feature called "direct link". If you right click on a container level node, select "Copy Direct Link to", you will get a url-like string in the clipboard. If someone later paste the url in the web browser, it will automatically open Storage Explorer (if installed) and try to navigate to that resource. Let us know if this serves your purpose and feel free to also tell us if you want something different or you have any suggestions on how this feature might be improved.

Or Are you expecting to use a url to quickly add a new resource? Our connection dialog allows connecting using direct urls. However, unless the resource is public, the url must be accompanied by SAS tokens so that we can authenticate with the resource.

**Comment by emjotde** [comment] 2021-11-04 23:56
For me the first point would be important. We work a lot with command line tools like azcopy that naturally work with URLs and URLs with SAS. Seamless interaction between these tools would be uber-useful. The feature you mention still have a bunch of indirections, why not be able to do this in the actual tool?

**Comment by mjpost** [comment] 2021-11-05 00:14
Hi @JasonYeMSFT, thanks so much for this response! This is exciting.

Echoing @emjotde, it’s the first feature (access, not creation) that appeals to me and people on my team. Say I have a URL, like `https://mjpost.blob.core.windows.net/container/path/to/deeply/embedded/folder/or/file`. Ideally, I’d like to be able to paste this directly into an address bar *in* ASE, and it would take me to the folder within the blob (assuming it exists). Is that clear?

But are you saying that this feature already exists? You wrote

> If someone later paste the url in the web browser, it will automatically open Storage Explorer (if installed) and try to navigate to that resource. 

I have often tried this, but it results in an error. For example, if I enter such URLs into the Edge address bar, the browser displays a short page indicating that the resource doesn’t exist. It doesn’t try to open ASE even though it’s installed. This is on Windows 11 (and previously 10).

**Comment by emjotde** [comment] 2021-11-05 02:20
Another good comparison is File Explorer on Windows that also has an "address bar" at the top which allows you to directly navigate to deeply nested paths like "C:\Users\marcinjd\Downloads\polonium-configs\enu-deu" and it works both ways. At the same time these paths are meaningful for other tools like for instance cmd or powershell or any other tool that uses paths.

**Comment by JasonYeMSFT** [comment] 2022-12-09 23:19
We need to learn how to register our app as a handler for an https url.

**Comment by JasonYeMSFT** [comment] 2023-01-06 00:50
Our connect dialog is able to consume a url assuming it has a valid SAS token or the resource is public. We automatically open the explorer for the added connection. I think the missing part is to extract the sub-path from the url and automatically navigate to the nested location. Is my understanding correct?

![image](https://user-images.githubusercontent.com/39359541/210907405-920d0738-daa0-44bd-819e-1d402d73791a.png)

**Comment by mjpost** [comment] 2023-01-06 00:59
Yes, I believe so.

**Comment by mjpost** [comment] 2023-01-06 03:10
To elaborate, registering URLs with the underlying OS is one way to accomplish this. But in my view, it's strange that ASE doesn't already have its own address bar (just like all modern browsers or Windows Explorer) that can be used for retrieving and navigating to links.

**Comment by JasonYeMSFT** [comment] 2023-01-13 22:12
The OS only allows setting one default program to handle http/https urls. It doesn't make sense for Storage Explorer to replace the legit browser for handling those urls. There are a few things we can do to make this scenario less a hustle
- Allow creating direct link to directories/blobs
- Allow the connect dialog to take urls with directory/blob path and automatically navigate

**Comment by mjpost** [comment] 2023-01-14 01:53
I don't think it's important to handle this at the system level (e.g., via registration of http). The problem is that ASE does not know how to take a URL and navigate to the specified nested folder. It will give you that URL, but it doesn't know how to use it.

**Comment by mjpost** [comment] 2023-01-14 01:57
To repeat the analogy, this would be like if Windows Explorer (or MacOS Finder or the command line) didn't let you load a path directly but made you manually click down from the root folder. From my perspective this is a fundamental use case. I really do not understand why this feature is not present, and why the need for it is not obvious to the ASE team.

**Comment by aaronpburke** [comment] 2023-01-31 20:58
> Our connect dialog is able to consume a url **assuming it has a valid SAS token or the resource is public.** We automatically open the explorer for the added connection. I think the missing part is to extract the sub-path from the url and automatically navigate to the nested location. Is my understanding correct?
> 
> ![image](https://user-images.githubusercontent.com/39359541/210907405-920d0738-daa0-44bd-819e-1d402d73791a.png)

**This** part is incorrect. I've already logged in to Storage Explorer with my Azure account. It's able to browse private containers. When I'm within a container, I can right-click on a resource and select "Copy URL" **on a private blob**.

![image](https://user-images.githubusercontent.com/1234244/215880293-f899fc74-0978-4f32-9834-2eb760982437.png)

It generates a URL as thus: https://hotfixtest.blob.core.windows.net/hotfix/test-data/enu.esn.generalnn.phrasefix.src.snt

The problem we're all talking about is that the above URL is completely useless. Since it is a private blob and doesn't have a SAS token (nor do I want it to), opening it in my browser gives a 404 since it lacks security context (this is the correct thing to do from Blob Storage's perspective). Azure Storage Explorer has no way to consume that URL. 

If I give that URL to another user with the same storage account permissions to view/download, they should be able to enter it into a dialog or address bar somewhere within the UI (and preferably also accessible via Ctrl+O or similar). If the URL points directly to a resource blob, it should give the option of downloading the file directly (basically just a wrapper around azcopy). If it's a "folder" (for as much as blob storage supports folders), it should give me the option to navigate directly to that folder _or_ download its contents recursively.

**Comment by aaronpburke** [comment] 2023-03-07 01:28
> Are you expecting to use a url (e.g. https://stgacct.blob.core.window.net/container) to navigate to a resource you already own, as opposed to manually navigate through subscriptions -> storage accounts ...? We have a feature called "direct link". If you right click on a container level node, select "Copy Direct Link to", you will get a url-like string in the clipboard. If someone later paste the url in the web browser, it will automatically open Storage Explorer (if installed) and try to navigate to that resource. Let us know if this serves your purpose and feel free to also tell us if you want something different or you have any suggestions on how this feature might be improved.

Follow up on the above: this also doesn't work, but the _idea_ is correct, except we want that for deeper links within the container itself (i.e., support direct navigation to a nested "folder" within the container, not just the container itself).

When I used the above-described Direct Link feature, it gave me this:
storageexplorer://v=1&accountid=/subscriptions/da98ac41-7e81-431f-84bf-8e4efa13b85b/resourceGroups/aaburke/providers/Microsoft.Storage/storageAccounts/hotfixtest&subscriptionid=da98ac41-7e81-431f-84bf-8e4efa13b85b

I closed ASE and pasted the link into my browser. It opened ASE as expected, but did not automatically navigate to the container. My only startup tab is the usual Get Started tab with "Quick Access" pre-selected on the left as though I'd just opened ASE directly:

![image](https://user-images.githubusercontent.com/1234244/223295582-38eceedf-706e-4c6a-bbb5-3ee893047841.png)

**Comment by pmintusEA** [comment] 2023-03-14 00:51
Hi, 

I just want to add my vote for 
> Allow creating direct link to directories/blobs

This would be incredibly useful. 

Thanks!

**Comment by edbarnes01** [comment] 2023-05-18 13:06
**Deep Linking (with queries/filters)**

Hi,

Unsure if this would need to be a separate feature request but believe it directly links with this one. I can make a separate feature request if better.

It would be great if in addition to deep linking to a specific directory (or in my case, a table), we could send a query/filter in the url too. For example:

storageexplorer://v=1&accountid=/subscriptions/XXXXX/resourceGroups/XXXX/providers/Microsoft.Storage/storageAccounts/XXXXXXX&subscriptionid=XXXXXX&resourcetype=Azure.Table&resourcename=SomeTable&query=SomeKey=SomeValue

With the key bit being **_&query=SomeKey=SomeValue_** or **_&filter=SomeKey=SomeValue_**

That would speed things up so much and allow for better integration with other systems.

**Comment by JasonYeMSFT** [comment] 2023-05-26 20:30
Here is a summary of what I did for 1.30.0 attempting to improve our UX in this scenario. Starting from 1.30.0, Storage Explorer will allow creating direct links for
- Blob container
- A directory in a blob container
- A file in a blob container

The direct link is a customized URL using storageexplorer:// protocol. If you open the URL in the browser on Windows or Mac and Storage Explorer is installed on the machine, it will start, if not already started, and provide the following options
- Navigate to the container and open its explorer. If your direct link is created for a directory, the explorer will automatically navigate to that directory. If your direct link is created for a file, the explorer will automatically navigate to its parent directory. This action requires that you are signed in to a user account that has access to all the nodes to the container including the subscription and the storage account.
- Azure AD attach the container or directory. This action requires that you are signed in to a user account.
- Download the directory/file. This action is only presented if the direct link is created from a directory/file.

**Comment by mjpost** [comment] 2023-05-26 21:26
I look forward to trying this out when 1.30.0 is available!

**Comment by pmintusW** [comment] 2023-05-26 21:31
Thank you! Looking forward to it as well!

**Comment by emjotde** [comment] 2023-05-27 03:45
Being able to somewhere enter the `https://`-style url into Storage Explorer in a text field and get the same deep navigation would also be great. Just based on a principle that if Storage Explorer can generate that kind of URL it should also be able to consume it.

**Comment by spencerrarrick** [comment] 2023-05-27 11:50
> Being able to somewhere enter the `https://`-style url into Storage Explorer in a text field and get the same deep navigation would also be great. Just based on a principle that if Storage Explorer can generate that kind of URL it should also be able to consume it.

+1 to this. Deep links working in the browser is a still a huge step up, but pasting into a textbox within the application seems like the most intuitive and easiest to use solution. 

Away from my PC, but if I recall, there's a textbox at the top of the explorer where the currently navigated path is displayed. I was always curious why it wasn't possible to paste the urls there and have explorer navigate.

**Comment by JasonYeMSFT** [comment] 2023-06-12 22:34
1.30.0 has been released.

> > Being able to somewhere enter the `https://`-style url into Storage Explorer in a text field and get the same deep navigation would also be great. Just based on a principle that if Storage Explorer can generate that kind of URL it should also be able to consume it.
> 
> +1 to this. Deep links working in the browser is a still a huge step up, but pasting into a textbox within the application seems like the most intuitive and easiest to use solution.
> 
> Away from my PC, but if I recall, there's a textbox at the top of the explorer where the currently navigated path is displayed. I was always curious why it wasn't possible to paste the urls there and have explorer navigate.

We added a new dialog for opening direct links within the app. We understand it might not be the ideal way to open direct links compared to a global address bar. Unfortunately we don't have enough resource to design the feature and make it happen. It's mainly a workaround for Linux users since web browsers on Linux don't recognize our custom protocol as of today.

**Closed by JasonYeMSFT** 2023-06-12 22:34 UTC
Labels: :bulb: feature request, :exclamation: P1

**Comment by pmintusW** [comment] 2023-06-13 01:04
Thank you! I just tried it out in 1.30. This is much improved from where it was, however I would love to see the ability to navigate to the folder/director or file. Currently there is only the option to download the file or navigate to the container. 

I also feel like the option to navigate to container should take you to the root if it cannot take you to the folder or file that is in the direct link. Currently it takes you to the last folder you browsed in that container. This could easily introduce a lot of confusion. For example, if I had the following structure in my storage account:

/container/1/foo.bar
/container/2/foo.bar

If I was previously browsing /container/1/ in storage explorer and someone gave me a direct link to /container/2/foo.bar, if I select "navigate to container" it would take me to /container/1/, which looks identical to /container/2/
