### ISSUE TITLE
'Set Default Access Tier…' is not localized for one GPV2 storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2031] opened 2019-10-10 08:09 UTC
**Storage Explorer Version:** 1.10.1
**Build:** [20191010.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3128931)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-CN)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Expand Storage Accounts -> Select one GPV2 storage account.
3. Check its context menu.

**Expect Experience:**
All strings on the context menu are localized.

**Actual Experience:**
'Set Default Access Tier…' is not localized.

**More Info:**
Only verified this issue in Chinese (zh-CN).

**Comment by lukaschal** [comment] 2019-10-10 08:17
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/2010 .

**Closed** 2019-10-10 08:30 UTC
Labels: 🌐 localization, 🧪 testing
