### ISSUE TITLE
Properties pane is blank for items under "Quick Access"

### ISSUE THREAD

**Issue by zendu** [microsoft/AzureStorageExplorer#1491] opened 2019-06-24 22:37 UTC
**Storage Explorer Version**: 1.8.1
**Build Number**: 20190510.6
**Platform/OS**: Windows 10
**Architecture**: It is x64 OS but Help -> About window of Storage Explorer shows ia32
**Regression From**:  Not sure

## Bug Description ##
Select any item added to Quick Access. Properties pane at the bottom is empty.

## Steps to Reproduce ##

1. Add an Azure account/subscription to storage explorer.
2. Expand it and select a storage account.
3. Add the item to Quick Access using context menu.
4. Select the item under Quick Access.

## Expected Experience ##
Properties pane should show information about selected item, like subscription, primary connection string, etc.

## Actual Experience ##
Properties pane is empty.

## Additional Context ##
It seems that issue #1035 is back.

**Comment by MRayermannMSFT** [comment] 2019-07-01 18:11
@zendu , what type of resource did you pin to quick access?

**Comment by zendu** [comment] 2019-07-02 15:29
@MRayermannMSFT - a storage account.

**Comment by MRayermannMSFT** [comment] 2019-07-08 18:01
@zendu , I'm having a hard time reproducing this in both 1.8.1 and 1.9.0, can you try detaching and then reattaching the item to see if it fixes the issue?

**Comment by MRayermannMSFT** [comment] 2019-08-05 18:10
Closing due to lack of customer response.

**Closed by MRayermannMSFT** 2019-08-05 18:10 UTC
