### ISSUE TITLE
When having multiple subscriptions and one one of them requires MFA - WHY ask me MFA for all of them???

### ISSUE THREAD

**Issue by alvipeo** [microsoft/AzureStorageExplorer#3799] opened 2020-11-20 17:25 UTC
v.1.16.0, Windows 10 x64

So I have quite a few subscriptions and only 1 or 2 has MFA, and I use same account for all of them. Every time I open storage explorer and want to get into this MFA protected storage accounts, I have to 'Reenter my creds'. And I have to do this 'number of subscriptions' times! Can you just ask to auth for this single subscription I'm trying to open?

**Comment by MRayermannMSFT** [comment] 2020-11-23 18:56
Duplicate of #460

**Closed by MRayermannMSFT** 2020-11-23 18:56 UTC
