### ISSUE TITLE
Tab crashes if query is run while sorting a boolean column

### ISSUE THREAD

**Issue by sberrad** [microsoft/AzureStorageExplorer#2243] opened 2019-11-08 16:32 UTC
I am able to reproduce regularly, sorting a large table by the values in a boolean column, and then clicking a run query while the loading circle is spinning.

Tab crashes and the error message:
'rowA[col]._.toLowerCase is not a function'

![Screenshot (19)](https://user-images.githubusercontent.com/38466348/68493899-5d3ef100-021b-11ea-9786-3f4bff83eded.png)

**Comment by sberrad** [comment] 2019-11-08 16:35
**Storage Explorer Version**: 1.11.0
**Build Number**: 20191105.2
**Platform/OS**: Windows 10
**Architecture**: x64

**Comment by jinglouMSFT** [comment] 2019-11-08 19:04
We haven't touched that code for a while.  This must be in the old releases as well.

**Comment by MRayermannMSFT** [comment] 2020-03-02 19:49
Won't fixing this. We're having trouble reproducing this. We also don't recommend running a query while the table is still loading.

**Closed by MRayermannMSFT** 2020-03-02 19:49 UTC
Labels: :beetle: bug

**Comment by MatisseHack** [comment] 2020-05-28 17:53
You can also reproduce this by clicking **Column Options** and moving a boolean column to the top of the list. Save, close the table tab, and reopen it. The tab will not be able to load because it is trying to sort the table by the first column, which is now a boolean column.

You can fix this issue by opening this file on macOS (or the equivalent on Windows): `/Applications/Microsoft\ Azure\ Storage\ Explorer.app/Contents/Resources/app/out/CloudHub/js/StorageExplorer/Tables/TableEntityListViewModel.js`

On line 241 (currently) you will find the following switch block:

```js
switch (rowA[col].$) {
    case StorageExplorerConstants.EdmType.Int32:
    case StorageExplorerConstants.EdmType.Int64:
        itemA = parseInt(rowA[col]._, 0);
        itemB = parseInt(rowB[col]._, 0);
        break;
    case StorageExplorerConstants.EdmType.Double:
        itemA = parseFloat(rowA[col]._);
        itemB = parseFloat(rowB[col]._);
        break;
    case StorageExplorerConstants.EdmType.DateTime:
        itemA = new Date(rowA[col]._);
        itemB = new Date(rowB[col]._);
        break;
    default:
        itemA = rowA[col]._.toLowerCase();
        itemB = rowB[col]._.toLowerCase();
}
```

Add a new case to handle boolean values. Something like this will work:

```js
case StorageExplorerConstants.EdmType.Boolean:
    itemA = rowA[col]._;
    itemB = rowB[col]._;
    break;
```
