### ISSUE TITLE
Fail to upload/download empty folder for ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1127] opened 2019-02-11 09:13 UTC
**Storage Explorer Version**: 1.7.0/20190208.3
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: d247f51b
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> 'Blob Containers' node.
2. Open one blob container and create a empty folder.
3. Download the empty folder/Upload one empty folder -> Check the result.

#### Expected Experience: ####
The empty folder can be downloaded/uploaded successfully.

#### Actual Experience: ####
Fail to download/upload the empty folder with the below error.
![image](https://user-images.githubusercontent.com/34729022/52553901-1f45a580-2e20-11e9-863b-27646bfccd9e.png)

**Comment by MRayermannMSFT** [comment] 2019-02-11 17:58
Close as duplicate of #905

**Closed by MRayermannMSFT** 2019-02-11 17:58 UTC
Labels: :gear: adls gen2, testing
