### ISSUE TITLE
Date picker in access policy is unpredicable

### ISSUE THREAD

**Issue by stewartadam** [microsoft/AzureStorageExplorer#2907] opened 2020-04-28 21:22 UTC
Version: 1.12.0
AzCopy Version: 10.3.3

Platform: macOS
Architecture: x64 
Build Number: 20200116.10 
Commit: 0a86d4ecc 
Support ID: 70f20b02-ca4a-d914-07c0-f17d73883239 

## Bug Description ##
The expiration date picker on access policies is wholly ineffective:
1. Two-digit numbers cannot be entered because it treats "12" as two separate inputs of "01" and "02"
2. Flipping moving the minute counter up or down one also toggles, AM/PM and day fields even if the minute wasn't on a day boundary
3. Various other bugs (see below)

## Steps to Reproduce ##
1. Create an access policy
2. Try to set 12/31/2099 12:00:00 AM as the expiration date

## Expected Experience ##
1. Entering "12" in the month field sets month to 12 not 02
2. Moving the minute counter up/down with the arrow keys does not affect any other field unless crossing the minute boundary between AM/PM within a day or between days (i.e. 11:59 PM <--> 12:00 AM)
3. Setting a day field doesn't change the time
4. Moving the hour field with arrow keys moves it by one hour, not skipping by two or more (and changing the day field)

## Actual Experience ##
See attached video (in ZIP): [storageexplorer-dateselector-repro.zip](https://github.com/microsoft/AzureStorageExplorer/files/4548531/storageexplorer-dateselector-repro.zip)

**Comment by MRayermannMSFT** [comment] 2020-05-04 17:52
Duplicate of #2812

**Closed by MRayermannMSFT** 2020-05-04 17:52 UTC
