### ISSUE TITLE
The localized 'Refresh' displays incompletely in German

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2494] opened 2019-12-26 09:39 UTC
**Storage Explorer Version:** 1.11.2
**Build:** [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616)
**Branch:** hotfix/1.11.2-to-master
**Language:** German
**Platform/OS:** Windows 10/ CentOS 7.6.1810
**Architecture:** ia32/ x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Deutsch' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Select one table -> Check the localized Refresh button in the toolbar.

**Expect Experience:**
The localized 'Refresh' displays completely.

**Actual Experience:**
The localized 'Refresh' displays incompletely.
![image](https://user-images.githubusercontent.com/41351993/71470209-648b7f80-2806-11ea-8a56-a138d38a26b1.png)

**More Info:**
1. This issue reproduces for one file share/ queue/ resource group.
2. This issue reproduces for one **blob container**/ file share/ queue/ table/ resource group **on MacOS.**
3. This issue still reproduces after zooming out Storage Explorer.

**Comment by johnliu2016** [comment] 2019-12-27 02:51
Sending to localization for review

**Comment by johnliu2016** [comment] 2019-12-30 12:34
This looks the default behavior when the command name string over-sizes. @craxal could you please confirm?

**Comment by craxal** [comment] 2020-01-06 16:59
This is intended behavior if button string lengths get too large for their declared size. We can increase the size of the button.

**Comment by MRayermannMSFT** [comment] 2020-01-13 19:15
Won't fix. We'd rather not impact other langs. The ... is intended for now.

**Closed by MRayermannMSFT** 2020-01-13 19:15 UTC
Labels: :triumph: easy, 🧪 testing

**Comment by MRayermannMSFT** [comment] 2020-01-13 19:16
Related to #2194
