### ISSUE TITLE
RA-GRS secondary endpoint

### ISSUE THREAD

**Issue by swieder** [microsoft/AzureStorageExplorer#2759] opened 2020-03-26 16:50 UTC
Error when using the secondary endpoint of a RA-GRS account:   Unable to retrieve child resources Details: One of the request inputs is out of range

I connected to the secondary endpoint using a Connection String (copied from Storage Account in Portal and added -secondary to the accountname.

How can we use Storage explorer to access secondary side of RA-GRS storage account.

**Comment by MRayermannMSFT** [comment] 2020-03-30 17:54
Duplicate of #421

**Closed by MRayermannMSFT** 2020-03-30 17:54 UTC
