### ISSUE TITLE
Queued transfer via copy & paste across storage account blobs never completes

### ISSUE THREAD

**Issue by dbrennan** [microsoft/AzureStorageExplorer#2222] opened 2019-11-05 21:58 UTC
**Storage Explorer Version**: 1.11.0, AzCopy 10.3.1
**Build Number**: 20191105.2
**Platform/OS**: Linux Ubuntu
**Architecture**: x64
**Regression From**: unknown

## Bug Description ##
Can't copy & paste files

## Steps to Reproduce ##
1. In same subscription, open blob container from one storage account
2. select and right-click copy 1 or more blogs
3. switch to container in another storage account
4. right click paste

## Expected Experience ##
Files should be copied.

## Actual Experience ##
result: message appears in Activities like
"Queued transfer of 'images/008b1421-81a2-4145-9680-2ba30810f419' to 'images/' (using SAS)"
 
but files never paste and message never goes away

## Additional Context ##
Doesn't look like download to local folder works either. Something seems pretty broken.

**Comment by craxal** [comment] 2019-11-05 23:43
@dbrennan Just tried several copy and paste operations on my Linux Ubuntu 18 machine, and it worked just fine. Let's see if we can break this down some more:

- Can you give me more details about the source? What kind of account is it (classic, ADLS Gen2, standard, v2, premium, etc.)?
- Can you give me more details about the destination? What kind of account is it (classic, ADLS Gen2, standard, v2, premium, etc.)?
- Are you running behind any sort of proxy? Do you have any network limitations (slow connection, for example)?
- How big are files you are trying to copy?
- Does the activity have any action to copy the AzCopy command to the clipboard? Or to view any logs?
- Does this repro consistently for you?

**Comment by dbrennan** [comment] 2019-11-06 21:26
Thanks @craxal 
It worked on a previous version, but I don't know which as it's been a while, so probably before azcopy integration. I ran azcopy directly from the source in dest with URLs generated from Storage Explorer and that worked.
Source & destination are Storage V2
I'm not behind a proxy and network is very fast (University of Washington)
Files are very small - 3 to 70k, failed for 1 or 43.  
I don't see any actions on the activity (no UI elements, nothing on right-click,etc.)

**Comment by JasonYeMSFT** [comment] 2019-11-11 20:06
@dbrennan, can you try reproduce this issue once and see if there is a corresponding generated AzCopy log file in the `$HOME$\.azcopy` directory? We are only showing the progress and the in-progress actions (e.g. cancel, copy command, etc.) after receiving the first message that AzCopy gives us. It is possible that AzCopy is running into some internal errors.

**Comment by JasonYeMSFT** [comment] 2019-11-19 00:34
@dbrennan, are you using storage explorer via snap?

**Comment by dbrennan** [comment] 2019-12-15 08:43
Yes, my latest install was via Snap.  Previously I had installed manually. Sorry for the delayed reply.

**Comment by MRayermannMSFT** [comment] 2019-12-18 18:54
Can you try closing Storage Explorer and then deleting `~/snap/storage-explorer/current/.config/storage-explorer/sessions`?

**Comment by MRayermannMSFT** [comment] 2020-01-27 21:39
Closing due to lack of response. A fix related to snap updating was shipped in 1.12.0. So this should be fixed. Please open a new issue if you continue to have problems.

**Closed by MRayermannMSFT** 2020-01-27 21:39 UTC

**Comment by dbrennan** [comment] 2020-01-27 23:18
I'll give it a try this week.
