### ISSUE TITLE
Disk Copy Error - Azure Storage Explorer

### ISSUE THREAD

**Issue by blozza** [microsoft/AzureStorageExplorer#2076] opened 2019-10-15 07:29 UTC
Trying to copy a disk from one region to another, its works with a smaller disk (ie 128GB) but when trying to copy 1024GB disk is fails when nearing completion (its taking a couple hours).  I suspect the token is expiring?

Storage Explorer was unable to revoke access to a disk.
The disks involved in this operation may still be in an 'Active SAS' state. You may need to return the disks to an 'Unattached' state before retrying this operation, or before performing new operations on the disks.

Service response: {
  "name": "Error",
  "message": "The access token expiry UTC time '10/14/2019 8:00:48 PM' is earlier than current UTC time '10/14/2019 10:18:34 PM'.",
  "stack": "Error: The access token expiry UTC time '10/14/2019 8:00:48 PM' is earlier than current UTC time '10/14/2019 10:18:34 PM'.\n    at new RestError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:2400:28)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:3544:37\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
  "code": "ExpiredAuthenticationToken",
  "statusCode": 401,

**Comment by MRayermannMSFT** [comment] 2019-10-16 16:22
Duplicate of #2048. Closing. See that issue for discussion.

**Closed by MRayermannMSFT** 2019-10-16 16:22 UTC
