### ISSUE TITLE
Cannot connect to storage account

### ISSUE THREAD

**Issue by yxie97** [Microsoft/AzureStorageExplorer#1077] opened 2019-01-17 23:40 UTC
**Storage Explorer Version**: 1.6.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: It worked before but don't remember what version

**Bug description**
We tried to connect to a Storage Account using connection string, SAS as well as storage account name plus key. We are seeing a message "Adding new connection" but it just sit there forever.

**Steps to Reproduce**
1. Start Azure Storage Explorer
2. Add Account
3. Enter display name
4. Choose any of the above mentioned options
5. Next
6. Connect

**Expected Experience**
Connection created and we can access the storage account

**Actual Experience**
Connection never gets completed.

**Additional Context**

**Comment by yxie97** [comment] 2019-01-18 15:49
The issue seems to be gone but not sure what has changed. anyone has any insight?

**Comment by jinglouMSFT** [comment] 2019-01-18 19:16
network availability? service availability?  The scenarios you mentioned above have been tested hundreds times and used by thousands of users, so they are fairly stable.  I am pretty sure what you've experienced wasn't caused by Storage Explorer itself.

**Comment by yxie97** [comment] 2019-01-18 22:37
I'm not sure what the issue was yesterday. But it happened to multiple team members across geographical locations so it's hard to image it's on the client side.

Also i heard from other team members that they have to download Azure Storage Explorer quite often to ensure it works?

**Comment by jinglouMSFT** [comment] 2019-01-18 23:49
In a normal release cadence, we usually release once a month. There have been times we needed to release hot fixes in between the normal releases.  These are the only upgrades I am aware of. I don't have all the context to comment on the question you asked above. 
If you don't have other outstanding questions, could you please close the issue?  Thanks.

**Closed** 2019-01-22 15:06 UTC
