### ISSUE TITLE
Always navigate to the first folder after clicking 'Back' button from any subfolders 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1871] opened 2019-09-19 10:13 UTC
**Storage Explorer Version:** 1.10.1
**Build:** 20190919.2
**Branch:** hotfix/1.10.1
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Blob containers.
2. Create a new blob container -> Upload two folders. 
3. Open the second folder then clicking 'Back' button in the toolbar.
4. Check the result.

**Expect Experience:**
 Navigate to the second folder.

**Actual Experience:**
 Navigate to the first folder.

**More Info:**
1. This issue also reproduces for directories under one file share.
2. This issue also reproduces for folders under one ADLS Gen1 account.

**Comment by craxal** [comment] 2019-09-19 15:41
@v-xianya If I understand correctly, you did something like this:
1. Create a new blob container named "my-container".
2. Create a folder at the root called "first".
3. Crate a folder at the root called "second".
4. Open "second".
5. Click the Back button.

I would think the expected behavior is to navigate back to the root, since the root folder is where you were last. Yet you're saying that we navigate to "first"? I'm also confused about you expected result, because "second" is the current folder you're in, not the previous one.

Does this blob container have hierarchical namespaces turned on?

**Comment by v-xianya** [comment] 2019-09-20 01:20
Hi @craxal Thanks for your updates!
 1. For the repro steps. Yes. It's exactly what I want to express.
 2. For this issue, in my opinion, it's better to navigate back to the parent folder instead of the root folder. I understand the back is just to return to the previous step.
 3. The blob container doesn't have the hierarchical namespaces turned on.

**Comment by craxal** [comment] 2019-09-23 16:30
@v-xianya Since the blob container doesn't have hierarchical namespaces turned on, did you upload a file to each folder? Because they don't actually exist in Azure otherwise.

Just to be absolutely sure, this is the hierarchy you're creating, right?
```
blob-container
├ first
│ └ file.txt
└ second
  └ file.txt
```

For "second", the root folder is the same as the parent folder, so if you navigate from the root to "second", clicking Back works the same as clicking Up, which is expected.

**Comment by MRayermannMSFT** [comment] 2019-11-18 19:29
@v-xianya can you let Craig know if he's understanding your correctly? Thanks.

**Comment by v-xianya** [comment] 2019-11-19 03:12
Hi @craxal  It is better to remember the last parent folder when using Back.

For this hierarchy.
blob-container
├ firstfolder
│ └ file1.txt
└ secondfolder
  └ file2.txt

**Steps:**
1. Click the blob-container-> Secondfolder-> file2.txt.
2. Click 'Back'.

**Expect:**
secondfolder is selected.

**Actual:**
firstfolder is selected.

**Comment by craxal** [comment] 2019-11-19 19:15
@v-xianya I'm sorry, but the new repro steps don't make any sense to me. How do you navigate into a blob? I can't investigate this unless we get the repro steps clarified. Please give me exact repro steps so I can follow along without any ambiguity.

**Comment by v-xianya** [comment] 2019-11-20 08:59
Hi @craxal Details please see the below.😊

**Repro Steps:**

1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload 2 folders (folder1 & folder2).
![image](https://user-images.githubusercontent.com/41351993/69222857-262be200-0b2f-11ea-89f0-66dc37d34a21.png)

3. Select 'folder2' and open it.
![image](https://user-images.githubusercontent.com/41351993/69222900-3e9bfc80-0b2f-11ea-9647-3a26561c4f98.png)
4. Click 'Back' icon -> Check the result.

**Expect:**
'folder2' is selected.
![image](https://user-images.githubusercontent.com/41351993/69223274-e87b8900-0b2f-11ea-869b-107206ca4fde.png)



**Actual:**
'folder1' is selected.
![image](https://user-images.githubusercontent.com/41351993/69223286-ee716a00-0b2f-11ea-980e-d69784277bf3.png)

**Comment by craxal** [comment] 2019-11-20 18:48
Oh...OK, I see now why I was so confused. This is about which item is _selected_, not about navigation. The title is misleading.

I'm going to mark this as Won't Fix. We call into Azure every time we navigate to get the list, so we're basically creating a new list every time. If customers bring this up, we can revisit.

**Closed by craxal** 2019-11-20 18:48 UTC
Labels: :heavy_check_mark: won't fix, 🧪 testing
