### ISSUE TITLE
No red border displays on the value filed of 'PartitionKey/RowKey' when typing one value then deleting it

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5120] opened 2021-11-02 09:50 UTC
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211102.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.6
**Architecture**: ia32/x64
**How Found**: From running test cases 
**Regression From**: Previous release (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Open one table -> Click 'Add'.
3. Type one value into the 'PartitionKey' value field -> Delete the value.
4. Check whether there is a red border.   

## Expected Experience ##
There is a red border.
![image](https://user-images.githubusercontent.com/41351993/139823957-9876e4ce-4b89-4fc5-8e5d-8b5fa8c059fe.png)

## Actual Experience ##
There is a no red border.
![image](https://user-images.githubusercontent.com/41351993/139823909-09bac319-0bd8-4647-ae6e-9198603039cf.png)

## Additional Context ##
Related issue: [2787](https://github.com/microsoft/AzureStorageExplorer/issues/2787).

**Comment by craxal** [comment] 2021-11-02 18:49
Empty values for partition or row keys are valid. I'm not really sure why we invalidated this before.

@MRayermannMSFT @JasonYeMSFT Do we know if there was a reason we originally invalidated empty keys?

@v-xianya Assuming there are no other entities with the same partition and row key, does adding an entity with empty keys still succeed?

**Comment by JasonYeMSFT** [comment] 2021-11-02 20:19
I don't know. However, could you check if there is any side effect for entities whose partition key or row key is empty (like blobs with empty name). If it is valid and there is no side effect, we should stop validating it.

**Comment by v-xianya** [comment] 2021-11-03 01:44
Hi @craxal 

> Assuming there are no other entities with the same partition and row key, does adding an entity with empty keys still succeed?

Yes, succeed to add an entity with empty partition/row keys.

**Comment by craxal** [comment] 2021-11-03 23:52
@JasonYeMSFT @v-xianya I double-checked that the platform accepts empty strings for keys when creating entities, and it does, so I'm closing this as by design.

**Closed** 2021-11-03 23:52 UTC
Labels: 🧪 testing, :gear: tables, :heavy_check_mark: by design, :beetle: regression
