### ISSUE TITLE
Can not browse snapshot contents for some Azure Files shares

### ISSUE THREAD

**Issue by Storm-BE** [microsoft/AzureStorageExplorer#5751] opened 2022-05-19 14:56 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.1
1.24.2

### Architecture

x64

### Storage Explorer Build Number

20220510.2
20220527.5

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Using Azure Storage Explorer v1.24.1, we can no longer browse snapshot contents for some of our Azure Files shares

The snapshots can be listed using the **View Share Snapshots** button:
![image](https://user-images.githubusercontent.com/3585108/169326513-ee9ff6a1-9e45-43d6-b21d-cad27f770f95.png)

However, they are not present in the dropdownlist (which only contains `Current` for this share):
![image](https://user-images.githubusercontent.com/3585108/169326584-44be9920-9677-4460-805b-1dae93cc1268.png)

Double clicking a snapshot just switches to browsing the `Current` state, not the snapshot contents.

This happens for all team members running this version.
A colleague is running v1.20.1 of ASE on Mac OS and does not have this issue.

Using the same accounts, we can browse these very same snapshots using the Azure Portal without any issues.

### Steps to Reproduce

1. Launch ASE
2. Navigate to the affected shares
3. Try to open a snapshot

### Actual Experience

See Bug Description

### Expected Experience

I expect to be able to browse the contents of all snapshots of all Azure Files shares, as I could before

**Comment by MRayermannMSFT** [comment] 2022-05-23 17:37
@Storm-BE can you do the following:
1. Re-open Storage Explorer
2. Do the minimum steps to repro the issue (including viewing the share snapshots in the data table and then double clicking on one)
3. Go to Help > Open Logs Directory
4. In the file explorer window that opens, open the newest folder/the one named with the most recent date
5. Zip up all the files in that folder
6. Come to this issue on github.com and drag and drop the zip into a reply to the issue

**Comment by Storm-BE** [comment] 2022-05-23 18:20
@MRayermannMSFT , well, I tried to reproduce this again to gather the logs, and well...
I can browse all snapshots for this share without any issues now.
So can my colleagues.

Strange, but okay, I'll close the ticket :)

Thanks!

**Comment by Storm-BE** [comment] 2022-06-02 08:55
@MRayermannMSFT , this is happening again for my team and I, but for some other file shares now.
Here are the requested logs:
[2022-06-02_105011.zip](https://github.com/microsoft/AzureStorageExplorer/files/8822260/2022-06-02_105011.zip)

**Comment by MRayermannMSFT** [comment] 2022-06-06 16:23
@Storm-BE are the number of snapshots for this share (share-devchili) changing frequently? Could the number have been different 14 vs 4 days ago?

**Comment by Storm-BE** [comment] 2022-06-07 15:25
@MRayermannMSFT  
Yes, we have automation jobs that create new snapshots and manage retention for existing ones.
The number of snapshots can fluctuate a little bit.

**Comment by MRayermannMSFT** [comment] 2022-06-13 17:15
@Storm-BE what I think is going on is that the service is sometimes returning 0 file share snapshots to Storage Explorer in the first call for listing snapshots for your file share. This would explain the context menu being empty and the data table not, as the context menu makes no effort to follow continuation tokens. It also explains not being able to double click on a share snapshot in the data table, as the process of double clicking on a share snapshot relies on that snapshot being in the dropdown.

We've never seen a continuation token come back for file share snapshots and we've tested having a share with max snapshots before. But perhaps there's just something about the state of your share/shares that is causing this for you. We will figure out when we can implement and ship a fix for this to you.

**Comment by MRayermannMSFT** [comment] 2022-06-13 17:55
@Storm-BE right now we're thinking we'll ship a fix for this as part of our 1.25 release. In the meantime if you are blocked you can view and explore snapshots in the portal:
![image](https://user-images.githubusercontent.com/21112697/173414896-9c7e5afb-3d0b-4764-b311-388bb2689e9d.png)

**Comment by MRayermannMSFT** [comment] 2022-06-15 17:57
@Storm-BE we're going to try and do a 3rd hotfix of 1.24, which will include a fix for your issue. If you have time, please try this release candidate and let us know if this issue still reproduces: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.24.3-rc-1-build/StorageExplorer-ia32.exe

Note, since this is a release candidate, I do not recommend using this build extensively with production data. Please try to limit usage to just verifying if this issue is fixed or not.

**Comment by MRayermannMSFT** [comment] 2022-06-22 18:04
@Storm-BE we've shipped the hotfix. Please install from here (even if you've installed the release candidate build): https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.24.3

Since we haven't been able to reproduce this, I will keep this issue open and track it for the remainder of our 1.25 milestone. If you don't respond by the time we ship that we'll consider this fixed.

**Comment by Storm-BE** [comment] 2022-07-11 12:12
Thanks for following up on this, @MRayermannMSFT!
We haven't been able to reproduce this issue myself yet since the update to 1.24.3
If it were to happen again, I'll update the ticket.

**Comment by MRayermannMSFT** [comment] 2022-07-11 21:41
Thanks @Storm-BE. Since you haven't reproduced yet, I'm going to close this. Please open a new issue if it happens again. We don't normally look at closed issues. :)

**Closed by MRayermannMSFT** 2022-07-11 21:41 UTC
Labels: :heavy_check_mark: merged, :gear: files
