### ISSUE TITLE
Stop shipping files not needed for native modules

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#4778] opened 2021-08-10 21:53 UTC
Need to clean up `.pdb`, `.ilk`, `.lib`, `.exp` files from these native modules:

- osx-keychain
- clipboard-files
- system-format
- msint-selectcert (related: https://github.com/microsoft/AzureStorageExplorer/issues/4779)
- keytar

On Windows this would save north of 41 MB of install space.

**Comment by fdwr** [comment] 2021-10-15 23:00
Seems mine is a dupe of yours: https://github.com/microsoft/AzureStorageExplorer/issues/5068

It's actually double 41MBs - at least 81MB's! For this class of app given its functionality compared to other similar apps, a target size really should be <=40MB's rather than 491MBs (given fully functional web browsers, frameworks, and even entire operating systems like Windows 2000 are smaller). It makes me think there's a lot more low hanging fruit hiding in space savings beyond the more obvious files that we easily see.

**Comment by fdwr** [comment] 2021-10-21 00:55
With the Edge WebView2 control, where multiple occurrences of the runtime from different apps are deduplicated via NTSF hard links, you could likely save a chunk more for file space the user. https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution It might save memory too, if Teams' experience applies: https://tomtalks.blog/2021/06/microsoft-teams-2-0-will-use-half-the-memory-dropping-electron-for-edge-webview2/

**Comment by JasonYeMSFT** [comment] 2021-11-01 20:07
I merged the work to remove those files when packaging the application.

**Closed by JasonYeMSFT** 2021-11-01 20:07 UTC
Labels: :test_tube: engineering

**Comment by JasonYeMSFT** [comment] 2021-11-01 20:11
We still have other unused files during runtime. We will track them in a separate issue #5117.

**Comment by MRayermannMSFT** [comment] 2021-11-10 21:41
@fdwr , since you seemed interested, after completing all of the size reduction work we had planned for this milestone, we are now just squeaking under 350MB. Only slightly larger than VS Code. There's definitely still more work for us to do in the future though. Thanks for being so involved!

**Comment by fdwr** [comment] 2021-11-10 21:54
@MRayermannMSFT
> There's definitely still more work for us to do in the future though
140MB's is a good first start though. Thanks for listening and pushing it through.
