### ISSUE TITLE
The string 'Active Directory' is not localized on Connect dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2052] opened 2019-10-11 08:43 UTC
**Storage Explorer Version:** 1.10.1
**Build:** [20191011.12](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3133776)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-CN) /Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings panel -> Preference (Locale) -> Select **Chinese (simplified)** as application language -> Restart Storage Explorer.
3. Click the plug icon to open connect dialog.
4. Check the strings on the dialog.

**Expect Experience:**
The string 'Active Directory' is localized.

**Actual Experience:**
The string 'Active Directory' is not localized.
![image](https://user-images.githubusercontent.com/41351993/66637609-f2af8b00-ec45-11e9-9bbe-853951d8542e.png)

**More Info:**
Only verified this issue in Chinese(zh-CN)/Chinese(zh-TW).

**Comment by lukaschal** [comment] 2019-10-11 10:56
Correct translation according to termstudio.

https://termstudio.azurewebsites.net/viewdata.aspx?tid=2029805&langCode=English

**Comment by craxal** [comment] 2019-10-11 15:37
As per comment from @lukaschal, closing as by design.

**Comment by v-xianya** [comment] 2019-10-12 02:43
Hi @craxal Thanks for your updates for this issue.
 In my opinion, the string 'Active Direcroty' can be localized.
 (**The string 'Active Direcroty' can be translated to '活动目录' in Chinese(zh-CN)**)
![image](https://user-images.githubusercontent.com/41351993/66693466-97c87300-ecdb-11e9-9445-a697edb8bee9.png)

**Comment by JasonYeMSFT** [comment] 2019-10-14 17:57
Active Directory is a the name of the specific service and is supposed to be kept as is.

**Closed by JasonYeMSFT** 2019-10-14 17:57 UTC
Labels: :heavy_check_mark: by design, 🌐 localization, 🧪 testing
