### ISSUE TITLE
The snapshot doesn't auto display when selecting 'Snapshot original blob then upload' for one leased blob under Snapshots view

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2530] opened 2020-01-10 11:29 UTC
**Storage Explorer Version**: 1.12.0
**Build**: [20200109.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3369695)
**Branch**: rel/1.12.0
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Expand one storage account -> Blob Containers.
3. Create a new blob container -> Upload one blob to it -> Acquire leased for the blob -> Manage Snapshots.
4. Make changes for the leased blob and save it.
5. Select 'Snapshot original blob then upload' in the popped dialog.
6. Check the result. 

**Expect Experience:**
The created snapshot displays automatically.

**Actual Experience:**
The created snapshot doesn't display automatically.
![image](https://user-images.githubusercontent.com/54055206/72147259-174c0800-33d9-11ea-9fba-25c042640aec.png)

**More Info:**
This issue doesn't reproduce after manually refresh.

**Comment by MRayermannMSFT** [comment] 2020-11-06 20:04
Determine if the root cause of this bug is affecting anything other than snapshots. If yes, then fix, if no then won't fix.

**Comment by JasonYeMSFT** [comment] 2020-12-08 00:20
The cause is that the upload failed and we don't refresh container on failed uploads. It doesn't affect the snapshot creation or anything else.

**Closed by JasonYeMSFT** 2020-12-08 00:20 UTC
Labels: :gear: blobs, 🧪 testing
