### ISSUE TITLE
Provide Sort by Date column inside the File Shares folders

### ISSUE THREAD

**Issue by arulkumar4** [microsoft/AzureStorageExplorer#3213] opened 2020-07-10 07:57 UTC
Currently inside the **File Shares** folders, there are two sort options by "Name" and "Size". There is no option to sort by Date. So it is difficult to find the recently created files. We need to use the Search by prefix option always.

So providing the Sort by Date option will be improve the productivity.

![image](https://user-images.githubusercontent.com/11418896/87130767-09584080-c2b1-11ea-9fc9-d023d4ed8374.png)

**Comment by MRayermannMSFT** [comment] 2020-07-13 17:57
Duplicate of #1731. At this time, the file share service does not return date created when listing things in a share:
https://docs.microsoft.com/en-us/rest/api/storageservices/list-directories-and-files#response-body

**Closed** 2020-07-13 17:58 UTC
Labels: :heavy_check_mark: duplicate

**Comment by khelkun** [comment] 2021-02-11 17:04
> Duplicate of #1731. At this time, the file share service does not return date created when listing things in a share:
> https://docs.microsoft.com/en-us/rest/api/storageservices/list-directories-and-files#response-body

@MRayermannMSFT You can get directories and files properties (including Last-Modified) through those routes:
https://docs.microsoft.com/en-us/rest/api/storageservices/get-file-properties
https://docs.microsoft.com/en-us/rest/api/storageservices/get-directory-properties

I wanted to point that out but I guess it's a performance issue to query every single items in a file share directory only to get the Last-Modified date.
Still this feature would be a very nice to have.

**Comment by MRayermannMSFT** [comment] 2021-05-10 17:02
> I wanted to point that out but I guess it's a performance issue to query every single items in a file share directory only to get their Last-Modified dates.

Yes exactly. :)
