### ISSUE TITLE
Error during an import file in TABLE

### ISSUE THREAD

**Issue by giuale88** [microsoft/AzureStorageExplorer#5416] opened 2022-02-08 11:56 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.1

### Regression From

1.22.0

### Architecture

x64

### Platform

Windows

### Bug Description

An RestError appear during an update from import

### Steps to Reproduce

Steps:
Select TABLE X
import file.csv
if the record exist an error appear

### Actual Experience

An error appear during the import

**Comment by giuale88** [comment] 2022-02-14 15:12
Help us please!

**Comment by MRayermannMSFT** [comment] 2022-02-14 18:36
Hi @giuale88 a fix will be going for this in our upcoming release. In the meantime, if you are blocked, you can download 1.21 here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.21.3

Duplicate of #5387

**Closed by MRayermannMSFT** 2022-02-14 18:36 UTC
