### ISSUE TITLE
Colored tabs based on subscription name

### ISSUE THREAD

**Issue by lucaciup** [microsoft/AzureStorageExplorer#2239] opened 2019-11-07 16:15 UTC
Whenever I have multiple table storage tabs pinned and they are from different subscriptions, it's really hard to know if the tab I am editing is a production related one or a development one. This makes the whole editing process very error prone.

I would propose a solution similar to the one from SQL Server Management Studio. In SSMS you can assign a custom color to individual servers. Thus, each new query window connected to that server would have a colored footer.

I know that if we hover over the tab, it shows the entire path (including subscription name) but something more visual would help us avoid costly mistakes.

**Comment by jinglouMSFT** [comment] 2019-11-07 18:35
Thank you for the nice suggestion.  This is something we are considering and is on our backlog of work items.  However, we can't just rely on the color to differentiate the tabs .  It doesn't meet the accessibility standards.  We'll have to look for something else to address this.

**Comment by MRayermannMSFT** [comment] 2019-11-11 19:24
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/20

**Closed by MRayermannMSFT** 2019-11-11 19:24 UTC
Labels: :bulb: feature request
