### ISSUE TITLE
User Install Setup similar to Azure Data Studio and VS Code

### ISSUE THREAD

**Issue by rbharathkumar** [microsoft/AzureStorageExplorer#3146] opened 2020-06-25 06:02 UTC
**Is your feature request related to a problem? Please describe.**
Unable to install or update Azure Storage Explorer without Administrative Privileges.

**Describe the solution you'd like**
It would be great to have a user install setup similar to how Azure Data Studio and VS Code have.

**Additional context**
We have remote desktops where we do not have administrative privileges and sometimes we see crashes happening which I hope would have been fixed. I have seen colleagues still using the 1.8 version of the software.

**Comment by jinglouMSFT** [comment] 2020-06-25 17:34
Duplicate of #1108.  Please take a look at #1108 to see if that is what you are looking for.  Thanks.

**Closed by jinglouMSFT** 2020-06-25 17:34 UTC

**Comment by rbharathkumar** [comment] 2020-06-28 10:23
Thank you for your response. I see the option has been added since the 1.13 version.
I had to request help to first uninstall the existing 1.12 version before installing the newer verson..
But good to see that the option was available. Thank you for all the work..
