### ISSUE TITLE
Metadata key names are displaying and persisting as lowercase only

### ISSUE THREAD

**Issue by melatronix** [microsoft/AzureStorageExplorer#2959] opened 2020-05-11 19:08 UTC
**Storage Explorer Version**: 1.13.0
**Build Number**: 20200430.5
**Platform/OS**: Windows 10
**Architecture**: x64

## Bug Description ##
When viewing/updating a blob's metadata (User Properties), the metadata key names are always displayed and saved as lowercase ...regardless if the metadata data was originally persisted as upper or mixed case.

## Expected Experience ##
Metadata key names should maintain case for display and persistence.

**Comment by MRayermannMSFT** [comment] 2020-05-18 18:32
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/2573

Long story short, metadata keys hould be treated case insensitively.
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-properties-metadata#set-and-retrieve-metadata

**Closed by MRayermannMSFT** 2020-05-18 18:32 UTC
