### ISSUE TITLE
A11y_AzureToolsStorageExplorer_Attachtolocalemulator_Attachtolocalemulator_Screenreader : NVDA is not announcing the editable content along with display name.

### ISSUE THREAD

**Issue by Radha2019** [microsoft/AzureStorageExplorer#1905] opened 2019-09-25 06:59 UTC
**" Check out Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing aster and easier.”**

**GitHubTags**: #A11y_AzureToolsStorageExplorer; #A11yMAS; #A11YTCS; #DesktopApp; #MAS1.3.1; #NVDA; Win10;3

**Environment Details:**
Application Name: Azure Tools Storage Explorer
Application Version: 1.10.0
Windows10

**Repro Steps:**
1. Launch Storage Explorer
2. Navigate to "Open Connect Dialog" pane present on left side of screen and hit enter.
3. Select "Attach to local emulator" radio button and hit enter on Next button.
4. "Attach to Local Emulator" screen gets opened.
5. Verify that all the elements of "Attach to Local Emulator" screen are accessible and MAS Compliant.
6.Start NVDA and navigate using the tab key.Observe the NVDA readings.

**​Actual:​**
NVDA is not announcing the editable content along with display name.

**Similar issue is observed for below scenarios:
Use a SAS URL : Attach with SAS URL:**
1. Launch Storage Explorer
2. Navigate to "Open Connect Dialog" pane present on left side of screen and hit enter.
3. Select "Use a SAS URL" radio button and hit enter on Next button.
4. "Attach with SAS URL" screen gets opened.
5. Verify that all the elements of "Attach with SAS URL" screen are accessible and MAS Compliant.

Expected:
NVDA should  announce the editable content along with display name.

**User Impact:**
Screen readers user will get unnecessarily get information three times.

**Recommendation:**
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx 

**MAS Reference:
MAS1.3.1**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4} 

Attachment for Reference
![1905_A11y_AzureToolsStorageExplorer_Attachtolocalemulator_Attachtolocalemulator_Screenreader](https://user-images.githubusercontent.com/55691739/65576751-2b860980-df90-11e9-8bd9-9913616a4c94.png)

**Comment by MRayermannMSFT** [comment] 2019-11-19 21:59
This is related to #1891 and will be fixed when the PR for that is merged. 😀

**Comment by MRayermannMSFT** [comment] 2019-11-20 18:27
Fix merged into master.

**Closed by MRayermannMSFT** 2019-11-20 18:27 UTC
Labels: :wheelchair: MAS, :wheelchair: accessibility

**Comment by MRayermannMSFT** [comment] 2020-01-27 18:19
@Radha2019 @Charanrajkb @nirmalsahoo @Suraj1200499 @vinodbk197

Please verify whether or not this bug was fixed to your satisfaction in the latest release of Storage Explorer. You can obtain that release from https://www.storageexplorer.com

If the bug has not been fixed to your satisfaction, please:
- Explain how did the fix not meet your expectations.
- Tell us exactly how we can meet your expectations. If there is more than one way to do so, feel free to list the different ways.

**Comment by vinodbk197** [comment] 2020-02-04 14:31
Verified this issue on:Azure Tools Storage Explorer (Version: 1.12.0)
The issue is no longer to reproduces, Hence closing this bug.

**Comment by fsteffi** [comment] 2023-02-17 12:28
GithubTags:#Closed;

**Comment by mstechie** [comment] 2023-03-05 18:33
GitHubTags:#BM-TCS-StorageExplorer-Win32-Sep2019;
