### ISSUE TITLE
Ability to Pause downloads

### ISSUE THREAD

**Issue by kylejohnstonGV** [microsoft/AzureStorageExplorer#7207] opened 2023-08-22 20:28 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

On Azure, I would like to be able to pause downloads and be able to set them to resume at a certain time

### Desired Solution

Provide the ability to pause downloads and resume them at a set time

**Comment by MRayermannMSFT** [comment] 2023-08-23 02:07
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/1279

**Closed by MRayermannMSFT** 2023-08-23 02:07 UTC
