### ISSUE TITLE
Cannot Clear Queue if all message on queue are hidden

### ISSUE THREAD

**Issue by PureKrome** [Microsoft/AzureStorageExplorer#82] opened 2018-04-26 08:15 UTC
![image](https://user-images.githubusercontent.com/899878/39293887-7ac73154-497d-11e8-9a82-4547b2e9ef59.png)

**Storage Explorer Version:**
1.0.0

**OS Version:**
Windows 10 most recent blah blah blah

**Steps to Reproduce:**

1. Add a message to a queue
2. Pop message with visibility to something short, like 20 secs.
3. Refresh Queue in ASE
4. You should now see, what I'm seeing, in that image, above.
5. Cry.

**Expected Experience:**
Regardless of the queue visibility, I would _hope_ I should be able to nuke all messages in a queue, regardless of their visibility.

**Actual Experience:**
Refer to picture, above.

Pew pew!

**Comment by xt0rted** [comment] 2018-04-26 08:52
The .net webjobs sdk has had bugs where messages go into the poison queue but aren't also removed from the main queue. Then your job gets stuck in an endless loop of re-processing a bad message, over and over and over. Since the messages aren't visible in the portal or ASE it's really difficult to recover from this 😢

I'd love the ability to purge a queue, or single message, no matter what the visibility of the messages is.

**Comment by MRayermannMSFT** [comment] 2018-05-10 23:25
Duplicate of #135

**Closed by MRayermannMSFT** 2018-05-10 23:25 UTC
Labels: feature request
