### ISSUE TITLE
Preview of parquet files

### ISSUE THREAD

**Issue by rvgfox** [microsoft/AzureStorageExplorer#6358] opened 2022-12-12 12:21 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

It would be nice to view the parquet files in preview

### Desired Solution

Preview parquet files in tabular mode.

**Comment by JasonYeMSFT** [comment] 2022-12-12 18:50
This is a duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/6153. Since you mentioned a tabular mode, if you have a rough idea of how you expect parquet files can be previewed in mind, please share your ideas in that issue. We are still debating on how we want to let people preview parquet data.

**Closed** 2022-12-12 18:50 UTC
Labels: :heavy_check_mark: duplicate
