### ISSUE TITLE
File with ":" in name cannot be downloaded by AzCopy

### ISSUE THREAD

**Issue by grahambunce** [microsoft/AzureStorageExplorer#2455] opened 2019-12-17 10:43 UTC
**Storage Explorer Version**: 1.11.1
**Build Number**: 20191121.1
**Platform/OS**: Windows 19
**Architecture**: x64
**Regression From**:  Yes, upgraded from older version (not sure which) and it was working fine.

## Bug Description ##
Navigate to blob storage. View files with *.log suffix. Attempt to "open" (or download) any file. Warnng dialog "Security Warning. This file is potentially unsafe. Are you sure you want to open it?". Click yes. File is downloaded but is empty.

if "download" selected then no dialog box but downloaded file is also empty.

## Steps to Reproduce ##
See description

## Expected Experience ##
File to download as previous versions without warning dialog box and to correctly contain file content.

## Actual Experience ##
Incorrect dialog box and empty file

## Additional Context ##
File is correctly downloaded via the Azure Portal, so it's not a file issue. Portal is more unwieldy to use than AZ Explorer so is not a viable option.

File content type is "text/plain"

Related to #164

**Comment by JasonYeMSFT** [comment] 2019-12-17 22:30
I have just verified that ".log" is one of the file extensions in our white list. I have also tried downloading *.log files and they don't give any warning. If possible, can you create an empty file with the same name and share a SAS with us so we can test? Or at least you can share the exact blob name with us.

**Comment by grahambunce** [comment] 2019-12-18 11:00
An example: tst-patronprofile-api-test/2019/12/2019-12-18/10:00.log

**Comment by JasonYeMSFT** [comment] 2019-12-18 18:18
Thanks for the repro case. The cause of it is a known AzCopy bug which doesn't encode `:` properly when downloading blobs to local file system. We are working on a fix for this right now.

**Comment by MRayermannMSFT** [comment] 2020-01-06 18:44
Looks like we already had a bug for this! Duplicate of #2297

**Closed by MRayermannMSFT** 2020-01-06 18:44 UTC
Labels: :beetle: bug, :gear: azcopy
