### ISSUE TITLE
The delete icon of custom environment displays empty when pressing 'Tab' to focus it

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6007] opened 2022-08-08 08:31 UTC
**Storage Explorer Version:** 1.26.0-dev
**Build Number:** 20220808.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open the connect dialog.
2. Click 'Subscription -> Custom Environment -> Management custom environments...'.
3. Add one custom environment.
4. Press 'Tab' to focus the delete icon.
5. Check whether the delete icon displays well.

## Expected Experience ##
The delete icon displays well.

## Actual Experience ##
The delete icon displays empty.
![image](https://user-images.githubusercontent.com/87792676/183371217-d124b418-e94d-47c6-a1f5-116d82fe6735.png)

**Comment by craxal** [comment] 2022-08-30 16:35
This only reproduces in the Light theme. The bug is due to a mistyped color value missing the "#".

**Comment by v-xianya** [comment] 2022-08-31 01:33
Verified this issue on the build main/20220831.1. Fixed. So, we are going to close it.

**Closed by v-xianya** 2022-08-31 01:33 UTC
Labels: 🧪 testing
