### ISSUE TITLE
Feature Request - Color Code Tabs

### ISSUE THREAD

**Issue by rdefreitas** [Microsoft/AzureStorageExplorer#276] opened 2018-06-08 14:22 UTC
Similar to being able to color a connection in SSMS, it would be useful to be able to color-code individual blob/cosmos/data lake accounts or even whole subscriptions, so that you can easily filter visually between different environments (set the tab color to RED for production, for example)

**Comment by craxal** [comment] 2018-06-08 15:43
Duplicate of #20. Please continue the discussion there!

**Closed by craxal** 2018-06-08 15:43 UTC
Labels: :white_check_mark: duplicate
