### ISSUE TITLE
Make it possible to rename a local/attached storage account

### ISSUE THREAD

**Issue by nspiteri** [microsoft/AzureStorageExplorer#3375] opened 2020-08-10 12:20 UTC
**Is your feature request related to a problem? Please describe.**
If you attach to a storage account and afterwards you want to change the name, you're unable to do it

**Describe the solution you'd like**
I'd like to be able to right click and change the storage account name

**Describe alternatives you've considered**
Detaching and attaching the storage account

**Comment by craxal** [comment] 2022-10-14 18:52
Duplicate of #2819.

**Closed by craxal** 2022-10-14 18:52 UTC
Labels: :heavy_check_mark: duplicate, :bulb: feature request, :gear: emulator
