### ISSUE TITLE
The Size column in Blobs->Containers->My Container is not as granular anymore

### ISSUE THREAD

**Issue by spacecat** [microsoft/AzureStorageExplorer#7411] opened 2023-10-16 14:10 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.2

### Architecture

i86

### Platform

Windows

### OS Version

Windows 11 Pro

### Bug Description

The Size column for Blobs->Containers does not show granular detail about files anymore.

For example:

I have a file that is 1.20 GB.

Before it would should 1.20 GB in that column.

Now it shows 1 GB. That's really annoying. Btw, it's been like this since 5 years or more that I've used Storage Explorer. If it aint broken don't try to fix it.

Please revert back to the way it was.

Thanks.

### Steps to Reproduce

See above.

### Actual Experience

See above.

**Comment by MRayermannMSFT** [comment] 2023-10-16 17:25
I believe this is a duplicate of this: https://github.com/microsoft/AzureStorageExplorer/issues/7296

**Closed** 2023-10-16 23:31 UTC
Labels: :heavy_check_mark: duplicate, :heavy_check_mark: merged

**Comment by spacecat** [comment] 2023-10-19 14:13
> I believe this is a duplicate of this: #7296 So this will be fixed in 1.32.0, which is going out soon (I hope 🙃).

Okay, that's great to hear. Thanks.
