### ISSUE TITLE
Toolbar not visible in CosmosDb Explorer

### ISSUE THREAD

**Issue by DJKampouris** [Microsoft/AzureStorageExplorer#968] opened 2018-12-06 00:12 UTC
![2018-12-05_19-10-41](https://user-images.githubusercontent.com/9744187/49552451-b1ca4580-f8c1-11e8-99e6-ecd922398a00.png)

Upgraded to version 1.6.0 and when going to a Documents collection in CosmosDb explorer, the toolbar is not visible and not documents are loaded.

**Comment by scholtes** [comment] 2018-12-06 15:59
See #971 for reproduction steps

**Comment by drhkocher** [comment] 2018-12-06 16:39
Same for me. Back to 1.5.0

**Comment by craxal** [comment] 2018-12-06 23:13
Duplicate of #971.

**Closed by craxal** 2018-12-06 23:13 UTC
Labels: :gear: cosmosdb, :white_check_mark: duplicate, :x: bug

**Comment by MRayermannMSFT** [comment] 2018-12-14 22:39
For anyone facing this issue, we're shipping a hotfix to fix this regression. Until then, if you'd like to preview the hotfix simply go to the "Help" menu on Windows and Linux/app menu on macOS ->" Opt in to Insider Builds" We'll still doing some final testing and a few other fixes, but we wanted to at least let people who needed the fixes we have done so far, have them. Thanks!
