### ISSUE TITLE
Quick Access items not saving items

### ISSUE THREAD

**Issue by Kizmar** [microsoft/AzureStorageExplorer#4879] opened 2021-09-02 12:23 UTC
I've added the same two storage accounts to quick access three times now and the next day when I open things up, Quick Access is empty again.

**Comment by MRayermannMSFT** [comment] 2021-09-10 17:45
@Kizmar are you perhaps opening multiple Storage Explorer windows at once? Can you also tell us:
- Storage Explorer version
- OS

**Comment by Kizmar** [comment] 2021-09-10 17:48
Nope, just one window.

Version: 1.20.1
OS: Windows 10

**Comment by MRayermannMSFT** [comment] 2021-09-20 05:15
@Kizmar can you please check 2 things?
1. Go to Help > Toggle Developer tools, go to the Application tab, then navigate to Local Storage > file://, and make sure you have an entry for `StorageExplorer_InPlaceQuickAccessItems_v1`:

![image](https://user-images.githubusercontent.com/21112697/133959264-32855767-3d62-4902-b790-707e2719ce4e.png)

2. In your start menu, search for "Credential Manager". Open the search result, and then go to "Windows Credentials". In that list, make sure you have `Microsoft_StorageExplorer/app`:

![image](https://user-images.githubusercontent.com/21112697/133959407-c3558b69-4796-47fa-8fee-bbe68f0242ad.png)

**Comment by Kizmar** [comment] 2021-09-20 12:42
I do have that entry in the Local Storage. (Quick Access is currently showing empty)

![image](https://user-images.githubusercontent.com/606842/134003751-6b1d0273-9614-41a1-b32a-bea0358da5e8.png)

I also have an entry in Credential Manager: 

![image](https://user-images.githubusercontent.com/606842/134003921-caa9c137-d57d-438f-8eb6-b2902b823b24.png)

**Comment by Kizmar** [comment] 2021-10-05 12:48
Hey, the two things I added to Quick Access a week and a half ago are still there after opening it today. There was a bit of a rocky authentication flow though. Authorized a couple tenants then had to close and reopen the app. Seems fine now though.

**Comment by JasonYeMSFT** [comment] 2022-01-12 19:22
@Kizmar Are you still consistently seeing this problem? When the problem occur, could you try to keep refreshing the tree ("refresh all" button at the top) to see if it is able to get the items render or disappear? From your description, it seems that the data is still there but something goes wrong at the rendering phase. Refreshing the tree will force the Quick Access to reload its children. If the problem randomly occurs at the rendering phase, keeping refreshing the tree should be able to reproduce the issue.

**Comment by Kizmar** [comment] 2022-01-12 21:02
Items still aren't showing up under Quick Access. I've stopped trying to use it at this point.

If I repeatedly hit "Refresh All", I do see items (under Quick Access) show up and disappear very quickly every few times. So fast I can't even tell what is showing, I just see everything below it jump down and back up. It does seem like something is removing the items.

**Comment by JasonYeMSFT** [comment] 2022-01-12 21:40
When the items are gone. Is there an expander icon next to the Quick Access node? If yes, is it showing up as expanded or collapsed? I wonder if it's due to styling issue or some of our code is accidentally removing loaded items in the tree.

![Screen Shot 2022-01-12 at 1 37 47 PM](https://user-images.githubusercontent.com/39359541/149225243-24f7b68c-6a27-4ee3-84a6-eae1e4e0004f.png)

**Comment by Kizmar** [comment] 2022-01-12 21:42
@JasonYeMSFT  No expand icon
![image](https://user-images.githubusercontent.com/606842/149225687-d1904231-9213-4bfe-911e-bfc8bbf9c825.png)

**Comment by Kizmar** [comment] 2022-01-12 22:08
@JasonYeMSFT If I open up the Developer Tools panel: the expander icon has "display: none" on it. If I change it to "display: block", it shows up and I can toggle it, but there is no list that shows. In the elements, there is an empty `<ul>` in that section.

**Comment by JasonYeMSFT** [comment] 2022-01-13 01:21
OK, it's not a styling issue. It's good to know that you are familiar with the dev tools. Could you please do me one more favor to further locate the cause of the problem?

1. Open the dev tools again
2. Open the source file named `QuickAccessProducer` (ctrl + P and enter the file name)
3. Search for `nodePromises = quickAccessItems.map` in the file and set a break point on that line, which should be line 70
4. Go back to the tree view and refresh the tree once.
5. When the break point is hit, hover over the `quickAccessItems` above the paused line and share the contents of the object with us. You can call `JSON.stringify(quickAccessItems.map((it) => { delete it.producerArgs; return it; }))` in the console to get the serialized version of the object. It also trims the `providerArgs` part of the object since that will contain the credentials for your resource.

The object should look like an array of items, each of which has `id`, `displayName`, `providerArgs` and `providerNamespace`. I may be able to reproduce the issue by mocking the same list of items of yours.

**Comment by Kizmar** [comment] 2022-01-13 13:55
Looks like the array is empty:
![image](https://user-images.githubusercontent.com/606842/149342943-dffcc076-5052-4a54-b2f2-4be8adb7c605.png)

**Comment by JasonYeMSFT** [comment] 2022-01-13 18:16
That means there is no data or some error occurred while decrypting the data. If there is an error, we should have logged an error message in the console. Please check that. I suspect that something is occasionally deleting the `Microsoft_StorageExplorer/app` entry in the credential manager. That entry stores our encryption/decryption key for the quick access items. If my hypothesis is correct, you should be able to add a quick access item and see them immediately showing up. Does that match your observation? Later when something deletes the key, we lose the capability to decrypt the exiting quick access items and they appear to be gone.

**Comment by Kizmar** [comment] 2022-01-13 18:23
I originally kept an eye on the Console as well, and wasn't seeing any messages show up there. I just added a new item to Quick Access. It shows. I closed, rebooted the VM and re-opened and it's still there. I'll keep an eye on it and see if/when it disappears again.

**Comment by JasonYeMSFT** [comment] 2022-01-13 18:46
While it's still there, could you save the value of the "modified date" for the entry `Microsoft_StorageExplorer/app` in the credential manager? If it gets deleted and recreated later we can tell then.

**Comment by Kizmar** [comment] 2022-01-13 18:51
That entry currently says Modified: 2/18/2021

**Comment by JasonYeMSFT** [comment] 2022-04-19 21:57
It's been a while since this issue is opened but there is not much we can do for now. I am going to close this issue. If you run into the same problem again, please open a new issue and link this one. We can then revisit this issue.

**Closed by JasonYeMSFT** 2022-04-19 21:57 UTC
Labels: :heavy_check_mark: no repro, :grey_question: investigate, :gear: quick access
