### ISSUE TITLE
Child process not starting in a timely manner

### ISSUE THREAD

**Issue by tehlen** [Microsoft/AzureStorageExplorer#281] opened 2018-06-11 19:33 UTC
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10
**Architecture**: x64
**Regression From**: 1.1.0

#### Steps to Reproduce: ####
1. Open a Blob Container

#### Expected Experience: ####
Blob Container browser shows contents

#### Actual Experience: ####
Browser window closes and error message "The child process failed to start in a timely manner."
![seerror](https://user-images.githubusercontent.com/24721700/41252930-4ac7b4bc-6d84-11e8-9cf0-8e3cc8fb1193.PNG)

**Comment by craxal** [comment] 2018-06-11 20:23
If you open the developer tools (F12), do you get any error outputs? If you're working with other Azure storage services (files, tables, etc.), do they encounter the same issue?

**Comment by JakeRadMSFT** [comment] 2018-06-11 20:33
We haven't been able to reproduce the issue ... so I don't believe it's version specific but likely something environmental.

If you could also try restarting the machine or making sure all StorageExplorer processes are killed and try again, that might resolve the delayed process start time.

How much available memory does the machine have? Is it a Virtual Machine?

**Comment by tehlen** [comment] 2018-06-11 21:27
Sorry I missed a previous email with the old version disregard my request.  I will do some more debugging and get back to you

Thank you,
Tim Ehlen
________________________________

**Comment by JakeRadMSFT** [comment] 2018-06-11 21:29
Please report back if the previous version works.

Cheers,
Jake

**Comment by tehlen** [comment] 2018-06-12 14:19
Enclosed is the log with the errors…

It looks like this happens for all of the types and seems to happen for all people in Chevron, they have rolled back to 1.0.

Thank you,
Tim Ehlen<https://www.linkedin.com/in/timehlen>
Senior Product Manager – Azure CAT | Microsoft |  (o) 346-718-6187 (m) 713-478-0168

[MSFT_logo_Gray DE sized SIG1.png]

**Comment by tehlen** [comment] 2018-06-12 15:59
The previous version works.

Thank you,
Tim Ehlen<https://www.linkedin.com/in/timehlen>
Senior Product Manager – Azure CAT | Microsoft |  (o) 346-718-6187 (m) 713-478-0168

[MSFT_logo_Gray DE sized SIG1.png]

**Comment by MRayermannMSFT** [comment] 2018-06-27 17:55
Hello everyone! If you are running into this issue, please attempt the following steps to mitigate:

1. Open "C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\se-process-manager\dist\Host\ForkedProcess.js" in your text editor of choice (if you are using an editor other than VSCode, make sure to run the editor as admin before opening the file)
2. Find `ForkedProcess._startupTimeoutInSeconds = 20;`
3. Change the `20` to a larger value, something around `60` or even `120` is probably a safe place to start.

If the issue is mitigated, awesome! If not, you can continue trying to up the value until the process has enough time to start. And if you do end up doing that, please comment on this issue with what value you ended up using. We will be increasing the value in our next release, and so if you needed a very high value, we would love to know.

Thanks!

**Comment by MRayermannMSFT** [comment] 2018-07-05 22:37
Merged in to rel/1.3.0, will be shipped with 1.3.0. We went with a 90 second timeout. Hopefully that will be enough.

**Comment by JoaoRaimundo14** [comment] 2018-07-10 14:54
Still get the same error

**Comment by MRayermannMSFT** [comment] 2018-07-10 21:44
@JoaoRaimundo14 , can you try the instructions on setting the timeout period, and do a longer value? I'm curious as to how long your machine needs. I did not expect anyone to need 90 seconds (or longer).

**Comment by donkz36** [comment] 2018-07-18 02:51
Have tried up to 240 and am still getting the same error.

**Comment by MRayermannMSFT** [comment] 2018-07-18 16:00
If y'all open task manager and watch the group of Storage Explorer processes as you open the tab, do you at least see a new process appear? You'll probably need to sort by name:
![image](https://user-images.githubusercontent.com/21112697/42893311-d432733a-8a68-11e8-940f-e2ac56a7214e.png)
Additionally, what other software do y'all have running on your machine? Any anti-virus or monitoring software?

**Comment by gitmichalk** [comment] 2018-09-11 13:45
Hi all, 
I have this issue but my version is 1.4.1

![image](https://user-images.githubusercontent.com/36610941/45364034-6a415f80-b5d9-11e8-9c02-57f477d52703.png)

![image](https://user-images.githubusercontent.com/36610941/45364065-79281200-b5d9-11e8-80b4-4c85c964e761.png)

So far nothing help.

Any advice?

**Comment by Helen2011** [comment] 2018-09-20 02:51
Just installed 1.4.1, increased ForkedProcess._startupTimeoutInSeconds, but no luck, any advice?

![image](https://user-images.githubusercontent.com/777511/45793032-3b249100-bc5e-11e8-8514-f29b3e83349a.png)

**Comment by PandaShoots** [comment] 2018-10-04 20:49
Okay I've still got this issue in 1.4.2 on Windows 10. It looks like the child process is timing out after 20 seconds even though the default ForkedProcess._startupTimeoutInSeconds is set to 90 seconds in the config file and bumping it up to say 300 makes no difference.

**Comment by jLynx** [comment] 2018-10-07 20:59
I'm having this issue 
![image](https://user-images.githubusercontent.com/4393979/46586856-d8961680-cae0-11e8-9c2e-8a08c8e0c403.png)

**Comment by mafer09** [comment] 2018-10-08 21:44
Issue has not been resolved. Still encountering this issue while using version 1.4.2. Increased 
![image](https://user-images.githubusercontent.com/9340526/46635244-8b2d9f80-cb08-11e8-9c18-5c9efba9e77c.png)

**Comment by gitmichalk** [comment] 2018-10-17 08:30
Hello all victims :)

For workaround I suggest start using Cloud Explorer in Visual Studio (like I did - if they don't know how to resolve this problem). When you login into yours account on Azure you should have access for all Storage Accounts where you can open Blobs or tables you want without any problems.

references:
https://docs.microsoft.com/pl-pl/azure/vs-azure-tools-resources-managing-with-cloud-explorer

Kind Regards,
Michal

**Comment by craxal** [comment] 2018-10-17 18:14
Hey folks! Something that might help us narrow this down: try launching Storage Explorer from the command line and observe the output. If the child processes are working correctly, you should see some output from them in the command line. It might get messy, but you're looking for words like "child", "process", and "message". You should also see process IDs.

**Comment by Caldina777** [comment] 2018-11-08 21:53
I can't believe we are up to version 1.5 of Storage explorer and this issue is STILL happening, it has been happening since version 0.9,7 (I thankfully kept an old install of 0.9.6).

**Comment by jinglouMSFT** [comment] 2018-11-08 22:05
@Caldina777 There are many root causes to run into this issue. We haven't been able to repro this issue in house.  Have you tried with these steps to mitigate the issue?

- Open "C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\se-process-manager\dist\Host\ForkedProcess.js" in your text editor of choice (if you are using an editor other than VSCode, make sure to run the editor as admin before opening the file)
- Find ForkedProcess._startupTimeoutInSeconds = 20;
- Change the 20 to a larger value, something around 60 or even 120 is probably a safe place to start.

This is to help extend the timeout.  

Please let us know the findings. Thanks.

**Comment by gdamyanova-fourth** [comment] 2019-01-17 13:34
Ver. 1.6.2 - still has it. ForkedProcess._startupTimeoutInSeconds = 240; doesn't help. What is the oldest version that doesn't manifest this behavior? Can I have a link, please? I think that it's really inconvenient that no older versions are available.

**Comment by jinglouMSFT** [comment] 2019-01-17 18:51
We are working on capturing additional logs when this happens to help us further diagnose the root cause.  If bumping up the timeout value doesn't help you, feel free to use a version that works for you. You can find our previous release here on Github under the "Releases" tab.  We have all releases there since our GA.   
![image](https://user-images.githubusercontent.com/10081483/51341218-abdd8d80-1a45-11e9-8a25-46236dd12987.png)

**Comment by gdamyanova-fourth** [comment] 2019-01-18 07:37
Thanks jinglou!
Downloaded ver. 1.0.0 and no issues so far.

**Comment by jaysheelkalgal** [comment] 2019-01-28 14:04
Hi,

I am using version 1.6.2 on Mac on Mojave 10.14.3. I get the below error when trying to expand the blob container or file share.

<img width="991" alt="storage_expolrer_error" src="https://user-images.githubusercontent.com/47111184/51841060-b811f680-2333-11e9-8586-867f681771d3.png">

**Comment by craxal** [comment] 2019-01-28 16:56
@jaysheelkalgal, this doesn't appear to be related to the child process issue this thread is about. Have you followed our [troubleshooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2fazure%2fstorage%2fblobs%2ftoc.json)? If you need assistance, we invite you to submit a [service request](https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request). If you believe this behavior is a bug, you many open a [new issue](https://github.com/Microsoft/AzureStorageExplorer/issues/new/choose).

**Comment by jaysheelkalgal** [comment] 2019-01-28 17:08
I have a storage account name and key. I am trying to connect using the account name and key method. I dont have any proxy settings on my Mac. I am able to connect but when I try to expand the Blob container I get this error. Is there any other troubleshooting I should try ?

**Comment by jaysheelkalgal** [comment] 2019-01-29 08:17
I would need to get those details from our Admin team. Probably in a day or two.

**Comment by MRayermannMSFT** [comment] 2019-04-17 19:00
Closing due to lack of activity.

**Closed by MRayermannMSFT** 2019-04-17 19:00 UTC
Labels: :beetle: bug, :heavy_check_mark: merged
