### ISSUE TITLE
Pop up a Cloud Explorer window when clicking the 'Refresh All' using the mouse middle key

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2556] opened 2020-01-17 09:37 UTC
**Storage Explorer Version**: 1.12.0
**Build**: [20200117.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3393793)
**Branch**: master
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Open Storage Explorer.
2. Click 'Refresh All' using the mouse middle key.
3. Check the results.

**Expect Experience:**
No window pops up.

**Actual Experience:**
Pop up a Cloud Explorer window.
![image](https://user-images.githubusercontent.com/54055206/72599893-82ec2300-394d-11ea-8d46-7881bcc6b097.png)

**More Info:**
This issue also reproduces when clicking 'Collapse All' using the mouse middle key.

**Comment by JasonYeMSFT** [comment] 2020-01-17 19:08
This is caused by the default behavior for <a> elements in Electron. It also reproduces for the "learn more" links in our various dialogs.

**Comment by JasonYeMSFT** [comment] 2020-01-21 18:52
It is a very good catch. Unfortunately we won't fix it because it is not directly impacting user experience.

**Closed by JasonYeMSFT** 2020-01-21 18:52 UTC
Labels: :heavy_check_mark: won't fix, 🧪 testing

**Comment by v-xianya** [comment] 2020-01-23 06:11
Hi @JasonYeMSFT There is one question need your help😀

What's the expected behavior after middle clicking link in Storage Explorer?
The pages prompt are incompletely after middle clicking the below links.
1. Link 'Learn more about access tiers...'.
![image](https://user-images.githubusercontent.com/41351993/72960465-c250be80-3de8-11ea-8857-ed2348f5e481.png)

2. Link 'Microsoft Privacy Statement' on Telemetry Settings.
![image](https://user-images.githubusercontent.com/41351993/72960517-f6c47a80-3de8-11ea-8be7-79368504d299.png)
3. Link 'Learn more about default ACLs'.
![image](https://user-images.githubusercontent.com/41351993/72960592-4440e780-3de9-11ea-9ce8-bc608d7c4eaa.png)

**Comment by JasonYeMSFT** [comment] 2020-01-23 16:40
@v-xianya , they are not supposed to be able to do anything with middle click. We will consider disabling all behaviors associated with middle click on those links.

**Comment by v-xianya** [comment] 2020-02-03 06:43
@JasonYeMSFT OK, I see it. Thank you!
