### ISSUE TITLE
Cannot search by prefix in Storage Explorer, it's available in the Azure Portal Storage Browser

### ISSUE THREAD

**Issue by steve-torchia** [microsoft/AzureStorageExplorer#6359] opened 2022-12-12 13:40 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

i86

### Storage Explorer Build Number

20221018.5

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Storage explorer does not allow me to search by prefix in blob storage.   For the same container/folders in the Azure portal version, the functionality is available:

![image](https://user-images.githubusercontent.com/3823841/207058291-5d81c630-e9e3-4627-a6ae-11f9e995932e.png)

![image](https://user-images.githubusercontent.com/3823841/207058675-6ac59dbb-4fda-4051-91fa-697d12e9cbe5.png)

### Steps to Reproduce

Launch Storage Explorer
go to blob container 
Notice that the filter or search by prefix functionality is not available

### Actual Experience

If you go to the same container in the Azure Portal to browse that blob container, you are able to search by prefix

**Comment by MRayermannMSFT** [comment] 2022-12-12 18:48
Duplicate of: https://github.com/microsoft/AzureStorageExplorer/issues/2189

**Closed by MRayermannMSFT** 2022-12-12 18:48 UTC
