### ISSUE TITLE
StorageError-"Server encountered an internal error. Please try again after some" while uploading blobs to local storage on Azure Storage Emulator

### ISSUE THREAD

**Issue by mvmnrao** [Microsoft/AzureStorageExplorer#817] opened 2018-10-29 11:13 UTC
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10

#### Steps to Reproduce: ####
1. Downloaded blobs from cloud to local disc.
2. Uploading to blob container on Storage Emulator using Microsoft Azure Storage Explorer.

Error is also reproducible while uploading using AzCopy.

**Exception Details:**
```json
{
  "name": "StorageError",
  "message": "Server encountered an internal error. Please try again after some time.\nRequestId:15694ebf-d08e-4daa-955f-029800ca11d0\nTime:2018-10-29T11:06:57.1328600Z",
  "stack": "StorageError: Server encountered an internal error. Please try again after some time.\nRequestId:15694ebf-d08e-4daa-955f-029800ca11d0\nTime:2018-10-29T11:06:57.1328600Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "InternalError",
  "statusCode": 500,
  "requestId": "15694ebf-d08e-4daa-955f-029800ca11d0"
}
```

**Comment by jinglouMSFT** [comment] 2018-10-29 18:18
Did you have your emulator running?  Storage Explore doesn't automatically start the emulator.

**Comment by mvmnrao** [comment] 2018-10-30 04:55
Hi,

Thank you for looking into it.

Yes, I am running emulator before trying the copy.

One more clue is, upload to local storage is failing only for few of the
blobs.

**Comment by jinglouMSFT** [comment] 2018-10-30 18:04
What kind of blobs are those that are failing?  Append blobs?  Page blobs? Block blobs?

**Comment by MRayermannMSFT** [comment] 2018-10-30 23:08
It sounds like this is an issue with the emulator. Can we ping someone on the emulator team to help investigate this?

**Comment by mvmnrao** [comment] 2018-10-31 01:30
Yes, we also suspect that, because we are getting this exception while
copying using AzCopy command also.

Please point me to right community.

**Comment by jinglouMSFT** [comment] 2018-10-31 19:12
I've already contacted the emulator team. Someone there will comment on the issue here.

**Comment by seguler** [comment] 2018-11-01 23:09
It turns out the emulator is unable to keep up with the amount of requests AzCopy is sending all at once. It is a known issue. We'll have to tweak it so that AzCopy is sending requests to the emulator at a slower rate.

**Comment by mvmnrao** [comment] 2018-11-02 09:06
>           It turns out the emulator is unable to keep up with the amount of requests AzCopy is sending all at once. It is a known issue. We'll have to tweak it so that AzCopy is sending requests to the emulator at a slower rate.

Could you let me know if there any ETA for this?
Also one more clue is that the entire thing works when the copy command is executed from Ukraine but not working from Hyderabad/INDIA.

**Comment by zezha-msft** [comment] 2018-11-02 18:30
@mvmnrao could you please clarify what is not working from Hyderabad? Are you uploading files to the public cloud?

**Comment by zezha-msft** [comment] 2018-11-05 22:36
Hi @mvmnrao, thanks for getting back to us. Could you please clarify what "local
storage created in Azure Storage Emulator" means?

@MRayermannMSFT Any insights?

**Comment by mvmnrao** [comment] 2018-11-06 06:05
I created local storage for development and debugging purpose. Please refer below link for the details, those are the steps I followed to setup local storage.

https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator

**Comment by zezha-msft** [comment] 2018-11-06 23:41
Hi @mvmnrao, thank you so much for getting back to me!

I see, so you are transferring blobs from the public cloud to the emulator directly. @MRayermannMSFT, what is the AzCopy command that Stg Exp uses in this scenario? Does it do a download from public cloud to a local cache first, and then upload to emulator from local?

**Comment by mvmnrao** [comment] 2018-11-08 05:37
Hi,
Below is the command we are using:
_/source:<<Cloud Account Name>> /dest:devstoreaccount1 /sourcekey:<<SourceKey>> /destkey:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw== /pattern:<<BlobName>> /snapshot /y /s /synccopy_
And yes, I believe AzCopy downloads blobs to local cache first and then it pushes to local storage and it is behavior of the AzCopy. I don't think there is other way AzCopy works?

**Comment by zezha-msft** [comment] 2018-11-08 07:42
I see. So you are using AzCopy V8. @EmmaZhu could you please help with this issue?

**Comment by mvmnrao** [comment] 2018-11-08 12:15
Sure @EmmaZhu , I will try this option and get back, thank you for inputs.

**Comment by craxal** [comment] 2018-12-17 21:08
Doesn't appear to be a Storage Explorer issue, so I will close.

@mvmnrao, @EmmaZhu, @zezha-msft, since this appears to be an emulator issue, please continue the thread at an appropriate location.

**Closed by craxal** 2018-12-17 21:08 UTC
Labels: :white_check_mark: mitigated, 🔍 external

**Comment by mvmnrao** [comment] 2018-12-19 06:01
@craxal would you mind sharing locations for AzCopy and Storage Emulator? I will post it there because this is still an issue for us and needs to be fixed.

**Comment by craxal** [comment] 2019-01-15 16:58
Unfortunately, I don't know where to go to post issues on Storage Emulator. There is a different emulator you can try: Azure/Azurite.

**Comment by fperreaultnv** [comment] 2019-07-17 20:11
This error started happening to me when I was using a different storage account connection string for the runtime (AzureWebJobsStorage) and for the actual BlobTriggerAttribute(Connection = "%ConfigSection:ConnectionString%")

**Comment by craxal** [comment] 2019-07-22 15:46
@fperreaultnv Are you referring to the .NET client library? We use the _JavaScript_ client library.

**Comment by fperreaultnv** [comment] 2019-07-22 15:51
@craxal Indeed I am.

**Comment by craxal** [comment] 2019-08-05 17:08
@fperreaultnv Are you suggesting then the problem is with the emulator? Since we don't yse the .NET client library, I'm not sure how that fits in here.

**Comment by philipp-bananaware** [comment] 2020-09-18 19:32
I tried to put (upload) multiple files on a container with SAS token, but get the same Response 500:
`PUT http://127.0.0.1:10000/devstoreaccount1/inbox/9jsV5uKbAEM.jpg?sv=2018-03-28&sr=c&sig=ax9Flsc5F9wtjwqjAt76P9akEE3s3Geiy%2Bzmlpry0WY%3D&st=2020-09-18T18%3A53%3A10Z&se=2020-09-18T19%3A53%3A10Z&sp=w 500 (Server encountered an internal error. Please try again after some time.)`
But it says "201 created" at the end...

**Comment by craxal** [comment] 2020-09-23 18:03
@philipp-bananaware What emulator are you using? Connecting to an emulator via SAS is not supported scenario, as it depends on whether the emulator supports authenticating requests using a SAS. If you continue to encounter issues, and you believe this to be a bug in Storage Explorer, please open a new issue.

**Comment by Dzoukr** [comment] 2021-08-13 09:49
It happened to me as well and it seems it's caused by a combination of an old (deprecated) emulator (now Azurite is the one you should use) and file name being too long (over 128 chars including container name).
