### ISSUE TITLE
unable to open blob containers from fresh azure storage emulator (not azurite) on latest versions

### ISSUE THREAD

**Issue by mithom** [microsoft/AzureStorageExplorer#6124] opened 2022-09-29 10:22 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Regression From

1.20.1

### Architecture

x64

### Storage Explorer Build Number

20220809.7

### Platform

Windows

### OS Version

Windows 10

### Bug Description

opening the following nested tabs results in an error when using old or new emulated blob storage using the azure storage emulator (not azurite, we use VS2019, which does not yet support azurite)
> Emulator & Attached
> Storage Accounts
> (Emulator - Default Ports) (Key)
> Blob Containers

### Steps to Reproduce

1. launch azure storage emulator
2. launch azure storage explorer
3. expand emulator blob containers
4.  get the error

### Actual Experience

getting following error:
[Uploading ase_error.txt…]()

### Expected Experience

seeing a list of available blob containers

### Additional Context

this storage emulator is deprecated, but works still perfectly as it used to.
Azurite is not yet supported in visual studio 2019 which we are using, and i've tried installing it separately, but could not configure the project to use azurite. So i would like to keep using the currently supported emulator.

**Comment by andresbnd** [comment] 2022-09-29 14:57
I have the same problem

**Comment by JasonYeMSFT** [comment] 2022-09-29 17:27
The error is not uploaded and it links to this issue. This might be a duplicate of this issue https://github.com/microsoft/AzureStorageExplorer/issues/5665

**Comment by eyhorn** [comment] 2022-09-30 03:43
Have the same problem. Rolled back to 1.24.3 and everything works just fine.

**Comment by mithom** [comment] 2022-09-30 11:01
@JasonYeMSFT on monday i will replicate the issue and reupload the error message file.

some extra info: i can still get blob containers to show by right clicking find container by name and knowing the name myself. It just fails to list them automatically, so this might be related to #5665 but definatly isn't a duplicate.

**Comment by MRayermannMSFT** [comment] 2022-10-03 17:40
Yes, this appears to be a duplicate of #5665

**Closed by MRayermannMSFT** 2022-10-03 17:40 UTC
