### ISSUE TITLE
Cannot connect to storage in Mac OS X & Windows

### ISSUE THREAD

**Issue by swainjo** [microsoft/AzureStorageExplorer#1524] opened 2019-07-02 09:56 UTC
**Storage Explorer Version**: 
**Build Number**: 20190701.8
**Platform/OS**: OS X 10.14.5
**Architecture**: 
**Regression From**:  

## Bug Description ##
When I try to connect to storage account using any method (SAS, Key, Connection String) I get the following error: "Error occurred while adding new connection: TypeError:Cannot read property 'uids' of undefined"

## Steps to Reproduce ##
Try to add a connection. All attempts get this error. 

## Expected Experience ##
Expect to connect. 

## Actual Experience ##
Fails.

## Additional Context ##
Connection to same storage accounts works fine on Windows version of Storage Explorer on the same machine using Parallels. *UPDATE* - This now fails in Windows version of Explorer after an overnight reboot.

Tried the steps in #726 & #788 - does not fix the error.

**Comment by swainjo** [comment] 2019-07-03 06:41
Detailed error message from Windows:

{
  "name": "TypeError",
  "message": "Cannot read property 'uids' of undefined",
  "__zone_symbol__error": {
    "originalStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
    "zoneAwareStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)"
  },
  "stack": "TypeError: Cannot read property 'uids' of undefined\n    at StorageExplorerProvider.<anonymous> (file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:282:51)\n    at step (file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:47:23)\n    at Object.next (file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:28:53)\n    at fulfilled (file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:19:58)\n    at <anonymous>",
  "originalStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
  "zoneAwareStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
  "__zone_symbol__stack": "TypeError: Cannot read property 'uids' of undefined\n    at StorageExplorerProvider.<anonymous> (file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:282:51)\n    at step (file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:47:23)\n    at Object.next (file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:28:53)\n    at fulfilled (file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:19:58)\n    at <anonymous>",
  "__zone_symbol__name": "TypeError",
  "__zone_symbol__message": "Cannot read property 'uids' of undefined",
  "__zone_symbol__originalStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
  "__zone_symbol__zoneAwareStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)"
}

**Comment by craxal** [comment] 2019-07-08 17:56
Duplicate of #1532.

**Closed by craxal** 2019-07-08 17:56 UTC
