### ISSUE TITLE
Microsoft Storage Explorer isn't responding after Installation

### ISSUE THREAD

**Issue by saikongara** [microsoft/AzureStorageExplorer#3788] opened 2020-11-17 19:19 UTC
Microsoft Storage Explorer has saved the Authentication details and is throwing below error;

Unable to retrieve child resources.

Details:
{
  "name": "Error",
  "message": "Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token",
  "__zone_symbol__error": {
    "originalStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)",
    "zoneAwareStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)"
  },
  "stack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at Object.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-managed-disks-extension/dist/src/AzureSdkHelpers/CredentialFactory.js:29:31)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at fulfilled (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:112:62)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
  "originalStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)",
  "zoneAwareStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)",
  "__zone_symbol__stack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at Object.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-managed-disks-extension/dist/src/AzureSdkHelpers/CredentialFactory.js:29:31)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at fulfilled (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:112:62)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token",
  "__zone_symbol__originalStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)",
  "__zone_symbol__zoneAwareStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)"
}

**Comment by JasonYeMSFT** [comment] 2020-11-19 02:29
@saikongara At what point did you see this error message? For example, did you see the error when Storage Explorer starts up, expands subscription or something else, etc?

**Comment by saikongara** [comment] 2020-11-19 14:18
> @saikongara At what point did you see this error message? For example, did you see the error when Storage Explorer starts up, expands subscription or something else, etc?

Right after installation when I tried to open the application.
I have used the application earlier in this Mac. When there is a new version I installed it and since then I face this issue, Probably because my credentials got saved somewhere and couldn't clear those for newly downloaded one. Do you have any idea of figuring this out ?

**Comment by fevaldez** [comment] 2020-11-23 17:00
Same happens to me on OSX 
Do we have a workaround for this?

**Comment by MRayermannMSFT** [comment] 2020-11-23 19:11
Y'all can disable disks from Settings -> Services -> Disks, un check the check box.

But do y'all have any accounts which need reauthenticating? We see people with this error, and the most likely reason for it is that the account is stale...but so far no one has confirmed or denied if this was the case for them when seeing this.

**Comment by saikongara** [comment] 2020-11-23 21:07
Well I tried to do so, apart from that error dialog box I couldn't see any other window of the Application after installing it.
I couldn't see any window though I tried to open settings of the application.

**Comment by fevaldez** [comment] 2020-12-01 19:01
Same for me, I can't see any window even when clicking on the Settings menu.
@MRayermannMSFT I do have an account that needs reauthenticating ...

**Comment by MRayermannMSFT** [comment] 2020-12-07 17:47
@saikongara oh so you're saying that when you try to open storage explorer, you get this error dialog, and even if you close it, the main window doesn't come up?

@fevaldez after clicking on settings, it should open as a new tab: 
![image](https://user-images.githubusercontent.com/21112697/101385868-35ccb480-3871-11eb-9d2d-150c5d04f9c8.png)
Are you not seeing this tab appear?

**Comment by saikongara** [comment] 2020-12-07 20:11
nope, after getting the error window I shared in the screenshot nothing else show up.

**Comment by fevaldez** [comment] 2020-12-07 20:29
That's correct @MRayermannMSFT, main issue is that nothing appears after seeing the initial error.
i.e.
![StorageExplorer_LoadIssue](https://user-images.githubusercontent.com/8205504/101401822-7ee42f00-3898-11eb-947e-d2b09a3150c6.gif)

**Comment by MRayermannMSFT** [comment] 2021-01-19 18:30
That's very very odd. Can y'all try to do this?
1. Go to `~/Library/Application Support/StorageExplorer/ `
2. Open settings.json, or if it doesn't exist, then make that file with contents simply being: 
```
{
}
```
3. In the file, add `"services.disks.enable": false` between the curly braces, and if the file already existed, than as the last entry in the list of settings.

**Comment by fevaldez** [comment] 2021-02-02 05:24
Did try the steps you mentioned @MRayermannMSFT but got the same behavior as before with the difference that the error screen disappeared.

In my case the ```settings.json``` file was already there so I added the entry you mentioned
<img width="578" alt="image" src="https://user-images.githubusercontent.com/8205504/106556132-857fd300-64e4-11eb-86cd-648683f1840a.png">

**Comment by MRayermannMSFT** [comment] 2021-02-22 17:13
> the error screen disappeared.

So you're not blocked now then?

**Comment by fevaldez** [comment] 2021-02-23 13:38
No, I'm still unable to use the application since nothing appears after initial loading screen.

**Comment by JasonYeMSFT** [comment] 2021-02-23 18:07
@fevaldez It seems that you are running into another issue. Could you try the steps we posted in #3763? It basically clears your existing config for window location and size which might be corrupted.

**Comment by MRayermannMSFT** [comment] 2021-03-29 21:00
Closing due to a lack of response. If you are still seeing this problem please open a new issue. Thanks.

**Closed by MRayermannMSFT** 2021-03-29 21:00 UTC
Labels: :gear: disks, retrieve child resource error
