### ISSUE TITLE
Cancel button in activity log before action starts

### ISSUE THREAD

**Issue by zerweck** [microsoft/AzureStorageExplorer#3589] opened 2020-09-15 07:41 UTC
**Is your feature request related to a problem? Please describe.**
When you accidentally paste twice and the second paste is queued, there is no way to cancel the second paste from the activity log until it starts

**Describe the solution you'd like**
Actions that get placed in the activity queue should be cancel-able immediately

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by MRayermannMSFT** [comment] 2020-09-28 17:58
Dupe of #1306

**Closed by MRayermannMSFT** 2020-09-28 17:58 UTC
Labels: :heavy_check_mark: duplicate
