### ISSUE TITLE
An error message shows when trying to rename a blob

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1304] opened 2019-04-18 08:17 UTC
**Storage Explorer Version:** 1.8.0_20190418.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release 1.7.0

**Steps to reproduce:**

  1. Expand a storage account -> Blob Containers -> Create a new blob container -> Upload a file.
  2. Try to rename the file -> Check the Activities.

**Expect Experience:**
Succeed to rename the file.

**Actual Experience:**
Fail to rename the file.
![image](https://user-images.githubusercontent.com/41351993/56345968-966a3200-61f3-11e9-9268-fcadf1327747.png)

**More Info:**
1. This issue also reproduces for **files under file share**.
2. This issue doesn't reproduce for **HNS blobs**.
3. This issue also reproduces when **pasting** blobs and files under file share.
4. This issue also reproduces when executing **Prompt Snapshot** for one blob.

**Comment by craxal** [comment] 2019-04-18 18:10
Very likely the same root cause as #1305, since rename is basically a copy/delete, and copy uses SAS.

**Comment by craxal** [comment] 2019-04-18 20:45
Sort of related to SAS. We were passing the parameters incorrectly to the SAS generation function.

**Comment by v-xuanzh** [comment] 2019-04-22 02:51
Hi @craxal , Verified this issue on latest master build. Still reproduces with the below error message. So re-opened it.
![image](https://user-images.githubusercontent.com/34729022/56480416-d6891900-646e-11e9-9b26-56761eb1f289.png)

**Comment by craxal** [comment] 2019-04-22 16:23
Code changes didn't actually make it in yet. Also, this isn't going to be checked into the master branch. Please test again on another build from the release branch.

**Closed** 2019-04-22 18:25 UTC
Labels: :beetle: regression, :gear: sas, 🧪 testing
