### ISSUE TITLE
large file uploads fail with SAS URI connected container

### ISSUE THREAD

**Issue by eschultink** [Microsoft/AzureStorageExplorer#305] opened 2018-06-14 18:34 UTC
**Storage Explorer Version**: Both 1.1 and 1.2 (tried both)
**Platform/OS Version**: macOS and Windows (we've had people try on both platforms, although I'm personally on macOS)
**Architecture**:
Version: 1.2.0

Platform: macOS
Architecture: x64
Build Number: 20180604.2
Commit: f8373d5a
Support Id: 87e505ce-9d60-4576-5c5e-dfb4dccd49a9

Copyright © 2018 Microsoft. All rights reserved.
**Regression From**:  Not sure it ever worked. We've tried on various machines and various versions.

#### Steps to Reproduce: ####
1. create a SAS URI for a bucket, with wdl perms
2. connect it by right clicking on "Storage Accounts" --> "Connect ..", choosing SAS URI method, pasting in the URI in there. Otherwise all defaults. 
3. Upload with defaults. Small file works; Large file fails.

```json
{
  "name": "StorageError",
  "message": "Forbidden",
  "stack": "StorageError: Forbidden\n    at Function.StorageServiceClient._normalizeError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1191:23)\n    at Object.StorageServiceClient._processResponse (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:738:50)\n    at Request.processResponseCallback [as _callback] (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:311:37)\n    at Request.self.callback (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/request/request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/request/request.js:1079:12)",
  "code": "Forbidden",
  "statusCode": 403,
  "requestId": "f09047e2-501e-0013-070d-04d352000000"
}
```

![microsoft azure storage explorer 2018-06-14 11-29-42](https://user-images.githubusercontent.com/102831/41431017-7f365b7e-6fc6-11e8-9b53-34fb18bd3dcb.png)

#### Expected Experience: ####
It should work for both small and large files.

#### Actual Experience: ####
It works only for small files.

**Comment by jinglouMSFT** [comment] 2018-06-14 18:40
What's the approx size of the larger files to repro this?  Also there was a period of time yesterday Azure Storage was down.

**Comment by eschultink** [comment] 2018-06-14 18:40
So with a SAS token that also has READ permissions, it works.

**Comment by eschultink** [comment] 2018-06-14 18:41
70MB+

**Comment by eschultink** [comment] 2018-06-14 18:41
it is current, happens now.

**Comment by craxal** [comment] 2018-06-14 18:54
Yeah, this is a known issue. Here's what happens.

For particularly large files (like your 70+MB), we want to know if a blob of that name already exists before trying to upload the file. Otherwise you could be waiting a few minutes just for the platform to tell you the blob already exists before dropping the uploaded file!

So, before uploading anything, we just ask the platform if the blob exists using the Get Blob Properties operation. Unfortunately, this means you need read permissions. In most cases, this isn't an issue. But in your case, your SAS needs read permissions. Otherwise larger uploads will fail.

See #140 for more info.

**Comment by eschultink** [comment] 2018-06-14 19:06
OK, very confusing to have it work differently depending on the file-size - especially when it provides no useful feedback about the error.

The original token *did* have LIST permission as #140 indicates is required - just not WRITE.

Use-case is that I want customers to be able to securely upload data files. Hence we send them a URI that allows them to write only - so they can send us the files, but if that URI was ever compromised, it would not allow someone to read those files.

**Comment by craxal** [comment] 2018-06-14 19:12
In your case, the key is read permissions, not write.

We'll need to spend some time looking into this. We've gotten reports of this several times, so we'll want to look at our options. It looks like the platform supports just overwriting blobs if they already exist, but that may be undesirable in some cases. I'm sure, for example, you don't want users overwriting other users' blobs when they happen to upload something with the same name.

**Comment by eschultink** [comment] 2018-06-14 19:20
well, we're not going to hand different customers SAS tokens for the same container. We create a container per customer. So that risk is minimal.

But regardless:
   1. the behavior of this shouldn't vary based on file-size. If READ is needed to WRITE, it should ALWAYS be able to required. Otherwise I create a SAS token, test it, it works fine for me - so I send to customer - and then it fails for them.  We look stupid. 
   2. if you allow a write-only token to be created, it should work for writing - the potential overwrite case is the user's problem. If you don't want to allow that, your UX shouldn't allow me to check the "WRITE" box without also having checked the "READ" box.  Mysterious failures on the other end isn't correct.
   3. there should be some permission short of READ that allows for reading of blob meta-data, but not the blob itself. I thought that's what the LIST permission did, but I guess not?

**Comment by craxal** [comment] 2018-06-14 20:15
List permissions let you ask the container what blobs it has. Read permissions let you get specific data from the blob, including content and metadata.

Don't worry; we're with you on this one! We're aware of the problem, and we intend to fix it without breaking other user needs. We've been chatting, and we think we have a simple solution. Theoretically, we should be able to just query the container for blobs using the target blob as a prefix. If there are no matching blobs returned, then we don't have to worry about overwriting. This should release the requirement for read permissions.

**Comment by craxal** [comment] 2018-06-15 23:10
I've just merged a potential fix for this issue. @eschultink, @grundencp, @chriseul, would you be interested in trying a preview build and verifying that this fix resolves your issues?

**Comment by eschultink** [comment] 2018-06-19 03:07
Yeah, happy to give it a try.

**Comment by grundencp** [comment] 2018-06-19 19:58
Sure.  It's still not working for me.

**Comment by craxal** [comment] 2018-06-21 15:53
Here are some links to preview builds you can use. Keep in mind they will expire in 7 days.
- [Windows](https://cralvordtest02.blob.core.windows.net/customer-share/release/SasPermissionFix/StorageExplorer-ia32.exe?st=2018-06-21T15%3A34%3A20Z&se=2018-06-28T15%3A34%3A00Z&sp=r&sv=2017-07-29&sr=b&sig=hGAOMd5TWWLz%2FDOlI%2B08UJMLgO66STRU4CFHo3tVdNw%3D)
- [Mac](https://cralvordtest02.blob.core.windows.net/customer-share/release/SasPermissionFix/StorageExplorer-v1.2.0-darwin-x64.zip?st=2018-06-21T15%3A36%3A40Z&se=2018-06-28T15%3A36%3A00Z&sp=r&sv=2017-07-29&sr=b&sig=tBMpXSlCCj%2B0VoRQf%2FUzsit0SMdGRlCTolTu2I4ruqI%3D)
- [Linux](https://cralvordtest02.blob.core.windows.net/customer-share/release/SasPermissionFix/StorageExplorer-v1.2.0-linux-x64.tar.gz?st=2018-06-21T15%3A37%3A05Z&se=2018-06-28T15%3A37%3A00Z&sp=r&sv=2017-07-29&sr=b&sig=AB8UKOw7j3dXFcjzJZ9u3wMuzbQl%2FBkN9IuGawJWCk0%3D)

**Comment by grundencp** [comment] 2018-06-21 19:12
Thanks craxal!  The preview build worked for me.

**Comment by MRayermannMSFT** [comment] 2018-06-22 18:05
@eschultink , please let us know if the build did not work for you. Otherwise, we're closing this bug, and you will see the fix officially ship in 1.3.0.  Thanks!

**Closed** 2018-06-22 18:05 UTC
Labels: :gear: blobs, :gear: sas, :white_check_mark: merged, :x: bug

**Comment by seacen** [comment] 2018-07-09 02:13
@craxal @MRayermannMSFT may I know the timing of this 1.3 release? We are having the same issue currently and have to change our SAS token permissions.

**Comment by seacen** [comment] 2018-07-09 02:14
Can I also know if this issue applies to uploading via Blob APIs as well, or just GUI only?

**Comment by craxal** [comment] 2018-07-09 15:41
If you're sending your own blob upload requests, you should only need write permissions, so this is likely just a bug in Storage Explorer. Other CLI tools, such as AzCopy, don't have the same issue.

You can expect 1.3.0 out sometime this week.

**Comment by unruledboy** [comment] 2019-03-04 11:25
V1.6.2 still has the same problem, any idea?

**Comment by A141864** [comment] 2019-11-04 02:28
I'm experiencing the same issue via the Azure Portal
```Upload block blob to blob store failed. Details: Make sure blob store SAS uri is valid and permission has not expired. Make sure CORS policy on blob store is set correctly. StatusCode = 0, StatusText = .```

**Comment by skanalytic** [comment] 2020-04-03 16:07
I am still experiencing an issue with 'WRITE ONLY' SAS tokens on Azure Storage Explorer. If I create an SAS token with 'read', 'list', 'write' (rlw) then I can connect to my Azure File Storage account and upload/download files no problem, but if I follow this exact same process without 'read' permissions - so just list and write (lw) - then I can still connect to the account but not longer upload (even though I should be able to with 'write'). 

I verified this issue does not exist using the same SAS token on Azcopy (e.g. with just 'wl' permissions i can upload but not download files) so I think it is a specific bug with Azure Storage Explorer. 

I also beleive this is the exact same issue mentioned here: https://github.com/microsoft/AzureStorageExplorer/issues/305#issuecomment-397409292 

Any support of this would be much appreciated.
Happy to provide more details if needed.

**Comment by skanalytic** [comment] 2020-04-03 16:17
@eschultink did you ever figure out a solution to this https://github.com/microsoft/AzureStorageExplorer/issues/305#issuecomment-397409292

**Comment by craxal** [comment] 2020-04-06 17:01
@eschultink What you're experiencing is really by design. Storage Explorer was never meant to work with write-only SAS. The explorer always tries to show blobs/files in a container, which requires list permissions. Read permission is also required, because we use it for certain checks. If you would still like Storage Explorer to work with write-only SAS, please open a new feature request issue.

**Comment by skanalytic** [comment] 2020-04-06 19:37
OK cheers @craxal, I will do that and have found a work-round for now. Thanks for replying. 

Just in general though - it does seem a bit counterintuitive to me that Azure will allow me to make an SAS token with just write permissions, will tell me I have just write permissions when I connect this token to Storage Explorer, but then will forbid actions that seem like just write tasks (e.g. uploading a file) without any warning or useful error message. 

Anyway, thanks again,

**Comment by skanalytic** [comment] 2020-04-06 19:46
FEATURE REQUEST OPENED HERE: https://github.com/microsoft/AzureStorageExplorer/issues/2793

**Comment by judyanndixon** [comment] 2021-08-16 18:51
> I'm experiencing the same issue via the Azure Portal
> `Upload block blob to blob store failed. Details: Make sure blob store SAS uri is valid and permission has not expired. Make sure CORS policy on blob store is set correctly. StatusCode = 0, StatusText = .`

I just fell into this and was able to get around it by turning public blob access back on.
