### ISSUE TITLE
Quick Access empty on New Window

### ISSUE THREAD

**Issue by ericfitskieolyslager** [microsoft/AzureStorageExplorer#6301] opened 2022-11-23 07:22 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

i86

### Storage Explorer Build Number

20221018.5

### Platform

Windows

### OS Version

Windows 11 Pro 21H2 22000.1219

### Bug Description

When i have the Storage Explorer running with a few storage accounts pinned in the Quick Access and start a new instance with File -> New Window the new opened Storage Explorer windows does not show the pinned storage accounts in the Quick Access. The Quick Access is empty

First Storage Explorer window:
![image](https://user-images.githubusercontent.com/31337317/203490861-9abe52db-673f-4aac-bec3-62644f980d46.png)

New Storage Explorer windows after File -> New Window:
![image](https://user-images.githubusercontent.com/31337317/203491019-380bf334-031f-4742-a684-5c83dbaa0f57.png)

### Steps to Reproduce

1. Launch Storage Explorer
2. See that there are items pinned in the Quick Access
3. Open new window with File -> New Window
4. See that the Quick Access is empty

### Actual Experience

The new opened Storage Explorer window does not show the Quick Access items

### Expected Experience

Every Storage Explorer window should have the Quick Access items populated.

**Comment by MRayermannMSFT** [comment] 2022-11-28 17:49
Hi @ericfitskieolyslager unfortunately this is a known issue. Thanks for the additional report though.

**Comment by MRayermannMSFT** [comment] 2022-11-28 17:49
Closing as duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/638

**Closed by MRayermannMSFT** 2022-11-28 17:49 UTC
