### ISSUE TITLE
The toolbar actions are selected when pressing 'Ctrl + A' to select all items

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6558] opened 2023-02-14 09:56 UTC
**Storage Explorer Version:** 1.28.0
**Build Number:** 20230213.4
**Branch:** rel/1.28.0
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2 (Apple M1 Pro)
**Architecture:** ia32/x64/arm64
**How Found:** Exploratory testing
**Regression From:** Previous release (1.23.1)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload serval blobs.
3. Select one blob -> Press "Ctrl+A" with caps lock on.
4. Check whether all blobs are selected.

## Expected Experience ##
All blobs are selected.

## Actual Experience ##
The toolbar actions are selected.
![image](https://user-images.githubusercontent.com/87792676/218697767-33e033a8-6d45-4d18-a968-4eafbd3e6c2d.png)

## Additional Context ##

1. This issue doesn't reproduce for regular blobs.
2. This issue also reproduces for file shares/tables.
3. This issue doesn't reproduce when pressing "Ctrl + a".

**Comment by craxal** [comment] 2023-02-14 21:01
Related to #6337.

**Comment by MRayermannMSFT** [comment] 2023-02-27 22:38
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/6454

**Closed by MRayermannMSFT** 2023-02-27 22:38 UTC
Labels: 🧪 testing, :gear: tables, :gear: files, :beetle: regression, :gear: adls gen2
