### ISSUE TITLE
Uploading too many files causes the app to keep using network but never send the files

### ISSUE THREAD

**Issue by andre-ss6** [microsoft/AzureStorageExplorer#1105] opened 2019-01-30 11:29 UTC
**Bug description**
I've tried uploading ~60 files, all at once (drag'n'dropped them). The default queue size is 5, so only 5 were being uploaded. The problem is, while Resource Monitor said that Azure Storage Explorer was using all of my network, SE itself reported 0.0Mbps. 

We then tried to upload only one file. It worked. Although the speed and % completed reported were all off, it worked. We then tried two files at once. Again, 0.0Mbps. However, we waited and eventually they completed. So we thought that it must be some UI issue. We tried the 60 files again and left it overnight uploading. Today morning, when I open the server,  this is what I see:

![image](https://user-images.githubusercontent.com/15827357/51977386-776ac800-246e-11e9-98bc-368713445b15.png)

We've checked several times during these hours, and it was like this all the time: SE using some 20Mbps of network, but reporting 0.0Mbps. Some 15 hours have passed since it started uploading and not even a single file (700MB each) was uploaded. 

So, first question, why aren't the files there?
And, perhaps more importantly, where is my data going?

Azure Portal is buggy (just like everything else at Microsoft, it seems) and isn't able to report metrics for me for my storage resource. When I try to see Avg Used Capacity, Sum Used Capacity, Sum Ingress or Sum Egress for the last 48h with automatic granularity in the metrics blade, they all show up empty, even though - as you can see in the screenshot - there are files there.

**Steps to Reproduce**
I'm not sure of the steps to repro as I haven't had the time to really test this. I'll just leave here what I've done.
1. Open SE.
2. Connect to a storage resource like the one below via connection string.
![image](https://user-images.githubusercontent.com/15827357/51978290-f2cd7900-2470-11e9-91af-7b007901d9b5.png)
3. Open a blob container
4. Drag'n'drop some 60 700MB .rar files

**Expected Experience**
The files are uploaded.

**Actual Experience**
The app reports having uploaded only ~5% of one of the files, even though it has used more than 100GB of my network.

This specific experience happened on Windows Server 2012 (not sure if R2).
However, we've tried the app other times, using other OSes, including Windows 10 Pro 1803 and Windows 7.

**Comment by craxal** [comment] 2019-02-06 20:08
Has anyone given integrated AzCopy a try? You can switch it on by selecting **Experimental** > **Use AzCopy for Improved Blob Upload and Download**.

**Comment by andre-ss6** [comment] 2019-02-06 20:10
Doesn't work here. It just gives an error every time I try it.

**Comment by craxal** [comment] 2019-02-07 21:24
Good to know! We really want to get input on AzCopy in Storage Explorer. Since they tend to do things better than the default way, we're planning on making AzCopy the default module for uploads/downloads.

**Comment by andre-ss6** [comment] 2019-02-17 18:45
Well, the error with AzCopy I mentioned before happened again. Multiple times even. But I can't seem to find a pattern. Seems quite random. The error message is just this:
```

{
  "message": "\"AzCopy quit unexpectedly\""
}
```

**Comment by craxal** [comment] 2019-02-19 16:56
Storage Explorer launches AzCopy as a separate process, so that may be why reported bandwidths look strange.

We're working with the AzCopy folks to see if we can't get some better error messages and find out why this is happening.

**Comment by MRayermannMSFT** [comment] 2019-02-19 17:01
(this comment is currently only relevant if you're not using an ADLS Gen2 Storage account)

The great thing about our experimental AzCopy integration is that if you're seeing issues, we can have you try your transfers via the command line. This helps us figure out where exactly the issue is. Also, the reason you see "AzCopy quit unexpectedly" is because when AzCopy crashes it currently doesn't give us error messages in a readable format (this is something their working on), but when you run it on the command line it is much more human readable.

Anyway, @andre-ss6 , if you're still seeing the issue with AzCopy, I suggest you download it, [here](https://github.com/Azure/azure-storage-azcopy). use the "Copy AzCopy Command to Clipboard" action, and try running AzCopy in PowerShell. That way we can get the real error.

**Comment by andre-ss6** [comment] 2019-02-19 18:59
Ok, will do that!

And about the wrong bandwidth, that can't be the full explanation. Maybe it can for AzCopy, but for the original issue at least it can't. As I reported, ASE used more than 100GB of my network but didn't upload not even a single 700MB file to our storage account (also note that the sum of the files was 50gb, so something is _really_ wrong here).

**Comment by craxal** [comment] 2019-02-19 22:47
I suppose one possibility is that Storage Explorer did in fact send the blocks to Azure, but for some reason Azure didn't commit them. The only way to be sure that I can think of is to use Fiddler to watch the network traffic.

**Comment by andre-ss6** [comment] 2019-04-01 20:28
The error happened again. The command was this:

```
.\azcopy copy "[redacted]\bin\Release\netcoreapp2.2\publish\*" "https://[redacted].blob.core.windows.net/release/[redacted]/?st=2019-04-01T20%3A20%3A54Z[redacted]" --overwrite=false --follow-symlinks --recursive --fromTo=LocalBlob --list-of-files "[redacted]\AppData\Local\Temp\stg-exp-azcopy-[redacted].json"
```

The error: `Error: unknown flag: --fromTo`

**Comment by MRayermannMSFT** [comment] 2019-04-29 18:15
Hey @andre-ss6 , in a recent AzCopy update they changed --fromTo to be --from-to. So you can just edit that manually. Alternatively when we ship 1.8.0 we'll be running against the first non-beta version of AzCopy and all the flag values will be correct.

**Comment by andre-ss6** [comment] 2019-04-29 18:19
Ok, so I guess I'm stuck between using something that doesn't work and... another thing that also doesn't work. :(

Will be waiting for that version.

**Comment by jinglouMSFT** [comment] 2019-04-29 19:01
We can give you a release candidate of our next release.  Would you be interested in trying that out?

**Comment by andre-ss6** [comment] 2019-04-29 19:06
Yea, sure.

**Comment by jinglouMSFT** [comment] 2019-04-29 19:17
OK. @MRayermannMSFT will give you a RC build this afternoon once we have the build ready.

**Comment by MRayermannMSFT** [comment] 2019-07-08 18:34
I definitely forgot to send the build. 😓 @andre-ss6 , are you still running into issues?

**Comment by andre-ss6** [comment] 2019-07-09 15:24
@MRayermannMSFT nope, seems to be working fine now.

**Comment by andre-ss6** [comment] 2019-07-09 15:26
Just to be clear, however, I have not tested it on a situation like the one I first described on this issue tho (trying to upload something like 60 large files at the same time).

**Comment by MRayermannMSFT** [comment] 2019-07-15 18:12
Ok, we'll go ahead and close this then. Feel free to open new issues if you run into similar problems. Thanks!

**Closed by MRayermannMSFT** 2019-07-15 18:12 UTC
Labels: :gear: azcopy, :gear: blobs, :mag: investigate
