### ISSUE TITLE
An extra scrollbar appears in the 'Manage Custom Environments' dialog if a custom environment with a long name is added

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8007] opened 2024-06-14 07:41 UTC
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240614.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04 & MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Open the connect dialog -> Click 'Subscription -> Custom Environment'.
2. Click 'Manage custom environments...' -> Click 'Add'.
3. Add one custom environment with a long name -> There is a scrollbar in the 'Custom environment' section.
4. Click 'Back' -> Then click 'Manage custom environments...'.
5. Check whether only the 'Custom environment' section has a scrollbar.

## Expected Experience ##
Only the 'Custom environment' section has a scrollbar.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/7b8bcae7-c61b-481b-bd4e-0e335055fcd0)

## Actual Experience ##
An extra scrollbar appears in the 'Manage Custom Environments' dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/2050a242-6306-495b-a122-6a4260240e93)

**Comment by v-xianya** [comment] 2024-07-16 02:07
Verified this issue on the main build 20240716.5. Reproduce, so, we are going to reopen it.
![image](https://github.com/user-attachments/assets/2d57d717-ccd0-4f40-80b6-614ff81ffff3)

**Comment by craxal** [comment] 2024-07-16 17:00
@v-xianya The ellipsis is intended. It is very, very unlikely a user is going to enter a name that long, so I do not believe anything else needs to be done.

**Comment by v-xianya** [comment] 2024-07-17 08:13
Hi @craxal There is an extra scrollbar in the 'Manage Custom Environments' dialog.
![image](https://github.com/user-attachments/assets/9d10767d-f193-4382-ae2d-e2c53e8147dd)

**Comment by craxal** [comment] 2024-07-23 20:45
I've merged another fix to remove the scrollbar. The extra width was coming from the select element in the Select Azure Environment page. Please note that very long names will be cut off in the native menu that opens when clicking the select. As before, names this long is very, very unlikely for users, so we consider this expected behavior.

**Closed by craxal** 2024-07-23 20:45 UTC
Labels: :white_check_mark: merged, 🧪 testing, :beetle: regression

**Comment by v-xianya** [comment] 2024-07-24 02:12
Verified this issue on the main build 20240724.1. Fixed.
![image](https://github.com/user-attachments/assets/d055e772-823d-4061-a002-c06cfe933fd3)
