### ISSUE TITLE
A11y_AzureToolsStorageExplorer_Settings_DataExplorers_Screenreader : NVDA unnecessarily reading the line as heading level 2.

### ISSUE THREAD

**Issue by Radha2019** [microsoft/AzureStorageExplorer#1892] opened 2019-09-24 09:34 UTC
**" Check out Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing aster and easier.”**

**GitHubTags:** #A11y_AzureToolsStorageExplorer; #A11yMAS; #A11YTCS; #DesktopApp; #MAS1.3.1; #NVDA; Win10;

**Environment Details:**
Application Name: Azure Tools Storage Explorer
Application Version: 1.10.0
Windows10

**Repro Steps:**
1. Launch Storage Explorer
2. Navigate to Setting menu on left pane and click on it.
3. Navigate to Data Explorers on right pane and  click on it.
4. "Data Explorers" screen gets opened.
5. Verify that all the elements of "Data Explorers" Screen are accessible and MAS Compliant.
6.Start NVDA and navigate using the tab key.Observe the NVDA readings.

​Actual:​
NVDA unnecessarily reading the line as heading level 2.

Expected:
NVDA should not read the line as heading level 2.

User Impact:
Screen readers user will get unnecessary information.

Recommendation:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx  

MAS Reference: 
MAS1.3.1
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4} 

**Attachment for Reference**

![1892_A11y_AzureToolsStorageExplorer_Settings_DataExplorers_Screenreader](https://user-images.githubusercontent.com/55691739/65500294-b9a0b800-dedc-11e9-862b-3f20e16c22ce.png)

**Comment by MRayermannMSFT** [comment] 2019-12-02 19:45
Jason merged a fix for this into master.

**Closed by MRayermannMSFT** 2019-12-02 19:45 UTC
Labels: :heavy_check_mark: merged, :wheelchair: MAS, :wheelchair: accessibility

**Comment by MRayermannMSFT** [comment] 2020-01-27 18:19
@Radha2019 @Charanrajkb @nirmalsahoo @Suraj1200499 @vinodbk197

Please verify whether or not this bug was fixed to your satisfaction in the latest release of Storage Explorer. You can obtain that release from https://www.storageexplorer.com

If the bug has not been fixed to your satisfaction, please:
- Explain how did the fix not meet your expectations.
- Tell us exactly how we can meet your expectations. If there is more than one way to do so, feel free to list the different ways.

**Comment by vinodbk197** [comment] 2020-02-04 14:39
Verified this issue on:Azure Tools Storage Explorer (Version: 1.12.0)
The issue is no longer to reproduces, Hence closing this bug.

**Comment by fsteffi** [comment] 2023-02-17 12:27
GithubTags:#Closed;

**Comment by mstechie** [comment] 2023-03-05 18:34
GitHubTags:#BM-TCS-StorageExplorer-Win32-Sep2019;
