### ISSUE TITLE
There is an error info in one ADLS Gen2 secondary blob container if the original blob container contains a blob that is being rehydrated

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6630] opened 2023-03-02 07:46 UTC
**Storage Explorer Version:** 1.29.0-dev
**Build Number:** 20230302.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Chang its access tier to 'Archive' -> Change its access tier to 'Hot'/'Cool'.
4. The blob access tier value is 'Archive (rehydrating to Hot/Cool)'.
5. Right click the blob container -> Click 'Open Secondary Location'.
6. The secondary blob container opens.
7. Check whether there is no error info.

## Expected Experience ##
There is no error info.

## Actual Experience ##
There is an error info.
![image](https://user-images.githubusercontent.com/87792676/222360626-6aacc6ad-5020-4abe-aa9f-a0ef2e5f20d9.png)
`Server encountered an internal error. Please try again after some time. RequestId:3f3e20f8-301e-0016-62d8-4cf436000000 Time:2023-03-02T07:30:04.6419515Z`

## Additional Context ##
This issue doesn't reproduce for regular blob container.

**Comment by JasonYeMSFT** [comment] 2023-03-02 17:55
Hmmm. OK, this is definitely a service issue. I'll forward this to the service team and close this issue once I get anyone looking into it.

**Comment by JasonYeMSFT** [comment] 2023-03-16 18:08
I get back from the service team. The error is expected and the error message is actually correct. The root cause of the error is that while listing Gen2 blobs, the backend needs to wait until certain configurations are synced. If you wait for some time it will work again.

**Closed by JasonYeMSFT** 2023-03-16 18:08 UTC
Labels: 🧪 testing, :gear: adls gen2, :cloud: service
