### ISSUE TITLE
Uploading from One Drive folder doesn't work

### ISSUE THREAD

**Issue by JakeRadMSFT** [Microsoft/AzureStorageExplorer#17] opened 2018-03-10 01:57 UTC
Storage Explorer Version: 0.9.6

OS Version: Windows 10

Steps to Reproduce:

1. Upload file form One Drive Folder

Expected Experience:
File Uploads

Actual Experience:
Upload fails

**Comment by MRayermannMSFT** [comment] 2018-04-27 18:30
Closing as duplicate of #96

**Closed by MRayermannMSFT** 2018-04-27 18:30 UTC
Labels: bug, duplicate
