### ISSUE TITLE
Rename the tab

### ISSUE THREAD

**Issue by weigq** [microsoft/AzureStorageExplorer#5312] opened 2022-01-05 03:00 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Sometimes I need to open serveral path under the same container in different tabs, currently the tab name is fixed as the container name, making it harder to find the specific tab quickly.

### Desired Solution

Customize the tab like, rename or set tab color

**Comment by MRayermannMSFT** [comment] 2022-01-20 18:35
Duplicate of #2679

Though I will let you know, we're making good progress towards being at a place where we can make this feature request a reality. I'd personally love to see this feature happen when it can. We often have the same container open in multiple tabs, where each tab is associated with a different way the account was connected. Having Storage Explorer dynamically add context to tabs, or even being able to do that manually, would be so helpful.

**Closed by MRayermannMSFT** 2022-01-20 18:35 UTC
