### ISSUE TITLE
The 'Emulator - Default Ports' node is added to Quick Access after trying to add one attached account to QA

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1658] opened 2019-08-13 10:51 UTC
**Storage Explorer Version:** 1.9.0
**Build:** 20190813.3
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Attach one account with SAS(Or attach it with Key/Name).
2. Expand '**Local & Attached**' -> '**Storage Accounts**' ->Right click the attached account then select 'Add to Quick Access'.
3. Check whether the attached account can be added to quick access or not.

**Expect Experience:**

The attached account appears under the Quick Access node.

**Actual Experience:**

The '(Emulator - Default Ports)(Key)' node appears under the Quick Access.
![image](https://user-images.githubusercontent.com/34729022/62935111-cf5c9100-bdf8-11e9-9b09-50dc7505c72c.png)

**Comment by MRayermannMSFT** [comment] 2019-08-13 16:54
Fix merged into master.

**Comment by v-xianya** [comment] 2019-08-14 10:36
This isue still reproduces on the latest master build  20190813.12. So reopened it.

**Comment by MRayermannMSFT** [comment] 2019-08-19 16:10
I think this was still repro'ing due to a bad CE commit. @v-xianya can you check for repro on tonight's build? Thanks.

**Closed by MRayermannMSFT** 2019-08-19 16:10 UTC
Labels: :beetle: regression, :gear: attach, :gear: quick access, :heavy_check_mark: merged, 🧪 testing
