### ISSUE TITLE
'Attached Container' instead of 'SAS-Attached Service' under 'Local & Attached'

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1391] opened 2019-05-23 08:11 UTC
**Storage Explorer Version:** 1.8.1_20190523.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** 1.8.1 release

**Steps to reproduce:**
1. Expand 'Local & Attached' -> 'Storage Accounts'.

Expect Experience:

There shows 'SAS-Attached Service'.
Actual Experience:

There shows 'Attached Container'.
![image](https://user-images.githubusercontent.com/34729022/58236334-46900500-7d75-11e9-8430-e767a94e757f.png)

**Comment by jinglouMSFT** [comment] 2019-05-23 17:32
I believe this is by design as we will soon support RBAC attach.  Matthew can confirm if he has already checked in the code.

**Comment by MRayermannMSFT** [comment] 2019-05-23 18:08
Yes. I checked in the name change.

**Closed by MRayermannMSFT** 2019-05-23 18:08 UTC
Labels: :beetle: regression, :gear: attach, :gear: sas, 🧪 testing
