### ISSUE TITLE
Sort all (including non-cached) blobs

### ISSUE THREAD

**Issue by CamiloTerevinto** [microsoft/AzureStorageExplorer#5275] opened 2021-12-17 15:26 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Sorting is performed on cached items, which paints a picture completely different to reality

### Desired Solution

Sorting is only useful if it's performed *before* pagination. Loading tens of thousands of items to see today's items isn't really optimal

### Alternatives and Workarounds

The only workaround is to load *all* objects, to ensure you're actually seeing all the items that you expect to see.

**Comment by CamiloTerevinto** [comment] 2021-12-17 15:28
I realize that this might be a problem in the API that the Storage Explorer uses, rather than on Storage Explorer itself. If that's the case, I'm glad to open the same issue on the relevant place.

**Comment by MRayermannMSFT** [comment] 2022-01-20 18:32
@CamiloTerevinto 

> I realize that this might be a problem in the API that the Storage Explorer uses

Yes unfortunately your intuition is correct 😰

> I'm glad to open the same issue on the relevant place.

Unfortunately this is no GitHub repo for Azure Storage. You could submit this as feedback here: https://feedback.azure.com/d365community/ , or if you have someone from sales/CSS you or your company frequently works with you could try sending this feedback that way. We're of course still trying from our side to get the service team to provide an API that would let us sort properly, but alas, nothing yet.

Closing as duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/134

**Closed by MRayermannMSFT** 2022-01-20 18:32 UTC
