### ISSUE TITLE
The warning message is set to red color on CORS Settings dialog when 5 CORS rules are added

### ISSUE THREAD

**Issue by v-etzha** [microsoft/AzureStorageExplorer#1362] opened 2019-05-10 09:33 UTC
**Storage Explorer Version:** 1.8.1_20190510.3
**Platform/OS:** Windows 10/macOS High Sierra/Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer and expand Storage Account.
2. Right click one Blob Containers node then select 'Configure CORS Settings...'.
3. Click 'Add' button and add 5 CORS rules.
4. Check the warning message that is showing below the rule table.

**Expect Experience:**

The color of the warning message is white.
![image](https://user-images.githubusercontent.com/34734408/57515940-5277d200-7346-11e9-9cf6-d8258d1ee071.png)

**Actual Experience:**

The color of the warning message is red.
![image](https://user-images.githubusercontent.com/34734408/57515900-3ffd9880-7346-11e9-856b-a791b642db3d.png)

**Comment by craxal** [comment] 2019-05-10 17:00
By design. Red is reserved for validation errors. This is not a validation error.

**Comment by jinglouMSFT** [comment] 2019-05-10 17:13
@craxal your explanation is exactly the reason why there is a bug here.  we shouldn't display the warning in red as this is not a validation error.

**Comment by craxal** [comment] 2019-05-10 17:45
Sorry, got the two screenshots backwards. Yes, we can fix this.

**Comment by MRayermannMSFT** [comment] 2019-05-30 18:27
Changing to:
![image](https://user-images.githubusercontent.com/21112697/58654947-ded63e80-82cd-11e9-80c6-6de0844d06e1.png)

**Comment by MRayermannMSFT** [comment] 2019-05-30 21:37
Change merged to master.

**Comment by craxal** [comment] 2019-05-31 17:04
This does not solve the issue where _any_ warning message is red. Warning messages should be the default color, this bug is saying. Only errors should be red.

**Closed** 2019-06-06 22:00 UTC
Labels: :heavy_check_mark: merged, 🧪 testing
