### ISSUE TITLE
Support for SQL DB, Synapse SQL-POOL or SQL Managed Instance ?

### ISSUE THREAD

**Issue by juriaan-atos** [microsoft/AzureStorageExplorer#5309] opened 2022-01-04 12:38 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

The resource type SQL DB, Synapse SQL-POOL or SQL Managed instance is not supoported 

### Desired Solution

being able to use the resource types: SQL DB, Synapse SQL-POOL or SQL Managed instance 

### Alternatives and Workarounds

-

### Additional Context

-

**Comment by MRayermannMSFT** [comment] 2022-01-10 18:27
Duplicate of #5308

**Closed by MRayermannMSFT** 2022-01-10 18:27 UTC
