### ISSUE TITLE
Group subscriptions by tenant

### ISSUE THREAD

**Issue by alpinedelight** [microsoft/AzureStorageExplorer#2682] opened 2020-03-02 11:49 UTC
**Is your feature request related to a problem? Please describe.**
Whilst not a technical problem, it is a problem when dealing with 10s / 100s of subscriptions and not knowing which tenant they belong to.

**Describe the solution you'd like**
I would like to be able to group subscriptions by tenant in the left panel, so I can easily collapse or show different tenant groups, i.e. different partners, customers that I may be working with.

**Describe alternatives you've considered**
Not using the tool and using Azure Portal instead

**Additional context**
Thanks.

**Comment by MRayermannMSFT** [comment] 2020-03-09 17:49
Duplicate of #2621

**Closed by MRayermannMSFT** 2020-03-09 17:49 UTC
