### ISSUE TITLE
The description 'inferred' disappears after executing acquire lease for one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1741] opened 2019-08-29 08:48 UTC
**Storage Explorer Version:** 1.10.0
**Build:** 20190828.15
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storageV2 account -> Blob Containers.
2. Create a new blob container -> Upload a blob to it.
3. Try to acquire lease for the blob then observe the Access Tier value.

**Expect Experience:**
The description 'inferred' still shows.
![image](https://user-images.githubusercontent.com/41351993/63924319-a5eb6880-ca7a-11e9-91eb-66d647611203.png)

**Actual Experience:**
The description 'inferred' disappears.
![image](https://user-images.githubusercontent.com/41351993/63924981-daabef80-ca7b-11e9-81ed-d8cafa6418b3.png)

**More Info:**
The description 'inferred' appears after refreshing manually .

**Comment by MRayermannMSFT** [comment] 2019-09-23 18:35
Won't fix/by design. These values come from the server/we are listing the blob differently after acquiring the lease.

**Closed by MRayermannMSFT** 2019-09-23 18:35 UTC
Labels: :gear: blobs, 🧪 testing
