### ISSUE TITLE
Issue on MacOS with empty cache files for blob containers

### ISSUE THREAD

**Issue by MScarno** [microsoft/AzureStorageExplorer#422] opened 2018-07-13 07:32 UTC
**Storage Explorer Version**:
**OS/Platform**:
**Architecture**:
**Regression From**:

#### Repro Steps ####

1.
2.

#### Actual Experience ####

On MacOS, when the Blob Container has empty cache files, a download will fail following error: 
'message': 'EEXIST: file already exists, mkdir '/Users/<file directory>' 
 
Part of the Containers content mostly (virtual folders) are not downloaded and throw this error. Instead there are files with the same name but  no type with (0 Byte) . 
 
For reference, see this video. 
https://www.youtube.com/watch?v=zv9p-qPvg7g&feature=youtu.be

**Comment by craxal** [comment] 2018-07-18 15:58
We need some information from you to better understand your issue (check your original comment):
- Storage Explorer Version
- OS Version
- Regression From (version this last appeared to work, if applicable)
- Steps to Reproduce (concise, detailed steps that would allows us to reproduce your issue)
- Expected/Actual Experience

If I understood you correctly, the issue you're encountering is some folders you're attempting to download appear as empty files on your machine. I noticed you had a lot of failed downloads, but you didn't look into those more closely. Have you tried resolving those failed downloads? It's possible that might resolve your folder issue.

**Comment by MRayermannMSFT** [comment] 2020-03-23 18:15
Closing due to lack of response. Please open a new issue if you are still having problems.

**Closed by MRayermannMSFT** 2020-03-23 18:15 UTC
Labels: :gear: blobs, :grey_question: more info
