### ISSUE TITLE
'Task Scheduler' to sync between two storage objects

### ISSUE THREAD

**Issue by robsmi-msfte** [microsoft/AzureStorageExplorer#7165] opened 2023-08-09 15:21 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I have to sync two storage blobs in different subs periodically.

### Desired Solution

I would like to be able to set up a scheduled task to automatically sync those two

### Alternatives and Workarounds

Manually sync now

**Comment by MRayermannMSFT** [comment] 2023-08-09 20:54
Hi @robsmi-msfte this is something we may look to do in the future. For now, you can invoke AzCopy from the command line and use the `sync` command: https://learn.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-sync

Duplicate of #4476.

**Closed by MRayermannMSFT** 2023-08-09 20:54 UTC
