### ISSUE TITLE
"Get SAS" DateTimePicker is some kind of Rubik's puzzle

### ISSUE THREAD

**Issue by untilted-document** [microsoft/AzureStorageExplorer#2988] opened 2020-05-16 11:38 UTC
v1.130 on windows. Please see the attached video in zip file; i'm trying to type a time into the DateTimePicker in the "Get SAS" dialog, and the DTP's behaviour is crazy - I couldn't work out the logic, managed it with a huge amount of trial and error. Pressing the UP/DOWN cursor keys on any given field causes other fields to change, and pressing number keys seems to reset the input to 0 after one or 2 keypresses

But it was a good game!

[azure storage explore datepicker wtf.zip](https://github.com/microsoft/AzureStorageExplorer/files/4638276/azure.storage.explore.datepicker.wtf.zip)

**Comment by MRayermannMSFT** [comment] 2020-05-18 17:45
Hey @untilted-document unfortunately yes there is a bug in our date time picker. We have a fix for it that will be shipped in 1.14. Thank you for reporting the issue.

Duplicate of #2812 2812

**Closed by MRayermannMSFT** 2020-05-18 17:45 UTC
