### ISSUE TITLE
Blobs under unnamed folders are not shown

### ISSUE THREAD

**Issue by yuyez** [microsoft/AzureStorageExplorer#2747] opened 2020-03-23 21:57 UTC
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  N/A

## Bug Description ##
If a blob resides in a named folder that's under an unnamed folder, the blob isn't accessible from Storage Explorer.

## Steps to Reproduce ##
1. Upload a blob with path "///folder/blob.txt"
2. In storage explorer, open the unnamed folders until "folder" is shown
3. Open "folder"

## Expected Experience ##
blob.txt is shown

## Actual Experience ##
no blobs are shown

## Additional Context ##
Originally reported from https://icm.ad.msft.net/imp/v3/incidents/details/180985613/home

**Comment by MRayermannMSFT** [comment] 2020-03-26 16:46
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/1512

**Closed by MRayermannMSFT** 2020-03-26 16:46 UTC
