### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by kroz1** [microsoft/AzureStorageExplorer#7515] opened 2023-11-14 23:59 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.0

### Architecture

x64

### Storage Explorer Build Number

20231101.3

### Platform

Windows

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "TypeError",
  "message": "{\"name\":\"TypeError\"}"
}

### Steps to Reproduce

1. Launch storage explorer

### Actual Experience

<img width="511" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/27245508/fee9f5c0-5ecc-42f7-a3d9-000c354ac8a0">

I get this error when I open the program

**Comment by MRayermannMSFT** [comment] 2023-11-15 17:03
@kroz1

Normally in this scenario you would get a better error message telling you what to do/what the problem actually is. Typically you would just need re-enter your credentials/sign-in again. Unfortunately that error is being blocked from showing by a bug elsewhere in our code.

We're going to ship a fix for this in an upcoming hotfix. Until then there are two things you can try:

1. Removing your azure account and sign back in
2. 2. owngrade back to 1.31: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.31.2 , so you can see the real error message and act accordingly.

I'm going to close this as a duplicate of the first issue to report this, please feel free to comment there if you still need help after trying to sign back in/downgrading.

**Closed by MRayermannMSFT** 2023-11-15 17:03 UTC
