### ISSUE TITLE
Search should work for when there are 1000+ storage accounts

### ISSUE THREAD

**Issue by amithegde** [Microsoft/AzureStorageExplorer#225] opened 2018-05-30 01:26 UTC
**Version**: 1.1.0
**Platform**: Windows
**Architecture**: ia32
**Build Number**: 20180507.1
**Commit**: bcc8990d
**Support Id**: 0233cf6b-5aa5-46c6-317d-93ee42da9f98

I have a subscription with 1000+ storage accounts. I could never use this tool with the subscription because I can't reach the storage account I need quickly by searching fort. Please make the search experience better.

**Comment by craxal** [comment] 2018-05-30 17:37
Duplicate of #75.

**Closed by craxal** 2018-05-30 17:37 UTC
Labels: resolved: duplicate

**Comment by amithegde** [comment] 2019-03-19 09:19
@craxal this is not a duplicate. What I am stating here is it's super hard to find a storage that I need account on the subscription because search doesn't work that well.
