### ISSUE TITLE
The SAS attached table doesn't open automatically

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5567] opened 2022-03-28 08:01 UTC
**Storage Explorer Version**: 1.23.0
**Build Number**: 20220328.1
**Branch**: hotfix/1.23.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.23.0)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Attach the table via SAS URL.
3. Check whether the attached table opens automatically. 

## Expected Experience ##
The attached table opens automatically. 

## Actual Experience ##
The attached table does not open automatically. 

## Additional Context ##
Similar issue: [5506](https://github.com/microsoft/AzureStorageExplorer/issues/5506).

**Comment by craxal** [comment] 2022-03-28 16:43
The fix is present in the main branch, so we need to cherry pick it over to the hotfix branch. I'm going to close this as a duplicate of #5506.

**Closed** 2022-03-28 16:59 UTC
Labels: 🧪 testing, :gear: tables, :beetle: regression
