### ISSUE TITLE
Last Modified column blank for all directories

### ISSUE THREAD

**Issue by marcuslind90** [microsoft/AzureStorageExplorer#2242] opened 2019-11-08 15:42 UTC
**Storage Explorer Version**: 1.11.0
**Build Number**: 20191105.2 
**Platform/OS**: macOS High Sierra
**Architecture**: x64
**Regression From**:  1.10.x

## Bug Description ##
Last Modified column display empty value for directories, even though data exists within the blob properties.

Old version:

<img width="439" alt="Screenshot 2019-11-08 at 14 58 06" src="https://user-images.githubusercontent.com/8709266/68489027-33e38c80-023e-11ea-9db3-d2eb1344df5a.png">

New version (display blank values):

<img width="775" alt="Screenshot 2019-11-08 at 15 32 48" src="https://user-images.githubusercontent.com/8709266/68489045-3a720400-023e-11ea-9228-af012a671770.png">

New version blob properties (Show that data actually do exist):

<img width="491" alt="Screenshot 2019-11-08 at 15 41 58" src="https://user-images.githubusercontent.com/8709266/68489100-54abe200-023e-11ea-8909-db8695869497.png">

## Expected Experience ##
Just like earlier versions, I would expect the Last Modified date of directories to be displayed just life files.

## Actual Experience ##
Last Modified display blank value.

**Comment by craxal** [comment] 2019-11-11 22:27
@marcuslind90 Are you looking in a blob container, or an ADLS Gen2 blob container?

**Comment by marcuslind90** [comment] 2019-11-12 10:57
@craxal I'm sure there are plenty of use cases like ours -- especially within data science -- where you create unique names for directories (e.g. based on a run id?) where it would be incredibly useful to see which was the latest directory created and to sort them by timestamps.

It is pretty ugly/hacky to be forced to add timestamps to the directory names to enable timestamp sorting.

Hopefully, this is something that could be added if it's not supported by your current API. 👍

**Comment by jinglouMSFT** [comment] 2019-11-12 18:59
@marcuslind90 We hear you.  We have already made a request for the SDK team to add back the support.  Once the SDK adds the feature, we will re-enable the feature.  Thank you for helping us understand your scenario.

**Comment by craxal** [comment] 2019-11-13 17:29
For reference, see Azure/azure-sdk-for-js#6179.

**Comment by andreacassioli** [comment] 2020-04-02 12:58
This very important in my opinion, it force people to encode dates in the folder names to be able to navigate!

**Comment by craxal** [comment] 2020-05-13 22:40
Here's a status update for everyone:

The Azure platform team has identified the root cause of the issue, and they are now working on a plan to fix it. I can't say when they'll have a fix ready. We will also have to wait on an update from the Node client SDK before this will make it to Storage Explorer. Stay tuned; we'll let you know when we get updates.

**Comment by craxal** [comment] 2021-02-22 19:03
After some further discussion with the platform, the service is not yet ready for to provide what we need in one API call. They suspect it will be ready in June/July, but they're not sure. We can revisit in August to see if this has been fixed.

**Comment by JasonYeMSFT** [comment] 2021-06-23 21:48
Let's check with the service team on the progress.

**Comment by JasonYeMSFT** [comment] 2021-08-12 17:47
The new List Blobs API now provides these information. I have merged a PR adding them to our data table.

**Closed by JasonYeMSFT** 2021-08-12 17:47 UTC
Labels: :beetle: regression, :gear: adls gen2
