### ISSUE TITLE
Copying managed disk does not preserve hyperVGeneration property

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureStorageExplorer#4288] opened 2021-04-03 02:43 UTC
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210304.5 
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  N/A

## Bug Description ##
Copying a managed disk (in my case, specifically between subscriptions and tenants) does not preserve the Hyper-V Generation property of the managed disk resource.

## Steps to Reproduce ##
1. Locate a generation 2 VM OSDisk.
2. Copy it.
3. Navigate to another tenant/subscription/rg [This might happen even within the same resource group, untested].
4. Paste it. Give it a name, etc.

## Expected Experience ##
All managed disk properties should be maintained.

## Actual Experience ##
The Hyper-V Generation property of the managed disk is unset.

## Workaround ##
Use az cli to set the property back:
```
az disk update -g rg-name --name disk-name --set hyperVGeneration=V2

**Comment by JasonYeMSFT** [comment] 2021-04-05 17:42
Let's investigate the cause in 1.19.0 and see if it can be fixed in 1.19.0. Otherwise, we will fix it in a future release.

**Comment by MRayermannMSFT** [comment] 2021-04-05 18:20
@SvenAelterman what about copying it within the same tenant?

**Comment by MRayermannMSFT** [comment] 2021-04-06 21:28
Merged fix into main. Will ship with 1.19

**Closed by MRayermannMSFT** 2021-04-06 21:28 UTC
Labels: :bulb: feature request, :gear: disks
