### ISSUE TITLE
Double clicking a file share cannot make its temporary opened tab permanent

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5822] opened 2022-06-09 08:01 UTC
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220609.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.2)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Click one file share to open a temporary tab.
3. Double click the file share.
4. Check whether the temporary tab becomes permanent.

## Expected Experience ##
The temporary tab becomes permanent.

## Actual Experience ##
The temporary tab doesn't become permanent.

**Comment by JasonYeMSFT** [comment] 2022-06-09 16:46
This is a duplicate of issue https://github.com/microsoft/AzureStorageExplorer/issues/5747. We will need to add that support for all the new type of explorers as a separate task.

**Closed** 2022-06-09 16:51 UTC
Labels: :heavy_check_mark: duplicate, 🧪 testing, :gear: files, :beetle: regression
