### ISSUE TITLE
A11y_Azure Tools Storage Explorer_DiskInfoTable_AI4D: (StorageExplorer/image 'disk image') The Name must not include the same text as the LocalizedControlType.

### ISSUE THREAD

**Issue by v-inanda** [microsoft/AzureStorageExplorer#4980] opened 2021-09-28 11:51 UTC
### GitHubTags:
#A11yTCS;#A11ySev2;#A11yWCAG;#DesktopApp;#AI4D;#A11yAuto;#Azure Tools Storage Explorer;#BM-AzureToolsStorageExplorer-Win32-Sep2021;#WCAG 4.2.1;#Benchmark;#Win32

### Environment Details:​
Application Name: Azure Tools Storage Explorer
Windows Version: Windows 10

### Repro Steps:​
1.Open Azure Tools Storage Explorer
2.Tab till the "Disks" of the selected subscription and press enter.
3.Click on any existing disk.
4.Navigate to DiskInfoTable under the tool bar.
5. Open AI4D and Verify.

### Note:
The same issue is also observed in the below scenario:
Toggle Explorer Pane - Tree View

### **Element path:
image 'disk image'

### **Issue Details:
The Name must not include the same text as the LocalizedControlType. [Section 508 502.3.1](https://www.access-board.gov/ict/#502-interoperability-assistive-technology)

### **How To Fix:
Provide a UI Automation Name property for the element that:
 · Concisely identifies the element, AND
 · Does not include the same text as the element's LocalizedControlType property.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

### Attachment:
![A11y_Azure Tools Storage Explorer_DiskInfoTable_AI4D (StorageExplorerimage 'disk image') The Name must not include the same text as the LocalizedControlType](https://user-images.githubusercontent.com/91525824/135081329-ef6e6208-8062-4bb8-bdf0-26caa3855553.PNG)

**Comment by MRayermannMSFT** [comment] 2021-09-30 21:42
@v-inanda So to be clear the issue is that the localized control type, "image", is also part of the name?

![image](https://user-images.githubusercontent.com/21112697/135534098-d5fb08b3-5e4c-40f2-ac67-6da3b028f680.png)

**Comment by Latha2564** [comment] 2021-10-01 07:06
Closing this bug as it is an Electron App .For Electronic apps no need to log AI bugs

**Comment by MRayermannMSFT** [comment] 2021-10-01 17:42
Oh ok. That works too!

**Closed by MRayermannMSFT** 2021-10-01 17:42 UTC
Labels: :computer: windows, :wheelchair: WCAG

**Comment by Sobi261** [comment] 2023-02-10 07:23
#Closed
