### ISSUE TITLE
Editor doesn't automatically close after detaching one SAS-attached blob container

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#426] opened 2018-07-13 10:28 UTC
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180711.4
**Commit**: 47039639
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Create a SAS URl for a blob container.
2. Open the Connect dialog and attach the container using the SAS URI. 
3. After successfully attached -> Detach the attached blob container.

#### Expected Experience: ####
The opened editor is automatically closed.

#### Actual Experience: ####
The opened editor remains open.

**More Info:**
1. This issue doesn't reproduce for an attached file share/ queue/ table whose display name matches the resource name.
2. This issue reproduces for an attached blob container/ file share/ queue/ table whose display name doesn't match the resource name.

**Comment by craxal** [comment] 2018-07-13 19:39
Looks like we need to do some work with the tree node/tab integration. We're only using the resource name as the tab. We need to pass both the display name and the resource name.

**Comment by v-xianya** [comment] 2019-12-30 08:37
This issue also reproduces on build [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616).

**Comment by MRayermannMSFT** [comment] 2020-03-16 18:30
Duplicate of #2656

**Closed by MRayermannMSFT** 2020-03-16 18:30 UTC
Labels: :gear: attach, :gear: sas, :heavy_check_mark: duplicate, need attention, 🧪 testing
