### ISSUE TITLE
Deleting folder placeholders (created by blobfuse) deletes the actual folder

### ISSUE THREAD

**Issue by munael** [microsoft/AzureStorageExplorer#4558] opened 2021-06-14 11:55 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Architecture

x64

### Platform

Windows

### OS Version

19042

### Bug Description

When using blobfuse and `mkdir`, you get 0 byte placeholder files at the point where an empty folder is expected. You can then populate that folder. In ASE, you will see both the folder and the 0B file with the same name. Delete the 0B file and you delete the actual "folder".

### Steps to Reproduce

1. Mount through blobfuse.
2. `mkdir foo`
3. Write some random files to `container/foo`
4. Open ASE to `container`
5. You'll see: Folder `foo/` and 0B file `foo`.
6. Delete the file `foo`.
7. `foo/` is also deleted.

### Actual Experience

Deleting files with the same name as an adjacent folder should not trigger a glob-based delete.

**Comment by MRayermannMSFT** [comment] 2021-06-14 17:47
@munael because the stub blobs are representative of the directory, then that's why the directory is deleted. If Storage Explorer was simply to delete the stub blob, then that would break the pseudo file system, as the files for the directory would still exist, but the stub blob, which signifies the existence of the directory, would be gone.

Is there a reason you wish to see/manage/delete the stub blob? By default we do not show stub blobs, so unless there's a bug, you shouldn't be seeing it unless you enabled the setting to make stub blobs visible. If you did not enable the setting please let us know as that would be a bug.

**Comment by MRayermannMSFT** [comment] 2021-07-12 17:15
Closing due to lack of reply/the issue is by design. Please see the explanation in my previous comment for more information.

**Closed by MRayermannMSFT** 2021-07-12 17:15 UTC
Labels: :gear: blobs
