### ISSUE TITLE
Drag to reorder tabs

### ISSUE THREAD

**Issue by LarsKemmann** [microsoft/AzureStorageExplorer#3208] opened 2020-07-09 19:48 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I intuitively try to drag tabs around to rearrange them but they don't respond to being dragged.

**Describe the solution you'd like**
I'd like a standard drag-to-reorder mechanism for tabs in Storage Explorer.

**Describe alternatives you've considered**
Rising up against the machine and injecting a virus into the Matrix. Unfortunately it sent a Terminator after me.

**Additional context**
None, the context menus on tabs are just fine the way they are. ;)

**Comment by MRayermannMSFT** [comment] 2020-07-13 18:11
"Rising up against the machine and injecting a virus into the Matrix. Unfortunately it sent a Terminator after me."
😂😂😂😂😂

**Comment by MRayermannMSFT** [comment] 2020-07-13 18:13
Duplicate of #501

**Closed by MRayermannMSFT** 2020-07-13 18:13 UTC
Labels: :bulb: feature request

**Comment by LarsKemmann** [comment] 2020-07-13 21:12
Thanks! Sorry, I must have missed the other issue.
