### ISSUE TITLE
Add .deb package for Linux [simple template included here]

### ISSUE THREAD

**Issue by niklas-e** [Microsoft/AzureStorageExplorer#736] opened 2018-10-06 11:37 UTC
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Linux (debian based)
**Architecture**: x86_64
**Regression From**: 

#### Steps to Reproduce: ####
Tarball requires manual work to have the app as a "regular app" on OS level (e.g. properly registered app, menu item, purge on unistall etc...) 

#### Expected Experience: ####

Install Azure Storage Explorer via .deb package. Of course PPA would be even better, but this would be easiest way to provide better user experience.

I created simple template to create the package from your tarballs. Most likely it could be used on your CI pipeline with minor modifications. Here's the template: https://github.com/niklas-e/azure-storage-explorer-deb

**Comment by JakeRadMSFT** [comment] 2018-10-08 16:54
Thanks @niklas-e! That helps a ton! We'll try to integrate it into our Azure Dev Ops Pipeline https://azure.microsoft.com/en-us/services/devops/.

**Comment by niklas-e** [comment] 2018-10-08 17:03
That's cool @JakeRadMSFT! Ask me if you have any problems or questions with it - I might be able to help :smiley:

**Comment by MRayermannMSFT** [comment] 2018-11-07 17:17
@niklas-e , I took a look at your code, and didn't see anything regarding Storage Explorer depending on .NET Core 2.0 and gnome keyring. Am I just not seeing it or is that not something you added?

**Comment by craxal** [comment] 2018-11-08 21:22
Duplicate of #68.

**Closed by craxal** 2018-11-08 21:22 UTC

**Comment by mkozioro** [comment] 2018-12-06 08:17
Hi @MRayermannMSFT 
I see some dependencies in https://github.com/niklas-e/azure-storage-explorer-deb/blob/master/files/DEBIAN/control

I would just threat this as a template to be used by Microsoft engineers.

**Comment by niklas-e** [comment] 2018-12-06 08:43
@MRayermannMSFT sorry, I forgot to reply. I set the dependencies according to documentation available at that time. There's some dependencies in the file @mkozioro pointed out. Rest of the dependencies can also be added there.

I can add the ones you mentioned later today.
