### ISSUE TITLE
Emulator deletes all data on update

### ISSUE THREAD

**Issue by dloukola** [microsoft/AzureStorageExplorer#2081] opened 2019-10-15 12:06 UTC
**Storage Explorer Version**: All of them so far.
**Build Number**:  All of them so far.
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  This has never worked properly

## Bug Description ##
When you update Azure Storage Explorer, it deletes all your emulator data.

## Steps to Reproduce ##
1. Add data to the emulator
2. Update storage explorer
3. Check the data

## Expected Experience ##
Data in emulator to be retained on update of Azure Storage Explorer version

## Actual Experience ##
All data in emulator is wiped. It looks like it may even be creating a new SQL instance

## Additional Context ##
This makes me never want to update storage explorer since it happens every time. If you don't fix this, I will never update again. I await to see this fix in the release notes.

**Comment by JasonYeMSFT** [comment] 2019-10-15 17:02
What emulator and which version are you using? We don't delete emulator data when we update. I just tried using AzureStorageEmulator v5.9.0.0 CLI while updating Storage Explorer from 1.9.0 to 1.10.1 and the data doesn't get wiped. Could you please give us more details about how to reproduce this problem?

**Comment by dloukola** [comment] 2019-10-15 18:15
Well, I'm not 100% sure if azure storage explorer updated my emulator version, but it's currently  5.10.0.0.
I had updated from 1.9.x (not sure which, but it was 1.9 something) to 1.10.1 and it deleted everything. When I started the storage emulator it said something about creating a new sql instance that ended with 510 (thinking this is due to version 5.10). 

This issue has seriously been happening since azure storage explorer was in beta. It's very frustrating. I've just lived with it, but it just got me so frustrated today that I had to speak out.
*note: this happens to everyone on my team, so it's not just me.

**Comment by JasonYeMSFT** [comment] 2019-10-15 18:35
I just tried upgrading my emulator from 5.9.0.0 to 5.10.0.0. The data does get deleted and I do see the creating new SQL instance message in the emulator console. Storage Explorer doesn't upgrade the emulator. You might have upgraded your emulator sometime prior to upgrading to Storage Explorer. We will try to escalate this issue to the emulator team to fix it. Sorry about the abrupt behavior.

**Comment by dloukola** [comment] 2019-10-15 18:37
hmmm, I also upgraded to the latest visual studio and visual studio code. Maybe one of them updated the emulator? It was update day for me.

**Comment by jinglouMSFT** [comment] 2019-10-15 19:10
The Azure SDK in Visual Studio installs storage emulator.

**Comment by MRayermannMSFT** [comment] 2019-11-18 19:09
Closing due to lack of reply.

**Closed by MRayermannMSFT** 2019-11-18 19:09 UTC
