### ISSUE TITLE
Fail to save file properties for ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#871] opened 2018-11-19 08:06 UTC
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181117.12
**Commit**: 78a0d1ab
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Create one account with Azure Data Lake Storage Gen2 enabled.
2. Expand the created account -> Create one blob container.
3. Upload a file -> Open the file 'Properties' dialog then try to add properties for it -> Click 'Save'.

#### Expected Experience: ####
The added user properties can be saved successfully.

#### Actual Experience: ####
Fail to save the file properties with the below error.
```json
{
  "name": "TypeError",
  "message": "Cannot read property 'CacheControl' of undefined",
  "stack": "TypeError: Cannot read property 'CacheControl' of undefined\n    at Object.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-adls2-extension\\dist\\Actions\\PathActions.js:121:73)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:133:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:114:57)\n    at fulfilled (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:104:62)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"
}
```

#### More info: ####
This issue doesn't reproduce for blob containers of ADLS Gen2 accounts

**Comment by craxal** [comment] 2018-11-26 23:15
I'm confused. The repro steps say you should create an ADLS Gen 2 account, yet in the notes below you say this doesn't reproduce for blob containers in ADLS Gen 2 accounts...?

**Comment by jinglouMSFT** [comment] 2018-11-27 00:17
We basically had problems saving properties regardless the type of accounts.  I believe the root cause is the same for all account types.

**Comment by v-xuanzh** [comment] 2018-11-27 01:48
Hi @craxal , this issue doesn't reproduce when viewing account properties of the ADLS Gen2 (Right click the account node -> Select 'Properties...')

It reproduces for ADLS Gen2 **blobs**

**Comment by MRayermannMSFT** [comment] 2018-11-27 18:09
Merged into feature branch and available in latest builds.

**Closed by MRayermannMSFT** 2018-11-27 18:09 UTC
Labels: :exclamation: must fix, :gear: adls gen2, testing, 🔍 more info
