### ISSUE TITLE
Open tabs no longer have attached properties showing in the "Properties" pane if Explorer tree view is refreshed

### ISSUE THREAD

**Issue by munael** [microsoft/AzureStorageExplorer#6612] opened 2023-02-24 14:40 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28

### Architecture

x64

### Platform

Windows

### OS Version

Windows 11 22H2

### Bug Description

Open tabs do not show anything "Properties" if the Explorer tree view is refreshed (e.g. by pinning a new resource).

### Steps to Reproduce

1. Pin some container to the explorer view.
2. Right click and open in a new tab. Possibly do this with a few more containers.
3. Click on the tab of one of the open containers.
4. Notice the `Properties` pane updating to show things like the container URL, type, etc.
5. Now go back to the Explorer and pin another container. Notice the quick access sub-tree refreshing.
6. Now click on the tab of another of the already open containers.
7. Notice the empty `Properties` tab. 

### Actual Experience

See steps.

### Expected Experience

That it continues to work as it does before the tree is updated.

Same behavior happens when restarting the app. Fixing it there also would be great :D

**Comment by MRayermannMSFT** [comment] 2023-02-27 22:46
@munael by "confirm" do you mean "the issue reproduces with containers that are directly pinned to quick access"?

**Comment by JasonYeMSFT** [comment] 2023-02-28 19:04
I was not able to reproduce this issue. The node-tab association is persisted as long as the node is still visible in the tree. The most likely way it was broken that I can think of is
- A storage account in Quick Access is expanded to list containers.
- Among those containers, one of them is opened as an explorer on the right hand side. Now that tab is associated with the node under storage account.
- The container node is pinned to Quick Access. It causes Quick Access to reload which discards the previous container node under the storage account.
- Now the node-tab association is broken and you won't see properties panel update if you select the that tab.

**Comment by munael** [comment] 2023-03-28 09:57
@JasonYeMSFT
A storage account in quick access is indeed expanded to list containers.
The association is broken at _any_ refresh event, however, not just on pinning.

**Comment by JasonYeMSFT** [comment] 2023-04-11 22:26
I see. Since refreshing Quick Access discards the 2nd level children, losing the node-tab association is the expected behavior. This is an edge case and we are going to won't fix this for now. We will wait for more feedback on this scenario and reevaluate this issue in the future.

**Closed by JasonYeMSFT** 2023-04-11 22:26 UTC
Labels: :heavy_check_mark: won't fix
