### ISSUE TITLE
A11y_AzureToolsStorageExplorer_DeletePopup_Keyboard: Keyboard focus goes on non-actionable controls(Texts).

### ISSUE THREAD

**Issue by Radha2019** [microsoft/AzureStorageExplorer#1878] opened 2019-09-23 10:24 UTC
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.” 

GitHubTags: #A11y_AzureToolsStorageExplorer; #A11yMAS; #A11YTCS; #DesktopApp; #MAS2.1.1; #Keyboard; #Win10;

**Environment Details:**
Application Name: Azure Tools Storage Explorer
Application Version: 1.10.0
Windows10

**Repro Steps:**
1. Launch Storage Explorer
2. Navigate to "Open Connect dialog" pane and Sign in to Azure.
3. Go to "Manage Accounts" pane and Select the subscriptions you will use. Once selected, click on "Apply" button.
4. Navigate to "Blob Containers" of the selected subscription, right click and hit enter on "Create Blob container" to Create a new Blob container.
5. Once completed, Navigate to "Upload" button and Upload a blob/file by using  "Upload Files" control.
6. Once Completed, Right click on uploaded blob and Select "Delete" and hit enter.
7. Start navigating on the screen using Tab key.
8. Verify Keyboard focus goes on non-actionable control.

**Actual:**
Keyboard focus goes on non-actionable controls(Texts) Using Tab key.

**Same issue is observed in below Scenarios:**
1. Rename blob
* Here in this Scenario Keyboard focus goes on Texts.
2. SAS URL
* Here in this Scenario Keyboard focus goes on Disable controls(Blob, URL, Query string).
3. Blob Container Properties Tab
* Here in this Scenario Keyboard focus goes on Texts.
4. Properties Tab
* Here in this Scenario Keyboard focus goes on Texts.
5. Undelete Selected
* Here in this Scenario Keyboard focus goes on Texts.
6. Blob Container Actions tab
* Here in this Scenario Keyboard focus goes on disabled buttons using Tab key.
7. Actions tab
* Here in the Scenarios keyboard focus goes on disabled buttons using Tab key.

**Expected:**
Keyboard focus should not go on non-actionable controls(Texts) Using Tab key.

**UserImpact:**
Keyboard only users face difficulty to know whether the control is actionable or not if keyboard focus goes on non-actionable controls using Tab key.

**Recommendation:**
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}

**Attachment for Reference:**
[A11y_AzureToolsStorageExplorer_DeletePopup_Keyboard.pptx](https://github.com/microsoft/AzureStorageExplorer/files/3642166/A11y_AzureToolsStorageExplorer_DeletePopup_Keyboard.pptx)

**Comment by MRayermannMSFT** [comment] 2019-12-04 01:22
@vinodbk197 , for everything you mentioned here's what I'll be doing:

1. Delete confirmation - I will remove the focusing.
2. Rename dialog - I will remove the focusing.
3. Generate SAS Dialogs - Those inputs are not disabled, they are read only. It is correct for them to be focusable.
4.  Properties panel - Those inputs are not disabled, they are read only. It is correct for them to be focusable.
5. Undelete confirmation - I will remove the focusing.
6. Actions panel - I will remove the focusing.
7. Actions panel - I will remove the focusing.

**Comment by MRayermannMSFT** [comment] 2019-12-05 17:59
The changes I have outlined above have been merged into master.

**Closed by MRayermannMSFT** 2019-12-05 17:59 UTC
Labels: :wheelchair: MAS, :wheelchair: accessibility

**Comment by MRayermannMSFT** [comment] 2020-01-27 18:21
@Radha2019 @Charanrajkb @nirmalsahoo @Suraj1200499 @vinodbk197

Please verify whether or not this bug was fixed to your satisfaction in the latest release of Storage Explorer. You can obtain that release from https://www.storageexplorer.com

If the bug has not been fixed to your satisfaction, please:
- Explain how did the fix not meet your expectations.
- Tell us exactly how we can meet your expectations. If there is more than one way to do so, feel free to list the different ways.

**Comment by vinodbk197** [comment] 2020-02-04 15:09
Verified this issue on:Azure Tools Storage Explorer (Version: 1.12.0)
The issue is no longer to reproduces, Hence closing this bug.

**Comment by mstechie** [comment] 2023-03-05 18:36
GitHubTags:#BM-TCS-StorageExplorer-Win32-Sep2019;
