### ISSUE TITLE
How to query column containing JSON string

### ISSUE THREAD

**Issue by yalamarti** [microsoft/AzureStorageExplorer#2769] opened 2020-03-30 15:01 UTC
I am trying to perform a filtering using the query as shown in the image below, expecting it to filter specific matching rows. But, it doesn't filter the matching rows.

Any thoughts on how to limit it, short of exporting it to a file? I think it has something to do with the string representing a JSON object.

The purpose of filtering the table is to quickly filter and delete the matching rows from the table in the UI.

 I have tried following - with no luck: 

// no encoded or escaped values 
DataKey eq '{ "id": "002427", "type": "E" }' - bad req 

// colon and comma - encoded value 
DataKey eq '{ "id"%3A "002427"%2C "type"%3A "E" }' - bad req 

// curly-brace, colon and comma - encoded value 
DataKey eq '%7B "id"%3A "002427"%2C "type"%3A "E" %7D' - bad req 

// comma replace with encoded value - double-quotes escaped 
DataKey eq '{ ""id""%3A ""002427""%2C ""type""%3A ""E"" }' - no data 

// comma replace with encoded valued 
DataKey eq '{ "id": "002427"%2C "type": "E" }' - bad req 

Greatly appreciate any insights/inputs into this.

Thank you 
Regards 
Athadu

![image](https://user-images.githubusercontent.com/44853062/77927866-b9132080-7275-11ea-83d9-f23e725985d2.png)

**Comment by MRayermannMSFT** [comment] 2020-03-30 17:39
Hey @yalamarti, unfortunately what you are asking for is not possible. Table queries use the OData query language and as far as we understand it does not support running the query you are wanting to do. Exporting it to a file would be your best bet in this case.

**Comment by pavelsaman** [comment] 2021-03-19 10:27
> 
> 
> Hey @yalamarti, unfortunately what you are asking for is not possible. Table queries use the OData query language and as far as we understand it does not support running the query you are wanting to do. Exporting it to a file would be your best bet in this case.

Could you share a bit more on that? As far as it it shown in the screen, DataKey column is a string, why is it not possible to perform a query with a condition involving a string column?

I mean some queries are allowed:

![image](https://user-images.githubusercontent.com/24702416/111766220-91adcd00-88a5-11eb-8a88-61b24df78200.png)

and some report a wrong syntax:

![image](https://user-images.githubusercontent.com/24702416/111766548-f537fa80-88a5-11eb-81fc-371a27e045cf.png)

Is the problem with `"` character? Why? It's just another character that I'm using inside single quotes, so it should not be interpreted in any special way.

**Comment by asos-eugeneniemand** [comment] 2021-04-07 09:52
@JasonYeMSFT @MRayermannMSFT I'm also experiencing an issue with double quotes, for example I have a column called Attributes and a value "WeekID" with the quotes 

![image](https://user-images.githubusercontent.com/78201421/113846780-bdc6ba80-978e-11eb-92d8-1bcacc2e7806.png)

When I try query this column with any of the following I get syntax error
![image](https://user-images.githubusercontent.com/78201421/113846932-e353c400-978e-11eb-9451-140ae29df16f.png)
![image](https://user-images.githubusercontent.com/78201421/113846972-ebabff00-978e-11eb-8e22-016eac3d0965.png)
![image](https://user-images.githubusercontent.com/78201421/113847011-f36ba380-978e-11eb-8037-ec9eae39baf1.png)
![image](https://user-images.githubusercontent.com/78201421/113847057-fd8da200-978e-11eb-8471-6153b24f29c0.png)

Then with triple quotes `"""WeekID"""` or a single then double quotes `'""WeekID""'` I get not error but I also get no results
![image](https://user-images.githubusercontent.com/78201421/113847251-30379a80-978f-11eb-8a34-2089d21ea960.png)

Version Info
![image](https://user-images.githubusercontent.com/78201421/113847417-5f4e0c00-978f-11eb-8c04-907e03f4437c.png)

**Comment by JasonYeMSFT** [comment] 2021-04-07 17:43
There seems to be a bug in our table query code where we incorrectly replace " with ' character.

**Comment by JasonYeMSFT** [comment] 2021-05-03 19:12
I merged a fix to remove the incorrect logic which replaces double quotes (") with single quotes('). This should unblock this scenario. For your information, if you also have single quotes in your query string, you need to represent each single quote with two single quote instead.

For example, for querying an entity whose `content` is `'single'`, the query expression for it needs to be `content eq '''single'''`.

**Comment by v-xianya** [comment] 2021-05-20 06:45
@JasonYeMSFT 
Verified this issue on the latest build 20210519.5. Not reproduce.
![image](https://user-images.githubusercontent.com/41351993/118931800-ee973380-b979-11eb-9105-01e91947f492.png)

**Closed** 2021-06-07 18:07 UTC
Labels: :beetle: bug, :gear: tables, :heavy_check_mark: merged
