### ISSUE TITLE
automatically sync of Quick Access across different devices.

### ISSUE THREAD

**Issue by aries-M** [microsoft/AzureStorageExplorer#6252] opened 2022-11-03 08:01 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

When I use AzureStorageExplore on different devices, the Quick Access is not automatically synchronized, and I have to add them again and again

### Desired Solution

automatically sync the quick access and show the blob name along with the container name

**Comment by JasonYeMSFT** [comment] 2022-11-07 18:48
This is a duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/2880. We have bumped the milestone of that issue to 1.28.0.

**Closed by JasonYeMSFT** 2022-11-07 18:48 UTC
Labels: :bulb: feature request
