### ISSUE TITLE
Saving a blob with no extension shows duplicate item after selecting 'Upload' in the 'File Changes Detected' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#147] opened 2018-05-04 09:22 UTC
**Storage Explorer Version**: 1.1.0 RC

**Platform**: Windows/Linux/Mac

**Architecture**: x64

**Build Number**: 20180503.1

**Commit**: 253b437b

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand storage accounts. 
2. Open one blob container and upload a blob to it. 
3. Rename the uploaded blob with no extension.
4. Make changes for the blob and save it.
5. Select 'Upload' in the popped 'File Changes Detected' dialog.

#### Expected Experience: ####
 Only one blob displays.

#### Actual Experience: ####
Display a duplicate blob name after uploading successfully.
![duplicate](https://user-images.githubusercontent.com/34729022/39620049-5fac5bcc-4f79-11e8-8d8d-8b9db0af5718.png)

**Comment by MRayermannMSFT** [comment] 2018-08-09 18:43
Duplicate of #183

**Closed by MRayermannMSFT** 2018-08-09 18:43 UTC
Labels: testing
