### ISSUE TITLE
{   "message": "\"ERR_EMPTY_RESPONSE\"" }

### ISSUE THREAD

**Issue by kondapallibhargav** [microsoft/AzureStorageExplorer#2491] opened 2019-12-26 08:12 UTC
**Storage Explorer Version**:  1.112
**Build Number**: 
20191217.4
**Platform/OS**: 
Windows 10
**Architecture**: 
x64
**Regression From**:  
nope

## Bug Description ##

I had changed my azure password and storage explorer asked me to sign-in. From there the problem started. I'm getting error 
<img width="960" alt="StorageExplorerError" src="https://user-images.githubusercontent.com/32007191/71466410-74b34880-278d-11ea-8a2f-2ed8f4fc4eb8.png">
{
  "message": "\"ERR_EMPTY_RESPONSE\""
}

**Comment by JasonYeMSFT** [comment] 2019-12-26 18:00
The error message directly comes from the authentication service. Changing password is a complex operation on the service side and may take some time to propagate the change. Have you tried re-signing in after a while?

**Comment by kondapallibhargav** [comment] 2020-01-02 09:29
Yes. I tried today as well. Still I'm facing same issue

**Comment by JasonYeMSFT** [comment] 2020-01-02 22:17
I have tried changing my password and unfortunately I cannot reproduce the issue. 

Could you please tell us if Settings->Application->Sign-in->Microsoft Authentication Library is checked in the setting panel? Are you using device code flow? We can then forward the information to the auth library team to investigate this issue. 

What you can do as well is to try toggling the auth library setting and device code flow setting to see if any configuration can work around the issue and let you sign in.

**Comment by kondapallibhargav** [comment] 2020-01-03 06:21
Settings->Application->Sign-in->Microsoft Authentication Library was unchecked. I checked it and it allowed me to sign-in through browser.

**Comment by kondapallibhargav** [comment] 2020-01-03 06:28
I appreciate your assistance. You can close the issue. If you want me to do, I can

**Closed** 2020-01-06 08:34 UTC
Labels: :gear: sign-in
