### ISSUE TITLE
The red border still shows after removing the conflict metadata for blobs

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#512] opened 2018-07-30 11:21 UTC
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180727.7
**Commit**: 3fd8ad34
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open one blob container which contains one blob at least.
2. Open the 'Properties' dialog for one blob -> Add two metadata with the same name -> Remove one metadata then check the rest metadata.

#### Expected Experience: ####
No red border displays after removing the conflict metadata.

#### Actual Experience: ####
Display a red border after removing the conflict metadata.
![conflict](https://user-images.githubusercontent.com/34729022/43393113-7c8d65f0-93e5-11e8-9324-30977c1e7b8e.png)

**Comment by craxal** [comment] 2018-07-30 17:24
Duplicate of #368.

**Closed** 2018-07-30 17:25 UTC
Labels: :white_check_mark: duplicate, testing
