### ISSUE TITLE
Account not added after successful authentication

### ISSUE THREAD

**Issue by polarapfel** [Microsoft/AzureStorageExplorer#625] opened 2018-08-31 01:39 UTC
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Linux (Ubuntu 18.04)
**Architecture**: x64
**Regression From**: It worked in a previous version.

#### Steps to Reproduce: ####
1. Got to Account Management. Add Azure account. 
2. Authenticate.
2.1. Use a two-factor authentication account.
2.2. Or use a single factor authentication account.

#### Expected Experience: ####
After successful authentication, Azure account is added.

#### Actual Experience: ####
After successfully authenticating, the Microsoft Azure Storage Explorer - Connect window stays open displaying "Waiting for authentication..." until timing out. The account is not added.

**Comment by craxal** [comment] 2018-08-31 16:16
Possibly a duplicate of #377. If you don't thing so, we can reopen. Also keep in mind we have yet not done any work to ensure Storage Explorer works on Ubuntu 18.04, so we can't make any guarantees for you.

**Closed by craxal** 2018-08-31 16:16 UTC
Labels: :computer: linux, :gear: sign-in, :white_check_mark: duplicate
