### ISSUE TITLE
"This file is potentially unsafe" warning on opening a plain-text .csv file

### ISSUE THREAD

**Issue by Vivelin** [microsoft/AzureStorageExplorer#164] opened 2018-05-11 09:01 UTC
**Storage Explorer Version**: 1.1.0
**Platform**: Windows
**Architecture**: ia32
**Build Number**: 20180507.1
**Commit**: bcc8990d
**Regression From**: N/A

#### Steps to Reproduce: ####

1. Open a file with the .csv extension from blob storage (e.g. created using Azure App Service application logging)

#### Expected Experience: ####
Depending on the file type, a warning dialog is shown before opening the file. For safe files, I should not get this warning. Otherwise, I should be able to suppress this dialog to prevent it from being shown next time I open a file of the same type.

#### Actual Experience: ####
Every time I open a .csv blob, I get the following warning dialog:

>[Window Title]
> Microsoft Azure Storage Explorer
> 
> [Content]
> Security warning: This file is potentially unsafe.
> Are you sure you want to open it?
>
> [Yes] [No]

I am unable to suppress this warning, so every blob I want to open, I get the same warning. I'm not sure why I get this warning in the first place:

- A CSV blob with Content Type `application/octet-stream` (generated by Azure App Service application logging) triggers the warning, even though it is plain text;
- An XML blob with Content Type `application/xml` triggers the warning as well;
- An extensionless blob with Content Type `image/jpeg` also triggers the warning;
- Both PDF and LOG blobs with Content Type application/octet-stream do _not_ trigger the warning.

**Comment by craxal** [comment] 2019-02-21 22:56
It is possible for .csv files to contain potentially malicious code, so we purposely don't include it in our list of safe-to-open files.

In a future update, we could provide a way to customize the list of files a user would consider safe to open.

**Comment by jinglouMSFT** [comment] 2019-12-14 01:08
Duplicate of #690

**Comment by craxal** [comment] 2019-12-16 16:43
Actually, #690 is the duplicate.

**Comment by grahambunce** [comment] 2019-12-16 20:34
Latest version 1.11.1 is causing this for every text file in my system (suffix *.log). Even if I click "yes" it will download an empty file.

Previous versions worked perfectly fine.

Accessing via the Azure portal and the file downloads fine and checks out - no viruses.

**Comment by craxal** [comment] 2019-12-17 18:33
@grahambunce This issue is a duplicate. Please continue the discussion with issue #690.

**Comment by grahambunce** [comment] 2019-12-17 19:25
#690 is closed

Sent from my iPhone

On 17 Dec 2019, at 18:33, Craig Alvord <notifications@github.com<mailto:notifications@github.com>> wrote:


@grahambunce<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgrahambunce&data=02%7C01%7C%7Cdb7758cb269f426fa93108d7831f9076%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637122043894588830&sdata=OSWJoHMzbNDUyUtw1YqjCAGL6nBj3mp8JWleFiNDw2g%3D&reserved=0> This issue is a duplicate. Please continue the discussion with issue #690<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FAzureStorageExplorer%2Fissues%2F690&data=02%7C01%7C%7Cdb7758cb269f426fa93108d7831f9076%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637122043894598859&sdata=ZJaXA7ZnkgRJvEFPc8AkwGrb%2Bo%2FEYUubwz6j2FB1%2Fms%3D&reserved=0>.

**Comment by craxal** [comment] 2019-12-17 19:47
@grahambunce Sorry, I totally lied. This is the right issue. 🤦‍♂️

**Closed** 2020-03-19 16:15 UTC
Labels: :beetle: bug, :bulb: feature request, :bulb: setting candidate, :heavy_check_mark: merged
