### ISSUE TITLE
Always keep searching when typing to a non-exist name directly more than 1 hour

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1899] opened 2019-09-24 11:43 UTC
**Storage Explorer Version:** 1.10.1
**Build:** [20190924.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3076815)
**Branch:** master
**Platform/OS:** Windows 10/ Ubuntu Linux 18.04
**Architecture:** ia32/x64

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Type a non-existing name like 'tier' on the search box.
![image](https://user-images.githubusercontent.com/54055206/65506501-41e38500-defe-11e9-977b-673c5f1837f4.png)
3. Wait a moment and check the result.

**Expect Experience:**
'Nothing to displays' shows well on the result.

**Actual Experience:**
Always keep searching more than 1 hour.
![image](https://user-images.githubusercontent.com/54055206/65506518-4f990a80-defe-11e9-8ff5-9fdfef94a2e3.png)

**Comment by craxal** [comment] 2019-09-24 21:46
Duplicate of #1790

**Closed by craxal** 2019-09-24 21:46 UTC
Labels: :globe_with_meridians: localization, 🧪 testing
