### ISSUE TITLE
[Suggestion]Support to paste a deep-level directory path to clipboard

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#52] opened 2018-04-20 09:15 UTC
**Storage Explorer Version:** master/20180419.2

**OS Version:** Windows 10/Mac/Linux

**Steps to Reproduce:**

1. Launch Storage Explorer and expand Storage Accounts.
2. Open one file share and go to a deep-level directory.

**Suggestion:**
Support to paste the deep-level directory path so that share the files/directories to others.
![suggestion](https://user-images.githubusercontent.com/34729022/39042315-080b119c-447a-11e8-8609-558b7e83d01c.png)

**Comment by MRayermannMSFT** [comment] 2018-04-20 16:35
Duplicate of #45.

**Closed by MRayermannMSFT** 2018-04-20 16:35 UTC
Labels: duplicate, feature request, testing
