### ISSUE TITLE
Show a strange activity log after deleting multi files at one time from one file share in zh-CN

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2340] opened 2019-11-27 08:57 UTC
**Storage Explorer Version:** 1.11.0
**Build:** [20191127.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3277410&view=results)
**Branch:** master
**Language:** Chinese(zh-CN) 
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Expand File Shares -> Create one file share -> Upload 2 files.
4. Select the 2 files and delete them.
5. Observe the activity log.

**Expect Experience:**
Show a right activity log.
Like: Delete 1 file
![image](https://user-images.githubusercontent.com/41351993/69708317-40763a80-10b0-11ea-9b0c-c7b0360b2c0a.png)

**Actual Experience:**
Show a strange activity log.
![image](https://user-images.githubusercontent.com/41351993/69708454-8206e580-10b0-11ea-8eda-0e6cd8c48e67.png)

**More Info:**
In zh-TW:
![image](https://user-images.githubusercontent.com/41351993/69708380-5edc3600-10b0-11ea-9057-3b87951fd6d3.png)

**Comment by lukaschal** [comment] 2019-11-27 15:00
@v-xianya Is it possible to provide ENU screenshot ?

**Comment by JasonYeMSFT** [comment] 2019-11-27 18:04
This is caused by the swapped order of the two languages. We should be specifying the order of the placeholders.

**Comment by v-xianya** [comment] 2019-11-29 02:08
@lukaschal   ENU screenshot
![image](https://user-images.githubusercontent.com/41351993/69838820-0ae56480-120a-11ea-9ee3-f94c1689cb00.png)

**Comment by lukaschal** [comment] 2019-11-29 09:16
File: loc\en\src\Standalone\resources\Activities.json
ID: 0; "MessageFileDeletedMultiple"
SRC: Deleted %s files/directories from '%s'
TGT: 已从 "%s" 中删除 %s 个文件/目录

**Comment by craxal** [comment] 2019-12-09 20:34
"Deleted %s files/directories from '%s'": The first placeholder should be a number, and the second placeholder should be a path.

**Comment by craxal** [comment] 2020-02-14 23:12
String changes have been merged. Ready for translation/verification.

**Comment by v-limu** [comment] 2020-02-17 05:58
Verified on build [20200216.2](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9283&_a=summary). This issue has been fixed. So we close it.
![image](https://user-images.githubusercontent.com/54055206/74627315-6f6eea80-518d-11ea-87cd-d99fb8007c08.png)

**Closed by v-limu** 2020-02-17 05:58 UTC
Labels: :gear: files, :heavy_check_mark: merged, 🌐 localization, 🧪 testing
