### ISSUE TITLE
Date format for "Last Modified" is not formatted according to regional settings

### ISSUE THREAD

**Issue by mochr** [microsoft/AzureStorageExplorer#4796] opened 2021-08-13 06:51 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Date format for "Last Modified" is not formatted according to regional settings. E.g. an item has "10/1/2020, 2:10:11 PM" as the Last Modified value, but the correct formatting according to my regional settings (Norwegian) is "01.10.2020, 14:10:11". This can be confusing, especially if the user is not aware that the US format is used with month first instead of day first.

### Desired Solution

I'd like to have Storage Explorer use the system regional format for dates.

### Alternatives and Workarounds

Alternatively be able to choose regional format in settings, or use ISO 8601 as the format for the date and time.

**Comment by JasonYeMSFT** [comment] 2021-08-14 04:29
This is a duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/59. We have made significant progress on it and plan to ship it in 1.21.0.

**Closed** 2021-08-14 04:29 UTC
Labels: :heavy_check_mark: duplicate
