### ISSUE TITLE
Producing a report ignores the specific clauses after latest update.

### ISSUE THREAD

**Issue by xSeanOx** [microsoft/AzureStorageExplorer#5335] opened 2022-01-14 12:17 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0 

### Regression From

Previous Version to 1.22.0

### Architecture

i86

### Storage Explorer Build Number

20211211.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

(Architecture ia32)
I used to produce reports called MessageLogs for a specific week or specific month. I was able to custom the dates and this would produce the required report. Since the latest update, I put in specific dates but it just ignores and produces a report on all MessageLogs.

<img width="462" alt="Capture1" src="https://user-images.githubusercontent.com/97737683/149513574-d4c90117-30e5-4e3a-8173-3cb021968d92.PNG">

<img width="462" alt="Capture1" src="https://user-images.githubusercontent.com/97737683/149513606-53f709ea-c481-4adf-be72-7d29bcaee586.PNG">

### Steps to Reproduce

1. Launch Storage Explorer
2. Open Microsoft Azure
3. Open Storage Accounts
4. Open Site
5. Open Tables
6. Open MessageLogs
7. Click Query
8. Input Clauses required
9. Click Green play button
10. Click Export

### Actual Experience

1. Ignores the clauses and produces a report containing all messagelogs

### Expected Experience

Produces a report within the specified dates and times

**Comment by craxal** [comment] 2022-01-14 19:27
@xSeanOx This is a known issue and has been addressed.

Duplicate of #5320.

**Closed** 2022-01-14 19:27 UTC
