### ISSUE TITLE
Dates are not formatted using the current locale

### ISSUE THREAD

**Issue by polys** [microsoft/AzureStorageExplorer#1668] opened 2019-08-15 10:40 UTC
**Storage Explorer Version**: 1.9.0
**Build Number**: 20190701.8
**Platform/OS**: Windows 10 (version 1903)
**Architecture**: ia32 (from About box); 64-bit OS; x64 processor
**Regression From**:  N/A

## Bug Description ##
Dates seem to always be formatted using the US locale instead of the system's (e.g. 8/15/2019).

Could you please respect the locale or at least use a less ambiguous format?

I'll admit that seeing something like `8/15/2019` isn't the end of the world because it's obvious `15` can't be the month, but there's no way to know what's what with something like `8/9/2015`.

## Steps to Reproduce ##
Just see any date anywhere.

## Expected Experience ##
Date formatting respects the locale or uses a standard like ISO 8601.
## Actual Experience ##
Dates seem to always use the US locale.

## Additional Context ##
Windows regional format: **English (United Kingdom)**

**Comment by craxal** [comment] 2019-08-19 18:17
Duplicate of #59.

**Closed by craxal** 2019-08-19 18:17 UTC
