### ISSUE TITLE
Wrong content type for service-worker.js on Windows 10

### ISSUE THREAD

**Issue by m0jimo** [microsoft/AzureStorageExplorer#3200] opened 2020-07-09 07:46 UTC
**Storage Explorer Version**: 1.13.0, 1.13.1, 1.14.0
**Build Number**: 20200430.5, 20200624.3
**Platform/OS**: Windows
**Architecture**: ia32
**Regression From**:  no other version tested

## Bug Description ##
When PWA application is copied from Windows File Explorer to remote location static web site `$web`, there is a wrong content type `text/plain` for `service-worker.js` after the file is copied. It results in non working PWA with `The script has an unsupported MIME type ('text/plain')` error in the console and PWA is not loaded.

If the file is copied on **iMac** version of Azure Copy Explorer or using **portal.azure.com** PWA works as expected.

## Steps to Reproduce ##
Drag and drop `service-worker.js` (generated from Quasar - VueJs application) to upload it to $web (static website) the file type is `text/plain` on Windows.

## Expected Experience ##
Content type should be `text/javascript` or other supported mime type for service-worker.js.

## Actual Experience ##
Content type is `text/plain`

## Additional Context ##
Web interface for uploading files on portal.azure.com remains the correct content type as well as iMac Azure Copy Explorer.

**Comment by m0jimo** [comment] 2020-07-09 09:20
Related to: #2289 , #2956

**Comment by MRayermannMSFT** [comment] 2020-07-11 00:14
Ya basically a duplicate of those two. Both of which should be fixed in our upcoming 1.14.1 release. I'm going to close this. After we ship, feel free to open a new issue if there's something you aren't happy with still.

**Closed by MRayermannMSFT** 2020-07-11 00:14 UTC
