### ISSUE TITLE
Auto light/dark mode based on system (macOS)

### ISSUE THREAD

**Issue by hologerry** [microsoft/AzureStorageExplorer#3690] opened 2020-10-18 17:06 UTC
**Describe the solution you'd like**
Update the appearance by reading the system light/dark mode api.
I am not familiar with the implementation, but I think it can be implemented as some applications already have this feature.
Thanks a lot!

**Comment by MRayermannMSFT** [comment] 2020-10-19 17:34
Duplicate of #2626 and will rename the title of that issue to include macOS/all OS's

**Closed by MRayermannMSFT** 2020-10-19 17:34 UTC
