### ISSUE TITLE
The value of the property 'Name' is focused when opening one item's Properties dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4424] opened 2021-05-06 10:19 UTC
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210506.3
**Branch**: main
**Platform/OS**: Linux Ubuntu 18.04
**Architecture**: x64
**How found**: From executing a test case
**Regression From**: Previous release (1.19.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Select one blob container -> Right click it -> Click 'Properties...'.
3. Check no property's value is focused on the Properties dialog.

## Expected Experience ##
No property's value is focused.

## Actual Experience ##
The value of the property 'Name' is focused.
![Linux](https://user-images.githubusercontent.com/41351993/117281100-dd3c2a80-ae95-11eb-89cb-e7721c6346bc.gif)

## Additional Context ##
1. This issue doesn't reproduce on Windows & Mac.
2. This issue reproduces for items that have Properties dialog.

**Comment by JasonYeMSFT** [comment] 2021-06-04 22:15
This might share the same cause with #4489.

**Comment by MRayermannMSFT** [comment] 2021-06-07 18:18
Let's go to accessibility office hours during 1.21 and figure out what is better for opening a dialog/new windows.

Focus the window vs focus the first control

?

**Comment by MRayermannMSFT** [comment] 2021-08-06 23:28
Accessibility office hours says that there is no guideline on what should be focused first. We also understand that this regression is likely caused by caching the dialog window. Ultimately we will won't fix for now. Can revisit in the future if needed.

**Closed by MRayermannMSFT** 2021-08-06 23:28 UTC
Labels: 🧪 testing, :beetle: regression, :computer: linux, :grey_question: investigate
