### ISSUE TITLE
[ADLSinASE] Can not find value type when create new vertex.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/AzureStorageExplorer#1333] opened 2019-04-24 09:25 UTC
Build:
StorageExplorer-ia32

Repro Steps:
1. Open Explorer
2. Find graph tab then click it.
3. Click New Vertex button.
4. Click Add Property

Result:
       Can not find and seclect value type.
![image](https://user-images.githubusercontent.com/35950097/56648421-e5154180-66b5-11e9-934d-faa0c526aac1.png)

**Comment by MRayermannMSFT** [comment] 2019-04-24 17:43
Dupe of #1237

**Closed by MRayermannMSFT** 2019-04-24 17:43 UTC
Labels: :gear: cosmosdb, 🧪 testing
