### ISSUE TITLE
propose that a json format "text" preview be added

### ISSUE THREAD

**Issue by lbilodeau** [microsoft/AzureStorageExplorer#6240] opened 2022-11-01 21:04 UTC
Concerning Storage explorer's preview feature It would be nice if the file has a json suffix it tries to display the file in formatted JSON, preferable with collapsible nodes.

**Comment by JasonYeMSFT** [comment] 2022-11-03 17:57
This is a duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/6195. We will consider the capability to toggle between original content and formatted JSON in the preview editor.

**Closed** 2022-11-03 17:58 UTC
Labels: :heavy_check_mark: duplicate
