### ISSUE TITLE
A confirmation dialog arises when opening a trusted file under one folder which name starting with whitespace

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3003] opened 2020-05-19 09:41 UTC
**Storage Explorer Version:** 1.14.0-dev
**Build**:[ 20200519.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3738672)
**Branch**: master
**Platform/OS:** Windows 10
**Architecture:** ia32
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer -> Go to Settings -> Transfers -> File Open -> Trusted File Extensions.
2. Make sure the **.txt** extension is included in Trusted File Extensions.
3. Expand one storage account -> File Shares.
4. Create a file share -> Create a folder with name starting with whitespace. 
5. Upload one .txt file to the folder -> Open the file.
6. Check the result.

**Expect Experience:**
No dialog arise.

**Actual Experience:**
A confirmation dialog arises.
![image](https://user-images.githubusercontent.com/41351993/82310425-f46cd880-99f6-11ea-8308-881bd6c9207b.png)

**More Info:**
1. This issue also reproduces for blob containers,
2. Related bug: [2857](https://github.com/microsoft/AzureStorageExplorer/issues/2857)

**Comment by craxal** [comment] 2020-05-19 16:37
Duplicate of #2857.

**Closed by craxal** 2020-05-19 16:37 UTC
Labels: :computer: windows, :gear: blobs, :gear: files, 🧪 testing
