### ISSUE TITLE
Speed Limitation Request

### ISSUE THREAD

**Issue by carlastubbs** [microsoft/AzureStorageExplorer#2017] opened 2019-10-08 11:29 UTC
Please add a way to limit the speed of the transfers.  

Even a slider with 10Mb / 100Mb / 1Gb / Unlimited would be welcome as we have seen it consume every bit of the pipe available.

We can not do transfers during office hours due to the saturation on the link that Azure Storage Explorer creates.

**Comment by craxal** [comment] 2019-10-08 18:16
Duplicate of #13.

**Closed by craxal** 2019-10-08 18:16 UTC
