### ISSUE TITLE
Provide timestamp for Folder Statistics

### ISSUE THREAD

**Issue by rababued** [microsoft/AzureStorageExplorer#1674] opened 2019-08-17 02:26 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rababued** [comment] 2019-08-17 02:27
Would be really nice to have the timestamp each time I run an activity like Folder Statistics... it would give me an idea on time slice between Folder Statistics snapshots...

**Comment by MRayermannMSFT** [comment] 2019-08-19 18:36
Duplicate of #222

**Closed by MRayermannMSFT** 2019-08-19 18:36 UTC
Labels: :bulb: feature request, :bulb: settings
