### ISSUE TITLE
After configuring an invalid proxy and restarting the program, it hangs in the startup process

### ISSUE THREAD

**Issue by cyluxx** [microsoft/AzureStorageExplorer#2639] opened 2020-02-17 13:12 UTC
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  

## Bug Description ##
After configuring an invalid proxy and restarting the program, it hangs in the startup process.

## Steps to Reproduce ##
1. Start the program and go to the Proxy Settings
2. Configure an invalid proxy (I can't say, if it has to be a valid address)
3. Restart the program
4. It now hangs in the startup process, i.e you only see the loading window.

## Expected Experience ##
The program should restart normally.

## Actual Experience ##
It hangs in the startup process.

## Additional Context ##
_No additional Context_

**Comment by MRayermannMSFT** [comment] 2020-03-03 18:16
@cyluxx , I'm unable to reproduce this issue. If I set an invalid proxy. I simply get:
![image](https://user-images.githubusercontent.com/21112697/75806061-d79a0080-5d37-11ea-9cc0-c1fd16c68f6a.png)
Can you elaborate on what you mean by "invalid proxy"? Maybe you're doing something that is invalid in a different way than I am testing.

Also, if you are blocked by startup not finishing, you can go edit the settings file and disable proxy manually. To do that:
1. Open C:\Users\<your username>\AppData\Roaming\StorageExplorer\settings.json
2. Change `"application.proxy.useProxy": true,` to be `"application.proxy.useProxy": false,` **Your line may or may not have a comma, if it does not, leave the comma off.``**

**Comment by MRayermannMSFT** [comment] 2020-03-13 18:46
Moving this to 1.14. Please reply @cyluxx!

**Comment by cyluxx** [comment] 2020-03-16 16:13
> 1. Open C:\Users<your username>\AppData\Roaming\StorageExplorer\settings.json
> 2. Change `"application.proxy.useProxy": true,` to be `"application.proxy.useProxy": false,` **Your line may or may not have a comma, if it does not, leave the comma off.**

This worked. I can start the program again.

I can recap what happened: The address is the location of the proxy autoconfig script of my company that I accedently put into the proxy input field. That probably produced a timeout.

**Closed** 2020-05-27 18:56 UTC
Labels: :beetle: bug, :grey_question: more info, :heavy_check_mark: no repro
