### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by aspnerd** [microsoft/AzureStorageExplorer#7200] opened 2023-08-17 17:12 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.0 (92)

### Regression From

yes, not sure

### Architecture

x64

### Storage Explorer Build Number

20230810.9

### Platform

Windows

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "{\"name\":\"Node Fetch Error\",\"cause\":{\"cause\":{\"name\":\"ConnectTimeoutError\",\"code\":\"UND_ERR_CONNECT_TIMEOUT\",\"message\":\"Connect Timeout Error\"}},\"code\":\"UND_ERR_CONNECT_TIMEOUT\"}"
}

### Steps to Reproduce

1. Launch Explorer
2. Expand subscription
3. expand storage account

### Actual Experience

I can't expand storage containers without an error:

### Expected Experience

that it would work?

### Additional Context

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "{\"name\":\"Node Fetch Error\",\"cause\":{\"cause\":{\"name\":\"ConnectTimeoutError\",\"code\":\"UND_ERR_CONNECT_TIMEOUT\",\"message\":\"Connect Timeout Error\"}},\"code\":\"UND_ERR_CONNECT_TIMEOUT\"}"
}

**Comment by JasonYeMSFT** [comment] 2023-08-17 22:06
@aspnerd This is the first time I see this error. Could you do the following things to help us figure out what's wrong?
- In settings, set log level to "Debug".
- Restart storage and reproduce this issue.
- Go to App Menu > Help > Go to log directories. It will open the directory for our log files. You can grab the latest folder of log files and share them with us.
- After that I recommend setting the log level back to "Info" to reduce your future log file sizes.

Besides, how long does it take for the error to show up? Does it immediately show up as soon as you expand the storage accounts node or does it show up after a few seconds? If it's the 2nd case, how many seconds does it take roughly before the error shows up?

I tried searching for the error and some people mention IPv6 network. Could you try to figure out if your network supports IPv4 or IPv6 or both?

**Comment by aspnerd** [comment] 2023-08-17 23:21
Ok, so....after having this error previously, I grabbed the old version and installed it over the latest update because I had to get back in and have it work. After your reply above, I updated ASE, set the log levels, restarted, and now I have no issue.
I am attaching the logs from earlier when I had the issue. Hopefully, it helps.
[2023-08-17_130814.zip](https://github.com/microsoft/AzureStorageExplorer/files/12374077/2023-08-17_130814.zip)

**Comment by MRayermannMSFT** [comment] 2023-08-21 16:17
Perhaps this was just a transient network issue then? I'm not seeing anything in the logs that point to anything obvious. We'll close this as no repro since you can't reprdouce anymore. Feel free to open a new issue if it happens again.

**Closed by MRayermannMSFT** 2023-08-21 16:17 UTC
Labels: :grey_question: investigate

**Comment by aspnerd** [comment] 2023-08-21 16:24
> Perhaps this was just a transient network issue then? I'm not seeing anything in the logs that point to anything obvious. We'll close this as no repro since you can't reprdouce anymore. Feel free to open a new issue if it happens again.

It was not, as I had just been connected, installed the new version and it failed.

**Comment by umedipi** [comment] 2024-12-05 15:52
Hi,

I've the  issue when accessing child resources 

attaching logs

please assist.[Logs.zip](https://github.com/user-attachments/files/18025947/Logs.zip)


Regards,
Umed Ali

**Comment by JasonYeMSFT** [comment] 2024-12-06 00:07
@umedipi Could you please open a new issue and fill the issue template to give more details of the issue you are facing? We need information like the platform you are on, the version of Storage Explorer you are using, and so on to help troubleshoot.

From the logs you shared. It seems you are listing blob containers for two kinds of storage accounts:
- A storage account with a weird name, which looks like an email address and is invalid
- The local emulator at 127.0.0.1:10000

Are you sure you are trying to list blob containers for either of the two cases? For the 1st case, you may double check to see if you have connected to your storage account with the correct storage account name. For the 2nd case, you may double check to see if you have your Azurite emulator started. If you need additional help, please provide more information in a new issue and we'll help you there.

**Comment by umedipi** [comment] 2024-12-06 08:50
Hi Jason,

Thanks for prompt response, you are right, I've started both storage at the same time, azurite and local emulator. this is probably therefore, both are fighting. 

I am trying to stop azurite from python script but it's not happening, 

can you please advise how to stop it?

Regards,
Umed Ali

**Comment by JasonYeMSFT** [comment] 2024-12-06 17:37
@umedipi To stop Azurite or emulator, you will need to find the process and kill it in the task manager.
