### ISSUE TITLE
'Undelete Selected' is enabled for one active blob

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#474] opened 2018-07-24 12:05 UTC
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: MacOS High Sierra
**Architecture**: x64
**Build Number**: 20180724.4
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Open one blob container which contains one blob at least.
3. Make sure under 'Active blobs(default)' -> Right click one blob then check the context menu.

#### Expected Experience: ####
The 'Undelete Selected' is disabled for the active blob.

#### Actual Experience: ####
The 'Undelete Selected' is enabled for the active blob.
![activeblob](https://user-images.githubusercontent.com/34729022/43136254-a65c015a-8f37-11e8-9315-9d6989a7240e.png)

**Comment by JasonYeMSFT** [comment] 2018-07-24 16:36
This is due to some limitation of Mac OS. We won't fix it for 1.4.0.

**Comment by jinglouMSFT** [comment] 2018-07-24 17:40
Keep it open for investigation in future milestone.

**Comment by v-xianya** [comment] 2019-11-25 10:12
This issue doesn't reproduce on build master/20191123.2. So we close it.
![image](https://user-images.githubusercontent.com/41351993/69531636-0c244200-0f29-11ea-8b99-33a3873afabb.png)

**Closed by v-xianya** 2019-11-25 10:12 UTC
Labels: 🧪 testing, :gear: blobs, :computer: mac, :grey_question: investigate
