### ISSUE TITLE
Azure Government - Error loading property

### ISSUE THREAD

**Issue by Phydeauxman** [Microsoft/AzureStorageExplorer#749] opened 2018-10-10 10:20 UTC
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Windows 10 and Mac OS High Sierra 10.13.6
**Architecture**: x64
**Regression From**: Was not using a previous version

#### Steps to Reproduce: ####
1. Connect to Azure Government subscription
2. Click on storage account name under Azure Government subscription
3. View `Properties`

#### Expected Experience: ####
Expect all functions, properties and details of a storage account to be enumerated

#### Actual Experience: ####
Can enumerate storage accounts and a limited set of the properties of the storage account but nothing underneath them nor functions. Have tried 3 different Azure Government subscriptions from 3 different computers.

![storageexplorererror](https://user-images.githubusercontent.com/16844071/46729364-23d03680-cc53-11e8-9636-a40d27e7497b.jpg)

**Comment by jinglouMSFT** [comment] 2018-10-10 17:53
Duplicate of #696.  There is a workaround outlined in #696 if you are blocked.  We are working on a build to revert back to the old API until all Azure supports the new API.  Should be available soon.

**Closed by jinglouMSFT** 2018-10-10 17:53 UTC
