### ISSUE TITLE
File preview feature

### ISSUE THREAD

**Issue by sdn77** [microsoft/AzureStorageExplorer#6172] opened 2022-10-17 06:30 UTC
Great idea on the new preview feature. Could you include the following in the future, parquet files as well as text files in compressed formats.

**Comment by MRayermannMSFT** [comment] 2022-10-17 16:57
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/6153

**Closed by MRayermannMSFT** 2022-10-17 16:57 UTC
