### ISSUE TITLE
There is no refresh notification when deleting a blob container with the setting 'Auto Refresh On Change' unchecked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7989] opened 2024-06-07 05:53 UTC
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240607.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.34.0)

## Steps to Reproduce ##
1. Open ‘Settings -> Data Explorers' -> Disable the setting 'Auto Refresh On Change'.
2. Expand one storage account -> Right click the 'Blob Containers' node.
3. Create a blob container -> Right click the 'Blob Containers' node -> Click 'View All'.
4. Select the blob container on the view all containers explorer -> Delete it.
5. Check whether there is a refresh notification.

## Expected Experience ##
There is a refresh notification.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d49caa79-86a4-4e82-bc87-2874825821cd)

## Actual Experience ##
There is no refresh notification.

## Additional Context ##
This issue can't be reproduced consistently.

**Comment by craxal** [comment] 2024-06-12 18:52
@v-xianya I'm not able to reproduce. Is it possible that the underlying issue with #7983 is also contributing to this? If you can figure out how to consistently reproduce this, that would be helpful.

**Comment by v-xianya** [comment] 2024-06-13 06:13
Hi @craxal could you run the steps below  to see if this issue can be reproduced? 
1. Disable the setting 'Auto Refresh On Change'.
2. Expand one storage account -> Blob Containers.
3. Open view all containers tab.
4. Then create a blob container (either the tree node or the View All Containers tab).
5. Then delete it from view all containers explorer.

**Comment by craxal** [comment] 2024-06-13 17:00
I have followed those exact steps multiple times and have not been able to reproduce. Do you have app logs to share (debug verbosity)?

**Comment by v-xianya** [comment] 2024-06-14 02:39
Here is the log:
[2024-06-14_023308.zip](https://github.com/user-attachments/files/15830919/2024-06-14_023308.zip)

**Comment by craxal** [comment] 2024-07-17 20:34
Likely the same root cause as #7976.

**Comment by craxal** [comment] 2024-07-23 22:05
Fix merged.

**Closed by craxal** 2024-07-23 22:05 UTC
Labels: :white_check_mark: merged, 🧪 testing, :gear: blobs, :beetle: regression

**Comment by v-xianya** [comment] 2024-07-24 02:19
Verified this issue on the main build 20240724.1. Fixed.
