### ISSUE TITLE
Very Slow Launch and High CPU Usage

### ISSUE THREAD

**Issue by KSib** [Microsoft/AzureStorageExplorer#478] opened 2018-07-24 19:17 UTC
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**:  Windows
**Architecture**: ia32
**Regression From**: It was fine but I don't know where the old downloads are to tell you. I was going to try a previous version before posting here. Also happened with 1.0.0. Where are the previous versions?

#### Steps to Reproduce: ####
1. Download and install this program from https://azure.microsoft.com/en-us/features/storage-explorer/
2. Do a clean boot https://support.microsoft.com/en-in/help/929135/how-to-perform-a-clean-boot-in-windows
3. Launch Task Manager
4. Launch this application

#### Expected Experience: ####
To launch faster and not consume so much CPU.

#### Actual Experience: ####
Watch as 60+ processes are created and CPU spikes to 99% for 10+ seconds if doing a clean boot. Increases a lot more if not doing a clean boot.

This is on an i7-3740QM, if that helps and on an SSD.
Original issue: https://social.msdn.microsoft.com/Forums/en-US/ad029871-462a-4815-b97b-29fd5d361068/azure-storage-explorer-high-cpu-usage?forum=windowsazuredata

**Comment by craxal** [comment] 2018-07-27 20:41
Marking this as duplicate of #166. The bug does not appear to be restricted to Windows 10.

**Closed by craxal** 2018-07-27 20:41 UTC
Labels: :white_check_mark: duplicate
