### ISSUE TITLE
File / Blob LastModified property as columns

### ISSUE THREAD

**Issue by ste-gia** [microsoft/AzureStorageExplorer#2862] opened 2020-04-21 22:36 UTC
In the current version (1.12.0) of Storage Explorer, the LastModified property of files / blobs is not shown as column.

This request is about providing the option to select the LastModified property of files / blobs to be shown as column, equal to the way the size is shown.

**Comment by MRayermannMSFT** [comment] 2020-05-11 18:37
@ste-gia 

For blobs, we see last modified. Can you show us a screenshot where you don't see it?

For files, at this time the API doesn't return that information to us. I'll pass your feedback to the API team.

**Comment by craxal** [comment] 2020-05-13 22:33
Possibly a duplicate of #2802?

**Closed** 2020-06-22 18:27 UTC
