### ISSUE TITLE
AzureStorageExplorer freezes upon deleting folder

### ISSUE THREAD

**Issue by sylr** [Microsoft/AzureStorageExplorer#476] opened 2018-07-24 15:29 UTC
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: 

#### Steps to Reproduce: ####
1. Delete folder with no more than 24 files in it
2. It freezes

**Comment by JasonYeMSFT** [comment] 2018-07-26 20:59
Duplicate of #416

**Closed** 2018-07-27 20:58 UTC
Labels: :white_check_mark: duplicate
