### ISSUE TITLE
Allow Custom Domains when using 'Copy URL'

### ISSUE THREAD

**Issue by jasongaylord** [microsoft/AzureStorageExplorer#2951] opened 2020-05-08 19:21 UTC
I'm frustrated when I use the **'Copy Url'** feature as it always copies the URL based on the default domain. It would be great if I can set the domain for the blog files as I may have an Azure CDN sitting on top of the resource. So, instead of getting `https://myblob.blob.core.windows.net/container/myfile.docx` it would be nice to get the URL from the **'Copy URL'** feature with my custom domain or subdomain such as `https://myfancydomain.com/container/myfile.docx`.

**Comment by craxal** [comment] 2020-05-09 00:07
Duplicate of #1153. This work has already been merged and will be available in 1.14.0.

**Closed** 2020-05-09 00:10 UTC
Labels: :heavy_check_mark: duplicate
