### ISSUE TITLE
The strings 'Services & Resource types' show blank and the strings 'Delete versions/ tag/ Filter' show 'Unkown' in the 'connect summary' dialog when using SAS to attach a storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4079] opened 2021-02-09 08:14 UTC
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210208.7
**Branch**: feature/connect
**Platform/OS**: Windows 10/MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one storage account -> Generate a SAS for it with full permissions -> Copy the SAS.
2. Open connect dialog by right clicking the second plug button in the vertical toolbar.
3. Select 'Storage account -> Shared access signature (SAS)' -> Click 'Next'.
4. Paste the SAS to the 'SAS connection string' text box.
5. Click 'Next' -> Check whether all the strings show well on the dialog.

## Expected Experience ##
All strings show well.

## Actual Experience ##
1. The strings 'Services & Resource types' show blank.
2. The strings 'Delete versions/ Tag/ Filter' show 'Unkown'.
![image](https://user-images.githubusercontent.com/41351993/107331352-bd42d800-6aed-11eb-9538-fb0d1794022a.png)

**Comment by craxal** [comment] 2021-02-09 17:58
@v-xianya
- Missing "Services" and "Resource types" labels is definitely a bug.
- "Unknown" is intentional when an unrecognized permission is found. It is misspelled, however.
- Can you explain how you generated the account SAS? According the portal and the Azure documentation, only the following permissions are allowed for account SAS:
  - Read (r)
  - Write (w)
  - Delete (d)
  - Permanent Delete (y)
  - List (l)
  - Add (a)
  - Create (c)
  - Update (u)
  - Process (p)

**Comment by v-limu** [comment] 2021-02-10 02:06
Verified on build 20210210.3 . This issue still reproduces. So we re-open it.
![image](https://user-images.githubusercontent.com/54055206/107454174-63e4a400-6b01-11eb-88cb-7c1bbc6a5c44.png)

**Comment by craxal** [comment] 2021-02-10 22:15
@v-limu We got the details sorted out. A fix has been merged.

Please remember that any unrecognized permissions will generate an "(unknown)" value. That is by design. This is to make it a little easier going forward whenever the platform adds new permissions and users try attaching using a SAS generated from elsewhere.

**Closed by craxal** 2021-02-10 22:15 UTC
Labels: :gear: attach, :heavy_check_mark: merged, 🧪 testing

**Comment by v-xianya** [comment] 2021-02-18 03:01
Verified this issue on build 20210218.1. Fixed.
![image](https://user-images.githubusercontent.com/41351993/108298791-7bdeb680-71d8-11eb-9521-520dc8eaf153.png)
