### ISSUE TITLE
Restore fileshare enabled when folders and files are selected

### ISSUE THREAD

**Issue by JasonYeMSFT** [Microsoft/AzureStorageExplorer#402] opened 2018-07-11 00:25 UTC
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: Not a regression
#### Steps to Reproduce: ####
1. Have a Fileshare and upload a folder and a file
2. Create a snapshot of the fileshare
3. Go to the snapshot view and select both the folder and the file
4. Click "Restore Snapshot"

#### Expected Experience: ####
Either "Restore Snapshot" is disabled or the operation ignores the folder and succeed on restoring the file.

#### Actual Experience: ####
It only tries on the folder and gives an error in the activity log.

**Comment by MRayermannMSFT** [comment] 2018-07-12 18:47
Duplicate of #328

**Closed** 2018-07-17 23:20 UTC
Labels: :white_check_mark: duplicate
