### ISSUE TITLE
Unable to open SE due to it keeps loading for a long time

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1438] opened 2019-06-05 09:10 UTC
**Storage Explorer Version:** 1.8.1
**Build**: 20190605.4
**Platform/OS:** Ubuntu 18.04
**Commit:** a7b2b07e
**Regression From:** Previous release 1.8.1

**Steps to reproduce:**
1. Try to open Storage Explorer

**Expect Experience:**

Succeed to open the Storage Explorer.

**Actual Experience:**

Keep loading for a long time.
![image](https://user-images.githubusercontent.com/34729022/58944582-b7431280-87b4-11e9-8b63-a110ab9efd0e.png)

**More info:**

This issue doesn't reproduce on latest master build.

**Comment by MRayermannMSFT** [comment] 2019-06-19 18:16
Closing. This build should not have been tested? We'll email you @v-xuanzh

**Comment by MRayermannMSFT** [comment] 2019-06-19 18:17
Reopening. This is from settings branch.

**Comment by craxal** [comment] 2019-07-01 21:50
Duplicate of #1438.

**Comment by craxal** [comment] 2019-07-08 17:39
@v-xianya I seem to be having trouble reproing with current builds. Does this still happen for you? Make sure you kill any other Storage Explorer processes before you try.

**Comment by v-xianya** [comment] 2019-07-09 06:33
Hi @craxal Verified this issue using the build feature/main-host 20190624.2. 

1. This issue doesn't reproduce when using snap to install Storage Explorer.
2. This issue still reproduces when downloading *.tar.gz file to install Storage Explorer.

**Closed** 2019-07-11 23:07 UTC
Labels: :beetle: regression, :computer: linux, 🧪 testing
