### ISSUE TITLE
Cannot get in to view or edit the blob containers after creating a static website.

### ISSUE THREAD

**Issue by comfycoder** [Microsoft/AzureStorageExplorer#373] opened 2018-07-01 14:22 UTC
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10
**Architecture**: Azure storage with a Vue.js app.
**Regression From**: N/A

#### Steps to Reproduce: ####
1. Create a new Storage Account using the StorageV2 kind.
2. Use the Static website (preview) to create a static website.
3. Upload static website files using Azure portal.
4. Launch the Microsoft Azure Storage Explorer application.
5. Try to open the storage account and view the blob container that was created ($web).

#### Expected Experience: ####
Expected to be able to see and edit files in the blob containers.

#### Actual Experience: ####
The Blob folder opens and a "Loading..." message appears that never goes away.
Cannot get into the blob containers at all.

**Comment by PeterSelchDahl** [comment] 2018-07-02 10:16
I see the same behavior on my Windows 10 PC with the same version. The Storage Explorer within the Azure Portal have no issues listed the new website. Once I disable static website and delete the contatiner I have no issue loading the containers in the storage account

**Comment by JasonYeMSFT** [comment] 2018-07-02 15:41
This issue is a duplicate of #223. We will make it work in the next release.

**Closed by JasonYeMSFT** 2018-07-02 15:41 UTC
Labels: :white_check_mark: duplicate
