### ISSUE TITLE
Quick Access Grouping - Tags/Folders

### ISSUE THREAD

**Issue by azmrb** [microsoft/AzureStorageExplorer#4389] opened 2021-04-26 17:06 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

It would be nice to be able to group Quick Access items either by tag(metadata) or folders as only the storage object name is brought across in the UI. A generic blob container name is difficult to identify and at that point the standard nav is faster.

### Desired Solution

User defined folders or tags in the Quick Access section.

**Comment by MRayermannMSFT** [comment] 2021-04-26 17:16
Going to close as duplicate of #2952.

**Comment by MRayermannMSFT** [comment] 2021-04-26 17:16
Please go give that issue a thumbs up if you can!

**Closed by MRayermannMSFT** 2021-04-26 17:16 UTC
Labels: :bulb: feature request
