### ISSUE TITLE
trying to open the storage account

### ISSUE THREAD

**Issue by veonua** [microsoft/AzureStorageExplorer#1990] opened 2019-10-03 10:56 UTC
[Window Title]
Microsoft Azure Storage Explorer

[Content]
Unable to retrieve child resources.

Details:
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:636dcee8-001e-0013-24d8-798ce3000000
Time:2019-10-03T10:54:30.0547997Z

[OK]

**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by JasonYeMSFT** [comment] 2019-10-07 16:20
What type of authentication are you using for the storage account. Did you sign in to some subscription? Or you were using a SAS token or name and key?

**Comment by veonua** [comment] 2019-10-07 16:39
My company credentials, this is an issue of Windows app.

Linux app worked in the end. But please add snap install instructions on
the main page.

**Comment by MRayermannMSFT** [comment] 2019-11-18 19:21
Closing since you were unblocked.

**Comment by veonua** [comment] 2019-11-18 19:59
I am not, a have to use another OS to use this beautiful piece of software! I can not tell it unblocked

**Comment by JasonYeMSFT** [comment] 2019-11-18 20:03
We have never seen this error before and might need to do some investigation to figure out the cause. Could you please tell us the storage account type (e.g. blob, adls gen2) and your auth type (e.g. sign-in, Key attached, SAS attached)? Also which version of Storage Explorer are you using?

**Comment by veonua** [comment] 2019-11-18 21:51
![image](https://user-images.githubusercontent.com/1540142/69096935-c1508900-0a55-11ea-920d-2cb63dcfc3bb.png)

this one never opens on Windows 10, spins forever

**Comment by veonua** [comment] 2019-11-18 21:52
signed in using my work email account, just re-authenticated

**Comment by MRayermannMSFT** [comment] 2019-12-16 19:30
At what point are you receiving the "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature." error message? Is it when expanding the Storage Account, listing blob containers, exploring a blob container, etc.?

**Comment by veonua** [comment] 2019-12-16 21:00
I believe the issue should be considered as stale , as soon as I don't use
the app anymore, and there is no way to provide better information

**Comment by MRayermannMSFT** [comment] 2020-01-06 18:45
Ok. Sounds good.

**Closed by MRayermannMSFT** 2020-01-06 18:45 UTC
