### ISSUE TITLE
Allow an option to set proxy settings centrally/automatically

### ISSUE THREAD

**Issue by Sokon77** [microsoft/AzureStorageExplorer#2383] opened 2019-12-04 16:14 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MRayermannMSFT** [comment] 2019-12-09 19:04
Duplicate of #1534

**Closed by MRayermannMSFT** 2019-12-09 19:04 UTC
