### ISSUE TITLE
Ability to Organise Quick Access Items into Folders

### ISSUE THREAD

**Issue by lymedo** [microsoft/AzureStorageExplorer#4795] opened 2021-08-13 06:48 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I have many storage accounts for solutions, across subscriptions/environments which are pinned in the quick access section and finding/selecting the desired account becomes difficult when viewed in a long list.

### Desired Solution

The ability to create folders within quick access to organise items into logical groups.

### Alternatives and Workarounds

Ability to group by subscription.

**Comment by MRayermannMSFT** [comment] 2021-08-16 17:11
Duplicate of #2952

**Closed by MRayermannMSFT** 2021-08-16 17:11 UTC
Labels: :bulb: feature request, :gear: quick access
