### ISSUE TITLE
The layout of the ‘Manage Permission’ dialog is odd

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#880] opened 2018-11-19 10:07 UTC
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181117.12
Commit: 78a0d1ab
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Expand an ADLS Gen2 account -> Create a blob container -> Create a folder .
2. Click ‘Manage Permission’ for the folder -> Check ‘Manage Permission’ dialog contents.

#### Expected Experience: ####
The layout of the 'Manage Permission' dialog shows well.

#### Actual Experience: ####
The layout of the 'Manage Permission' dialog is odd.
![image](https://user-images.githubusercontent.com/41351993/48698687-ae2c9280-ec22-11e8-9cd9-a28648d9e7c0.png)

**Comment by jinglouMSFT** [comment] 2018-11-22 01:59
This is because there are missing files the installer didn't install.

**Comment by jinglouMSFT** [comment] 2018-11-22 02:03
Bug 898 is a dupe of this bug.

**Comment by MRayermannMSFT** [comment] 2018-11-27 17:46
Merged into the feature branch

**Closed by MRayermannMSFT** 2018-11-27 17:46 UTC
Labels: :exclamation: must fix, :gear: adls gen2, testing
