### ISSUE TITLE
Show a failed activity log after deleting one blob snapshot successfully 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2402] opened 2019-12-09 11:09 UTC
**Storage Explorer Version:** 1.11.1
**Build:** [20191206.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3301659)
**Branch:** dev/marayerm/electron7/packaging
**Platform/OS**: Windows 10/Linux Ubuntu 18.04
**Architecture:** ia32
**Regression From:** Previous build ([20191206.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3299462))

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Upload a blob to it -> Create snapshot for the blob.
3. Manage Snapshots -> Try to delete the snapshot.
4. Check the result.

**Expect Experience:**
Show a successful activity log.

**Actual Experience:**

1. Succeed to delete the blob snapshot.
2. The activity log shows 'Failed to delete...'.
![image](https://user-images.githubusercontent.com/54055206/70424566-8e287500-1aaa-11ea-905d-b54f8bbec3b5.png)

**More Info:**
This issue doesn't reproduce on MacOS.

**Comment by JasonYeMSFT** [comment] 2019-12-16 22:23
The issue is caused by an Electron bug https://github.com/electron/electron/issues/21515.

A workaround for this bug will be implemented.

**Comment by v-xianya** [comment] 2020-05-07 02:50
This issue is fixed on build electron/8-[20200504.7](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3708219&view=results). So we close it.

**Closed by v-xianya** 2020-05-07 02:50 UTC
Labels: :beetle: regression, :gear: blobs, :grey_question: external, ⚡ electron update required, 🧪 testing
