### ISSUE TITLE
Hangs when attempting to execute any command that brings up a modal dialog

### ISSUE THREAD

**Issue by mrevow** [microsoft/AzureStorageExplorer#5276] opened 2021-12-17 17:03 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Regression From

Only started happening a couple of weeks - May be related to recent Windows 11 updates

### Architecture

x64

### Storage Explorer Build Number

20211211.10

### Platform

Windows

### OS Version

Windows 11

### Bug Description

When attempting an operation that brings up a modal dialog, for example deleting a blob, the dialog never appears and the entire app becomes inoperable. In other words clicking anywher on the app just produces a beep from the system

The issue has become more severe with recent Windows 11 updates - Is there an incompatbility?

### Steps to Reproduce

1. Launch Storage explorer
2. Navigate to a blob container 
3. Continue to navigate to a single file (blob) under the container
4. Select the file
5. Click Delete

### Actual Experience

After step (5) in repro steps:
 
6. The expected dialog never appears and the whole storage explorer app  becomes unresponsive. Clicking anywhere results in a beep indicative of when clicking on a windows app when a modal dialog is visible
7. The only course of action is to kill storage explorere from task manager

### Expected Experience

Expected:  When clicking on delete the confirmation dialog should appear enabling completion of the delete ction

### Additional Context

This only started happening in past few weeks - perhaps related to recent Windows 11 updates.  I tried upgrading from a previous version V1.21.xx to the latest version V1.22.0  but that made no difference to the behaviour

**Comment by MRayermannMSFT** [comment] 2021-12-17 20:00
@mrevow 

We think what may be happening is that that dialog is opened but just off screen such that you cannot see it/move it/interact with it using your mouse. However, you should be able to use the Windows key + either the left or right arrow key to move it back to being visible. So can you:

1. Open task manager
2. Sort by name and look for a group of StorageExplorer.exe processes
3. Count how many there are
1. Do something that should open a dialog
1. Go back to task manager and count how many StorageExplorer.exe processes there are, specifically we want to know if any additional processes appeared
2. Press Windows Key + arrow Key left/right and see if you can make the dialog appear

Let us know if any additional processes appeared, and if using the arrow keys made the dialog visible again.

**Comment by MRayermannMSFT** [comment] 2022-01-03 18:45
Closing as a duplicate of #5262

**Closed by MRayermannMSFT** 2022-01-03 18:45 UTC
