### ISSUE TITLE
Query Builder: Add Substring Search

### ISSUE THREAD

**Issue by jsbosch** [microsoft/AzureStorageExplorer#480] opened 2018-07-24 22:12 UTC
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10 Pro
**Architecture**: amd64
**Regression From**: unknown

#### Steps to Reproduce: ####
1. Open a table in an editor
2. Click Open Query
3. Add a clause for any string type field
4. Select the Operator pull-down menu

#### Expected Experience: ####
Some sort of substring operator. 

#### Actual Experience: ####
There is no substring operator or any other string operators other than lexical comparison. This is very limiting for query building.

**Comment by oaksboard** [comment] 2020-01-28 15:27
The old Azure Storage Explorer had an option to filter results by text matching, so please provide at least a post query filter or search capability within the query results.
As of version 1.12.0 I have to export the query results to a .csv file and then search that file in order to find what I'm looking for.

**Comment by MRayermannMSFT** [comment] 2020-03-16 18:23
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/571

**Closed by MRayermannMSFT** 2020-03-16 18:23 UTC
Labels: :bulb: feature request, :gear: tables
