### ISSUE TITLE
The operations 'Export Selected/Edit/Duplicate/Delete' will act on the wrong item if sort the table by one column previously

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6616] opened 2023-02-28 06:34 UTC
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230224.3
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
3. Right click one table -> Click '[2] Open'.
4. Add two entities as below -> Sort the table by the PartitionKey column.
![image](https://user-images.githubusercontent.com/41351993/221771167-aaedc15a-796b-4a0c-afc5-ab098126fc40.png)

5. The ordered tables as below:
![image](https://user-images.githubusercontent.com/41351993/221768781-1af4d430-622a-435f-bcc3-ce515dd35691.png)
6. Select one entity -> Click 'Edit'.
7. Check whether the command acts on the right item.

## Expected Experience ##
The command acts on the right item.

## Actual Experience ##
The command acts on the wrong item.

## Additional Context ##
This issue doesn't reproduce for the items that keeps in the same location after sorting.

**Comment by craxal** [comment] 2023-03-04 00:29
Duplicate of #6508.

**Closed by craxal** 2023-03-04 00:29 UTC
Labels: :heavy_check_mark: duplicate, 🧪 testing, :gear: tables, :beetle: regression
