### ISSUE TITLE
Authorisation is required 3 times

### ISSUE THREAD

**Issue by paul-charlton** [microsoft/AzureStorageExplorer#4268] opened 2021-03-29 08:08 UTC
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210304.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  n/a

## Bug Description ##
When first adding, or restarting the program, I am required to log in with password, then use the authenticator app three times before getting access to the resources.  This loop is automatic, after completing once the pop up appears again.  Closing it early (after one login) doesn't seem to allow access.

## Steps to Reproduce ##
1. Open app
2. Account Management --> re-enter credentials
3. Enter password
4. Use authenticator app
5. Go to 3

## Expected Experience ##
I'd expect to login once.  Re-entering credentials each time is a pain but I think part of the organisational settings.

## Actual Experience ##
Login x 3

## Additional Context ##
n/a>

**Comment by MRayermannMSFT** [comment] 2021-03-29 21:46
Duplicate of #460. Version 1.19 is going to include some big changes for account management/reauthentication scenarios. Please see the thread on #460 for more info. Thanks!

**Closed by MRayermannMSFT** 2021-03-29 21:46 UTC
