### ISSUE TITLE
A blob displays when cloning one folder if there is a blob which has the same name with the folder

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5444] opened 2022-02-15 08:27 UTC
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20220214.5
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/macOS Monterey 12.2
**Architecture:** ia32/x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob containers.
2. Create a new blob container -> Upload one blob.
3. Upload a folder with the same name as the blob.
4. Right click the folder -> Click 'Clone...'.
5. Input a valid name -> Click 'Clone'
6. Check whether the cloned folder displays.

## Expected Experience ##
The cloned folder displays.

## Actual Experience ##
A blob displays.

## Additional Context ##
Here is the record:
![folder](https://user-images.githubusercontent.com/87792676/154016764-f362905e-b149-4122-a9c2-26611b4e56bd.gif)

**Comment by JasonYeMSFT** [comment] 2022-02-15 18:05
This is a duplicate of issue https://github.com/microsoft/AzureStorageExplorer/issues/3888.

**Closed by JasonYeMSFT** 2022-02-15 18:05 UTC
Labels: 🧪 testing, :gear: blobs
