### ISSUE TITLE
An error occurs when adding an environment with valid Environment name and ARM endpoint on 'Custom Environment' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1580] opened 2019-07-24 08:51 UTC
**Storage Explorer Version:** 1.9.0
**Branch**: master
**Build**: 20190724.6
**Platform/OS:** Linux Ubuntu/macOS High Sierra
**Architecture:** x64
**Regression From:** Previous release 1.9.0

**Steps to reproduce:**
1. Open Connect dialog -> Select 'Add New Environment' from the environment drop down list -> Click 'Next'.
2. Input a valid Environment name and ARM endpoint like below:
**_Environment name_**: test
**_ARM endpoint:_** https://management.azure.com
3. Click 'Next' -> Check the result.

**Expect Experience:**

The sign in page appears after clicking the 'Next'.
![image](https://user-images.githubusercontent.com/34729022/61779157-c187a180-ae32-11e9-9250-99dcfacfb61e.png)

**Actual Experience:**

An error occurs after clicking 'Next' on the 'Custom Environments' dialog.
![image](https://user-images.githubusercontent.com/34729022/61779131-b16fc200-ae32-11e9-80f0-2f4a5dbe1b84.png)

**More info:**

This issue doesn't reproduce on Windows with the same build.

**Comment by JasonYeMSFT** [comment] 2019-08-08 18:00
This bug was caused by a wrong variable name in the identity library. We will close this when a fix is checked in.

**Closed** 2019-08-08 23:19 UTC
Labels: :beetle: regression, :computer: linux, :computer: mac, :heavy_check_mark: merged, 🧪 testing
