### ISSUE TITLE
The activity log is odd when undeleting one deleted blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2403] opened 2019-12-09 11:11 UTC
**Storage Explorer Version:** 1.11.1
**Build:** [20191206.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3301659)
**Branch:** dev/marayerm/electron7/packaging
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS High Sierra
**Architecture:**  ia32/x64
**Regression From:** Previous build ([20191206.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3299462))

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers -> Enable soft delete policy.
2. Create a new blob container -> Upload a blob to it -> Delete the blob.
3. Right click the deleted blob -> **Undelete** -> **Undelete Selected**.
4. Observe the activity log in Activities for minutes.

**Expect Experience:**
The activity log shows well.

**Actual Experience:**
The activity log changed.
![image](https://user-images.githubusercontent.com/54055206/70430184-2fb4c400-1ab5-11ea-8703-f9ff2f601494.png)

**More Info:**
This issue doesn't reproduce for '**undelete by date...**'.

**Comment by JasonYeMSFT** [comment] 2019-12-16 22:23
The issue is caused by an Electron bug https://github.com/electron/electron/issues/21515.

A workaround for this bug will be implemented.

**Comment by v-xianya** [comment] 2020-05-07 02:48
This issue is fixed on build electron/8-[20200507.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3708219&view=results). So we close it.

**Closed by v-xianya** 2020-05-07 02:48 UTC
Labels: :beetle: regression, :gear: blobs, :grey_question: external, ⚡ electron update required, 🧪 testing
