### ISSUE TITLE
A dialog with message "[sprintf] unexpected placeholder" pops up when clicking 'Configure Soft Delete Policy...' for blob containers node

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5394] opened 2022-01-30 06:39 UTC
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20220129.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04
**Language:** Chinese (simplified)
**How Found:** From running test case
**Regression From:** Previous release (1.20.0)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Right click Blob Containers node -> Click 'Configure Soft Delete Policy...'.
5. Check whether the dialog 'Configure Soft Delete Policy' pops up.

## Expected Experience ##
The dialog 'Configure Soft Delete Policy' pops up.
## Actual Experience ##
A dialog with message "[sprintf] unexpected placeholder" pops up.
![image](https://user-images.githubusercontent.com/87792676/151688959-47cee5b6-f343-4de1-a93d-a4dd23fe7879.png)

**Comment by JasonYeMSFT** [comment] 2022-01-31 19:31
This is caused by an incorrectly translated string.

**Comment by JasonYeMSFT** [comment] 2022-02-02 22:40
The fixed resource strings have been merged to main. This should have been fixed.

**Comment by v-kellyluo** [comment] 2022-02-07 02:21
Hi @JasonYeMSFT, verified this issue on the build main/20220206.3, it also reproduces.
![image](https://user-images.githubusercontent.com/87792676/152714687-bafc9c8d-91f0-4269-a3a7-7ff04f69ebd8.png)

**Comment by v-xianya** [comment] 2022-02-14 03:20
Verified this issue on the build main/20220212.2. Fixed.
![image](https://user-images.githubusercontent.com/41351993/153794668-f49cb523-dff9-4d65-98ff-e0ac7e1637d0.png)

**Closed by v-xianya** 2022-02-14 03:20 UTC
Labels: 🧪 testing, :gear: blobs, :beetle: regression, :globe_with_meridians: localization
