### ISSUE TITLE
Display duplicate blobs after uploading the same one blob with 'Use AzCopy ...' disabled 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#721] opened 2018-09-29 08:30 UTC
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180929.2
**Commit**: a985fab8
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Enable 'Use AzCopy for Improved Blob Upload and Download' -> Upload one blob.
2. Disable 'Use AzCopy for Improved Blob Upload and Download' -> Upload the same one blob.
3. Select 'Replace' on 'Upload Conflict' dialog -> Apply.
4. Check the result after replacing successfully.

#### Expected Experience: ####
Succeed to replace and only one blob displays.

#### Actual Experience: ####
Display duplicate blobs without refreshing manually.
![actual](https://user-images.githubusercontent.com/34729092/46243190-e7821800-c3c0-11e8-8f5b-7fdeb2625cb5.png)

**Comment by MRayermannMSFT** [comment] 2018-10-01 17:55
This is the same bug as #183 , except AzCopy is not setting a good content type. They are aware of this issue, so I'll close this as a duplicate of 183.

**Closed by MRayermannMSFT** 2018-10-01 17:55 UTC
Labels: :white_check_mark: duplicate, AzCopy+StgExp, testing
