### ISSUE TITLE
The cursor will jump to the 'Quick Access' node after single clicking the renamed table

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/AzureStorageExplorer#1663] opened 2019-08-14 10:44 UTC
**Storage Explorer Version:** 1.9.0
**Build:** 20190813.12
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a Regression

Steps to reproduce:

1. Rename one table.
2. Click the renamed table after renaming.
3. Check the cursor state.

Expect Experience:
The cursor will focus on the renamed table.

Actual Experience
The cursor will jump to the 'Quick Access' node.

**Comment by JasonYeMSFT** [comment] 2019-08-21 21:28
This is a duplicate of #1596. Closed.

**Closed by JasonYeMSFT** 2019-08-21 21:28 UTC
Labels: :gear: tables, :heavy_check_mark: duplicate, 🧪 testing
