### ISSUE TITLE
Selecting multiple containers (feature request)

### ISSUE THREAD

**Issue by eugenegous** [microsoft/AzureStorageExplorer#3743] opened 2020-11-04 09:39 UTC
I'd just like the option to select multiple containers at once and delete them instead of writing a script.

![Capture](https://user-images.githubusercontent.com/8994511/98094680-45339900-1e92-11eb-9341-2f536ae44968.PNG)

**Comment by MRayermannMSFT** [comment] 2020-11-10 00:40
Duplicate of #852

**Closed by MRayermannMSFT** 2020-11-10 00:40 UTC
Labels: :bulb: feature request
