### ISSUE TITLE
Windows: v1.11.1 can't be launched saying .NET 4.6.2 isn't installed

### ISSUE THREAD

**Issue by Zossin** [microsoft/AzureStorageExplorer#2321] opened 2019-11-25 06:19 UTC
**Storage Explorer Version**:  v1.11.1
**Build Number**:  I can't go to Help menu
**Platform/OS**: Windows 10
**Architecture**: I can't go to Help menu
**Regression From**:  It was working in previous version, but I can't get the version number now

## Bug Description ##

I'm seeing below dialog after upgrading to v1.11.1:
![image](https://user-images.githubusercontent.com/1637100/69516955-3e1bbf80-0f8e-11ea-9713-7bcafa3c109e.png)
I'm pretty sure that my Windows 10 has both latest .NET 4.6.2 & 4.7.2 (runtime + Dev Pack) installed.

## Steps to Reproduce ##

N/A

## Expected Experience ##

It's supposed to be launched.

## Actual Experience ##

I can't launched the tool any longer.

**Comment by LucGosso** [comment] 2019-11-25 12:34
Just updated, having the same issue. Ive got .net framework 4.8 installed on Win 10. Downgrade to 1.10.0 and it works again.

**Comment by Monkeyfish7000** [comment] 2019-11-25 16:35
@LucGosso How to get an older version? I have no downgrade option and I can't find a link to an older version from the site https://azure.microsoft.com/en-us/features/storage-explorer/

**Comment by MRayermannMSFT** [comment] 2019-11-25 17:28
Hi everyone. To help us diagnose this issue, we need some logs...to get those logs please do the following....

1. In file explorer navigate to `C:\Users\<your username>\AppData\Local\Temp\servicehub`
2. Delete the logs folder
3. Open PowerShell
4. `cd 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\'` (if you installed elsewhere, then you'll need to modify the path to account for that)
5. `$env:SERVICEHUBTRACELEVEL="all"`
6. `.\StorageExplorer.exe`
7. After you get the error, go back to `C:\Users\<your username>\AppData\Local\Temp\servicehub`, where you should see the logs folder again
8. Zip that folder up and attach it to this issue

Thanks!

**Comment by Monkeyfish7000** [comment] 2019-11-25 18:24
Attempted to get you some logs, but 1.11.1 is now working for me. No logs to provide, but sharing my experience:
I had 1.10 before, and when I ran it asked me to update, which I did. It updated to 1.11.1 which then caused the issue from this thread.
I fully uninstalled the application, then installed [1.11.0](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.11.0) so that I could go about my current task.
In response to the request for logs, I then [downloaded latest](https://azure.microsoft.com/en-us/features/storage-explorer/) which is currently 1.11.1, ran, and now it's working fine. Closed and re-open to check, but still fine.
No OS restarts during any steps above.

**Comment by MRayermannMSFT** [comment] 2019-11-25 18:39
Hmmm. That's very odd. We did notice an issue that doing a non-clean install (which we normally do) would result in the error you saw. But for that reason, we made the 1.11.1 update a clean install. I'll go ahead and do exactly as you did though. Maybe it will revealed something we missed...

**Comment by MRayermannMSFT** [comment] 2019-11-25 18:51
Well, doing that same upgrade path didn't cause me any issues. 

I'll say that for anyone else facing this problem please:

1. get the log files (if you're willing)
2. you can try uinstalling and then reinstalling from https://storageexplorer.com , as doing that fresh unblocked Monkeyfish

**Comment by tsulli** [comment] 2019-11-25 18:52
I just upgraded and am getting the same error message despite having .NET Framework 4.7 and 4.71 installed. Attaching log files.
[StorageServiceClient-24012-HqvHe5-1.zip](https://github.com/microsoft/AzureStorageExplorer/files/3888169/StorageServiceClient-24012-HqvHe5-1.zip)

**Comment by MRayermannMSFT** [comment] 2019-11-25 18:58
@tsulli , can you try uninstalling and then reinstalling from https://storageexplorer.com ? I think that will fix the issue based on the error message. Also, any idea what version of Storage Explorer you were on before you upgraded?

**Comment by tsulli** [comment] 2019-11-25 19:10
Uninstalling and reinstalling did solve the issue for me. I think I was using 1.7.0 but I'm not 100% sure. Thanks for looking into this!

**Comment by MRayermannMSFT** [comment] 2019-11-25 19:49
No problem. Having the upgrade process be solid is very important to us. I'll try doing an upgrade from 1.7.0 and see if I can reproduce.

For anyone else reproducing this problem, before you do the re-install, can you let us know what the contents of the folder `C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\ServiceHub` are? It should be this:
![image](https://user-images.githubusercontent.com/21112697/69572729-a2805400-0f79-11ea-842e-aad3346009aa.png)

**Comment by FDFessler** [comment] 2019-11-25 21:02
I had this problem also but I re-installed before I got to the request above (sorry).  However, when I look in "C:\Program Files (x86)\Microsoft Azure Storage Explorer\" now, there are NO files.  I suspect that this is because I installed it to C:\Apps (and possibly to the same location the previous time).  Maybe that additional piece of information (installing to a location other than the default) is helpful.

**Comment by MRayermannMSFT** [comment] 2019-11-25 21:47
No worries that you didn't see the request. My first priority is making sure none of you are blocked. :)

**Comment by Zossin** [comment] 2019-11-26 05:14
@MRayermannMSFT Below are my logs:

[AzureStorageExplorerLogs.zip](https://github.com/microsoft/AzureStorageExplorer/files/3890178/AzureStorageExplorerLogs.zip)

I'll try to reinstall it to see if it can be worked around.

**Comment by Zossin** [comment] 2019-11-26 05:19
A clean re-installation has addressed the issue, I'm unblocked anyway.

**Comment by MRayermannMSFT** [comment] 2019-11-26 20:59
@Zossin , yep. Looks the same as tsulli's logs. Glad you became unblocked. @FDFessler , how did you accomplish installing in C:\apps? I just noticed our installer doesn't let you customize install location, so are you merely copying the files manually?

**Comment by FDFessler** [comment] 2019-11-27 01:21
I was prompted to where I wanted to install it.  See screenshot below:
[image: image.png]

**Comment by MRayermannMSFT** [comment] 2019-11-27 17:54
Turns our a reg key is written when you install that saves the install location. Once I uninstalled and then restarted my machine, I was able to choose a different location (C:\apps). Though even doing that, I still can't repro the clean install failing.

**Comment by FDFessler** [comment] 2019-11-27 21:54
I did upgrade to Win 10 1909 in between so don't know if that made a
difference.  Also, I think I upgraded WASE from 1.3.1 instead of 1.8.1
which I mentioned in my post but TBH I don't actually remember (sorry)!

Also, I don't know if it has anything to do with it saying it's upgrading
to 1.10.1 but when it's all done it's 1.11.1  -- just something I noticed
(and I think other did also).  If I come across it again I will try to
capture the information you requested.  Have a HAPPY THANKSGIVING! 🦃🍰
---  Freeman

**Comment by MRayermannMSFT** [comment] 2019-12-02 17:29
@FDFessler your comment just made me understand what the issue is!!! Thank you!

**Comment by MRayermannMSFT** [comment] 2019-12-02 17:34
Ok, the issue was on our end. No one should encounter this problem now. I'll leave this open for a bit though just incase anyone does though...

**Comment by FDFessler** [comment] 2019-12-03 02:45
OK!  Glad I could help! :-)

**Comment by LucGosso** [comment] 2019-12-03 07:19
Confirming installing 1.11.1 worked for me now. 
Regards

**Comment by MRayermannMSFT** [comment] 2019-12-03 23:13
Given no new reports since yesterday, I'm going to go ahead and close this. Thanks everyone.

**Closed by MRayermannMSFT** 2019-12-03 23:13 UTC
Labels: :beetle: bug

**Comment by Cloudmersive** [comment] 2019-12-06 11:53
This is NOT fixed!

**Comment by Cloudmersive** [comment] 2019-12-06 11:54
Storage Explorer, on the latest version, is just utterly broken.  This is a DOA release and there is no fix.  

Environment; Windows server 2016

**Comment by Cloudmersive** [comment] 2019-12-06 11:57
Downgraded to 1.10.0 to fix the issue. 1.11.1 is DOA

**Comment by FDFessler** [comment] 2019-12-17 15:57
Hey, BAD NEWS ... it IS broken again.  The interesting thing is this is the
one that was FIXED after the uninstall and reinstall!!
Do you want me to go through the trouble-shooting steps you outlined before?

---  Freeman

**Comment by MRayermannMSFT** [comment] 2019-12-17 21:52
Yes, if you could go through the steps again that'd be fantastic. I'm assuming it is exactly the same error message yes?

**Comment by FDFessler** [comment] 2019-12-22 23:56
Yes, it is.  I'm not in the office until 2020 but I may remote in to get
that information for you.  In the meantime ... have a very *MERRY CHRISTMAS
*and *HAPPY NEW YEAR*!

**Comment by Cage-e** [comment] 2020-01-13 12:46
I got this error after updating to version 1.11.2
Shutting down the storage emulator, quitting the emulator and explorer and relaunching them solved the problem for me. Hope it can help some of you.

**Comment by DarikaShasai** [comment] 2020-01-27 18:24
I'm unable to use the version 1.12 i had to downgrade to version 1.10, i try everything above and nothing work. :( Please check this issue, i need to use the lastes version.

**Comment by jinglouMSFT** [comment] 2020-01-27 20:10
@DarikaShasai what error did you get while using 1.12.0?  Also, please check the build number of 1.12.0 you have.  Did you upgrade from 1.10 to 1.12 or 1.11 to 1.12 or you installed 1.12 from scratch (meaning you went to http://storageexplorer and installed 1.12 from there)?
