### ISSUE TITLE
 Azure Storage Explorer can not correctly display content of message present in a queue in View Message popup window

### ISSUE THREAD

**Issue by klachoo** [microsoft/AzureStorageExplorer#4912] opened 2021-09-10 11:21 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

i86

### Storage Explorer Build Number

20210720.10

### Platform

Windows

### OS Version

Windows 10 x64

### Bug Description

It appears that Storage Explorer can not correctly display content of message present in a queue in View Message popup window. However the content of the exact same message is correctly displayed in "Message Text" column in the main message list. See the sample attached images:

![ViewMessagePopup](https://user-images.githubusercontent.com/32616053/132845524-07e97108-6202-4833-bff4-325f3c2f4695.png)

![ViewMessagePopup_Utf8](https://user-images.githubusercontent.com/32616053/133384729-f2f21bf1-430c-4a65-b359-d4d8a20b938e.png)

Switching the encoding dropdown list between "UTF-8" and "Base64" does not help either, no matter which one is selected the message text is not displayed correctly.

### Steps to Reproduce

1. Launch Storage Explorer
2. Select given Azure Storage Queue
3. Double click on specific message

### Actual Experience

Content of message present in a queue in View Message popup window is not displayed correctly while the content of the exact same message is displayed fine in "Message Text" column in the main message list.

### Expected Experience

Content of message present in a queue in View Message popup window should be displayed correctly and be exactly the same as the content displayed fine in "Message Text" column in the main message list.

**Comment by MRayermannMSFT** [comment] 2021-09-14 20:45
@klachoo do you have any idea what the box characters could be? They are likely part of your message, and they probably aren't showing up in the table because we do some security related pre-processing on your text before inserting it into our HTML.

**Comment by klachoo** [comment] 2021-09-15 07:38
@MRayermannMSFT 
Mi Matthew and thank you for your prompt response.
Unfortunately not, no idea what these "box characters" could be.
The message content should be pure JSON hence I am not expecting any additional characters.
I do still have this specific message present in my queue so I can perhaps paste its content here, if this would be of any help?
Furthermore I can say that this issue is also present in the Azure Portal web interface for storage queues.
![ViewMessagePopup_Web](https://user-images.githubusercontent.com/32616053/133391016-6d50c2c3-5b70-4d6a-bcc7-666525ad62aa.png)

**Comment by MRayermannMSFT** [comment] 2021-09-16 17:43
@klachoo I think given that the portal is also showing the boxes, the root cause of this issue lies in whatever thing/code is inserting these messages to the queue. 

Did you insert the messages with Storage Explorer, some other tool, or some code? 

Were the messages generated by some code or a human?

If by a human, were the messages typed out or copy and pasted from somewhere?

**Comment by klachoo** [comment] 2021-09-20 08:09
@MRayermannMSFT 
I assume these messages are generated by code and also put into the queue by code as I haven't personally done anything manually here.
I will have a closer look at it, at some point.
Thanks for your feedback.

**Comment by MRayermannMSFT** [comment] 2021-10-11 17:29
@klachoo do you have any update on your looking?

**Comment by klachoo** [comment] 2021-10-12 05:21
@MRayermannMSFT No, not as yet.

**Comment by MRayermannMSFT** [comment] 2021-10-20 21:49
@klachoo PowerShell must be able to properly display whatever those characters are. Have you looked into the code which is generating the messages? Would you be able to share the encoded message here with us? (just copy and paste it) And then we can try base64 decoding it ourselves to help investigate the root cause.

**Comment by MRayermannMSFT** [comment] 2021-11-13 00:43
Ok then. I'm going to go ahead and close this as won't fix then. If in the future you feel you can't live with the boxes and there is not a way for you to change them, please open a new issue and we'll find time to dig into this.

**Closed** 2021-11-15 21:07 UTC
Labels: :heavy_check_mark: won't fix, :gear: queues, :grey_question: investigate

**Comment by klachoo** [comment] 2022-08-19 07:43
@MRayermannMSFT I know this has been closed however I have investigated it recently and will post my findings for the sake of completeness.
I noticed that these null characters (rendered as 'boxes' in Azure Storage Explorer) appear only for the messages that are put in a DeadLetterQueue. Inspecting the code for construction of a dead letter queue message revealed that these null characters appear as a result of encoding a string containing serialized json to unicode bytes array as follows:

```
        /// <summary>
        /// Move the message to DLQ. Used after a number of failing attempts
        /// </summary>
        public override void DeadLetter(string errorMessage = null)
        {

            var deadletterBody = new AsqDeadLetterBody
            {
                ErrorMessage = errorMessage ?? "Unknown error",
                OriginalMessageId = _message.MessageId,
                OriginalMessageText = _messageText
            };

            var jsonBody = JsonConvert.SerializeObject(deadletterBody, jsonSerializerSettings);

            var bodyBytes = System.Text.Encoding.Unicode.GetBytes(jsonBody);
            var bodyBase64 = Convert.ToBase64String(bodyBytes);

            try
            {
                var receipt = _deadLetterQueueClient.SendMessage(bodyBase64, timeToLive: TimeSpan.FromDays(365));
                _queueClient.DeleteMessage(_message.MessageId, _popReceipt);
            }
            catch (Exception ex)
            {
                throw new ApplicationException($"Error was: '{errorMessage ?? "Unknown error"}' Body was: '{jsonBody}'", ex);
            }
        }
```
Changing the above to use UTF-8 encoding instead of Unicode seems to help as the null characters no longer appear in the resulting byte array.
