### ISSUE TITLE
Storage Explorer DST Handling

### ISSUE THREAD

**Issue by DAVIPUNT** [microsoft/AzureStorageExplorer#7466] opened 2023-10-30 09:56 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.2 (94)

### Architecture

x64

### Storage Explorer Build Number

20231003.6

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Files created after a DST change (CET going from UTC+2 to UTC+1) show a correct "Last Modified" timestamp while the files modified before the DST change have the times shifted by 1 hour.

### Steps to Reproduce

1. Launch Storage Explorer
2. Go in a folder that contains files created before and after the DST change
3. See that the timestamps previous to the DST change are displayed wrong.

### Actual Experience

When using Storage Explorer, the dates are inconsistent while when using the web explorer the data is correct.
Here's the screenshots for the same file called "EE_2023_10_28_32GG_32.csv". It was last modified on 10/28/2023, 4:41:27 PM (UTC+2) before the DST change that changed the timezone from UTC+2 to UTC+1 (we're CET).

On the Storage Explorer:
![storageexplorer_dst_bug-1](https://github.com/microsoft/AzureStorageExplorer/assets/22661332/9378ceb5-bda5-42c1-8cf3-efae2d076d8a)

While on the web explorer:
 
![storageexplorer_dst_bug-2](https://github.com/microsoft/AzureStorageExplorer/assets/22661332/a0a41044-6d95-45eb-85ed-dd007ab9346d)

### Expected Experience

We expect a consistent behavior between the Storage Explorer and the Web Explorer.
Moreover, the Storage Explorer shows wrong timestamps.

**Comment by MRayermannMSFT** [comment] 2023-10-30 19:26
Hi @DAVIPUNT

Thanks for opening this issue. Let me lay out what is going on and then you can give your thoughts in response.

So for the datetime you are looking at, the server returns the last modified date to Storage Explorer as a UTC time. Storage Explorer then converts that time to your local timezone. As you mention, daylight savings is represented as literally a different timezone. So in a way, we can imagine "you after DST" vs "you before DST"  like you took a plane from a place in one timezone to another which is in a timezone 1 hour behind.

So to us, if one purely thinks of daylight savings as a timezone shift, we think it makes sense to convert the UTC time to your current timezone and show it thusly. If we didn't, then it would be like if I uploaded a file at 9AM Seattle time, and then my cowoker in NYC immediately went and looked at the last modified time and saw 9AM insead of 12PM. What do you think about this thinking?

I will say that your screenshot from the Azure Portal is very interesting. I am curious to what they are doing. I can confirm on my end that Azure Portal is showing the last modified date converted to my local timezone. However as you show, it looks like it is going maybe even further and using the localtime zone that was hypothetically active on that date. I will try to reach out to the people who work on that to find out what they are doing.

**Comment by DAVIPUNT** [comment] 2023-10-31 07:49
Hi @MRayermannMSFT ,

Thanks for the explanation. It's very clear to me what DST is and how it works.
It seems that the issue is the DST is not an actual timezone. So, if I'm in CET, even if the times are (correctly) remotely stored as UTC  I would expect to see the times in CET (UTC+1 from the 2nd hour of the last Sunday of October to the 2nd hour of the last Sunday of March and UTC+2 for the rest).

To me, the Azure Portal behavior is the correct one, while the Storage Explorer is the "not so correct" one.

What do you think about my reasoning?

**Comment by MRayermannMSFT** [comment] 2023-10-31 16:14
Yes, I understand your POV as well. I actually talked about this issue with lots of people yesterday, and it turned out to be roughly 50/50 on opinions what should be displayed, with almost everyone agreeing that they can understand the argument for the other side.

I'm still waiting to hear back from the portal team, and I'm also spending some time double checking our implementation to refamiliarize myself with what code we're using to do the UTC conversion.

We'll keep this issue up to date as we learn more and eventually reach a decision.

**Comment by MRayermannMSFT** [comment] 2023-10-31 16:44
@DAVIPUNT , one quick favor to ask. Would you mind trying to view that last modified time on this version of Storage Explorer, and let me know if you also see the "not so correct" time?

https://github.com/microsoft/AzureStorageExplorer/releases/download/v1.18.1/Windows_StorageExplorer.exe

**Comment by MRayermannMSFT** [comment] 2023-11-01 04:44
Hi again @DAVIPUNT , after looking at our code some more and getting a report from another user we've decided to fix this. Nevermind on trying that old version. Instead, I'd like you to try this new version. It is a release candidate of our next version: Hi @P47K0 , nevermind on trying that old version. We've decided to fix this and we believe we have a fix. Can you double check for us that in this new version of Storage Explorer, you see timestamps as you expect? Thanks!

https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.32.0-dst-fix/StorageExplorer-windows-x64.exe?sv=2023-01-03&se=2023-10-30T04%3A27%3A00Z&sr=b&sp=r&sig=N%2BihBFqpySwnu0IF%2BGENmn7awTGo3kinYWpiNb%2F1yd0%3D

**Comment by MRayermannMSFT** [comment] 2023-11-01 22:19
Hi @DAVIPUNT , the other user confirmed that the fix worked for them, so I'm going to close this issue for now, but I'll try to check back in a day or two to see if you come back with a similar answer. Additionally, 1.32.0, which includes the fix, has now been released. Thanks!

**Closed by MRayermannMSFT** 2023-11-01 22:20 UTC
Labels: :beetle: bug, :heavy_check_mark: merged
