### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by andyraf** [microsoft/AzureStorageExplorer#4927] opened 2021-09-14 21:11 UTC
Many issues with download that make AzureStorageExplorer not ready for professional use:
- On network failures, unable to resume downloads.
- On app restarts, all downloads are forgotten, whether in-progress or completed.
- No option to pause/resume downloads.

**Comment by MRayermannMSFT** [comment] 2021-09-14 21:37
Duplicate of #1279

**Closed by MRayermannMSFT** 2021-09-14 21:37 UTC
