### ISSUE TITLE
It would be great if we can pause the current uploading activity

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3785] opened 2020-11-17 09:37 UTC
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201117.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: i32/x64
**Regression From**:  Not a regression

## Bug Description ##
I need to upload one small file immediately while there is an uploading activity.
I don't want to cancel the current uploading progress. If we can pause the current uploading. It would be great.
![image](https://user-images.githubusercontent.com/41351993/99371220-9794a100-28f9-11eb-83bf-2d330a66ae67.png)

## Expected Experience ##
Can pause the current uploading activity.

## Actual Experience ##
Cannot pause the current uploading activity.

**Comment by MRayermannMSFT** [comment] 2021-09-14 21:36
Duplicate of #1279

**Closed** 2021-09-14 21:39 UTC
Labels: :heavy_check_mark: duplicate, :bulb: feature request, 🧪 testing
