### ISSUE TITLE
The name of the 'Create Snapshot' icon in the toolbar against one resource group shows incompletely and end with '...' 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3933] opened 2020-12-24 09:27 UTC
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201222.4
**Branch:** main
**Language:** German/ Dutch/ Swedish/ Turkish/ Spanish
**Platform/OS:** ia32/x64
**Architecture:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina 
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Svencka' -> Restart Storage Explorer.
3. Expand 'Disks' -> Open one resource group.
4. Observe the toolbar -> Check whether the name of the 'Create Snapshot' icon shows completely.

## Expected Experience ##
The name of the 'Create Snapshot' icon shows completely.
![image](https://user-images.githubusercontent.com/41351993/103078524-08bc2800-460d-11eb-8318-2c8951df34e1.png)

## Actual Experience ##
 The name of the 'Create Snapshot' icon shows incompletely and end with '...'.
![image](https://user-images.githubusercontent.com/41351993/103078577-22f60600-460d-11eb-94d9-fce149ddbfc0.png)

## Additional Context ##
1. In Spanish, this issue doesn't reproduce on Mac.
2. The screenshot in ENU.
![image](https://user-images.githubusercontent.com/41351993/103077941-c3e3c180-460b-11eb-915b-d4d9fce05797.png)

**Comment by craxal** [comment] 2021-01-26 17:57
Duplicate of #3932, just with a different toolbar button.

**Closed by craxal** 2021-01-26 17:57 UTC
Labels: :gear: disks, :heavy_check_mark: duplicate, 🌐 localization, 🧪 testing
