### ISSUE TITLE
Travelling Timestamp column in Table explorer

### ISSUE THREAD

**Issue by gdignard** [microsoft/AzureStorageExplorer#1851] opened 2019-09-14 01:52 UTC
**Storage Explorer Version**: v1.10.0
**Build Number**: 20190912.8
**Platform/OS**: Windows
**Architecture**: x64?
**Regression From**: v1.9.x

## Bug Description ##
In the Table explorer, the Timestamp column now appears sorted alphabetically rather than fixed in the 3rd column.

If this is by design, then consider this instead to be a Feature Request to have a preference/setting to automatically pin it with the Partition and Row key on the left of the row as it was in previous versions.

**Comment by craxal** [comment] 2019-09-19 21:25
Just verified myself. That's definitely not by design, and not sure how that's happening yet.

You can easily reorder the columns by either dragging and dropping or selecting Column Options from the toolbar.

**Comment by craxal** [comment] 2020-08-03 23:18
Bug was closed by mistake.

@gdignard Does this issue not reproduce for you anymore? If not, we'll go ahead and close properly.

**Comment by gdignard** [comment] 2020-08-05 14:18
Craig -

I've been making use of it for the past few days and it certainly has every
appearance of working as intended.

Close away!

- Gilles

**Closed** 2020-08-05 16:35 UTC
Labels: :beetle: bug, :gear: tables, :heavy_check_mark: mitigated
