### ISSUE TITLE
Provide installable package/repository for Linux

### ISSUE THREAD

**Issue by mkozioro** [microsoft/AzureStorageExplorer#68] opened 2018-04-24 10:19 UTC
Manual update of Storage Explorer is boring and causes problems - for example the latest Storage Explorer required me to install .NET framework.
Please, create packages and repository with all required dependencies for at least LTS versions of Ubuntu

**Comment by craxal** [comment] 2018-04-24 16:09
Thanks for your feedback! This is also something we've been wanting to do, and we've been investigating how to better package Storage Explorer for Linux systems recently. Unfortunately, we're not sure when we can address this issue, but we'll keep you informed as things change.

**Comment by MRayermannMSFT** [comment] 2018-08-09 22:17
Duplicate of #339 . We'll be looking into use snapcraft in the future for linux.

**Comment by craxal** [comment] 2018-08-16 15:57
Actually, no. #339 is the duplicate. 😄

**Comment by mkozioro** [comment] 2018-11-04 16:09
Hi.
Do you have any news about either .deb package or snap package?

**Comment by craxal** [comment] 2019-06-21 17:46
We are currently working on creating a Storage Explorer snap for the [Snap Store](https://snapcraft.io/store)! This will make Storage Explorer installation and updates fast and easy on many different Linux distributions.

**Comment by mkozioro** [comment] 2019-06-22 23:57
Wow. Thank for that happy update :) I almost thought this issue is dead.

**Comment by craxal** [comment] 2019-06-27 22:42
Adding link to request for password manager service auto-connect here:

https://forum.snapcraft.io/t/request-password-manager-service-auto-connection-for-storage-explorer/11937

**Closed** 2019-07-15 18:20 UTC
Labels: :bulb: feature request, :computer: linux, :heavy_check_mark: merged
