### ISSUE TITLE
Allow toggle between directory structure view and "flat" view

### ISSUE THREAD

**Issue by codefoster** [microsoft/AzureStorageExplorer#2867] opened 2020-04-22 15:43 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes, I'd like to look recursively at a directory to see if any of the files at any level below are at a certain access tier. It's difficult to navigate through every directory to see every file.

**Describe the solution you'd like**
I'd like to be able to temporarily turn off the directory structure view and see all files by fully-qualified name (full path) on a single level so I can sort by Access Tier (or other column) and see all files that I need to modify.

**Describe alternatives you've considered**

**Additional context**

**Comment by MRayermannMSFT** [comment] 2020-05-11 18:12
Duplicate of #19

**Closed by MRayermannMSFT** 2020-05-11 18:12 UTC

**Comment by MRayermannMSFT** [comment] 2020-05-11 18:17
@codefoster I'm going to ask you a question on the linked issue. Please try to answer there!
