### ISSUE TITLE
Cannot open files without an extension

### ISSUE THREAD

**Issue by kloopdogg** [microsoft/AzureStorageExplorer#2007] opened 2019-10-07 18:14 UTC
The vast majority of our blobs have no file extension (e.g. myfile-20191007-vendor-response). We used to be able to open them without failure, but now we get an error stating "This file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default Apps Settings page." 

The previous behavior is preferred, where it would detect that there wasn't a file extension or type, and then ask which app to open the file with.

When using the download feature, there is a maybe-related issue where it appends a period (.) to the end of the blob's name, where it used to leave the blob name as is.

**Comment by MRayermannMSFT** [comment] 2019-11-18 19:18
Duplicate of #1531

**Closed by MRayermannMSFT** 2019-11-18 19:18 UTC
