### ISSUE TITLE
The selected item isn't focused after searching from here

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/AzureStorageExplorer#298] opened 2018-06-13 09:55 UTC
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: All
**Architecture**: ia32/x64
**Build Number**: 20180611.3
**Commit**: e00d7640
**Regression From**: Not a regression

**Steps to Reproduce**:
1. Launch Storage Explorer and expand the Storage Accounts.
2. Select an item like 'Cosmos DB Accounts' then click 'Search From Here'.

**Expected Experience**:
The item 'Cosmos DB Accounts' is focused after searching from here.
![expect](https://user-images.githubusercontent.com/37653604/41343421-167fb284-6eee-11e8-86ab-ee63c79f3ddf.PNG)

**Actual Experience**:
The applied subscription is focused after searching from here.
![actual](https://user-images.githubusercontent.com/37653604/41343307-bd397a2a-6eed-11e8-81cd-1f6e4a52eb04.png)

**Comment by MRayermannMSFT** [comment] 2018-06-13 16:09
Closing as duplicate of #33 . Same root cause.

**Closed by MRayermannMSFT** 2018-06-13 16:09 UTC
Labels: :white_check_mark: duplicate, testing
