### ISSUE TITLE
Support force delete readonly file option in AzCopy

### ISSUE THREAD

**Issue by RodneyBradey** [microsoft/AzureStorageExplorer#587] opened 2018-08-18 08:13 UTC
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: don't know
![image](https://user-images.githubusercontent.com/42235109/44297190-bc5fcf80-a310-11e8-8238-c1fb947d52a3.png)

when copying files into a file share, after a while all copying stops with "getaddrinfo ENOTFOUND", if you wait a while and click [Retry All] it continues for a short while and the cycle repeats.

I understand it could be related to network connectivity but the explorer should be more resilient and self heal from transient network throughput situations.

**Comment by gerardnico** [comment] 2018-10-10 10:58
Storage Explorer version 1.4.2
Platform Windows
Architecture: Ia32
BuildNumber: 20180917.1
Commit: f66de7ea


I got the same here trying to upload a big file via Storage Explorer. I have tried on multiple day, on multiple network but I have always the same behavior. The upload starts and end with a ''getaddrinfo ENOTFOUND'' errors.

File size (3.6Gb). It's a tar file that I can untar without problem.
Azcopy is also complaining about a invalid block. See below.

The Storage explorer message:
`
{
  "name": "Error",
  "message": "getaddrinfo ENOTFOUND storageName.blob.core.windows.net storageName.blob.core.windows.net:443",
  "stack": "Error: getaddrinfo ENOTFOUND storageName.blob.core.windows.net storageName.blob.core.windows.net:443\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "code": "ENOTFOUND",
  "errno": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "storageName.blob.core.windows.net",
  "host": "storageName.blob.core.windows.net",
  "port": "443",
  "innerError": {
    "code": "ECONNRESET",
    "errno": "ECONNRESET",
    "syscall": "read"
  }
}
`




From Azcopy (AzCopy 8.1.0-netcore)
`
[2018/10/10 12:52:03][ERROR] C:\Users\gerard\Desktop\Installation_linux-x64.tar: The transfer failed.
The specified blob or block content is invalid.
The specified blob or block content is invalid.
RequestId:e1cbb7f1-001e-0127-7186-60eaca000000
Time:2018-10-10T10:52:03.6680516Z
Finished 0 of total 1 file(s).
[2018/10/10 12:52:03] Transfer summary:
-----------------
Total files transferred: 1
Transfer successfully:   0
Transfer skipped:        0
Transfer failed:         1
Elapsed time:            00.00:03:05
`

**Comment by gerardnico** [comment] 2018-10-10 13:43
Update: I downloaded the file once again and I got with AzCopy a timeout.

The trick was to use only two threads (nc:2)

```dos
AzCopy ^
/Source:. ^
/Dest:https://sa.blob.core.windows.net/container ^
/DestKey:UCK0oeZoCOuyuFe3IH6PYibkN5BvTiox6P46UCPAOgrsA== ^
/Pattern:"installation_linux-x64_1.tar" ^
/nc:2
```

The bigger the file the more thread it seems.

**Comment by softsolutionsau** [comment] 2019-09-21 08:32
I'm having the same issue with Storage Explorer v1.10.1.
Trying to upload a 11Gb file, gets about 100mb in and fails.

**Comment by biconix** [comment] 2020-01-02 14:33
I have the same problem with version 1.11.2
is there a solution or workaround for this?

**Comment by MRayermannMSFT** [comment] 2020-03-09 18:27
We'll be using AzCopy v10 for file shares in 1.13 (our next major version). Please upgrade to 1.13 once it is available and let us know if this still repro's then.

**Comment by JasonYeMSFT** [comment] 2020-05-29 17:58
@biconix Are you still having this problem after upgrading to 1.13.0?

**Comment by biconix** [comment] 2020-06-07 15:24
It seems not to be working. I was unable to delete a read-only file


_____________________________________________________________________
Moshe Raab, Ph.D.
Microsoft Certified Professional
Microsoft Certified Technology Specialist – Microsoft Dynamics CRM
Biconix, Inc., mailto:raab@biconix.com,
(USA)  +1 (561) 208-3858
(Israel) +972( 2) 590-0801
Sent from my Surface Book 2

**Comment by JasonYeMSFT** [comment] 2020-06-08 16:36
@biconix could you please elaborate your issue:
1. What version of Storage Explorer are you using?
2. What OS are you on?
3. How do you reproduce the issue?

**Comment by biconix** [comment] 2020-06-08 18:22
See answers below



_____________________________________________________________________
Moshe Raab, Ph.D.
Microsoft Certified Professional
Microsoft Certified Technology Specialist – Microsoft Dynamics CRM
Biconix, Inc., mailto:raab@biconix.com,
(USA)  +1 (561) 208-3858
(Israel) +972( 2) 590-0801
Sent from my Surface Book 2

**Comment by JasonYeMSFT** [comment] 2020-06-08 19:03
@biconix I cannot see your pictures of the Storage Explorer version and OS. BTW, the original error message comes from a deprecated code path for operating files in file share. Could you please share the error + the AzCopy log for the failed action with us?

**Comment by biconix** [comment] 2020-06-08 19:13
AzStorageExplore v1.13.1
Windows 10 Pro, v2004 OSBuild 19041.264
The error says: Deletion of 'Raab Properties LLC.qbw' from 'biconix/Financial/Raab Properties/' failed: 0 completed, (used SAS)
_____________________________________________________________________
Moshe Raab, Ph.D.
Microsoft Certified Professional
Microsoft Certified Technology Specialist – Microsoft Dynamics CRM
Biconix, Inc., mailto:raab@biconix.com,
(USA)  +1 (561) 208-3858
(Israel) +972( 2) 590-0801
Sent from my Surface Book 2

**Comment by JasonYeMSFT** [comment] 2020-06-08 19:39
@biconix, thanks for the info. Unfortunately we haven't seen any similar issue so far. To locate the cause of the issue, the following information would be very helpful.

* Could you explain what do you mean by "read-only" file? Is there any special property/metadata on the files/directories you are trying to delete?
* Re-perform a failed delete. Go to C:\Users\your_username\.azcopy directory and get the latest (by Date modified) .log file for us. That log file will be the one for the failed delete action.
* Share the azcopy command with us. You can get the command from the "Copy AzCopy Command to Clipboard" button in the activity. Please remember to remove your SAS token in the "sig=" parameter so that you are not disclosing your credentials to anybody.

**Comment by JasonYeMSFT** [comment] 2020-08-14 19:10
Closed due to lack of response. Please open a new issue if you are still having the issue. Thanks.

**Comment by biconix** [comment] 2020-08-17 18:57
I certainly responded to this, but I never received a response from you.
I am attaching my response to your previous request….



_____________________________________________________________________
Moshe Raab, Ph.D.
Microsoft Certified Professional
Microsoft Certified Technology Specialist – Microsoft Dynamics CRM
Biconix, Inc., mailto:raab@biconix.com,
(USA)  +1 (561) 208-3858
(Israel) +972( 2) 590-0801

**Comment by JasonYeMSFT** [comment] 2020-08-17 19:08
@biconix, could you please make sure your response is visible from the GitHub issue page? I still cannot see your response in the issue thread.

**Comment by biconix** [comment] 2020-08-20 18:21
I am not sure what you are asking for? I am hesitant to put my files here

**Comment by JasonYeMSFT** [comment] 2020-08-20 18:29
@biconix you don't need to put any of your file here. Could you please try typing the answers for these questions here? I couldn't see your response even though you said so.

* Could you explain what do you mean by "read-only" file? Is there any special property/metadata on the files/directories you are trying to delete?
* Re-perform a failed delete. Go to C:\Users\your_username\.azcopy directory and get the latest (by Date modified) .log file for us. That log file will be the one for the failed delete action.
* Share the azcopy command with us. You can get the command from the "Copy AzCopy Command to Clipboard" button in the activity. Please remember to remove your SAS token in the "sig=" parameter so that you are not disclosing your credentials to anybody. Feel free to redact the account name/blob name as well if you think they contain sensitive information.

**Comment by biconix** [comment] 2020-08-20 18:39
1) By Read only  I mean that the Read Only attribute in the file properties is set to True. I am trying to update a file and so it needs to delete the old and write the new file. since it is read only it cannot delete the old one and so the write fails.
2) This is the line that indicated to me that the error is due to the fact that the file is READ-ONLY: 
 2020/06/09 04:24:01 ERR: [P#0-T#0] https://company.file.core.windows.net/company/Financial/Personal%20Properties/Personal%20Properties%20LLC.qbw?se=2020-07-09t04%3A23%3A53z&sig=-REDACTED-&sp=rdl&sr=s&sv=2018-03-28: 0: DELETE ERROR -target is readonly. To force the action to proceed, add --force-if-read-only to the command line. X-Ms-Request-Id:
3)$env:AZCOPY_CRED_TYPE = "Anonymous";
./azcopy.exe remove "https://company.file.core.windows.net/company/Financial/Personal%20Properties/Personal%20Properties%20LLC.qbw?se=2020-07-09T04%3A23%3A53Z&sp=rdl&sv=2018-03-28&sr=s&sig=REDACTED-" --recursive
$env:AZCOPY_CRED_TYPE = "";

**Comment by JasonYeMSFT** [comment] 2020-08-20 18:42
@biconix Thanks for answering again. I think we now have good information to start investigate this issue.

**Comment by biconix** [comment] 2020-08-20 18:43
great! thanks so much!

**Closed** 2020-11-12 18:58 UTC
Labels: :gear: azcopy, :heavy_check_mark: merged
