### ISSUE TITLE
Resource type of SAS generated with access policy should be "blob" instead of "container"

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#2961] opened 2020-05-12 00:07 UTC
**Storage Explorer Version**: 1.13.0
**Build Number**: 20200430.5
**Platform/OS**: Windows 10/macOS/Linux
**Architecture**: i86/x64
**Regression From**:  1.12.0

## Bug Description ##
The "sr" field of a SAS generated for a blob using a stored access policy is incorrectly set to "c" (container) instead of "b" (blob).

## Steps to Reproduce ##
1. Create an access policy for a blob container in `Manage Access Policies...`.
2. Open the blob container, select a blob and click `Generate Share Access Signature...` in the context menu.
3. Select the access policy in the drop down menu and click next.
4. View the generated SAS

## Expected Experience ##
The "sr" field should be "b".

## Actual Experience ##
The "sr" field is "c".

**Comment by v-xianya** [comment] 2020-05-12 02:28
@JasonYeMSFT Any feature changes for this part?🙃
[This is caused by the underlying behavior of the SDK. An access policy applies to container level access control so that the SDK decides to set the resource type to "c" for a generated SAS with access policy.](url)
Refer to this bug：[2719](https://github.com/microsoft/AzureStorageExplorer/issues/2719)

**Comment by JasonYeMSFT** [comment] 2020-05-12 16:51
We didn't realize at the moment that it was a bug in the SDK.

**Comment by MRayermannMSFT** [comment] 2020-05-18 18:28
Duplicate of #2981

**Closed by MRayermannMSFT** 2020-05-18 18:28 UTC
Labels: :beetle: regression, :gear: blobs
