### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by SAGARNATH-S** [microsoft/AzureStorageExplorer#6127] opened 2022-10-03 11:09 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

x64

### Platform

Windows

### OS Version

11

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "The specifed resource name contains invalid characters.\nRequestId:d7d137af-0db0-43d8-8d3a-07-07"
},

### Steps to Reproduce

Try to Open Blob Container

### Actual Experience

![image](https://user-images.githubusercontent.com/69468896/193563081-f174b41a-8984-4bfa-bbeb-482405681ebb.png)
Blob container is like empty folder

**Comment by MRayermannMSFT** [comment] 2022-10-03 17:42
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/6030 . A fix for this is shipping in 1.26. In the meantime you can either move to Azurite, which is recommended since the emulator you are using is deprecated, or you can downgrade to 1.24.

**Closed by MRayermannMSFT** 2022-10-03 17:42 UTC
