### ISSUE TITLE
The QA attached file share/queue/table doesn't auto display as broken after renaming its attachment

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6244] opened 2022-11-02 07:57 UTC
**Storage Explorer Version:** 1.27.0-dev
**Build Number:** 20221102.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Attach the table.
3. Pin the attached table to Quick Access.
4. Right click the attached table -> Click 'Rename connection...'.
5. Type a valid name -> Click 'Rename'.
6. Check whether the QA table auto displays as broken.

## Expected Experience ##
The QA table auto displays as broken.

## Actual Context ##
The QA table displays well.

## Additional Context ##
The QA file share/table/queue shows as broken after manually refreshing.

**Comment by JasonYeMSFT** [comment] 2022-11-07 19:15
This is a duplicate of #6186.

**Closed by JasonYeMSFT** 2022-11-07 19:15 UTC
Labels: 🧪 testing, :gear: quick access
