### ISSUE TITLE
The base blob and its snapshots are deleted successfully at the same time

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#672] opened 2018-09-18 08:51 UTC
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180917.1
**Commit**: f66de7ea
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open one blob container then upload a blob to it.
2. Create snapshots for the uploaded blob.
3. Go to the blob snapshots view -> Select the base blob and its snapshots at the same time -> Delete

#### Expected Experience: ####
Fail to delete the base blob with an error.

#### Actual Experience: ####
Able to deleted the base blob and its snapshots at the same time.

**Comment by v-limu** [comment] 2019-11-26 02:55
This issue has been fixed on build [20191126.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3273921&view=logs). So we close it.

**Comment by v-limu** [comment] 2019-11-28 02:33
This issue reproduces on build [20191128.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3280503). So we reopen it.

**Comment by MRayermannMSFT** [comment] 2020-02-03 19:35
1. We think that if everything is selected, then everything is deleted. So the behavior you originally saw is by design.
2. This behavior should be consistent and reproducible.

Let's revisit this once AzCopy supports deleting snapshots.

**Comment by v-xianya** [comment] 2020-04-20 09:58
Hi @MRayermannMSFT 
This issue is fixed on build 20200418.1. So we close it.

**Closed by v-xianya** 2020-04-20 09:58 UTC
Labels: :gear: blobs, 🧪 testing
