### ISSUE TITLE
Add 'Copy URL' on blob context menu

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#767] opened 2018-10-16 09:37 UTC
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181015.10
**Commit**: 0a03e736
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open one blob container which contains one blob at least.
2. Right click one blob then check the context menu.

#### Expected Experience: ####
'Copy URL' shows on the blob context menu.

#### Actual Experience: ####
'Copy URL' doesn't show on the blob context menu.
![menu](https://user-images.githubusercontent.com/34729022/47007171-30c8ba80-d16a-11e8-87a7-b05f1b3237a1.png)

**Comment by MRayermannMSFT** [comment] 2020-01-27 19:24
Also remove from toolbar, and do it for everything, not just blobs.

**Comment by MRayermannMSFT** [comment] 2020-02-02 20:03
Fix merged into master. File share, blob, and gen2 blob editor should now all have copy url on the context menu.

**Closed by MRayermannMSFT** 2020-02-02 20:03 UTC
Labels: 🧪 testing

**Comment by v-xianya** [comment] 2020-02-03 07:41
@MRayermannMSFT 
Verified this issue on build 20200201.2. 'Copy URL' is added on the context menu for files and blobs. 
We noticed that 'Copy URL' is removed from the toolbar, is this by design?
![image](https://user-images.githubusercontent.com/41351993/73634111-62d19900-469b-11ea-9606-9d582f3f1a5b.png)
