### ISSUE TITLE
I'm unable to upload files from the /tmp directory

### ISSUE THREAD

**Issue by FilipStachowiak-TomTom** [microsoft/AzureStorageExplorer#5633] opened 2022-04-15 11:59 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.1

### Architecture

x64

### Storage Explorer Build Number

20220406.1

### Platform

Linux (snap)

### OS Version

Ubuntu 18.04

### Bug Description

I want to upload a file located in the /tmp directory. When I browse to this dir, I don't see any files, so I cannot upload them.

### Steps to Reproduce

1. Launch the tool
2. Browse to the blob location
3. Press the Upload button
4. Press ... button, the file browser opens
5. Click on the adress bar of the file browser, type "/tmp". 
6. No files are shown. Also if you browse from the top dir and go to /tmp, there are no files shown.

### Actual Experience

When I browse to this dir, I don't see any files, so I cannot upload them. I need to copy files to another dir and upload them from there. It's a waste of time.

### Expected Experience

Files from /tmp must be shown.

**Comment by JasonYeMSFT** [comment] 2022-04-18 22:46
For security reasons, snap apps will create their per-app /tmp directory instead of letting the app access the system wide /tmp directory. This is a duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/5184. We haven't been able to find a proper solution it. We are keeping that issue open until we find a proper solution for it.

If this is a blocking issue to you, you can use the .tar.gz release from [releases](https://github.com/microsoft/AzureStorageExplorer/releases) which doesn't have this limitation.

**Closed by JasonYeMSFT** 2022-04-18 22:46 UTC
Labels: :computer: linux, :package: snaps

**Comment by FilipStachowiak-TomTom** [comment] 2022-04-20 07:02
Ok, thank you. I'll use the tar.gz version.
