### ISSUE TITLE
When re-opening storage explorer, restored tab for blob container shows an empty panel. No refresh or other controls available

### ISSUE THREAD

**Issue by kweebtronic** [microsoft/AzureStorageExplorer#8331] opened 2024-11-27 01:53 UTC
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.2

### Regression From

1.34.x

### Architecture

x64

### Storage Explorer Build Number

20241029.2

### Platform

Windows

### OS Version

Windows 11 Pro, Build 26100

### Bug Description

I love the feature that I can retain opened tabs when re-starting Storage explorer.

The regression is only for blob containers, in tabs other than the first

Restored tabs, other than the first tab, show an EMPTY panel with no controls nor data, effectively rendering the saved tab useless.

### Steps to Reproduce

1. Launch Storage Explorer
2. In Settings, ensure that 'Preserve Explorer Session' is checked
3. Open a browsing session for a Table (tab 'tableName')
4. Open a browsing session for a Blob Container (tab 'containerName') ... can see virtual folders and blobs within that container, plus controls for navigation and browsing
5. Close Storage Explorer 
6. Reopen Storage Explorer
7. Tab 'tableName' shows default data view, and controls
8. Tab 'containerName' shows an empty frame, no content nor controls

### Actual Experience

Tab 2 BEFORE closing

![Image](https://github.com/user-attachments/assets/a2afb5c5-aabf-42cb-8548-e9ccc3fcdc65)

Tab 2 AFTER reopening

![Image](https://github.com/user-attachments/assets/f55ff191-94ee-40f2-9b42-00e36110c82b)

### Expected Experience

All restored tabs should be usable/browsable

**Comment by richardMSFT** [comment] 2024-11-27 19:21
This seems to be a duplicate of #8273 so I will be closing this issue. The fix has been merged and will be part of our 1.37.0 release.

**Closed by richardMSFT** 2024-11-27 19:21 UTC
