### ISSUE TITLE
The split tabs are inconsistent if apply 'Filter by prefix' in the original view all containers explorer

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8071] opened 2024-07-22 07:20 UTC
**Storage Explorer Version:** 1.35.0-dev (99)
**Build Number:** 20240720.1
**Branch:** main
**Platform/OS:** Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture:** arm64/x64/x64/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Right click the 'Blob Containers' node -> Click 'View All'.
3. Type a character in the 'Filter by prefix' field.
4. Split the tab -> Observe the split tab.
5. Check whether the split tabs are consistent.

## Expected Experience ##
The split tabs are consistent.

## Actual Experience ##
The split tabs are inconsistent.
![image](https://github.com/user-attachments/assets/3d082043-8441-445e-8293-b2f024ec721d)

**Comment by craxal** [comment] 2024-07-22 17:30
Closing as by design, same reason as #8068.

**Comment by v-kellyluo** [comment] 2024-07-23 01:21
Hi @craxal, For blob containers, the split tabs are consistent if apply 'Filter by prefix' in the original tab.
![image](https://github.com/user-attachments/assets/519cb00c-05d5-46ac-8c20-f97ddf760484)
And there is an open bug for file share about this issue: [4944](https://github.com/microsoft/AzureStorageExplorer/issues/4944). Maybe it should be consistent, could you help to take a look?

**Comment by craxal** [comment] 2024-07-23 17:27
@JasonYeMSFT Can you look into this? Not sure why we are preserving prefix search when a tab is split, but I assume this was a discussion point some time ago. Whatever we're doing, let's make sure we're consistent.

**Comment by JasonYeMSFT** [comment] 2024-08-08 22:24
Blob explorer writes the search prefix in the tab state data, which is why it is preserved in the split tab. I don't think it's critical for us to also preserve that for the view all containers explorer. I am going to close this issue as not planned. We can revisit this if there are customer issues for this.

**Closed by JasonYeMSFT** 2024-08-08 22:24 UTC
Labels: 🧪 testing, :gear: blobs, :white_check_mark: by design, :gear: adls gen2
