### ISSUE TITLE
Copy files between container and file share

### ISSUE THREAD

**Issue by ArmandoLacerda** [microsoft/AzureStorageExplorer#6158] opened 2022-10-12 18:05 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I've tried to copy a file from a blob container to a file share and the copy button is disabled. I tried the same operation using the Azure Portal and it works from there.

### Desired Solution

Mirror the same functionality in ASE

### Alternatives and Workarounds

None, really.

**Comment by JasonYeMSFT** [comment] 2022-10-17 17:13
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/4971. The linked issue is scheduled to be done in 1.28.0.

**Closed by JasonYeMSFT** 2022-10-17 17:13 UTC
Labels: :heavy_check_mark: duplicate, :bulb: feature request
