### ISSUE TITLE
Display the 'Last Modified' value for ADLS Gen2 folders in Editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2864] opened 2020-04-22 09:33 UTC
**Storage Explorer Version:** 1.13.0
**Build:** [20200422.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3663543&view=results)
**Branch:** rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one folder .
3. Check whether there shows the Last Modified value for the folder.

**Expect Experience:**
Display a last modified value.

**Actual Experience:**
No value displays.
![image](https://user-images.githubusercontent.com/41351993/79961134-daec7580-84b8-11ea-95d6-fce2e578ac31.png)

**Comment by MRayermannMSFT** [comment] 2020-05-11 18:22
@craxal please collect any related bugs into 1 issue and then follow-up with the SDK team about why this isn't coming through in the new SDK.

**Comment by craxal** [comment] 2020-05-13 22:35
Duplicate of #2242.

**Closed by craxal** 2020-05-13 22:35 UTC
Labels: :gear: adls gen2, 🧪 testing
