### ISSUE TITLE
Cannot edit table entities if they contain binary properties

### ISSUE THREAD

**Issue by KarpMac** [microsoft/AzureStorageExplorer#2030] opened 2019-10-10 07:28 UTC
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  weas fixed in 0.8.4 
## Bug Description ##
Cannot edit table entities if they contain binary properties

## Steps to Reproduce ##
1. edit entities in a table that contains a binary property
2. click on update and nothing happens

## Expected Experience ##
The edit window should be closed and the entity should be updated

## Actual Experience ##
Window is not closed and the entity is not updated

## Additional Context ##
This bug was solved in version 0.8.4 but has been reintroduced
https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-explorer-relnotes?toc=%2fazure%2fstorage%2fblobs%2ftoc.json#version-084

**Comment by MRayermannMSFT** [comment] 2019-11-18 19:14
Duplicate of #554

**Closed by MRayermannMSFT** 2019-11-18 19:14 UTC
Labels: :bulb: feature request, :gear: tables
