### ISSUE TITLE
The link 'how will Soft Delete affect overwrite?' is selected on the 'Conflict' dialog of blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4489] opened 2021-05-25 08:43 UTC
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210524.7
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.19.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one file -> Upload the file again.
3. Observe the 'Conflict' dialog.
4. Check whether the link 'how will Soft Delete affect overwrite?' is selected.

## Expected Experience ##
The link 'how will Soft Delete affect overwrite?' is not selected.
![image](https://user-images.githubusercontent.com/41351993/119465924-b9725300-bd76-11eb-9ef4-c591f3629922.png)

## Actual Experience ##
The  link 'how will Soft Delete affect overwrite?' is selected.
![image](https://user-images.githubusercontent.com/41351993/119465885-ad869100-bd76-11eb-85b9-cded5d9efa7a.png)

## Additional Context ##
1. This issue doesn't reproduce when dragging & dropping/copying & pasting one same blob.
2. This issue doesn't reproduce on MacOS Big Sur 11.3.
3. On Linux, this issue still reproduces when dragging & dropping/copying & pasting one same blob.

**Comment by JasonYeMSFT** [comment] 2021-06-04 16:32
I did some investigation on this issue. It seems to be related to some browser internal logic for giving focus to the first focusable element in the browser window on certain conditions. The cause may be a combination of timing and us hiding and reusing the dialog window. I experimented with either one of
- Quick drag/drop two files on Windows. (Still reproduces)
- Always destroy the old dialog window instead of reusing. (No reproduce)
- Don't hide the dialog but just reload its contents. (No reproduce)

Won't fix for now since this is of low impact.

**Closed** 2021-06-04 16:32 UTC
Labels: :beetle: regression, :gear: blobs, :heavy_check_mark: won't fix, 🧪 testing
