### ISSUE TITLE
"Continue where I left Off" - Restore my tabs with launching ASE

### ISSUE THREAD

**Issue by ndbills** [microsoft/AzureStorageExplorer#4257] opened 2021-03-24 19:44 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to close Storage Explorer to reboot my computer or anything else, because it disrupts my workflow in Azure Storage Explorer: I have to find and re-open all of my previous blob containers, tables, queues, etc. that I use throughout the day. Our team deals with MANY storage accounts on a daily basis and so navigating around and loading lists of storage accounts can be a pain (we typically are watching 180+ storage accounts at any given time).

**Describe the solution you'd like**
I would LOVE for Azure Storage Explorer to "remember" the tabs I had open (similar to a web browser) and "start where I left off", that is, when I launch Azure Storage Explorer, restore the tabs I had open when I exited the application.

**Describe alternatives you've considered**
I have tried making a note of each tab I had open during a session, from what storage account, etc. But that is a very tedious and manual process.

**Additional context**
Many modern applications provide this feature: VSCode, VS, Edge, Kusto Explorer, etc. I would love to see Azure Storage Explorer join this list. If this capability already exists, please point me to it so I can share it with my team as well, thank you! :)

**Comment by MRayermannMSFT** [comment] 2021-03-29 17:49
Duplicate of #1504

**Closed by MRayermannMSFT** 2021-03-29 17:49 UTC
Labels: :bulb: feature request
