### ISSUE TITLE
Hundreds of modal popups for missing .NET Framework

### ISSUE THREAD

**Issue by justinormont** [microsoft/AzureStorageExplorer#2753] opened 2020-03-25 20:15 UTC
**Storage Explorer Version**: Unknown, but downloaded yesterday
**Build Number**: Unknown, can not access
**Platform/OS**: Windows Server 2016
**Architecture**: x64
**Regression From**:  Unknown

## Bug Description ##

On a fresh install of Windows Server 2016, there is no .NET Framework installed (or perhaps just too low of version). When running Azure Storage Explorer, 100s of modal popup windows are displayed from ServiceHub.

![image](https://user-images.githubusercontent.com/4080826/77579491-a5dc0b80-6e97-11ea-8b34-1a96a5ac43ca.png)

Text is:
```
This application requires one of the following versions of the .NET Framework:
.NETFramework,Version=v4.7.2

Do you want to install this .NET Framework version now?
```
![image](https://user-images.githubusercontent.com/4080826/77579987-77aafb80-6e98-11ea-9aa1-bbcae494f0f8.png)

In addition, Storage Explorer displays one more popup asking for a different version number.
![image](https://user-images.githubusercontent.com/4080826/77581027-39aed700-6e9a-11ea-8b30-1f1ccf7d457c.png)

**Recommend:**
Pre-checking the .NET version then not calling the ServiceHub dependency if the version is too low. Also align your .NET Framework version with ServiceHub (or require newer).

## Steps to Reproduce ##
Perhaps uninstalling .NET Framework or using a version below of the wanted v4.7.2.

## Expected Experience ##
Exactly one error should be displayed.

## Actual Experience ##
100s of errors are displayed.

**Comment by JasonYeMSFT** [comment] 2020-03-26 16:49
Duplicate of #2708. We are updating our error message (the last one in your post) in our next release to reflect the correct version of .Net Framework required. As for the other error messages, they come from the OS and we don't have control over it.

**Closed** 2020-03-30 17:58 UTC
