### ISSUE TITLE
The notification message is not localized for one empty table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2207] opened 2019-11-05 08:32 UTC
**Storage Explorer Version:** 1.11.0
**Build:** [20191105.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3213388)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Create a new table -> Check the notification message in the editor.

**Expect Experience:**
The notification message is localized.

**Actual Experience:**
The notification message is not localized.
![image](https://user-images.githubusercontent.com/41351993/68190522-8c215100-ffe8-11e9-9505-8a4f84c86583.png)

**More Info:**
1. This issue also reproduces for one empty queue.(related bug: [1604](https://github.com/microsoft/AzureStorageExplorer/issues/1604))
![image](https://user-images.githubusercontent.com/41351993/68190663-c4c12a80-ffe8-11e9-960a-7d71f991408f.png)
2. This issue doesn't reproduce for one blob container/ file share.
![image](https://user-images.githubusercontent.com/41351993/68190945-60529b00-ffe9-11e9-92e2-f262fa4f1c3b.png)
 3. Related bug: [1697](https://github.com/microsoft/AzureStorageExplorer/issues/1697)

**Comment by lukaschal** [comment] 2019-11-05 12:57
@craxal Is this message exposed to localization ?

**Comment by craxal** [comment] 2019-11-05 16:58
Duplicate of #1697.

**Closed by craxal** 2019-11-05 16:58 UTC
Labels: :gear: queues, :gear: tables, :heavy_check_mark: duplicate, 🌐 localization, 🧪 testing
