### ISSUE TITLE
Storage Explorer unable to expand tables/files

### ISSUE THREAD

**Issue by v-lons** [Microsoft/AzureStorageExplorer#441] opened 2018-07-16 22:13 UTC
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Win10ENT
**Architecture**: x64
**Regression From**: NA

#### Steps to Reproduce: ####
1. Selected Resource
2. Double click on Tables

#### Expected Experience: ####
The tables would expand, showing the resources

#### Actual Experience: ####
We get a pop-up error stating that "Storage Explorer has encountered an unexpected error: Unable to retrieve child resources." "Details: The value for one of the HTTP headers is not in the correct format."

Is this an issue with incorrect versions?

**Comment by craxal** [comment] 2018-07-16 23:08
Do you have a screenshot to share? Are you trying to connect to the table via sign-in, key, account SAS, external SAS, or local emulator?

**Comment by xibix-fp** [comment] 2018-07-19 09:04
@craxal We experience the same issue with the new version 1.3.1, but in our case with file shares. The issue do not occur with all storage accounts, but with some of them. From my perspective there is no configuration difference between the accounts. Currently the problem occurs with the Windows and the Mac version of the storage explorer.

<img width="869" alt="bildschirmfoto 2018-07-19 um 10 59 02" src="https://user-images.githubusercontent.com/41422866/42932769-7c07eeca-8b43-11e8-9423-2735eea6ed56.png">

**Comment by craxal** [comment] 2018-07-19 15:45
Sure wish Azure was more helpful with these error messages.... Can you give me any details about the accounts that work vs the accounts that don't?

If you're connected via SAS or key, can you share the steps you used to connect to the account? For SAS, can you share the SAS (minus the sig portion)? If it's a key, has the key been regenerated?

**Comment by xibix-fp** [comment] 2018-07-19 20:42
Ich checked both accounts, they are the same. Nothing special and no difference from what I can see.
![image](https://user-images.githubusercontent.com/41422866/42968796-9d865b3e-8ba4-11e8-8687-e82d9b9e7250.png)
Here is the key I use to connect:
DefaultEndpointsProtocol=https;AccountName=XXXXXXXdataexchgint01;AccountKey=xxxxxxxxxxxx;EndpointSuffix=core.windows.net
Even if I login in Azure Storage Explorer in my subscription, I get this error.
If it helps, I send telemetry data, so may you can find the error with the correlation id?

**Comment by craxal** [comment] 2018-07-19 21:18
Ah, so it's a V2 account. Looks like I've run into the same problem here, too. We'll need to look into this and find out what's wrong.

![image](https://user-images.githubusercontent.com/3473026/42970460-321dbedc-8b5e-11e8-83fe-539f7cfa81f2.png)

Out of curiosity, can you select the account node and scroll through the list of properties? Anything missing, such as primary or secondary keys?

**Comment by xibix-fp** [comment] 2018-07-19 21:43
Primary and Secondary Keys can be bopied from the context menu of the node. It looks 
also that I am able to access the Table Storage, but not the File Shares:
![image](https://user-images.githubusercontent.com/41422866/42971694-7d9a0c9a-8bad-11e8-991a-7bb632ef732d.png)

**Comment by craxal** [comment] 2018-07-19 21:49
Oh, you've access to your keys. My repro appears to have a different root cause.

**Comment by MRayermannMSFT** [comment] 2018-07-19 21:49
@xibix-fp , what Azure environment are you working in?

**Comment by xibix-fp** [comment] 2018-07-19 21:51
Azure Standard (we have everything in West Europe deployed)

**Comment by MRayermannMSFT** [comment] 2018-07-19 22:31
Hmm that's odd. Can you do the following for me please?

1. Open the dev tools (F12)
2. Use ctrl+p to open `NodeGroupViewModel.js`
3. Set a breakpoint on line 82 by clicking on "82" (the line should contain "Unable to retrieve child resources")
4. Repro the error
5. When the breakpoint is hit, hover over `err` to see expanded error info, and comment here with what you see. What we're looking for is information as to what header is invalid.

**Comment by MRayermannMSFT** [comment] 2018-07-19 22:43
I'm guessing this is the same issue as #405

**Comment by xibix-fp** [comment] 2018-07-20 04:29
Sure, here you go...

`err:Error: The value for one of the HTTP headers is not in the correct format. RequestId:7c7554cf-b01a-010c-35e1-1fbda3000000 Time:2018-07-20T04:25:37.1041917Z at Function.StorageServiceClient._normalizeError (/Users/username/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1198:23) at Object.StorageServiceClient._processResponse (/Users/username/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:744:50) at Request.processResponseCallback [as _callback] (/Users/username/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:317:37) at Request.self.callback (/Users/fabian.pagel/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/request/request.js:185:22) at ZoneDelegate.invokeTask (/Users/username/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35) at Zone.runTask (/Users/username/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47) at Request.ZoneTask.invoke (/Users/username/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33) at emitTwo (events.js:126:13) at Request.emit (events.js:214:7) at Request.<anonymous> (/Users/fabian.pagel/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/request/request.js:1157:10) at ZoneDelegate.invokeTask (/Users/username/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35) at Zone.runTask (/Users/username/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47) at Request.ZoneTask.invoke (/Users/username/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33) at emitOne (events.js:116:13) at Request.emit (events.js:211:7)
code:"InvalidHeaderValue"
headername:"x-ms-version"
headervalue:"2018-03-28"
name:"StorageError"
requestId:"7c7554cf-b01a-010c-35e1-1fbda3000000"
statusCode:400
message:"The value for one of the HTTP headers is not in the correct format.↵RequestId:7c7554cf-b01a-010c-35e1-1fbda3000000↵Time:2018-07-20T04:25:37.1041917Z"
stack:"StorageError: The value for one of the HTTP headers is not in the correct format.↵RequestId:7c7554cf-b01a-010c-35e1-1fbda3000000↵Time:2018-07-20T04:25:37.1041917Z↵    at Function.StorageServiceClient._normalizeError (/Users/fabian.pagel/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1198:23)↵    at Object.StorageServiceClient._processResponse (/Users/fabian.pagel/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:744:50)↵    at Request.processResponseCallback [as _callback] (/Users/fabian.pagel/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:317:37)↵    at Request.self.callback (/Users/fabian.pagel/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/request/request.js:185:22)↵    at ZoneDelegate.invokeTask (/Users/fabian.pagel/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)↵    at Zone.runTask (/Users/fabian.pagel/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)↵    at Request.ZoneTask.invoke (/Users/fabian.pagel/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)↵    at emitTwo (events.js:126:13)↵    at Request.emit (events.js:214:7)↵    at Request.<anonymous> (/Users/fabian.pagel/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/request/request.js:1157:10)↵    at ZoneDelegate.invokeTask (/Users/fabian.pagel/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)↵    at Zone.runTask (/Users/fabian.pagel/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)↵    at Request.ZoneTask.invoke (/Users/fabian.pagel/Downloads/StorageExplorer_signed/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)↵    at emitOne (events.js:116:13)↵    at Request.emit (events.js:211:7)"
__proto__:Object
this:undefined `

**Comment by xibix-fp** [comment] 2018-07-24 09:39
@craxal @MRayermannMSFT 
Does this mean, that this can be fixed soon?

**Comment by MRayermannMSFT** [comment] 2018-07-24 17:23
@xibix-fp , are you still having problems? I just checked with some people, and every cloud/region is using the latest storage api versions at this point. If you are having issues, can you reconfirm that you West are in normal Azure (aka, you go to portal.azure.com to see your resources), and that you are in Europe? Thanks!

**Comment by xibix-fp** [comment] 2018-07-25 19:46
@MRayermannMSFT At the moment, I can not reproduce the issue anymore. Will let our customers check as well and give then a final feedback.

**Comment by MRayermannMSFT** [comment] 2018-07-26 16:12
Ok @xibix-fp , sounds good. Please close this issue once you  know for sure. Or let us know and we'll close it.

**Comment by xibix-fp** [comment] 2018-07-29 08:56
So, problem seems to be fixed on all sides.

**Comment by MRayermannMSFT** [comment] 2018-07-30 16:01
Ok, I'm closing the issue.

**Closed by MRayermannMSFT** 2018-07-30 16:01 UTC
Labels: :gear: files, :gear: tables, :x: bug, 🔍 more info
