### ISSUE TITLE
Auto scrolling to top when single clicking on directory 

### ISSUE THREAD

**Issue by SelakaKithmal** [microsoft/AzureStorageExplorer#6227] opened 2022-10-28 17:39 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Regression From

No

### Architecture

i86

### Storage Explorer Build Number

20221018.5

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Once you navigate you a specific folder in the storage explorer upon clicking on the folder it automatically scrolls to the top of the folder list.

### Steps to Reproduce

Open go to the File share search a folder and single click the directory.

### Actual Experience

Upon clicking on the directory on in the file share it should not auto scroll to the top of the list

### Expected Experience

Once clicking on single directory it should not be scrolling up automatically.

**Comment by JasonYeMSFT** [comment] 2022-10-28 23:08
I have seen this at some point but unfortunately I cannot consistently reproduce this issue in the file explorer. If I have a chance of reproducing it I will try to figure out why.

**Comment by akanailov** [comment] 2022-12-02 00:55
Here is how I keep seeing this issue: 

1. Open a list of folders in the storage explorer.
2. Open one of the folders.
3. Navigate back using the left arrow. You can see that no folders are selected from the list.
4. Scroll down and try to click on some folder. You will end up opening a different folder instead.
Happened to me many times, we even had some long-lasting issues before we identified that I accidentally downloaded the file from the wrong folder because of this :(

**Comment by JasonYeMSFT** [comment] 2022-12-02 01:03
@akanailov I can consistently reproduce it now. Thanks for the information. I will see if I can fix it in 1.28.0.

**Comment by MRayermannMSFT** [comment] 2022-12-02 19:31
Yes, thank you @akanailov for sharing your steps! Very helpful.

**Comment by JasonYeMSFT** [comment] 2023-01-09 22:41
This will be fixed in 1.28.0.

**Closed by JasonYeMSFT** 2023-01-09 22:41 UTC
Labels: :beetle: bug, :heavy_check_mark: merged
