### ISSUE TITLE
Typing subdirectory to filter by prefix box can't always open the correct path

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6554] opened 2023-02-13 09:22 UTC
**Storage Explorer Version**: 1.28.0
**Build Number**: 20230211.3
**Branch**: rel/1.28.0
**Platform/OS**: Linux Ubuntu 20.04/MacOS Ventura 13.2 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a new folder 'f1'.
3. Open the folder -> Back to the root.
4. Type 'f1/' into the filter by prefix box.
5. Check whether the folder is opened.

## Expected Experience ##
The folder is opened.

## Actual Experience ##
The folder is not opened.

## Additional Context ##
1. This issue also reproduces for file shares.
2. This issue can't be reproduced consistently.
3. This issue can be resolved by manually refreshing.
4. We didn't see this issue reproduced on Windows.
5. Here is the record:

https://user-images.githubusercontent.com/41351993/218416938-428db855-8c00-495e-980c-ab78781db8c5.mov

**Comment by JasonYeMSFT** [comment] 2023-02-13 18:35
The cause of the bug is that we don't allow concurrently reloading data in the explorer. When the data table is loading data, the new search text won't be able to trigger a reload in the data table. The chance of hitting this problem is low and the workaround is easy (retype the search text or manually refresh) so let's won't fix this and wait for more user feedback.

**Closed** 2023-02-13 18:35 UTC
Labels: :heavy_check_mark: won't fix, 🧪 testing, :gear: files, :gear: adls gen2
