### ISSUE TITLE
I want to use a Active Directory Managed Identity to connect 

### ISSUE THREAD

**Issue by jotterson** [microsoft/AzureStorageExplorer#3943] opened 2020-12-29 19:48 UTC
**Is your feature request related to a problem? Please describe.**
I want to use a Active Directory Managed Identity to connect.

Like described here: https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json#set-environment-variables

**Describe the solution you'd like**

Maybe an additional connect option that collected

* tenant id
* client id
* client secret or path to cert

**Describe alternatives you've considered**

Using access key does not offer enough granularity of authentication and authorization.

**Additional context**

**Comment by MRayermannMSFT** [comment] 2021-01-11 19:04
@jotterson thanks for the feature request. We've been receiving lots of interest in this recently. While we can see how this scenario would be valuable to you, since managed identity isn't intended to be used for something like this we're still investigating if adding this feature to storage explorer would create any additional issues or problems down the road. Thanks.

**Comment by MRayermannMSFT** [comment] 2022-06-27 18:47
Dupe of #2142

**Closed by MRayermannMSFT** 2022-06-27 18:47 UTC
Labels: :bulb: feature request, :gear: sign-in, :bulb: sign-in feature

**Comment by MRayermannMSFT** [comment] 2022-06-30 23:48
@jotterson FYI I have asked a question for the author of #2142 regarding managed identity support in storage explorer. If you'd like to answer that question as well, feel free to come on over to that issue and do so. Thanks.
