### ISSUE TITLE
Show storage account name in open tabs

### ISSUE THREAD

**Issue by JarroVGIT** [microsoft/AzureStorageExplorer#3297] opened 2020-07-27 08:54 UTC
**Is your feature request related to a problem? Please describe.**
When having multiple tabs open (for example blob containers) from different storage accounts, and the blob containers have the same name, there is no way of knowing for sure in which storage account you are currently working. Especially if you deselected the container name in the explorer-tree to use a sub-menu on a different storage account for example.

**Describe the solution you'd like**
Display storage account name in tab. Alternatively: display storage account name when hovering your mouse over the tab name.

**Describe alternatives you've considered**
Always open the tabs in specific order so you can use that to identity which tab is which storage account.

**Additional context**
None.

**Comment by MRayermannMSFT** [comment] 2020-07-27 17:44
Duplicate of #4

**Closed by MRayermannMSFT** 2020-07-27 17:44 UTC
