### ISSUE TITLE
Copy/Paste of Blob fails

### ISSUE THREAD

**Issue by SergeiKamnev** [microsoft/AzureStorageExplorer#6653] opened 2023-03-10 07:09 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.0

### Regression From

1.27.1

### Architecture

i86

### Storage Explorer Build Number

Build Number: 20230214.5 

### Platform

Windows

### Bug Description

When making Copy/Paste of blobs in Blob container attached with SAS Token, the error occurs.
All was fine in version 1.27.1. It fails in 1.28.0 and 1.28.1

### Steps to Reproduce

1.	Create a SAS token with Stored Access Policy. The policy permits all permissions.
2.	Attach a blob container.
3.	Open the container (which contains several folders inside). It is fine. Select a folder there and press “Copy”.
4.	Open any another folder in the container and press “Paste”
5.	Operation fails with error:
Transfer of 'deployments/PPE1-MAX/MBO-19896/' to 'deployments/' failed: 0 items transferred, error: failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
Description=This request is not authorized to perform this operation using this permission.
RequestId:3c338dce-901e-0062-141d-538c3d000000
Time:2023-03-10T06:54:34.5351942Z, Details:
Code: AuthorizationPermissionMismatch
GET https://mboppev2.blob.core.windows.net/deployments?comp=list&delimiter=%2F&include=metadata%2Ctags&prefix=ppe1-max%2Fmbo-19896%2F&restype=container&si=skamnev&sig=-REDACTED-&spr=https&sr=c&sv=2021-06-08&timeout=901
User-Agent: [Microsoft Azure Storage Explorer, 1.28.0, win32, azcopy-node/2.11.0-rc.1 (win32) AzCopy/10.17.0 Azure-Storage/0.15 (go1.19.2; Windows_NT)]
X-Ms-Client-Request-Id: [a25227e9-ea11-4330-439a-0ac54c3fed99]
X-Ms-Version: [2020-10-02]
--------------------------------------------------------------------------------
RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
Content-Length: [279]
Content-Type: [application/xml]
Date: [Fri, 10 Mar 2023 06:54:34 GMT]
Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
X-Ms-Client-Request-Id: [a25227e9-ea11-4330-439a-0ac54c3fed99]
X-Ms-Error-Code: [AuthorizationPermissionMismatch]
X-Ms-Request-Id: [3c338dce-901e-0062-141d-538c3d000000]
X-Ms-Version: [2020-10-02]

.
(used SAS, discovery not completed)
Started at: 3/10/2023 9:54 AM, Duration: 4 seconds

### Actual Experience

Copy/Paste doesn't work

### Expected Experience

It worked before 1.28.0 just as simple copy/paste experience.

**Comment by MRayermannMSFT** [comment] 2023-03-13 17:55
@SergeiKamnev it looks like your SAS is using a signed identifier with ID skamnev. Could you share a screenshot of what permissions that access policy has? You can view access policy permissions either via Storage Explorer or Portal. Let us know if you need additional help with this.

**Comment by SergeiKamnev** [comment] 2023-03-14 13:43
AzCopy log file:
2023/03/14 13:39:59 AzcopyVersion  10.17.0
2023/03/14 13:39:59 OS-Environment  windows
2023/03/14 13:39:59 OS-Architecture  amd64
2023/03/14 13:39:59 Log times are in UTC. Local time is 14 Mar 2023 16:39:59
2023/03/14 13:40:00 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2023-03-14T13:39:54Z or --include-after=2023-03-14T13:39:54Z
2023/03/14 13:40:01 WARN: Failed to create destination container deployments. The transfer will continue if the container exists
2023/03/14 13:40:01 Error -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:ae3bf4ec-d01e-006e-467a-5662cc000000
Time:2023-03-14T13:40:01.5374241Z, Details: 
   Code: AuthorizationFailure
   PUT https://mboppev2.blob.core.windows.net/deployments?restype=container&si=skamnev1&sig=-REDACTED-&spr=https&sr=c&sv=2021-12-02&timeout=180
   User-Agent: [Microsoft Azure Storage Explorer, 1.28.0, win32, azcopy-node/2.11.0-rc.1 (win32)  AzCopy/10.17.0 Azure-Storage/0.15 (go1.19.2; Windows_NT)]
   X-Ms-Client-Request-Id: [1ba5f9aa-7344-4347-549f-0cbaafaa53a8]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Tue, 14 Mar 2023 13:40:01 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [1ba5f9aa-7344-4347-549f-0cbaafaa53a8]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [ae3bf4ec-d01e-006e-467a-5662cc000000]
   X-Ms-Version: [2020-10-02]
2023/03/14 13:40:01 Any empty folders will not be processed, because source and/or destination doesn't have full folder support

**Comment by MRayermannMSFT** [comment] 2023-03-20 16:36
@SergeiKamnev are you working in a ADLS Gen2 blob container?

Assuming yes, then we discovered a bug last week that has a similar behavior as this. So this is likely that bug. For now the workarounds for this issue are:
- Use 1.27
- Use a SAS which does not use an access policy

We'll be including a fix for this in 1.29.0. Let us know if you have any further questions.

**Comment by MRayermannMSFT** [comment] 2023-03-31 17:31
Hi @SergeiKamnev if you have time, could you please try reproducing the issue using this private build of our upcoming 1.29.0 release? https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.29.0-copy-blob-access-policy-bug/StorageExplorer-windows-ia32.exe?sv=2021-10-04&st=2023-03-31T17%3A15%3A18Z&se=2023-04-16T17%3A15%3A00Z&sr=b&sp=r&sig=9MsV0WUrpsAcHwl7c%2F6Rxv18kUWVBXdtj3PFBSQHmSI%3D

Once done testing, please avoid the temptation to keep using the build and instead reinstall 1.28.1. At this time 1.29.0 has not gone through thorough enough testing for us to recommend using it on a day to day basis. Thanks.

**Comment by SergeiKamnev** [comment] 2023-04-01 08:00
Hello,
It looks this build works okay for the failed use case.

Sergei.

**Comment by MRayermannMSFT** [comment] 2023-04-01 23:39
Awesome. We'll mark this as fixed in 1.29.0.

**Closed by MRayermannMSFT** 2023-04-01 23:39 UTC
Labels: :beetle: bug

**Comment by SergeiKamnev** [comment] 2023-06-23 06:25
The issue is back in 1.30.0 release
