### ISSUE TITLE
An info bar 'name and key must be non-empty strings' prompts when attaching a table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5126] opened 2021-11-02 10:45 UTC
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211102.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Launch Storage Explorer -> Expand one storage account -> Tables.
2. Select one table and try to attach it.
3. Check whether no info bar prompts.

## Expected Experience ##
No info bar prompts.

## Actual Experience ##
An info bar 'name and key must be non-empty strings' prompts.
![image](https://user-images.githubusercontent.com/87792676/139825448-9b1c399b-276e-473a-b304-926b31a1d1ab.png)

**Comment by craxal** [comment] 2021-11-02 19:00
This sounds like a duplicate of #5124.

**Closed** 2021-11-02 19:00 UTC
Labels: 🧪 testing, :gear: tables, :gear: attach, :beetle: regression
