### ISSUE TITLE
There are untranslated strings in the localized 'Update Access Tier' dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3777] opened 2020-11-16 09:11 UTC
**Storage Explorer Version:** 1.16.0
**Build**: 20201116.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Language**: All
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Čeština' -> Restart Storage Explorer.
3. Expand one GPV2 storage account -> Blob Containers.
4. Select one blob container -> Right click one blob -> Click the localized action 'Change Access Tier...‘.
5. Check the strings in the localized 'Update Access Tier' dialog.

**Expect Experience:**
All strings are translated in the localized 'Update Access Tier' dialog.

**Actual Experience:**
There are untranslated strings in the localized 'Update Access Tier' dialog.
![image](https://user-images.githubusercontent.com/54055206/99231653-deb46080-282b-11eb-9fdf-05c3b12612df.png)

**Comment by MRayermannMSFT** [comment] 2021-04-09 22:30
Treating this as a duplicate of #3945

**Closed by MRayermannMSFT** 2021-04-09 22:30 UTC
