### ISSUE TITLE
 'Undelete' action is enabled for one active blob folder 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1476] opened 2019-06-19 08:36 UTC
**Storage Explorer Version:** 1.8.1_master_20190619.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 952cf5dc
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a non-ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Upload a folder which contains at least one file to it .
3. Right click the uploaded folder and check it's context menu.

**Expect Experience:**
'Undelete' action is disabled.

**Actual Experience:**
 'Undelete' action is enabled.
![image](https://user-images.githubusercontent.com/41351993/59748656-25580100-92ae-11e9-9992-9102df255a51.png)

**Comment by MRayermannMSFT** [comment] 2019-06-19 17:41
This is expected. We always show undelete enabled for a folder because we don't do any checking to see if there are deleted blobs in it. Closing as by design.

**Closed by MRayermannMSFT** 2019-06-19 17:41 UTC
Labels: :gear: blobs, :gear: delete policies, 🧪 testing
