### ISSUE TITLE
There is a failed activity log when exporting entities if Storage Explorer is installed by snap on Ubuntu 20.04

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6526] opened 2023-02-08 09:33 UTC
**Storage Explorer Version:** 1.28.0
**Build Number:** 20230208.3
**Branch:** rel/1.28.0
**Platform/OS:** Linux Ubuntu 20.04
**Architecture:** x64
**How Found:** From running test case
**Regression From:** Previous release
 
## Steps to Reproduce ##

1. Install Storage Explorer on Ubuntu 20.04 by snap.
2. Expand one storage account -> Tables.
3. Create a table -> Add some entities.
4. Click 'Export -> Export All...'.
5. Select a download location -> Click 'Save'.
6. Check whether there is a successful activity log and the download location is correct.

## Expected Experience ##

1. There is a successful activity log.
2. The download location is correct.
![image](https://user-images.githubusercontent.com/87792676/217479420-cbdbef16-d8fb-4925-a40b-df283ba0684a.png)

## Actual Experience ##

1. There is a failed activity log.
2. The download location is incorrect.
![image](https://user-images.githubusercontent.com/87792676/217479616-2dd9173c-e3c9-4f0a-8b91-f0b8677eb641.png)

## Additional Context ##
1. This issue doesn't reproduce on Ubuntu 22.04.
2. This issue doesn't reproduce if Storage Explorer is installed by tar.gz.
3. Show a successful activity log when there are no entities.
![image](https://user-images.githubusercontent.com/87792676/217478477-67fc7f0f-7a6f-4265-b2e7-3b93c8fb82b1.png)
4. Refer to bug [5363](https://github.com/microsoft/AzureStorageExplorer/issues/5363), this issue doesn't reproduce in the previous release 1.22.1.

**Comment by craxal** [comment] 2023-02-08 17:42
@v-kellyluo Can you click the View Errors button and show us what the error message is?

**Comment by JasonYeMSFT** [comment] 2023-02-08 18:18
@Kristine I can reproduce the same issue in 1.27.2 + Ubuntu 20.04. I don't think this is a regression.

**Comment by v-kellyluo** [comment] 2023-02-09 01:38
@craxal , the error detail is as below:
![image](https://user-images.githubusercontent.com/87792676/217692867-502e8c75-2316-4ec9-96f3-0e9b83b07f6c.png)

**Comment by v-xianya** [comment] 2023-02-09 02:24
@JasonYeMSFT I can reproduce the issue in 1.27.2 + Ubuntu 20.04.

Refer to the bug [5363](https://github.com/microsoft/AzureStorageExplorer/issues/5363). The export operation works fine in 1.21.1. So, we mark this issue as a regression.

**Comment by JasonYeMSFT** [comment] 2023-02-10 23:51
We'll track it in a future milestone. It's basically an external issue so there is nothing we can do in 1.28.0 for it.

**Comment by Kristine** [comment] 2023-02-11 03:51
I think you're tagging the wrong Kristine.

**Comment by JasonYeMSFT** [comment] 2023-02-28 04:12
The root cause is the fact that the document portal that snap/ubuntu combo uses doesn't support writing at the middle of a file. It can be externally reproduced and there is nothing we can do in Storage Explorer to mitigate it.

**Comment by JasonYeMSFT** [comment] 2023-03-15 22:43
I am going mark this as won't fix since this problem is mitigated in a newer version of Ubuntu 22.04.

**Closed by JasonYeMSFT** 2023-03-15 22:43 UTC
Labels: 🧪 testing, :gear: tables, :grey_question: external, :beetle: regression, :computer: linux, :package: snaps
