### ISSUE TITLE
Add a warning sign when renaming one blob container using an invalid name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2257] opened 2019-11-13 08:27 UTC
**Storage Explorer Version:** 1.11.0
**Build:** [20191112.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3234284)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Try to rename it using an invalid name. (like: 'bl')
3. Check the 'Rename' dialog.

**Expect Experience:**
A warning sign occurs.

**Actual Experience:**
No warning sign occurs.
![image](https://user-images.githubusercontent.com/41351993/68745087-f06b9280-0630-11ea-81aa-aeafabd1e353.png)

**More Info:**
1. There is a warning sign when creating a blob container with an invalid name.
![image](https://user-images.githubusercontent.com/41351993/68745109-fb262780-0630-11ea-8201-3afd5324af00.png)
2. This issue also reproduces for one file share/ table.

**Comment by MRayermannMSFT** [comment] 2019-11-18 18:56
Duplicate of #2258

**Closed by MRayermannMSFT** 2019-11-18 18:56 UTC
Labels: 🧪 testing
