### ISSUE TITLE
An error occurs after clicking action 'Manage Snapshot' for one public attached ADLS Gen2 blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4509] opened 2021-05-31 08:07 UTC
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210530.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Bug Description ##

No error occurs when executing the available actions 'Open, Download, Copy URL, Copy Path, Selection Statistics' and checking properties dialog for the public attached ADLS Gen2 blob. But there is an error when executing action 'Manage Snapshot'.

## Steps to Reproduce ##

1. Select one ADLS Gen2 blob -> Click 'Copy URL'.
2. Open Connect dialog -> Click 'ADLS Gen2 container or directory -> Anonymously (my blob container allows public access)' -> Paste the URL.
3. After attaching successfully -> Open the attached resource -> Right click the blob then click 'Manage Snapshot'.
4. Check whether there is no error.

## Expected Experience ##
There is no error.

## Actual Experience ##
An error 'Server encountered an internal error. Please try again after some time...' occurs.
![adls](https://user-images.githubusercontent.com/54055206/120158963-43af3100-c227-11eb-8469-2fc4a9295613.gif)

## More Info ##
1. This issue doesn't reproduce when using the URL of one ADLS Gen2 blob container or directory to public attach.
2. Fail to use the URL of one regular blob to public attach. An error '_The URL path appears to reference an object-level resource. Attaching to object-level resources is not supported_' displays in the 'Anonymously (my blob container allows public access)' dialog.
![image](https://user-images.githubusercontent.com/54055206/120157528-b3242100-c225-11eb-89ff-f36dd755b8cf.png)

**Comment by craxal** [comment] 2021-06-01 17:02
@v-limu This is by design. The expected experience is not possible. We do not support connecting to blobs. You can only connect to containers or directories. Catching this error for ADLS Gen2 is also not possible. We can show an error message for regular blobs, because we only support connecting to regular containers. There is no way for us to determine whether a URL points to an ADLS Gen2  blob or directory, because there is nothing in the URL that can help us determine that definitively (someone could name their folder "file.txt").

**Comment by craxal** [comment] 2021-06-01 18:48
After some deliberation, we decided to reopen this and seek a suitable fix for this. We want to add some sort of validation in the Connect dialog since we've never supported connecting to blobs.

We're also a bit surprised so many operations still appeared to work, so we should spend a little bit of time digging in to find out why listing, etc. still seemed to work after connecting with a blob URL.

**Comment by craxal** [comment] 2021-06-23 20:42
Related to #4592.

**Comment by craxal** [comment] 2021-08-09 23:11
When we first list, we send a prefix that looks something like "blob.text/". It looks like the service automatically trims the trailing slash (probably because it is a delimiter), which is why the list operation still works and shows the blob that was targeted as the "directory" to attach.

In any case, it's behavior we weren't expecting. The problems come because of this unexpected behavior combined with the explorer's current path. When we choose to manage screenshots, it tries to navigate to "blob.txt/blob.txt", which obviously isn't correct.

We should probably discuss ideas about how to address this problem, as I don't think the solution is straightforward.

**Comment by craxal** [comment] 2021-08-09 23:25
After some discussion, we decided we won't fix this, as this is a distant edge case with an easy workaround. If there was some easy way to tell whether a path was to a blob or a directory, we wouldn't allow this kind of connection at all.

**Closed by craxal** 2021-08-09 23:25 UTC
Labels: :heavy_check_mark: won't fix, 🧪 testing, :gear: adls gen2
