### ISSUE TITLE
List the value of 'Table Endpoint' to the 'Primary Connection String' for Cosmos DB accounts with Table API

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#424] opened 2018-07-13 10:00 UTC
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180711.4
**Commit**: 47039639
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open Storage Explorer and navigate to one Cosmos DB account with Table API.
2. Go to 'Properties' window and check the value of 'Table Endpoint' and 'Primary Connection String'.

#### Expected Experience: ####
It displays well in 'Table Endpoint' and it is included in 'Primary Connection String'.

#### Actual Experience: ####
Display '(Not Applicable)' for 'Table Endpoint' and it is included in 'Primary Connection String'.

**Comment by ziyel** [comment] 2018-07-24 10:43
@v-dantch , I cannot reproduce the issue.
Is it possible to provide some screenshots for this?

**Comment by v-dantch** [comment] 2018-07-27 06:49
@ziyel, please get the screenshot from below.
![screenshot](https://user-images.githubusercontent.com/34729092/43305641-13f3a84e-9168-11e8-97fd-9a666d685eb5.PNG)

**Comment by v-xianya** [comment] 2019-04-12 07:48
Verified on build 20190411.3. This issue doesn't reproduce. Could you help to resolve it.

**Comment by jinglouMSFT** [comment] 2019-04-12 17:34
Per Xian, closing.

**Closed by jinglouMSFT** 2019-04-12 17:34 UTC
Labels: :gear: cosmosdb, :heavy_check_mark: no repro, 🧪 testing
