### ISSUE TITLE
Attempts to Upload PageBlobs for BlobStorage and BlockBlobStorage Accounts Don't Appear to Reach Server

### ISSUE THREAD

**Issue by jcrobins** [Microsoft/AzureStorageExplorer#1172] opened 2019-02-28 01:38 UTC
**Storage Explorer Version**: 1.6.2
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: N/A

#### Steps to Reproduce:
1. Create a Premium BlockBlobStorage (or Standard BlobStorage) storage account.
2. Select the created storage account in Storage Explorer.
3. Select a container in this account in Storage Explorer and select **Upload** > **Upload Files...** to view the **Microsoft Azure Storage Explorer - Upload Files to Blob Container** dialog.
4. Upload a page blob.

#### Expected Experience:
The operation should result in an error containing the details of the ClientOtherError returned by Storage as a result of issuing a PutBlob of an invalid (PageBlob) type.
The Details of the error should contain the detailed message returned by storage for the failed operation.

#### Actual Experience:
Server-side logs do not indicate a PutBlob was issued.
The operation eventually fails client-side with the following error details:
{
  "message": "\"Upload failed unexpectedly after 5 attempt\""
}

**Comment by jcrobins** [comment] 2019-02-28 01:39
Semi-Related to the following issue (which requests we remove the "PageBlob" option for BlockBlobStorage and BlobStorage accounts):
https://github.com/Microsoft/AzureStorageExplorer/issues/1170

**Comment by craxal** [comment] 2019-04-02 22:44
After some investigation, this may be due to the same root cause encountered in #1050. The client library throws a error rather than calling our callback. Since it's an asynchronous situation, a try/catch block won't catch the error as expected.

**Comment by craxal** [comment] 2019-04-17 20:53
Ran quick verification. Appears to be fixed after resolving #1050.

**Closed by craxal** 2019-04-17 20:53 UTC
Labels: :beetle: bug, :mag: external, :mag: investigate
