### ISSUE TITLE
Export from table does not include query anymore but only exports full table

### ISSUE THREAD

**Issue by hnky** [microsoft/AzureStorageExplorer#5320] opened 2022-01-07 16:36 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Architecture

x64

### Storage Explorer Build Number

20211211.10

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Run a query on an Azure Table
Click Export
In previous versions it exported the result of the query
In this version it exports all the record in the table

### Steps to Reproduce

1 Launch Explorer
2 Connect to a Azure Table
3 Run a Query
3 Click export

### Actual Experience

It should export the result of the query

### Expected Experience

It should export the result of the query

**Comment by eakoek** [comment] 2022-01-10 17:08
I experience exactly the same problem. How can I downgrade to the previous version, because I urgently need to export a part of the table, because it is too big for a full export.

**Comment by zlmonroe** [comment] 2022-01-10 18:24
+1, I've been experiencing this after updating as well. The "Select Columns" feature also seems to be ignored now for export.

**Comment by MRayermannMSFT** [comment] 2022-01-10 18:33
@eakoek @hnky @zlmonroe you can find old version here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.21.3

**Comment by gamesgao** [comment] 2022-01-12 06:13
+1, This regression is CRITICAL.

**Comment by craxal** [comment] 2022-01-12 19:42
@gamesgao A fix has already been merged. We will be releasing a new version with this fix very soon.

**Closed** 2022-01-12 19:43 UTC
Labels: :beetle: regression
