### ISSUE TITLE
Incorrectly display 'Download...' on the restored tab's toolbar for blob containers/ADLS Gen2s/file shares if storage explorer is upgraded from  1.26.1 to a newer version

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6367] opened 2022-12-14 09:34 UTC
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20221213.3
**Branch**: main
**Platform/OS**: Linux Ubuntu 20.04/MacOS Ventura 13.0.1 (Apple M1 Pro)
**Architecture**: x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Bug Description ##
Upgrade storage explore from 1.26.1 -> 1.27.0, for the restored tabs.
1. The 'Download All' doesn't display.
2. The action 'Download' displays incorrectly on the toolbar.
![image](https://user-images.githubusercontent.com/41351993/207555194-fd7a9437-9948-416e-b18b-4ea4186334c6.png)

## Steps to Reproduce ##
1. Open version 1.26.1 storage explorer -> Enable the setting 'Preserve Explorer Session'.
2. Expand one storage account -> Blob Containers.
3. Open one blob container -> Close storage explorer.
4. Open storage explorer with build #20221213.2.
5. Observe the restored blob container's tab.
6. Check whether the 'Download' action displays correctly on the toolbar.

## Expected Experience ##
The 'Download' action displays correctly on the toolbar.
![image](https://user-images.githubusercontent.com/41351993/207555543-058bfae1-a621-4aa8-ad2e-c3b28e0a0b43.png)

## Actual Experience ##
The 'Download' action displays incorrectly on the toolbar.
![image](https://user-images.githubusercontent.com/41351993/207555085-137b3682-425f-4816-920c-a24913237f3d.png)

## Additional Context ##
This issue doesn't reproduce on Windows.

**Comment by JasonYeMSFT** [comment] 2022-12-14 17:27
This is expected if you keep two instances of Storage Explorer. The restored tab stores which source file to load which in this case will be the old build so the Download button won't be using the new one in 1.27.0.

**Comment by JasonYeMSFT** [comment] 2022-12-20 23:47
I made a change which will prevent Storage Explorer from attempting to restore tabs whose source files are different from the currently registered ones. For the referenced scenario, Storage Explorer won't restore the problematic tab.

**Comment by v-kellyluo** [comment] 2022-12-21 07:26
Verified this issue on the build main/20221220.8, it still reproduces.

**Comment by JasonYeMSFT** [comment] 2022-12-21 17:16
I see what is going on now. The code only checks if the panel to be restored matches any registered panel. I am going to close this issue as by design for now since this is a very edge case.

**Closed by JasonYeMSFT** 2022-12-21 17:16 UTC
Labels: :heavy_check_mark: merged, 🧪 testing, :heavy_check_mark: by design
