### ISSUE TITLE
Explorer doesn't display last files when ordered by Last Modified

### ISSUE THREAD

**Issue by Patafoin** [Microsoft/AzureStorageExplorer#743] opened 2018-10-09 07:55 UTC
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Windows 10
**Architecture**: x64
**Regression From**: Never seen it working

#### Steps to Reproduce: ####
1. Go to a container with many files (many pages)
2. Clic on the "Last Modified" column to make it ordered by date desc
3. See if you find your last modified files => you don't.
4. type the name of a file modified today in the "search by prefix" area => you see the file

#### Expected Experience: ####
I would like to see all the last modified files (with the date from today) order by descending date

#### Actual Experience: ####
I see files from yesterday and not the last modified files

**Comment by MRayermannMSFT** [comment] 2018-10-09 21:00
@Patafoin , is there a "Load more..." link in the bottom right of your editor?

![image](https://user-images.githubusercontent.com/21112697/46698358-b200da00-cbcb-11e8-80a4-5f1a3342bfd2.png)

**Comment by Patafoin** [comment] 2018-10-12 10:28
Yes, there is.
This link has a strange behavior... It loads more items but without taking care of the column ordering.

**Comment by MRayermannMSFT** [comment] 2018-10-12 17:39
Sigh, yep, this is a known behavior, one that we aren't 100% happy about. Basically, when you click on the column header, you are sorting the blobs we have listed thus far. That load more in the bottom right means there are more blobs on the server which we have not yet listed. So to get the behavior you desire, you need to click load more until you've loaded all of your blobs. We already have a bug open for making this experience better, so I'm going to go ahead and close this one as duplicate. Duplicate of #134.

**Closed by MRayermannMSFT** 2018-10-12 17:39 UTC

**Comment by joesalvati68** [comment] 2023-01-04 19:12
This is from 2018. It is now 2023.  Same experience.  How long do you guys take to work through bugs ?
