### ISSUE TITLE
Stop shipping unused files at runtime

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#5117] opened 2021-11-01 20:11 UTC
Files include:
- Typing files (*.d.ts).
- Source map (.js.map)
- Unused icon files

**Comment by MRayermannMSFT** [comment] 2021-11-10 21:40
Dupe of https://github.com/microsoft/AzureStorageExplorer/issues/4781

**Closed by MRayermannMSFT** 2021-11-10 21:40 UTC
