### ISSUE TITLE
Fail to paste one blob container under one 'Name & Key' attached storage account to emulator blob containers node

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5514] opened 2022-03-10 09:29 UTC
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220308.2
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.21.3)
## Steps to Reproduce ##

1. Install and run Azurite 3.15.0 -> Launch Storage Explorer.
2. Select one non-ADLS Gen2 storage account -> Attach it by 'Name & Key'.
3. Expand the attached storage account -> Blob Containers.
4. Create a blob container -> Right click the blob container -> Click 'Copy Blob Container'.
5. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)'.
6. Right click blob containers node -> Click 'Paste Blob Container'.
7. Check whether succeeds to paste the blob container.

## Expected Experience ##
Succeed to paste the blob container.
![image](https://user-images.githubusercontent.com/87792676/157616789-2c85754e-c8ce-4ee5-962f-a69961d6d887.png)

## Actual Experience ##
Fail to paste the blob container.
![image](https://user-images.githubusercontent.com/87792676/157615244-ac3a1b2e-1ab2-4558-b31c-39adbe551063.png)

## Additional Context #

1. This issue doesn't reproduce for tables.
2. This issue doesn't reproduce for SAS attached storage accounts.

**Comment by JasonYeMSFT** [comment] 2022-03-18 18:23
I found the cause of it. The problem is that Azurite doesn't recognize the new API version 2021-04-10, which is the default API version of the new SDK package. Given that this scenario is not common, I am going to close this issue. If any major scenarios of the Emulator is broken in the same way, we will add some special logic to fallback to a lower API version for Emulator.

**Comment by JasonYeMSFT** [comment] 2022-03-18 18:41
Let me check if normal Emulators scenarios are affected.

**Comment by JasonYeMSFT** [comment] 2022-03-18 18:50
Checked normal Emulator scenarios. We detect if the target resource is from an emulator by its default key credentials and override the api version if so. Since the copy src only has SAS credential, it cannot be detected and won't work. This seems to only impact copy and I think we can close this one for now.

**Comment by JasonYeMSFT** [comment] 2022-03-18 21:33
I confused this with #5529. The deleted posts there are supposed to be for that issue.

**Comment by JasonYeMSFT** [comment] 2022-03-18 22:06
We are creating incomplete connection strings for the copy source. I will have a fix for this bug.

**Comment by v-xianya** [comment] 2022-03-21 05:54
Verified this issue on the new build 20220320.3. Reproduce.

**Comment by v-xianya** [comment] 2022-04-12 09:20
Verified this issue on the build main/20220411.5 with Azurite 3.16.0. Fixed.
![image](https://user-images.githubusercontent.com/41351993/162926572-d7e7c89f-eead-460a-ba9b-ca0696b3639c.png)

**Closed by v-xianya** 2022-04-12 09:20 UTC
Labels: :heavy_check_mark: merged, 🧪 testing, :gear: blobs, :gear: attach, :beetle: regression
