### ISSUE TITLE
Keep consistent behavior between in the activities and 'Manage Access' dialog after changing the permissions for one Azure AD attached blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3871] opened 2020-12-08 09:47 UTC
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201208.6
**Branch**: main
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one ADLS Gen2 account -> Blob Containers.
2. Create a blob container -> Right click it -> Click 'Manage Access Control Lists…'.
3. Click '$superuser(Owner)' -> Add an account (do not has access to the container) -> Check all permissions -> Click 'OK'.
4. Attach the blob container with Azure AD.
5. Change the permissions in the 'Manage Access' dialog for the Azure AD attached blob container.
6. Check whether the behavior is consistent between the activities and 'Manage Access' dialog.

## Expected Experience ##
Keep consistent behavior between in the activities and 'Manage Access' dialog.

## Actual Experience ##

1. Show a failed activity log.
![image](https://user-images.githubusercontent.com/54055206/101464693-ef16b180-3979-11eb-8bfd-0a66b1f39c88.png)

2. The permissions is updated successfully when observing its permissions in the 'Manage Access' dialog.
![Azure AD](https://user-images.githubusercontent.com/54055206/101464738-fd64cd80-3979-11eb-9ae9-2b89d857ea6c.gif)

## Additional Context ##

1. This issue doesn't reproduce for one RBAC(Storage Blob Data Owner role) Azure AD attached blob container.
2. This issue also reproduces for one blob /folder under the attached blob container.
3. The error details of the failed activity log: [Details.txt](https://github.com/microsoft/AzureStorageExplorer/files/5658186/Details.txt)

**Comment by MRayermannMSFT** [comment] 2020-12-08 19:12
This is a bit too risky to fix right now. In short, the problem is that when set the path ACL after clicking OK, that operation includes both the ACL strings themselves AND the owner identity. It seems setting the owner identity requires special permissions. I'm unsure as of to what.

So we need to probably break things up into distinct operations that can fail:

- setting the ACL strings
- setting the owner identity
- setting the owning group identity

**Comment by MRayermannMSFT** [comment] 2021-01-13 19:21
Talked about this with Jason offline. Effort to split this into multiple setAcl calls isn't worth it at this time. Moving this issue to future though incase a customer would like us to improve this scenario.

**Comment by v-xianya** [comment] 2023-05-06 02:09
Update: This issue also reproduces on the below scenario [build: 20230505.3]

**_Steps:_**
1.	Check "Disable Usage of Keys" setting -> Restart Storage Explorer.
2.	Expand one ADLS Gen2 storage account -> Blob Containers.
3.	Right click one blob container -> Click ‘Manage Access Control Lists…’ -> Change the permissions.
4.	Click ‘Ok’.

**_Actual:_**
1.	There is a failed activity log.
2.	The permission has been changed.

**Comment by MRayermannMSFT** [comment] 2023-07-11 00:00
We have decided to address this issue in 1.30.1 due to a customer report.

It should now be possible to:
1. Change POSIX ACL owner of a container/file/directory to a user who does not have RBAC roles for the container/account/subscription
2. Have that POSIX ACL owner attach the container/file's parent directory/directory to Storage Explorer
3. Have that POSIX ACL owner manage the ACLs of the container/file/directory, specifically including: remove/add/update named users in the ACL.

However:
- It is not possible for such a POSIX ACL owner to change the owner or owning group of the container/file/directory. To do so you must have access to keys (and have "Disable Usage of Keys" unchecked) or have the Blob Data Owner Role.
- If the POSIX ACL owner edits the owner or owning group to be the same user/group, that will count as an "edit", and trying to save changes to the POSIX ACL will fail.

**Closed by MRayermannMSFT** 2023-07-11 00:00 UTC
Labels: 🧪 testing, :gear: attach, :gear: adls gen2

**Comment by v-xianya** [comment] 2023-07-11 07:13
@MRayermannMSFT Verified this issue on the hotfix/1.30.1 build. Reproduce.

**Comment by MRayermannMSFT** [comment] 2023-07-11 22:00
@v-xianya there was an issue last night and unfortunately the build did not contain my fixes. Please try again with tonight's build. :)

**Comment by v-xianya** [comment] 2023-07-12 05:56
Verified this issue on the build 20230712.2. Fixed.
The behaviors mentioned in the [comments](https://github.com/microsoft/AzureStorageExplorer/issues/3871#issuecomment-1629894836) work as expected on the new build 20230712.2.
