### ISSUE TITLE
Unable to retrieve child resources - version 1.32.0

### ISSUE THREAD

**Issue by priyaankparekh** [microsoft/AzureStorageExplorer#7507] opened 2023-11-13 13:54 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.0(95)

### Architecture

x64

### Storage Explorer Build Number

20231101.3

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "TypeError",
  "message": "{\"name\":\"TypeError\"}"
}

### Steps to Reproduce

Right after launching the Storage Explorer I get a pop stating "Unable to retrieve child resources"

### Actual Experience

When I launch the Storage Explorer I get a pop stating "Unable to retrieve child resources"

![image](https://github.com/microsoft/AzureStorageExplorer/assets/44260516/6cf5e535-f1b3-470f-bff7-90469dfda054)

**Comment by MRayermannMSFT** [comment] 2023-11-13 17:59
@priyaankparekh thanks for the report. I'm going to close it, as ultimately, you needing to open this issue is due to a bug in Storage Explorer which we are already tracking elsewhere. Normally you would get a better error message telling you what to do, which is probably just needing to sign in again. Can you please try removing your account and signing back in? If that doesn't work, then I unfortunately need to ask you to downgrade back to 1.31 (https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.31.2) so you can see the real error message/wait for our hotfix to ship. Thanks!

**Comment by MRayermannMSFT** [comment] 2023-11-13 18:01
Closing as duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/7474

**Closed by MRayermannMSFT** 2023-11-13 18:01 UTC
