### ISSUE TITLE
The website should link to the Arm64 Windows version

### ISSUE THREAD

**Issue by prayaas-a** [microsoft/AzureStorageExplorer#7982] opened 2024-06-04 22:11 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Architecture

arm64

### Platform

Windows

### Bug Description

The [download site](https://azure.microsoft.com/en-us/products/storage/storage-explorer/) should link to the Windows Arm64 version at the very least. Ideally, it should only have one Windows button and auto-detect architecture. You can find sample code [here](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11#sample-code-for-detecting-arm-or-x86).

### Steps to Reproduce

Visit the Azure Storage Explorer site. Click Download > Windows on a Windows Arm64 machine

### Actual Experience

The x64 version downloads

### Expected Experience

The Arm64 version should download, or at least a link to it should be present

**Comment by craxal** [comment] 2024-06-06 17:07
@prayaas-a Windows ARM64 is currently in preview. We have a work item for adding an ARM64 download option to the page when it becomes generally available. In the meantime, you can always download from our [GitHub releases page](https://github.com/microsoft/AzureStorageExplorer/releases).

Duplicate of #7958

**Closed by craxal** 2024-06-06 17:07 UTC
Labels: :white_check_mark: duplicate
