### ISSUE TITLE
Setting a non-private Public Access Level deletes container's Access Policies

### ISSUE THREAD

**Issue by dagood** [Microsoft/AzureStorageExplorer#318] opened 2018-06-18 21:46 UTC
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: Unknown (I have not used this feature before)
Build Number: 20180605.1
Commit: f8373d5a

#### Steps to Reproduce: ####
1. Set up a storage account blob container with at least one Access Policy.
2. Right click on the container => 'Set Public Access Level...'.
3. Select 'Public read access for blobs'.
   * The issue also reproduces with 'Public read access for containers and blobs'.
4. Click OK.

#### Expected Experience: ####
The Public Access Level is set to Private with no other changes to the container.

#### Actual Experience: ####
The Public Access Level is set to Private, **and all container Access Policies are deleted**.
 * This is a destructive change.
 * There is no indication in the UI that this change will happen.
 * In the Azure Portal, you can set Private Public Access Level without affecting Access Policies, suggesting the change is incorrect (even if the UI did tell me about it).

This is basically the inverse of https://github.com/Microsoft/AzureStorageExplorer/issues/317. It seems like there's an underlying assumption that only Private containers can have Access Policies, which is not true.

**Comment by craxal** [comment] 2018-06-19 16:04
Duplicate of #197.

**Closed by craxal** 2018-06-19 16:04 UTC
