### ISSUE TITLE
Quick access stuck in "loading" state when Azure resources have been moved to a different subscription

### ISSUE THREAD

**Issue by thomaslevesque** [microsoft/AzureStorageExplorer#1327] opened 2019-04-23 11:07 UTC
**Storage Explorer Version**: 1.7.0
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: N/A

**Bug description**
I had some resources (CosmosDB collections) in Quick Access. I moved them to a different subscription, and now Quick Access shows "Loading..." forever.

**Steps to Reproduce**
1. Create a Cosmos DB collection
2. Add it to Quick Access in Storage Explorer
3. Move the Cosmos DB account to a different subscription
4. Restart Storage Explorer

**Expected Experience**
Quick Access should either show the collection (if it can still find it), or remove it from Quick Access automatically.

**Actual Experience**
Quick Access is stuck in "Loading... " state:

![image](https://user-images.githubusercontent.com/1864281/56576479-cb4a0080-65c8-11e9-8ced-20d14c0c03db.png)

**Comment by syagev** [comment] 2019-05-19 11:02
I'm experiencing this also (I think my resources were deleted rather than moved). Is there anyway I can reset this manually somehow? Maybe just go where Storage Explorer saves the list of resources and just delete them. It's just very annoying since I really need a short list of favorite items for quick access but since it's stuck the Quick Access list is completely unusable.

**Comment by MRayermannMSFT** [comment] 2019-05-30 17:55
@syagev, was your resource cosmosdb related or storage related?

**Comment by MRayermannMSFT** [comment] 2019-05-30 18:22
Also, @syagev  and @thomaslevesque, can you tell me exactly what resource type you think is causing an issue? I've tried with a variety of types, and so far all of them have resulted in broken quick access items, which is the intended behavior.

**Comment by syagev** [comment] 2019-05-30 20:18
For me it was a Storage Account. Still experiencing this with version 1.8.1

**Comment by thomaslevesque** [comment] 2019-05-31 10:43
> Also, @syagev and @thomaslevesque, can you tell me exactly what resource type you think is causing an issue?

I had a few Cosmos DB collections, and maybe storage accounts too. I don't know which caused the issue. All I know is that I moved all these resources to a different subscription.

**Comment by MRayermannMSFT** [comment] 2019-06-03 21:45
Ok, I still can't repro this, even after moving resources. So let me do two things:

1. I'll add Quick Access to the reset dialog (Help -> Rest)
2. Give you instructions on how to get out of things until 1.9 ships

Ok instructions:
1. Open dev tools (f12)
2. Go to the application tab
3. Go to Local Storage -> file://
4. Look for the row with key `StorageExplorer_InPlaceQuickAccessItems_v1`
5. Delete the value of that row
![image](https://user-images.githubusercontent.com/21112697/58836683-47932300-860e-11e9-8219-614042ff9f8a.png)

**Comment by syagev** [comment] 2019-06-04 07:52
Thanks @MRayermannMSFT! This resolved the issue for me.

**Comment by thomaslevesque** [comment] 2019-06-04 07:52
That worked for me too. Thanks @MRayermannMSFT !

**Comment by MRayermannMSFT** [comment] 2019-06-04 16:05
Awesome. The reset dialog thing will do the equivalent of the instructions I just gave you. I'll keep trying to repro the issue though if I have time, since ideally you don't have to reset.

**Comment by MRayermannMSFT** [comment] 2019-06-05 18:30
Still can't repro, but I've finished adding QA to the reset dialog. Closing for now.

**Closed by MRayermannMSFT** 2019-06-05 18:30 UTC
