### ISSUE TITLE
The loading icon always shows if soft deleting one rehydrate ADLS Gen2 blob then switching context

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7589] opened 2023-12-14 09:57 UTC
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231214.4
**Branch**: main
**Platform/OS**: Windows 10/MacOS Sonoma 14.1.2 (Apple M1 Pro)
**Architecture**: x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Change the blob access tier to 'Archive' -> Then change the archive blob access tier to 'Hot'.
4. Soft delete the rehydrate blob -> Switch the context view to 'Active and soft deleted blobs'.
5. Check whether there is no loading icon in the editor.

## Expected Experience ##
There is no loading icon in the editor.

## Actual Experience ##
There is a loading icon in the editor.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/88fcd369-1fa6-4d41-9012-647360993b2c)

## Additional Context ##
1. Here is the log collected on Windows:
[2023-12-13_221758.zip](https://github.com/microsoft/AzureStorageExplorer/files/13671250/2023-12-13_221758.zip)
2. On Linux, there is no loading icon in the editor. but no items show under the context view 'Active and soft deleted blobs/Deleted only'.

**Comment by craxal** [comment] 2023-12-14 17:31
@JasonYeMSFT Can you find out if there's an easy fix? Seems odd rehydration would freeze up other processes.

**Comment by JasonYeMSFT** [comment] 2023-12-14 18:04
This is a duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/6870.

**Closed** 2023-12-14 18:05 UTC
Labels: :white_check_mark: duplicate, 🧪 testing, :gear: adls gen2
