### ISSUE TITLE
[Severe] Delete key while editing an Azure Tables query invoke the delete row function!

### ISSUE THREAD

**Issue by JCKodel** [microsoft/AzureStorageExplorer#2699] opened 2020-03-09 04:01 UTC
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64

## Bug Description ##

Every time I hit [Del] to delete a char from the Azure Table Query textbox, the Storage Explorer asks me if I'm sure I want to delete the selected row.

## Steps to Reproduce ##
1. Open an Azure Table table with data.
2. Clique on Query
3. Focus on the Value textbox
4. Hit [Del] to delete a char

## Expected Experience ##
[Del] should only delete the character in the textbox.

## Actual Experience ##
The char is deleted, but the delete row function is invoked (so a confirmation dialog appears)

**Comment by MRayermannMSFT** [comment] 2020-03-09 17:38
Duplicate of #2631 , we're working on fixing this for our next release.

**Closed by MRayermannMSFT** 2020-03-09 17:38 UTC
