### ISSUE TITLE
Feature Request: Offer self-contained version of storage explorer

### ISSUE THREAD

**Issue by gsacavdm** [Microsoft/AzureStorageExplorer#339] opened 2018-06-23 13:47 UTC
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Linux (Ubuntu 18.04)

#### Feature Request: ####
Please offer a [self-contained version](https://docs.microsoft.com/dotnet/core/deploying/#self-contained-deployments-scd) of Storage Explorer that doesn't require a separate installation of .Net Core on my machine.

**Comment by MRayermannMSFT** [comment] 2018-06-25 15:53
Hey @gsacavdm , how would you feel about us offering a version distributed via [Snapcraft](https://snapcraft.io/)?

**Comment by gsacavdm** [comment] 2018-06-25 16:15
Sure, that works!

**Comment by MRayermannMSFT** [comment] 2018-06-25 16:21
Ok, good to hear! 😃 It is definitely something we want to do, and are now simply looking for the time to get it all setup. I'll leave this issue open to track that work. Until then, let us know if you have any issues getting .Net Core installed.

**Comment by craxal** [comment] 2018-08-16 15:56
Duplicate of #68.

**Closed by craxal** 2018-08-16 15:56 UTC
Labels: :computer: linux, feature request
