### ISSUE TITLE
Formatting of datetimes not according to settings.

### ISSUE THREAD

**Issue by Dennizzzzz** [microsoft/AzureStorageExplorer#4220] opened 2021-03-16 10:53 UTC
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210304.5
**Platform/OS**: windows 19
**Architecture**: x64
**Regression From**:  ?

## Bug Description ##
Regional settings do not apply to date times the right way.

## Expected Experience ##
Regional settings set to 'Nederlands' then the datetimes expected should be in the dutch format.
Also tested with 'use system language', i've set this to English, but changed the formatting of dates to 2021-03-16 and hours to 24-clock notation (11:49).

## Actual Experience ##
Blob container 'last modified' column shows date time in US format: M/d/yyyy, HH:mm:ss AM|PM. 
This does not comply with the regional settings for 'Dutch' and my 'system settings'.

## Additional Context ##
The formatting should be applied to all datetimes used anywhere in the storage explorer.

**Comment by MRayermannMSFT** [comment] 2021-03-22 18:24
Duplicate of #59

**Closed by MRayermannMSFT** 2021-03-22 18:24 UTC
