### ISSUE TITLE
No paging controll in Linux version

### ISSUE THREAD

**Issue by martynas-m** [microsoft/AzureStorageExplorer#4204] opened 2021-03-12 16:05 UTC
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210304.5
**Platform/OS**: arch linux
**Architecture**: x64
**Regression From**: not sure

## Bug Description ##
no paging control for queue view

## Steps to Reproduce ##
select queue with more messages than fits to page. try to go to next page. there is no paging control

## Expected Experience ##
to be able to get to next page

## Actual Experience ##
frustrating

![image](https://user-images.githubusercontent.com/14193395/110965870-54a18200-835d-11eb-826a-3aa92089c55b.png)

**Comment by MRayermannMSFT** [comment] 2021-03-15 17:43
@martynas-m sadly this is by design. The APIs available for queues only allows Storage Explorer to peek at the first 32 messages. If Storage Explorer tried to look at messages further in the queue, Storage Explorer would have to dequeue your messages. You can read more about the API here: https://docs.microsoft.com/en-us/rest/api/storageservices/peek-messages

We've asked the service to increase this limit before but that request has not yet been fulfilled. I'm going to close this as by design now.

**Closed by MRayermannMSFT** 2021-03-15 17:43 UTC
