### ISSUE TITLE
Search for a file by file name

### ISSUE THREAD

**Issue by cdowns63** [microsoft/AzureStorageExplorer#6342] opened 2022-12-06 21:07 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I'd like to be able to find a file by entering its file name (or a portion thereof) in a search box. Currently there is no search box for that in ASE.

### Desired Solution

A search box just above the file name list, where I could enter a portion of a file name and have it filter the file list to show matching items. Similar to what you find in any other file UI, like File Explorer or SharePoint.

### Alternatives and Workarounds

Currently all we can do is browse through pages of files. No workarounds that we know of.

### Additional Context

My team uses our ADLS Gen2 Azure AD blob to archive zipped files containing video projects. As our list of files grows, we’re seeing more of a need for file search, so we can locate specific files we’ve stored. Simply browsing through pages of files is becoming less and less practical.  We're surprised that file name search is not a feature already, but it’s possible we don’t understand how the product is intended to be used. It seems like a very basic need that people would want. Our contact Amit Puthenpura recommended we request the feature. Thanks.

**Comment by MRayermannMSFT** [comment] 2022-12-12 18:49
Duplicate of: https://github.com/microsoft/AzureStorageExplorer/issues/2189

**Closed by MRayermannMSFT** 2022-12-12 18:49 UTC
