### ISSUE TITLE
The currently selected tab is auto closed after pasting one service

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2815] opened 2020-04-09 08:43 UTC
**Storage Explorer Version:** 1.13.0
**Build:** [20200409.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3625874)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open one tab (like: Settings.)
2. Expand one normal storage account -> Blob Containers.
3. Select one blob container -> Copy and paste it.
4. Check the opened tabs.

**Expect Experience:**
The opened tabs show well.

**Actual Experience:**
The currently selected tab is closed.

**More Info:**
1. This issue also reproduces when pasting one blob container/ file share/ table.
2. This issue also reproduces when renaming one table.
3. This issue doesn't reproduce for clone action.
4. Related bug: [1954](https://github.com/microsoft/AzureStorageExplorer/issues/1954). (Reproduces on **1.12.0** & **1.11.1** & **1.11.0** & **1.10.1** & **1.10.0** & **1.9.0** release).

**Comment by JasonYeMSFT** [comment] 2021-09-27 21:01
Copied from #4961
The expected behavior should be

"When pasting/cloning a container, the source explorer stays opened (if already opened) and the a new explorer for the destination opens."

**Comment by JasonYeMSFT** [comment] 2022-01-13 23:02
Features that have the expected behavior:
- [x] Blob Container paste
- [x] Blob Container clone
- [x] File Share paste
- [x] File Share clone
- [x] Table paste
- [x] Table clone

There is no paste/clone for Queue. Closing since we have made all such features following the expected behavior.

**Closed by JasonYeMSFT** 2022-01-13 23:02 UTC
Labels: 🧪 testing

**Comment by v-xianya** [comment] 2022-01-17 06:27
Verified on the latest main build 20220114.3. Fixed.
