### ISSUE TITLE
Request: 64bit Windows builds

### ISSUE THREAD

**Issue by pilcherd** [microsoft/AzureStorageExplorer#5002] opened 2021-10-01 13:18 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

64bit Windows shows this as primary remaining 32bit app.

### Desired Solution

Run as 64bit application on 64bit Windows

### Additional Context

Clearly this is low priority, but I would expect x86/x64/ARM native operation on Windows.

**Comment by MRayermannMSFT** [comment] 2021-10-04 17:17
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/106

**Closed by MRayermannMSFT** 2021-10-04 17:17 UTC
