### ISSUE TITLE
Azure storage expoler cannot connect to azure storage account

### ISSUE THREAD

**Issue by AndyXie1989** [microsoft/AzureStorageExplorer#1776] opened 2019-09-04 11:19 UTC
Hi Team,

I'v met the follow issue。 If you have any idea, pls tell me. Thanks.

Error details:

{
  "name": "TypeError",
  "message": "Cannot read property 'version' of undefined",
  "__zone_symbol__error": {
    "originalStack": "Error: Cannot read property 'version' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
    "zoneAwareStack": "Error: Cannot read property 'version' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)"
  },
  "stack": "TypeError: Cannot read property 'version' of undefined\n    at Function.CustomConnections.connectionIsV1 (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/CustomConnections/CustomConnections.js:11:32)\n    at getCustomConnectionAttributes (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Common/AzureStorageUtilities.js:204:51)\n    at Object.getRawDataFromAccountCustomConnection (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Common/AzureStorageUtilities.js:128:25)\n    at AzureStorageProducer.<anonymous> (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:549:81)\n    at step (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Actions/AzureGeneralActions.js:34:23)\n    at Object.next (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Actions/AzureGeneralActions.js:15:53)\n    at file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Actions/AzureGeneralActions.js:9:71\n    at new Promise (<anonymous>)\n    at __awaiter (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Actions/AzureGeneralActions.js:5:12)\n    at file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:547:69",
  "originalStack": "Error: Cannot read property 'version' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
  "zoneAwareStack": "Error: Cannot read property 'version' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
  "__zone_symbol__stack": "TypeError: Cannot read property 'version' of undefined\n    at Function.CustomConnections.connectionIsV1 (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/CustomConnections/CustomConnections.js:11:32)\n    at getCustomConnectionAttributes (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Common/AzureStorageUtilities.js:204:51)\n    at Object.getRawDataFromAccountCustomConnection (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Common/AzureStorageUtilities.js:128:25)\n    at AzureStorageProducer.<anonymous> (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:549:81)\n    at step (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Actions/AzureGeneralActions.js:34:23)\n    at Object.next (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Actions/AzureGeneralActions.js:15:53)\n    at file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Actions/AzureGeneralActions.js:9:71\n    at new Promise (<anonymous>)\n    at __awaiter (file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Actions/AzureGeneralActions.js:5:12)\n    at file:///D:/software/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:547:69",
  "__zone_symbol__name": "TypeError",
  "__zone_symbol__message": "Cannot read property 'version' of undefined",
  "__zone_symbol__originalStack": "Error: Cannot read property 'version' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
  "__zone_symbol__zoneAwareStack": "Error: Cannot read property 'version' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (D:\\software\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)"
}

**Comment by JasonYeMSFT** [comment] 2019-09-04 16:27
Hi @AndyXie1989 , 

We have recevied similar customer issues but unfortunately we still cannot fully understand why this would happen. I believe you are using connection string, right? The error is complaining about a certain property missing from your connection string, which should not happen if it's generated and passed to us correctly.

Are you getting this connection string inside Storage Explorer (e.g. through our 'Generate Shared Access Signature') or from other places? If it is generated from other places such as Azure Portal, could you please show us the steps to generate it? If you can assert that the connection string is corrupted when getting passed to our application, please share your findings so we can investigate.

Thanks,
Relate to #1626.

**Comment by JasonYeMSFT** [comment] 2019-09-04 22:16
I am going to close this issue since it is a duplicate of an existing issue. If you have any information to share, please post it in the referenced issue.

Thanks.

**Closed by JasonYeMSFT** 2019-09-04 22:16 UTC

**Comment by AndyXie1989** [comment] 2019-09-05 02:50
Dear support,

Thank you for contacting me.

In fact, I’v tried every methods which can access the storage account via azure storage explorer. Such as add azure account, connection string, SAS URL and account name & key.

My issue is a little complicated.
I can find some storage accounts via using add azure account but not every storage account. I’v verified that.


  1.  For storage accounts I can see by using azure account, I cannot access them via other ways(SAS URL, connections string and account name&key).
  2.  For storage accounts I cannot see by using azure account, I cannot access them via SAS URL, connections string and account name&key.
And all the error details are the same.

At the same time, I think this issue maybe related to my PC. I can access every storage accounts on another PC with the same version of azure storage explorer. So the only concern for this issue is if there is any cache of azure storage explorer software? Because I have uninstall the software and restart my PC but no luck.

Thank you very much for your support.

Br,
Andy Xie

**Comment by XuzhouHuang** [comment] 2019-09-05 03:31
> I am going to close this issue since it is a duplicate of an existing issue. If you have any information to share, please post it in the referenced issue.
> 
> Thanks.

Hi Jason, 

This is Xuzhou from CSS Mooncake support team. We also receive similar ticket regarding this issue. Could you ping at Teams to sync background? My alias is xuhuan.
