### ISSUE TITLE
Content Type not matching file type

### ISSUE THREAD

**Issue by mercurjl** [microsoft/AzureStorageExplorer#2768] opened 2020-03-30 14:54 UTC
**Storage Explorer Version**: 1.12
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: Not sure

## Bug Description ##
When copying a file from file explorer to Azure Storage Explorer, the content type is always `application/octet-stream`. I've tried this with both a `.js` and `.json` file.

## Steps to Reproduce ##
1. Make a `test.js` and a `test.json` file
2. Copy those files into a `Blob container`
3. See that the content type is `application/octet-stream` and does not match the actual file type

## Expected Experience ##
I expect the content type to be derived from the type of file or file extension of what's being copied over, not `application/octet-stream`

## Actual Experience ##
When copying files over it always uses `application/octet-stream`

## Additional Context ##
One odd thing I noticed is that on my mac, this does not happen and it correctly attributes the content type to a file. Here are the specs for that machine:
**Storage Explorer Version**: 1.4.2
**Build Number**: 20180917.1
**Platform/OS**: MacOS Catalina 10.15.4
**Architecture**: x64

**Comment by MRayermannMSFT** [comment] 2020-03-30 17:41
Duplicate of #2267

**Closed by MRayermannMSFT** 2020-03-30 17:41 UTC
