### ISSUE TITLE
Set the default blob type as 'Page Blob' in Upload dialog for premium accounts

### ISSUE THREAD

**Issue by v-haiz** [microsoft/AzureStorageExplorer#701] opened 2018-09-26 09:42 UTC
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180926.5
**Commit**: d6717c99
**Regression From**: Not a regression

**Steps to Reproduce**:
1. Drill down one **premium storage account**.
2. Open one blob container then open Upload dialog.
3. Check the default Blob type in Upload dialog.   

**Suggestion**:
Set the default Blob type as Page blob. It is convenient when uploading a page blob with **non .vhd/vhdx file**.

**Actual Experience**:
The default Blob type is Block blob .

**Comment by MRayermannMSFT** [comment] 2018-10-02 16:49
AzCopy doesn't support uploading non .vhd files as page blobs. So that's why the transfer failed. I've requested that this be supported: Azure/azure-storage-azcopy#69

**Comment by MRayermannMSFT** [comment] 2020-02-03 19:26
Duplicate of #703

**Closed by MRayermannMSFT** 2020-02-03 19:26 UTC
Labels: :gear: azcopy, :grey_question: external, 🧪 testing
