### ISSUE TITLE
No error displays when typing empty Metadata values in blob container 'Properties' dialog 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3258] opened 2020-07-17 09:07 UTC
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200717.1
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Click 'Properties...' -> Add Metadate -> Type an empty metedata value.
3. Check the result.

**Expect Experience:**
Display an error.
![image](https://user-images.githubusercontent.com/54055206/87765357-45a81580-c84a-11ea-9222-856bc30b343b.png)

**Actual Experience:**
No error displays.
![image](https://user-images.githubusercontent.com/54055206/87765673-ac2d3380-c84a-11ea-8fbd-8ebe169e2426.png)

**More Info:**
This issue also reproduces for one blob.

**Comment by MRayermannMSFT** [comment] 2020-08-04 18:34
@v-limu turns out blank is fine! If you try to save metadata with blank values, it works, and when looking again, the blank values are still there.  I'm going to close this as by design.

**Closed by MRayermannMSFT** 2020-08-04 18:34 UTC
Labels: :gear: blobs, 🧪 testing

**Comment by v-limu** [comment] 2020-08-05 01:57
Hi @MRayermannMSFT 

An error displays and save button is disabled when typing blank values in file properties dialog for **one file share.** Is it different from the blob containers?
![image](https://user-images.githubusercontent.com/54055206/89362790-50dfba00-d701-11ea-9362-2d95e34898a4.png)

**Comment by MRayermannMSFT** [comment] 2020-08-14 23:14
@v-limu can you open up a new bug for me to track for investigating if we should also allow blank metadata for file shares? Thanks!

**Comment by v-limu** [comment] 2020-08-17 10:09
Hi @MRayermannMSFT 😃 I has logged a new bug for the file share: [3408](https://github.com/microsoft/AzureStorageExplorer/issues/3408)
