### ISSUE TITLE
Display a failed activity log with the error "TypeError:Cannot read property 'uids' of undefined" when attaching one table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4399] opened 2021-04-28 09:27 UTC
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210428.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release (1.19.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Select one table -> Attach the table with full permissions.
3. Check whether display a successfully activity log.

## Expected Experience ##
Display a successfully activity log.

## Actual Experience ##
Display a failed activity log with the error "TypeError:Cannot read property 'uids' of undefined".
![image](https://user-images.githubusercontent.com/41351993/116377409-01c54200-a7c6-11eb-9f5e-4abbf6d60660.png)

**Comment by JasonYeMSFT** [comment] 2021-05-03 20:42
I tried the latest build and this doesn't reproduce there. Could you please try reproduce this in the latest build with the following setup and bring us the information?

- "Refresh all" in the tree view to bring it back to its initial state.
- Open connect dialog and complete the attaching.
- After seeing this error, record the state of the tree view (what nodes are expanded; under the expanded node, what are their children nodes). It would be perfect if you can provide a screenshot of the whole tree view at the moment.

Reason I ask was that Matthew fixed a very similar bug in 1.19.0 and it was caused by the tree not loading the attached node group which results in an undefined node to access `uids`. I'd like to see if this error is also caused by that.

**Comment by v-xianya** [comment] 2021-05-06 06:32
@JasonYeMSFT 
This issue can't be reproduced on the latest build 20210506.3.

**Comment by JasonYeMSFT** [comment] 2021-05-06 22:44
Gotcha. I wasn't 100% sure but it might be due to some of the tree view bugs Craig made at that point. I'll close this issue for now unless it reproduces.

**Closed by JasonYeMSFT** 2021-05-06 22:44 UTC
Labels: :beetle: regression, 🧪 testing
