### ISSUE TITLE
Localise DateTime format.

### ISSUE THREAD

**Issue by deangoddard** [Microsoft/AzureStorageExplorer#680] opened 2018-09-19 11:12 UTC
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Win10
**Architecture**: ia32
**Regression From**: (first time I've downloaded and used ASE

A quick and easy feature fix here: Can you please use the current local date/time format when displaying date/times?  Love the US but I live in Australia and we prefer dd/MM/yyyy.  Thanks :)

![image](https://user-images.githubusercontent.com/12726531/45749949-a10a1c00-bc50-11e8-84f9-10ecba846a63.png)

**Comment by craxal** [comment] 2018-09-19 17:12
@deangoddard, frankly, as an American, I think you've got the better format! 😄

Duplicate of #59.

**Closed by craxal** 2018-09-19 17:12 UTC
Labels: :white_check_mark: duplicate

**Comment by vicentemangas** [comment] 2019-05-17 09:09
Could it be just an option in which you can select the format data? cheers.
