### ISSUE TITLE
It takes about 16 seconds for one new created IOT blob container tab auto opens

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6416] opened 2023-01-06 08:26 UTC
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20230106.1
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Connect to a blob storage module on edge using the connection string.
3. Switch to the attached storage account -> Blob Containers.
4. Create a blob container.
5. Check whether the tab opens without delay.

## Expected Experience ##
The tab opens without delay.

## Actual Experience ##
It takes about 16 seconds to open the tab.
## Additional Context ##
Here is the record:
![0106](https://user-images.githubusercontent.com/41351993/210954428-895f9601-85ef-4e72-a135-a0aea5701778.gif)

**Comment by JasonYeMSFT** [comment] 2023-01-06 17:38
Could you try enabling targeting Azure Stack API and see if the delay goes away? I remember there is an API which will cause internal server error in the blob IoT module.

**Comment by v-xianya** [comment] 2023-01-09 01:38
@JasonYeMSFT Could help to share where to enable targeting Azure Stack API?

**Comment by JasonYeMSFT** [comment] 2023-01-09 17:29
You can find it under App Menu > Edit > Target Azure Stack API.

**Comment by v-xianya** [comment] 2023-01-10 07:47
@JasonYeMSFT After using 'Target Azure Stack API', below error occurs when trying to expand 'Storage Accounts' node under 'Emulator & Attached'.
![image](https://user-images.githubusercontent.com/41351993/211490969-68b42c22-9882-46a9-8d7d-5a481f9986a5.png)

**Comment by v-xianya** [comment] 2023-01-20 04:00
@JasonYeMSFT Verified this issue on the hotfix build 20230118.5.
Afte using 'Target Azure Stack API', no error occurs, and the delay goes away.

**Comment by JasonYeMSFT** [comment] 2023-01-23 19:00
We are going to won't fix this issue since it's root cause is out of our control. The IoT module only supports service version up to 2017-04-17 so the user is expected to turn on that flag.

**Closed by JasonYeMSFT** 2023-01-23 19:00 UTC
Labels: :heavy_check_mark: won't fix, 🧪 testing, :gear: blobs
