### ISSUE TITLE
Enhancement: Get directory listing

### ISSUE THREAD

**Issue by ishepherd** [microsoft/AzureStorageExplorer#545] opened 2018-08-06 04:35 UTC
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: 

My blob names are all in a regular format of `field1|field2|` etc. I want to pull out a part of each blob name and see what values exist.

I can happily use Unix text utils (`cut`, etc.) for this kind of task but to start with I need a directory listing of all the blobs. _Edit_ All pages - Just keep loading the blob list until complete (or I cancel it), dump it to some text file.

**Comment by craxal** [comment] 2018-08-06 15:59
When you say "directory listing", you mean you want the entire list of blobs in the container, or just with a certain prefix?

**Comment by ishepherd** [comment] 2018-08-07 00:45
@craxal For this use case I needed the whole blob container (or, empty prefix)

**Comment by ishepherd** [comment] 2019-04-02 07:08
Still wishing for this.

Basically I would like a way to turn off the pseudo-directory view, just see the blob container as it is: a list of all blobs, which I can enter a prefix to filter.

I could hit "Load 1000 more" a few times to get the whole lot, and then sort by size descending. (Today's use case was to find the largest blob in the container).

**Comment by craxal** [comment] 2019-04-05 18:03
This sounds ideal for a setting, because most users are accustomed to the hierarchical view. In addition, ADLS Gen 2 adds hierarchical namespaces to blobs, making directories a real thing. A setting would allow you to easily switch off the hierarchical view for a flat list of your blobs.

**Comment by MRayermannMSFT** [comment] 2021-02-08 20:04
Duplicate of #19

**Closed by MRayermannMSFT** 2021-02-08 20:04 UTC
Labels: :bulb: feature request, :bulb: setting candidate, :gear: blobs
