### ISSUE TITLE
Storage Explorer appears blank and cannot connect to subscription

### ISSUE THREAD

**Issue by omkarsogeti** [microsoft/AzureStorageExplorer#4818] opened 2021-08-18 17:07 UTC
<img width="954" alt="storageexp" src="https://user-images.githubusercontent.com/82447727/129941645-8fc268f9-f5bf-4148-a251-724a58f8f7dd.PNG">

**Comment by MRayermannMSFT** [comment] 2021-08-23 17:23
Maybe a duplicate of #4768 ? @omkarsogeti can you please try installing these two private builds:

- https://storageexplorerpublish.blob.core.windows.net/privatebuilds/4768-dev-builds/StorageExplorer-ia32-41178ff2.exe
- https://storageexplorerpublish.blob.core.windows.net/privatebuilds/4768-dev-builds/StorageExplorer-ia32-bcce041d.exe

And tell me if your issue repros on either of them? Thanks!

**Comment by omkarsogeti** [comment] 2021-08-24 08:53
Hi,

Thank you for your email.

Today my Azure Data Storage is working properly as expected and I am able to see the subscriptions on the left side.

If next time it disappears, I will try the below solution suggested by you. Thank you for your response and I really appreciate it.

Thanks,

Best Regards
Omkar Omble
Email : ***@***.******@***.***> | Cell: +353 894454232
Sogeti | Capgemini | Dublin | Ireland
***@***.***

**Comment by MRayermannMSFT** [comment] 2021-08-25 00:32
@omkarsogeti if you see this again, please take a look at #4768 and do whatever my latest comment says to do.

**Closed by MRayermannMSFT** 2021-08-25 00:32 UTC
Labels: :grey_question: investigate
