### ISSUE TITLE
There is an error message on the 'Break Lease' dialog for blobs/folders

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6577] opened 2023-02-17 09:07 UTC
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230217.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.27.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Acquire lease for the blob.
4. Right click the leased blob -> Click 'Break Lease...'.
5. Check there is no error message on the 'Break Lease' dialog.

## Expected Experience ##
There is no error message on the 'Break Lease' dialog.
![image](https://user-images.githubusercontent.com/41351993/219600739-d93e5c5e-94af-4528-a2eb-f6114bfff4e3.png)

## Actual Experience ##
There is an error message on the 'Break Lease' dialog.
![image](https://user-images.githubusercontent.com/41351993/219592818-4ddea75e-30de-4819-b259-b1005b19bd63.png)

## Additional Context ##
Refer to the bug: [6209](https://github.com/microsoft/AzureStorageExplorer/issues/6209)

**Comment by MRayermannMSFT** [comment] 2023-02-17 16:44
Hi @v-xianya, I believe we have recently been trying to avoid showing a user an error message when they haven't entered any input in situations like this. @craxal please confirm if this was the case for this dialog.

**Comment by craxal** [comment] 2023-03-22 23:49
@MRayermannMSFT Hiding the initial error is opt-in behavior. You have to add the `hideInitialValidationError` property to the config.

**Comment by v-xianya** [comment] 2023-03-24 01:31
Hi @craxal Verified this issue on the build main 20230324.1.
1. This issue has been fixed for regular blobs.
2. This issue reproduces for ADLS Gen2 blobs.

**Comment by craxal** [comment] 2023-03-24 15:57
@v-xianya A fix has been merged, but we are still verifying, because we have to update packages. We will close the bug once work is finished, and then you can verify as well.

**Comment by craxal** [comment] 2023-03-24 16:02
I am not able to reproduce with ADLS Gen2 using the current state of the main branch, so you probably got a build that didn't get the necessary changes. Try verifying with a newer build.

**Closed** 2023-03-24 16:02 UTC
Labels: :heavy_check_mark: merged, 🧪 testing, :beetle: regression

**Comment by v-xianya** [comment] 2023-03-27 02:55
Verified this issue on the main 20230327.1. Fixed for ADLS Gen2 blobs.
