### ISSUE TITLE
Fail to display the new added blob container under 'Quick Access' node when there is an existing table/file share/queue with same name

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/AzureStorageExplorer#567] opened 2018-08-09 10:16 UTC
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180808.1
**Commit**: 93925d3c
**Regression From**: Previous release 1.3.1(20180711.1)

**Steps to Reproduce**:
1. Expand storage accounts -> Add a file share/queue/table to Quick Access -> Add a blob container with same name again.
2. Check whether the blob container displays well under 'Quick Access' or not.  

**Expected Experience**:
The new added blob container displays well under 'Quick Access' node.

**Actual Experience**:
1. Fail to display the new added blob container under 'Quick Access' node. But the second added service will display well after removing the first service from Quick Access.
2. This issue also reproduces when adding a blob container to 'Quick Access' from different storage accounts.

**Comment by MRayermannMSFT** [comment] 2018-08-09 22:55
Duplicate of #189

**Closed by MRayermannMSFT** 2018-08-09 22:55 UTC
Labels: :gear: quick access, testing
