### ISSUE TITLE
The order of the pasted message text is inconsistent with the sorted messages

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7969] opened 2024-05-30 07:48 UTC
**Storage Explorer Version:** 1.35.0-dev (98)
**Build Number:** 20240530.2
**Branch:** main
**Platform/OS:** Windows 11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture:** arm64/x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.34.0)

## Steps to Reproduce ##

1. Expand one storage account -> Queues.
2. Open one queue which contains messages.
3. Sort messages by one column.
4. Click 'Select All' -> Right click messages -> Click 'Copy Message Text'.
5. Paste the message text to notepad.
6. Check whether the order of pasted message text is consistent with the sorted messages.

## Expected Experience ##
The order of pasted message text is consistent with the sorted messages.

## Actual Experience ##
The order of pasted message text is inconsistent with the sorted messages.

## Additional Context ##

1. This issue also reproduces for blobs when executing 'Copy URL/Path'.
2. This issue doesn't reproduce for files/entities.
3. Related issue: [7620](https://github.com/microsoft/AzureStorageExplorer/issues/7620).

**Comment by craxal** [comment] 2024-05-30 17:21
Duplicate of #7620

**Closed** 2024-05-30 17:22 UTC
Labels: :white_check_mark: duplicate, 🧪 testing, :gear: blobs, :gear: queues, :beetle: regression
