### ISSUE TITLE
Query tab is blank in Cosmos Db

### ISSUE THREAD

**Issue by snerting** [Microsoft/AzureStorageExplorer#1002] opened 2018-12-12 18:47 UTC
**Storage Explorer Version**: 1.6
**Platform/OS**: Windows 
**Architecture**: ia32
**Regression From**: Before desember update

**Bug description**
When I click on the document on an Cosmos Db collection, a new tab is opened, but the problem is that I can't se any documents, or any place to write the query. The same is happening if I open a New Query Tab. 
Tab is opened, but's it's content is blank. (Yes, I know it's document there, because I can see them in Data Explorer in the portal)

Have testet it on Cosmos Db (SQL api) and Graph Api. The same problem on both. 

This has worked great in previous versjon. Only different from then to now is 2 things. I have upgraded my Windows to 1809, and Microsoft Azure Storage Explorer has just been upgraded.

When I go on a Blob storage, everything work as expected.

No place to write my Query or browse the documents:
![blank query tab](https://user-images.githubusercontent.com/1882879/49891150-1d725c80-fe46-11e8-8acb-ada8895d93bf.jpg)

**Comment by jinglouMSFT** [comment] 2018-12-12 19:02
Duplicate of #971. There is a temp. workaround there. Also this will be fixed in the next hotfix release next week.

**Closed by jinglouMSFT** 2018-12-12 19:02 UTC
