### ISSUE TITLE
Fail to paste one empty emulator blob container to one storage account

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5529] opened 2022-03-16 09:29 UTC
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220316.1
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**Azurite Version:** 3.15.0
**How Found:** From running test cases
**Regression From:** Previous release (1.23.0)

## Steps to Reproduce ##

1. Install and run Azurite 3.15.0 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)' -> Blob Containers.
3. Create one blob container -> Right click the blob container -> Click "Copy Blob Container'.
4. Expand one storage account.
5. Right click Blob Containers node -> Click 'Paste Blob Container'.
6. Check whether succeeds to paste the blob container.

## Expected Experience ##
Succeed to paste the blob container.
![image](https://user-images.githubusercontent.com/87792676/158554971-0316a9ea-83ff-4d9e-b6c7-cb52b968788e.png)

# Actual Experience ##
Fail to paste the blob container.
![image](https://user-images.githubusercontent.com/87792676/158555471-3a7b9929-1efb-4b0f-8990-65ed6207bef3.png)

## Additional Context ##
This issue doesn't reproduce for tables.

**Comment by JasonYeMSFT** [comment] 2022-03-17 23:10
I tried it on my machine with Azurite 3.15.0 and the most recent 1.24.0 dev build and it doesn't reproduce. Could you try to get a fiddler trace for the failed creation request?

**Comment by v-kellyluo** [comment] 2022-03-18 07:19
@JasonYeMSFT , this issue still reproduces on the lasted build, but I have no way to get the fiddler trace.
Here is the record:
![test](https://user-images.githubusercontent.com/87792676/158954215-bb0f9595-4b98-48dc-8e23-1ba7f2411396.gif)

**Comment by JasonYeMSFT** [comment] 2022-03-18 21:32
I found the cause of it. The problem is that Azurite doesn't recognize the new API version 2021-04-10, which is the default API version of the new SDK package. Given that this scenario is not common, I am going to close this issue. If any major scenarios of the Emulator is broken in the same way, we will add some special logic to fallback to a lower API version for Emulator.

Checked normal Emulator scenarios. We detect if the target resource is from an emulator by its default key credentials and override the api version if so. Since the copy src only has SAS credential, it cannot be detected and won't work. This seems to only impact copy and I think we can close this one for now.

**Closed by JasonYeMSFT** 2022-03-18 21:32 UTC
Labels: 🧪 testing, :gear: blobs, :beetle: regression, :gear: emulator, :grey_question: investigate
