### ISSUE TITLE
Cannot copy, paste, clone containers, folders nor files when working with the local emulator

### ISSUE THREAD

**Issue by noontz** [microsoft/AzureStorageExplorer#7830] opened 2024-03-21 09:44 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.0 (97)

### Architecture

x64

### Storage Explorer Build Number

20240301.4

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Clone, Copy and Paste features are disabled on local accounts?

On Azure:

![image](https://github.com/microsoft/AzureStorageExplorer/assets/7408674/2388783a-73db-4f2f-8c89-0bfc948f0385)

Local: 

![image](https://github.com/microsoft/AzureStorageExplorer/assets/7408674/6a75fdfa-42a2-4bdc-9265-7c18c6290291)

![image](https://github.com/microsoft/AzureStorageExplorer/assets/7408674/835ac2fe-adb5-4e72-a192-f9e1cee734ce)

### Steps to Reproduce

Self explanatory ;)

### Actual Experience

Cannot copy, paste, clone containers, folders nor files when working with the local emulator

### Expected Experience

Be able to copy, paste, clone containers, folders and files when working with the local emulator

**Comment by craxal** [comment] 2024-03-21 21:38
This is by design. Storage Explorer uses AzCopy to copy/paste/clone. AzCopy uses Azure APIs that local emulators do not support. That's why copy/paste/clone is unavailable when viewing local emulator containers.

If you want to copy/paste objects from/to a local emulator, you should upload/download the files to your local machine first, then transfer them to the intended destination.

**Comment by noontz** [comment] 2024-03-22 07:22
@craxal Thx for your feedback. This is problematic when using a local test environment to emulate the cloud accounts. I will raise an issue on the Azurite repo and link to this one.  Cheers

**Comment by MRayermannMSFT** [comment] 2024-03-29 23:00
@noontz we're going to go ahead and close this as by design. If Azurite upates to support the APIs needed for AzCopy S2S blob copy, feel free to open a new issue asking for Storage Explorer to support it. :)

**Closed by MRayermannMSFT** 2024-03-29 23:00 UTC
Labels: :grey_question: external, :white_check_mark: by design
