### ISSUE TITLE
The icon of MongoDB/DocumentDB Account is incorrect

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/AzureStorageExplorer#639] opened 2018-09-07 09:01 UTC
**Storage Explorer Version:** 1.5.0
**Platform/OS Version:** Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture:** ia32
**Build Number**:20180905.3
**Commit:** 66ac14b9
**Regression From**: Previous release 1.4.1(20180822.1)

**Steps to Reproduce:**
1. Apply one subscription -> Drill down **Cosmos DB Accounts**.
2. Check the icon of MongoDB/DocumentDB Account.

**Expected Experience:**
The icon of MongoDB/DocumentDB Account is correct.

**Actual Experience:**
1.The icon of MongoDB/DocumentDB Account is incorrect.
2. The **icon of database** is also incorrect under all Cosmos DB Accounts.
![wrongicon](https://user-images.githubusercontent.com/37653604/45210196-6d0d1f00-b27e-11e8-936c-21459ba91706.png)

**Comment by craxal** [comment] 2018-09-07 16:40
By design. The icons better reflect what the portal has. Unless @djlan disagrees, I'm going to close this.

**Closed by craxal** 2018-09-07 16:40 UTC
Labels: :gear: cosmosdb, testing
