### ISSUE TITLE
Add --preserve-smb-permissions option to Azure Storage Explorer?

### ISSUE THREAD

**Issue by GreeneISDave** [microsoft/AzureStorageExplorer#6566] opened 2023-02-15 20:56 UTC
We were recently using MASE to copy FSLogix profiles from one storage account to another in a different region.
However, every time we copied the files, we received an error message about permissions not being correct when users connected to their AVD session.

I was able to find [THIS](https://ramprasadtech.com/fslogix-user-profile-migration-azure-files-within-a-azure-region/) blog post that mentioned the **--preserve-smb-permissions=true** parameter.

It looks like there is a setting in Microsoft Azure Storage Explorer for the **Preserve SMB Information** feature, but not the **Preserve SMB Permissions**..
![image](https://user-images.githubusercontent.com/97751494/219156049-a35adbe8-de4b-4252-8c0b-2c4051ff30b8.png)

It would be helpful to have **preserve-smb-permissions** as an available setting in MASE.

**Comment by MRayermannMSFT** [comment] 2023-02-27 22:50
Dupe of https://github.com/microsoft/AzureStorageExplorer/issues/4898

**Closed by MRayermannMSFT** 2023-02-27 22:50 UTC
Labels: :bulb: feature request, :gear: azcopy
