### ISSUE TITLE
Can't copy blob directory path from the address bar at the top

### ISSUE THREAD

**Issue by amithegde** [Microsoft/AzureStorageExplorer#136] opened 2018-05-03 17:15 UTC
[Window Title]
Microsoft Azure Storage Explorer

[Main Instruction]
Microsoft Azure Storage Explorer

[Content]
Version: 1.0.0

Platform: Windows
Architecture: ia32
Build Number: 20180415.2
Commit: 5d603052
Support Id: 0233cf6b-5aa5-46c6-317d-93ee42da9f98

Copyright © 2018 Microsoft. All rights reserved.

[OK]

#### Steps to Reproduce: ####

1. Open a container which has blobs with a directory strucutre
2. Drill down into the directory structure
3. Click on the textbox which shows the directory structure (left to "search by prefix" textbox)

#### Expected Experience: ####
Should be able to edit it, paste in new path and the explorer should navigate to the pasted in path if it is valid

#### Actual Experience: ####
Click it and like magic, nothing happens!

**Comment by JakeRadMSFT** [comment] 2018-05-03 17:28
Duplicate of #45. I'll add expected experience to #45.

**Closed by JakeRadMSFT** 2018-05-03 17:28 UTC
