### ISSUE TITLE
A11y_Azure Tools Storage Explorer_ Toolbar_ Toolbar controls_Keyboard: Tooltip is not accessible by keyboard tab keys for "Toolbar" but when we hoverover using mouse it’s accessible

### ISSUE THREAD

**Issue by Jtith** [microsoft/AzureStorageExplorer#6336] opened 2022-12-06 08:48 UTC
**GitHub Tags:**
#A11yMAS; #A11yTCS; #Win11; #DesktopApp; #A11ySev2; #BM_AzureToolsStorageExplorer_Win32_Dec2022; #Azure Tools Storage Explorer; #FTP; #WCAG2.1.1; #Keyboard;

## Environment Details:
Application: Microsoft Azure Storage Explore
version: 1.27.0

## OS Details
Microsoft Windows 11 Enterprise
version 22H2 OS Build 22621.819

## Repro Steps:

1. Launch Storage Explorer
2. Tab to "Open Connect dialog" pane and Sign into Azure.
3. Tab to "Manage Accounts" pane and select the subscriptions you will use. Once selected, click on the “Apply" button.
4. Tab to "Blob Containers" of the selected subscription, right click and hit enter on "Create Blob container" to Create a new Blob container.
5. Once completed, Tab to blob container "Toolbar" section 
6. and you will observe whether the tooltips are provided by navigating through keyboard tab keys.

## Actual results:
Tooltip is not accessible by keyboard tab keys for "Toolbar" but when we hoverover using mouse it’s accessible.
## Expected results:
Tooltips should be visible and accessible on navigating using keyboard tab key.
## User Impact:
Keyboard users may not get the information of the Toolbar button which are having tooltips but not accessible.

## Attachments:

https://user-images.githubusercontent.com/100552367/205863522-e02eaa06-d5c4-4270-badf-2fa3ea2f22ae.mp4

**Comment by MRayermannMSFT** [comment] 2022-12-15 18:36
We should take this to office hours to downgrade to a sev 3/close as duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/4987

**Comment by Jtith** [comment] 2022-12-16 11:27
Closing as it's a duplicate https://github.com/microsoft/AzureStorageExplorer/issues/4987

**Closed** 2022-12-16 11:45 UTC
Labels: :wheelchair: accessibility, :wheelchair: MAS, :wheelchair: WCAG, ♿ sev1/2

**Comment by tripathiakhil429** [comment] 2023-02-24 12:28
**Github Tags:**#Closed
