### ISSUE TITLE
RAGRS Accounts

### ISSUE THREAD

**Issue by alpinedelight** [microsoft/AzureStorageExplorer#2810] opened 2020-04-08 09:44 UTC
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x86
**Regression From**:  N/A

## Bug Description ##
When trying to browse the contents of a blob RAGRS (read access enabled) secondary region endpoints connect successfully, however upon opening containers, to explore contents we receive an authorisation issue.
Used "-secondary" suffix and used primary key as per https://docs.microsoft.com/en-us/azure/storage/common/storage-redundancy#read-access-to-data-in-the-secondary-region
My colleagues, customers, and other users on stackoverflow report the same problem.
I can however access the files directly using HTTPS URL from my browser.

## Steps to Reproduce ##
Create RAGRS account
Upload file
Connect via storage explorer to primary
Connect via storage explorer to secondary
Explore secondary container contents
Bingo.

## Expected Experience ##
Should be able to open and read secondary endpoint options

## Actual Experience ##
Error messages, not able to explore contents

## Additional Context ##
Thanks.

**Comment by MRayermannMSFT** [comment] 2020-04-13 18:02
Duplicate of #421

**Closed by MRayermannMSFT** 2020-04-13 18:02 UTC
