### ISSUE TITLE
The query condition specified in the request is invalid.

### ISSUE THREAD

**Issue by alejandropeto** [microsoft/AzureStorageExplorer#7503] opened 2023-11-10 22:20 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.0

### Regression From

1.30.0

### Architecture

x64

### Storage Explorer Build Number

20231101.3

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Exploring any Table from Local Emulator Storage Account results in "The query condition specified in the request is invalid." and no data is shown at all when those tables have plenty of data stored

### Steps to Reproduce

1. Launch Storage Explores
2. Expand Storage->Emulator->Table
3. Select any Table you know have data

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/117556243/37c48e9c-23e9-4ecb-8179-fbf04f953f76)

### Expected Experience

Should see my stored data in right panel

### Additional Context

UI Error Message: The query condition specified in the request is invalid.
When Opened using Debug level I find the error in attached file

[2023-11-10_160340_editor_23060.log](https://github.com/microsoft/AzureStorageExplorer/files/13323480/2023-11-10_160340_editor_23060.log)

**Comment by craxal** [comment] 2023-11-10 23:25
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/7485.

Double-check the version of Azurite (assuming that's the emulator you are using) and upgrade as necessary. We've been able to verify that at least 3.26.0 does not have this issue.

**Closed by craxal** 2023-11-10 23:25 UTC
