### ISSUE TITLE
Search in subfolders

### ISSUE THREAD

**Issue by ste-gia** [microsoft/AzureStorageExplorer#2861] opened 2020-04-21 22:31 UTC
In the current version (1.12.0), Storage Explorer only supports searches within a given directory of files / blobs.

This request is about introducing sub-directories / sub-folders when searching. A search then provides results from all sub-directories from the directory the search is executed.

**Comment by MRayermannMSFT** [comment] 2020-06-22 18:28
Duplicate of #1667

**Closed by MRayermannMSFT** 2020-06-22 18:28 UTC
