### ISSUE TITLE
Support to undelete all deleted blobs which within the set data range on 'Undelete by Date' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#536] opened 2018-08-02 10:12 UTC
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180802.6
**Commit**: e9fc436c
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one storage account then enable soft delete for 'Blob Containers'.
2. Open one blob container which contains two blobs at least.
3. Delete these two blobs then switch to 'Active and deleted blobs'.
4. Right click one deleted blob and select 'Undelete by Date' -> Set a valid data range and make sure the deleted time of these two blobs are included within the set data range.

#### Expected Experience: ####
These two deleted blobs are undeleted.

#### Actual Experience: ####
Only the selected blob is undeleted.

**Comment by JasonYeMSFT** [comment] 2018-08-02 16:18
This is the intended behavior. Won't fix.

**Comment by jinglouMSFT** [comment] 2018-08-02 17:28
I could see the potential confusion here. This is a side effect from changing the button string from "Undelete Selected" to just "Undelete".  We'll keep this issue open for future consideration.  Please do let us know if you, all the users out there, feel the current product behavior is confusing.  Thanks.

**Comment by MRayermannMSFT** [comment] 2020-03-16 18:12
No one has commented. We'll go ahead and close this. :)

**Closed by MRayermannMSFT** 2020-03-16 18:12 UTC
Labels: :gear: blobs, :gear: delete policies, 🧪 testing
