### ISSUE TITLE
The localized tooltip of 'Save Query as…' contains zh-TW when using zh-CN

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1898] opened 2019-09-24 11:38 UTC
**Storage Explorer Version:** 1.10.1
**Build:** [20190924.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3076815&view=logs&j=c9f4993e-ba9a-5f87-11e6-962dc1008ac4)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Architecture:** ia32/x64
**Language:** Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Open one table -> Click '查询' button on the toolbar.
3. Focus on the localized 'Save Query as...' -> Check the tooltip.

**Expect Experience:**
Dispaly '将查询另存为...'.

**Actual Experience:**
The localized tooltip of 'Save Query as…' contains zh-TW.
![image](https://user-images.githubusercontent.com/41351993/65507421-7c4e2180-df00-11e9-922a-93d8ce5c815d.png)

**More Info:**
This issue also reproduces for 'Export' button's tooltip.
![image](https://user-images.githubusercontent.com/41351993/65507661-f7173c80-df00-11e9-9e46-a095299984b2.png)

**Comment by v-xianya** [comment] 2019-09-25 02:38
**More Info:**
This issue doesn't reproduce on Mac.

**Comment by lukaschal** [comment] 2019-09-25 09:04
On review.

File: loc\en\src\components\se-table-extension\resources\TableEditor.json
ID: 0; "QueryBuilder.Buttons.SaveQueryAs"
SRC: Save query as...
TGT: 将查询另存为...

File: loc\en\src\components\se-table-extension\resources\TableEditor.json
ID: 0; "Toolbar.ExportCommandDescription"
SRC: Export all or queried entities to a file
TGT: 将所有实体或查询的实体导出到文件

**Comment by janbaltus** [comment] 2019-09-30 18:26
@v-xiania can you please confirm why you assume translation is Cht?

**Comment by jinglouMSFT** [comment] 2019-09-30 19:51
@janbaltus Because the character in the red squares above is a traditional character.  Thus "将" is the correct simplified version, which is in Lukaschal's latest reply marked "On review"

**Comment by janbaltus** [comment] 2019-10-01 06:39
The translation used for CHS is using this character "将".
On the screenshot is used same character when we enlarge font size.
![image](https://user-images.githubusercontent.com/18324209/65939639-c2d2dd00-e426-11e9-95f8-93f2aed0a594.png)

**Comment by lukaschal** [comment] 2019-10-01 09:43
Linguistic answer: "Disagree. This is not zh-TW. It's just the effect of this font."

**Comment by weeteckt** [comment] 2019-10-01 17:21
@craxal 

While this is not a linguistic issue, the rendering of these zh-CN characters seem unusual. Are you able to confirm if the same font type was applied to this particular string?

**Comment by jinglouMSFT** [comment] 2019-10-01 17:44
Interesting. All characters except the first one in this string are in the zh-CN.  The enlarged font mentioned above still has the traditional character.

**Comment by weeteckt** [comment] 2019-10-01 18:08
I looked at the translation that was checked-in to the repo, it looks correct in the source file but not in the build. This appears to be caused by font (for example Segoe UI doesn't display several CHS characters correctly). 

If we try rendering this with the right CHS font (for example SimSun), it should show the character correctly.

![CHS](https://user-images.githubusercontent.com/25108435/65987565-ebfd6880-e43a-11e9-8cf4-bbabff5238d1.PNG)

**Comment by craxal** [comment] 2019-10-01 18:11
Was a changed checked in since this bug was reported? If so, then we need to generate a new extension package version.

**Closed** 2019-10-01 18:51 UTC
Labels: :gear: tables, :heavy_check_mark: mitigated, 🌐 localization, 🌐 translation, 🧪 testing
