### ISSUE TITLE
An error occurs when adding an entity whose 'PartitionKey' value is empty to one local table with Azurite 3.13.1

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4577] opened 2021-06-16 09:39 UTC
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210616.2
**Branch**: rel/1.20.0
**Platform/OS**: Windows 10
**Architecture**: ia32
**Emulator Version**: Azurite 3.13.1
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Install and run Azurite 3.13.1 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports)(Key)'.
3. Right click the 'Tables' node -> Create a new table.
4. Click 'Add' -> Leave the value of Property 'PartitionKey' empty -> 'Click 'Insert'.
5. Check no error occurs.

## Expected Experience ##
No error occurs.

## Actual Experience ##
An error occurs.
![image](https://user-images.githubusercontent.com/41351993/122192885-a1e64000-cec6-11eb-9feb-9d2897569685.png)

## Additional Context ##
1. This issue doesn't reproduce when using 'Microsoft Azure Storage Emulator - V5.10'.
2. Azurite 3.13.1 does support table.
![image](https://user-images.githubusercontent.com/41351993/122194251-d9a1b780-cec7-11eb-849b-824b4f7cce57.png)

**Comment by craxal** [comment] 2021-06-16 21:07
@v-xianya This also doesn't reproduce with regular Azure. It looks like this is an Azurite bug, so I'll open a new issue with them and close this one.

```
127.0.0.1 - - [16/Jun/2021:20:54:08 +0000] "POST /devstoreaccount1/test01 HTTP/1.1" 400 -
```

**Closed** 2021-06-16 21:08 UTC
Labels: :gear: emulator, :gear: tables, :grey_question: external, 🧪 testing
