### ISSUE TITLE
The restored tabs display empty and in a wrong place if restarting MAC/Ubuntu then opening Storage Explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5829] opened 2022-06-10 07:55 UTC
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220610.4
**Branch**: main
**Platform/OS**: MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings -> Data Explorers' -> Enable the setting 'Preserve Explorer Session'.
2. Open one tab -> Restart the Storage Explorer.
3. The tab is restored -> Restart the MacOS.
4. Launch Storage Explorer -> Observe whether the tab displays well.

## Expected Experience ##
The tab displays well.

## Actual Experience ##
There is an empty tab displays in the lower left corner of editor.
![image](https://user-images.githubusercontent.com/41351993/173016674-cb7cad0c-d95b-4570-a04e-c0f32b4a7f2c.png)

**Comment by JasonYeMSFT** [comment] 2022-06-10 18:02
I only have an Intel mac so I tried it and it doesn't seem to reproduce there. Does this bug reproduce on Intel macs for you?

**Comment by v-xianya** [comment] 2022-06-13 06:29
@JasonYeMSFT 
Verified this issue on an intel Mac (MacBook Air Retina, 13-inch,2020), reproduce.
1. This issue doesn't repro if the preserve tab session setting is disabled
2. Here are the logs collected on M1:
[2022-06-12_230442.zip](https://github.com/microsoft/AzureStorageExplorer/files/8888466/2022-06-12_230442.zip)
[2022-06-12_231829.zip](https://github.com/microsoft/AzureStorageExplorer/files/8888467/2022-06-12_231829.zip)

**Comment by JasonYeMSFT** [comment] 2022-06-13 17:23
Our existing logs doesn't give any information on what is causing this. I will add more detailed logging and hopefully the next time you reproduce it, it will tell us what is causing it.

**Comment by JasonYeMSFT** [comment] 2022-06-15 03:24
I believe this is the root cause of the bug: https://wiki.keyboardmaestro.com/assistance/Translocation_Problem#:~:text=In%20macOS%20Sierra%2C%20Apple%20added,!)%2C%20the%20application%20will%20be

**Comment by v-kellyluo** [comment] 2022-06-16 08:56
@JasonYeMSFT , this issue also reproduces on Ubuntu 20.04, it is the first time met this issue on Linux.

**Comment by JasonYeMSFT** [comment] 2022-06-16 16:34
@v-kellyluo Are you running from a tar.gz or a snap? When that happens, could you please open the dev tools and enter "process.execPath" in the console tab and see what it prints? I am working on a workaround for this issue which I believe will prevent this from happening.

**Comment by v-kellyluo** [comment] 2022-06-17 03:10
@JasonYeMSFT , 
I installed Storage Explorer by tar.gz, here is the print on Linux: [print.txt](https://github.com/microsoft/AzureStorageExplorer/files/8924259/print.txt)

**Comment by JasonYeMSFT** [comment] 2022-06-17 19:20
@v-kellyluo Do you follow exactly the same steps to reproduce this issue on Ubuntu? If you can reproduce it one more time, could you share a VM with me so I can take a look at it?

**Comment by JasonYeMSFT** [comment] 2022-06-17 21:41
I have merged a code change to mitigate this issue. Basically the change will detect such "invalid" tab session data and remove them so that they won't interfere with the start up. For scenarios where this bug occur, it should now work as if there is no previous tab session and Storage Explorer starts from fresh.

**Comment by v-kellyluo** [comment] 2022-06-20 01:29
@JasonYeMSFT , Yes, this issue reproduces after restarting Ubuntu, I will share the VM on teams.

**Comment by v-xianya** [comment] 2022-06-20 01:44
Tried to repro this issue on the latest main build 20220620.1. The current behavior keeps the same as the [comment](https://github.com/microsoft/AzureStorageExplorer/issues/5829#issuecomment-1159246089) tells.

**Comment by JasonYeMSFT** [comment] 2022-06-21 18:50
@v-xianya Could you please clarify if you mean that my workaround works as expected or Storage Explorer still run into a broken state after I made the code change?

**Comment by JasonYeMSFT** [comment] 2022-06-22 17:25
Cool. I checked the Ubuntu repro and it seems to be sharing the root cause of the mac bug. Closing this issue.

**Closed by JasonYeMSFT** 2022-06-22 17:25 UTC
Labels: :heavy_check_mark: merged, 🧪 testing, :computer: linux, :computer: M1 mac
