### ISSUE TITLE
Cannot download a file using container level SAS uri

### ISSUE THREAD

**Issue by kgeorge314** [microsoft/AzureStorageExplorer#2703] opened 2020-03-10 10:40 UTC
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10 (18363)
**Architecture**: x64
**Regression From**:  _Unsure, haven't used this is previous versions_ 

## Bug Description ##
Unable to download a file using a container-level SAS signature. 

## Steps to Reproduce ##

1. **Create a Blob Container SAS** Key with **L**ist and **R**ead permissions 
```ps1
$StorageAccountName = '<<Your Storage AccountName>>'
$StroageAccountKey = '<<The Primary Or Secondary Key For The StorageAccount>>'
$BlobContainerName = '<<The Name of the Blob Container>>'
$Expiry = (Get-Date).AddDays(3).ToString('yyyy-MM-dd')

# Generate a SAS List Read Token
$sasToken = az storage container generate-sas --name $BlobContainerName --https-only --permissions lr --expiry $expiry --account-name $StorageAccountName --account-key $StroageAccountKey -o tsv

# Build out the SAS URI
$SasURI = "https://$StorageAccountName`.blob.core.windows.net/$BlobContainerName`?$sasToken"

# Display it for use
Write-output "$SasURI"

```
2. **Connect** to BlobContainer **using SAS Key**
   1. Open Azure Storage Explorer 
   1. Expand `Local & Attached`
   1. Right Click `Storage Accounts` -> Click `Connect to Azure Storage...`
   1. Select `Use a shared access signature (SAS) URI`
   1. Paste the URI generated from Step 1 into `URI`
   1. Click Next->Connect and finish
3. Browse the storage account and try to download/open any file

## Expected Experience ##
The file is downloaded

## Actual Experience ##
There is an error
```
  "message": "\"failed to perform copy command due to error: cannot start job due to error: cannot list blobs. Failed with error -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42\\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\nRequestId:a56e09cb-f01e-00d9-2ac5-f68053000000\\nTime:2020-03-10T10:17:38.0679954Z, Details: \\n   AuthenticationErrorDetail: se is mandatory. Cannot be empty\\n   Code: AuthenticationFailed\\n   GET https://REDACTED.blob.core.windows.net/extract?comp=list&include=metadata&prefix=blankfile.json%2F&restype=container&sig=-REDACTED-&sip=REDACTED&sp=rl&spr=https&sr=c&sv=2018-11-09&timeout=901\\n   User-Agent: [Microsoft Azure Storage Explorer, 1.12.0, win32,  AzCopy/10.3.3 Azure-Storage/0.7 (go1.13; Windows_NT)]\\n   X-Ms-Client-Request-Id: [d9cbafb1-2143-46d9-74f7-03e19c29b1b4]\\n   X-Ms-Version: [2018-03-28]\\n   --------------------------------------------------------------------------------\\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\n   Content-Length: [407]\\n   Content-Type: [application/xml]\\n   Date: [Tue, 10 Mar 2020 10:17:37 GMT]\\n   Server: [Microsoft-HTTPAPI/2.0]\\n   X-Ms-Error-Code: [AuthenticationFailed]\\n   X-Ms-Request-Id: [a56e09cb-f01e-00d9-2ac5-f68053000000]\\n\\n\\n.\\n\""
```

AzCommand Used 
```
$env:AZCOPY_CRED_TYPE = "Anonymous";
$env:AZCOPY_USER_AGENT_PREFIX = "Microsoft Azure Storage Explorer, 1.12.0, win32, ";
./azcopy.exe copy "https://REDACTED.blob.core.windows.net/extract/blankfile.json?REDACTED" "C:\Users\REDACTED\Desktop\blankfile.json" --overwrite=prompt --recursive --from-to=BlobLocal --check-md5 "FailIfDifferent";
$env:AZCOPY_CRED_TYPE = "";
$env:AZCOPY_USER_AGENT_PREFIX = "";
```

## Additional Context ##
I have tested the SAS Key using the PowerShell module `Az.Storage`

```ps1
# Assuming you are in the same session as step1
# Install / Import PowerShell Module 
# Install-Module -Name Az.Storage -Scope CurrentUser -AllowClobber -Force



Import-module Az.Storage

$DownloadPath = New-Item -Path $env:TEMP -Name "$([guid]::NewGuid().Guid.ToString())" -Type Directory

Write-output "File(s) will be downloaded to $($DownloadPath.FullName)"


# Create StorageContext | Connection
$StorageContext = New-AzStorageContext -StorageAccountName $StorageAccountName -SasToken $sasToken

# To Download a file, pipe `Get-AzStorageBlob` to `Get-AzStorageBlobContent` , it will preserve folder path.
Get-AzStorageBlob -Context $StorageContext -Container $BlobContainerName -MaxCount 1 | Get-AzStorageBlobContent -Destination $($DownloadPath.FullName)

# List Download
Get-ChildItem $DownloadPath -Recurse

# Cleanup 
$DownloadPath | Remove-Item -Recurse -Force

```

**Comment by kgeorge314** [comment] 2020-03-10 10:56
Using Powershell, the SAS token works. 

![image](https://user-images.githubusercontent.com/7089603/76305606-5bfefd00-62bd-11ea-96e5-68c5715ec710.png)

---

The same token fails in Storage Explorer
![image](https://user-images.githubusercontent.com/7089603/76305826-c6b03880-62bd-11ea-83f6-b93c44a86db6.png)

**Comment by kgeorge314** [comment] 2020-03-10 10:57
Possibly related to issue [825](https://github.com/microsoft/AzureStorageExplorer/issues/825)

**Comment by JasonYeMSFT** [comment] 2020-03-10 18:54
Possibly related to #2457. AzCopy only supports certain timestamp formats.

**Comment by JasonYeMSFT** [comment] 2020-03-16 19:39
I have doubled check and confirmed that time stamp yyyy-mm-dd (e.g. "2020-03-14") is not supported by AzCopy. And it seems that Azure CLI is not honoring the format of the timestamp you pass to `az storage container generate-sas`. Please consider using the Storage Explorer generated SAS for now.

**Comment by MRayermannMSFT** [comment] 2020-03-23 17:55
Duplicate of #2457

**Closed by MRayermannMSFT** 2020-03-23 17:55 UTC
