### ISSUE TITLE
Table export columns in unexpected order

### ISSUE THREAD

**Issue by gdignard** [microsoft/AzureStorageExplorer#1918] opened 2019-09-25 19:24 UTC
**Storage Explorer Version**: v1.10.1
**Build Number**: 20190919.2
**Platform/OS**: Windows
**Architecture**: x64
**Regression From**: v1.9.x

## Bug Description ##
Exporting a table now produces a csv file where all the rows are Alphabetically arranged. In previous versions, only the non-key fields are sorted. The first three columns were always PartitionKey, RowKey, and Timestamp.

This may be related to open issue #1851 'Travelling Timestamp column in Table explorer' where the Timestamp column is appearing sorted within the fields (although the PK and RK columns appear correctly on the left)

**Comment by craxal** [comment] 2019-11-18 19:24
Related to #1851.

**Comment by craxal** [comment] 2020-07-30 18:55
@gdignard I was unable to reproduce this in the latest version (1.14.2). Does this issue still reproduce for you?

@v-xianya Can you reproduce this issue?

**Comment by gdignard** [comment] 2020-07-31 17:24
Craig -

I'm using v1.14.2 and this issue appears to be resolved.

I presume it was solved at the same time as issue #1851 (
https://github.com/microsoft/AzureStorageExplorer/issues/1851)

I was surprised to see them get different milestones, though my own work is
currently on a module that's not related to Azure at the moment, so while I
did check #1851 when v1.14 was released, I didn't think to also check #1918.

Glad to have these behaviours back the way they were!

Thanks!

- Gilles

**Comment by craxal** [comment] 2020-08-03 23:17
#1851 was closed by mistake. But since this doesn't repro for you, we'll go ahead and close. Open a new bug if this happens again.

**Closed by craxal** 2020-08-03 23:17 UTC
Labels: :beetle: bug, :gear: tables, :heavy_check_mark: mitigated
