### ISSUE TITLE
Cant Rename or Delete Blob Containers

### ISSUE THREAD

**Issue by ashifalibd** [microsoft/AzureStorageExplorer#2177] opened 2019-10-31 07:59 UTC
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by JasonYeMSFT** [comment] 2019-10-31 18:49
Possible duplicate of #2124 .

**Closed by JasonYeMSFT** 2019-10-31 18:49 UTC
