### ISSUE TITLE
Blob container rename fails

### ISSUE THREAD

**Issue by SimonBrace** [microsoft/AzureStorageExplorer#2124] opened 2019-10-23 10:17 UTC
**Storage Explorer Version**: 1.10.0
**Build Number**: 20190912.8
**Platform/OS**: Windows 7
**Architecture**: x64
**Regression From**:  Unsure, but yes, many versions ago.

## Bug Description ##
When attempting to rename a blob container I am getting multiple errors saying the file already exists. Since it's a simple rename and blob name must be unique it shouldn't be possible to have this error.

## Steps to Reproduce ##
Create blob container
Add a reasonable number of blobs (tested with 100k)
Rename blob container to something else

## Expected Experience ##
I would expect this process to take some time but complete without errors.

## Actual Experience ##
Hundreds of conflicts complaining that a blob with the same name already exists (shouldn't be possible for a simple rename?)
Hundreds of errors complaining:

> Could not delete the original item after copying.
>  
>  Details:
>  The specified blob does not exist.

Again, shouldn't be possible if the blob was successfully copied?

Finally the rename operation fails due to too many errors occurring.

## Additional Context ##
None

**Comment by JasonYeMSFT** [comment] 2019-10-23 18:11
This is definitely a bug caused by us. It seems that we are incorrectly trying to paste/delete some of the blobs twice. However, it shouldn't block you from using the data in the new container because the data should have been transferred. If you really want the old container to be deleted, you can manually delete it for now.

**Comment by SimonBrace** [comment] 2019-10-24 09:13
The wider issue is that after multiple failures the whole process fails, then after additional retries it just stops retrying altogether leading to a partial copy.

**Closed** 2019-11-21 17:52 UTC
Labels: :beetle: bug, :heavy_check_mark: merged
