### ISSUE TITLE
Unable to preview Parquet files in Azure Storage Explorer.

### ISSUE THREAD

**Issue by manishj216** [microsoft/AzureStorageExplorer#7032] opened 2023-06-29 19:03 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

x64

### Platform

Windows

### OS Version

windows 10

### Bug Description

Unable to preview parquet files.

### Steps to Reproduce

Try to preview parquet file in Azure storage explorer.

### Actual Experience

{
  "name": "TypeError",
  "message": "o.buffer.readUInt32LE is not a function",
  "stack": "TypeError: o.buffer.readUInt32LE is not a function\n    at ZR (file:///C:/Users/manish-jain2/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:736826)\n    at Object.QR (file:///C:/Users/manish-jain2/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:736928)\n    at Tn (file:///C:/Users/manish-jain2/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:764741)\n    at rD (file:///C:/Users/manish-jain2/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:766114)\n    at async sb (file:///C:/Users/manish-jain2/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:765449)\n    at async fb (file:///C:/Users/manish-jain2/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:767625)\n    at async Mu.readRowGroup (file:///C:/Users/manish-jain2/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:763489)\n    at async Object.next (file:///C:/Users/manish-jain2/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:756357)\n    at async ParquetParser.getRecords (file:///C:/Users/manish-jain2/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:5046)\n    at async getParquetData (file:///C:/Users/manish-jain2/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:6298)"
}

### Expected Experience

File preview

**Comment by daviewales** [comment] 2023-06-30 00:36
Seems to be a duplicate of #6990.

**Comment by MRayermannMSFT** [comment] 2023-06-30 15:51
> Seems to be a duplicate of #6990.

Correct!

**Closed by MRayermannMSFT** 2023-06-30 15:51 UTC
