### ISSUE TITLE
There is no successful activity log after applying the option 'Snapshot original blob then upload' if the ADLS Gen2 storage account doesn't support snapshots

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5151] opened 2021-11-08 09:22 UTC
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211106.4
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Launch Storage Explorer (make sure the setting 'Enable ADLS Gen2 snapshots(Preview)' is enabled).
2. Expand one ADLS Gen2 storage account -> Blob Containers.
3. Create a blob container -> upload one blob.
4. Open the blob -> Make some changes -> Save changes.
5. Select the option 'Snapshot original blob then upload' in the 'File Changes Detected' dialog.
6. Check whether there is a successful activity log indicating that the blob was transferred.

## Expected Experience ##
There is a successful activity log.
![image](https://user-images.githubusercontent.com/87792676/140707309-0576c64c-7f42-48fe-a621-411590f15105.png)

## Actual Experience ##
There is no successful activity log.
![image](https://user-images.githubusercontent.com/87792676/140707605-a6620c43-8326-482d-9e0a-cf8db3916760.png)

**Comment by JasonYeMSFT** [comment] 2021-11-08 18:05
The regression was due to moving to use the v12 create snapshot code for watch blobs. The new behavior makes more sense to me. If the user selects snapshot and it overwrite regardless of whether snapshot is success, we may accidentally overwrite data the user wants to preserve. I am going to close this as by design.

**Closed** 2021-11-08 18:05 UTC
Labels: 🧪 testing, :gear: blobs, :heavy_check_mark: by design, :beetle: regression, :gear: adls gen2
