### ISSUE TITLE
Fail to manage access for one Azure AD attached ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2136] opened 2019-10-24 10:30 UTC
**Storage Explorer Version:** 1.10.1
**Build:** [20191024.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3176191)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Give RBAC access to an ADLS Gen2 blob container to a user like 'Blob Data Owner Role'.
2. Attach this ADLS Gen2 blob container via Azure Active Directory (Azure AD).
3. Manage access for the Azure AD attached blob container.
4. Check the result.

**Expect Experience:**
1. Manage Access dialog pops up.
2. No error occurs.

**Actual Experience:**
1. No Manage Access dialog pops up.
2. Show error log messages on Activities panel.
![image](https://user-images.githubusercontent.com/41351993/67476593-e3d7c800-f68a-11e9-8734-68ee98638b27.png)
3. Error Details:
{
  "message": "\"{\\n  \\\"message\\\": \\\"\\\\\\\"Unable to determine permissions for path '/'\\\\\\\"\\\"\\n}\""
}

**More Info:**
1. This issue also reproduces for ADLS Gen2 blobs. Error Details like below:
      
{
  "message": "\"{\\n  \\\"message\\\": \\\"\\\\\\\"Unable to determine permissions for path '128GB.vhd'\\\\\\\"\\\"\\n}\""
}

**Comment by craxal** [comment] 2019-10-28 18:00
Reproduced.

**Comment by craxal** [comment] 2019-10-28 19:02
Actually, may be related #2133. I can't reproduce after closing the initial editor tab then reopening.

**Closed** 2019-10-28 23:19 UTC
Labels: :beetle: regression, :gear: adls gen2, :gear: attach, :gear: blobs, :heavy_check_mark: merged, 🧪 testing
