### ISSUE TITLE
Unable to connect to Storage Account

### ISSUE THREAD

**Issue by Dglynn1990** [microsoft/AzureStorageExplorer#6430] opened 2023-01-10 22:57 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.1

### Regression From

1.27.0

### Architecture

i86

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "TypeError",
  "message": "Cannot read properties of undefined (reading 'version')",
  "stack": "TypeError: Cannot read properties of undefined (reading 'version')\n    at connectionIsV1 (C:\\Users\\Daniel Glynn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\IConnectionInfo.js:8:24)\n    at C:\\Users\\Daniel Glynn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\CustomConnectionStore.js:235:74\n    at Array.filter (<anonymous>)\n    at #sendTelemetry (C:\\Users\\Daniel Glynn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\CustomConnectionStore.js:235:14)\n    at async CustomConnectionStore.getCustomConnectionStore (C:\\Users\\Daniel Glynn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\CustomConnectionStore.js:44:9)\n    at async PersistentStorage.CustomConnections.getCustomConnections (C:\\Users\\Daniel Glynn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\providers\\CustomConnectionsProvider.js:10:39)\n    at async Provider.executeOperation (C:\\Users\\Daniel Glynn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async ElectronRendererHostProxy._handleExecuteRequest (C:\\Users\\Daniel Glynn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\ElectronRendererHostProxy.js:213:35)\n    at async ElectronRendererHostProxy._handleMessage (C:\\Users\\Daniel Glynn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\ElectronRendererHostProxy.js:156:24)"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Select "Storage Accounts"

### Actual Experience

There used to be several dropdowns within "Storage Accounts" that when attempting to access produce the detailed error message

**Comment by craxal** [comment] 2023-01-11 17:51
Duplicate of #6399

**Closed** 2023-01-11 17:53 UTC
Labels: :heavy_check_mark: duplicate
