### ISSUE TITLE
Double clicking a table cannot make its temporary opened tab permanent

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5801] opened 2022-06-08 06:36 UTC
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220608.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.2)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Select one table -> Click it to open a temporary tab.
3. Double click the table -> Check whether the temporary tab becomes permanent.

## Expected Experience ##
The temporary tab becomes permanent.

## Actual Experience ##
The temporary tab doesn't become permanent.

## Additional Context ##
1. Click 'Open' can't make temporary tab becomes permanent.
2. Click 'OLD Open' can make temporary tab becomes permanent.

**Comment by craxal** [comment] 2022-06-15 20:13
This issue is not specific to table nodes. Marking as duplicate of #5747.

**Closed by craxal** 2022-06-15 20:13 UTC
Labels: :heavy_check_mark: duplicate, 🧪 testing, :gear: tables, :beetle: regression
