### ISSUE TITLE
Error wile installing 1.20.0

### ISSUE THREAD

**Issue by SharmaHarsh7** [microsoft/AzureStorageExplorer#4666] opened 2021-07-13 05:02 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.0

### Regression From

1.19.0

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Getting bellow error message while installing the 1.20.0 version of it:

![Uploading image.png…]()

### Steps to Reproduce

Download and run installer

### Actual Experience

![Uploading image.png…]()

### Expected Experience

Should install properly

**Comment by MRayermannMSFT** [comment] 2021-07-13 17:50
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/4653

**Closed by MRayermannMSFT** 2021-07-13 17:50 UTC
