### ISSUE TITLE
Missing Search Box (Search bar)

### ISSUE THREAD

**Issue by AndreaLanza** [microsoft/AzureStorageExplorer#6413] opened 2023-01-05 10:15 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.1

### Architecture

i86

### Storage Explorer Build Number

20221220.2

### Platform

Windows

### OS Version

Windows 10 Pro - Version 10.0.19045 Build 19045

### Bug Description

Cannot search files inside a blob containers because the search bar is missing.

### Steps to Reproduce

1. Lauch Storage Explorer
2. Expand a blob container node.

### Actual Experience

Missing search box near the "path" box

![image](https://user-images.githubusercontent.com/23117175/210755147-1ad2c876-8b4f-45fe-b32d-b02f284d5a4c.png)

### Expected Experience

Presence of the search box near the "path" box

### Additional Context

![image](https://user-images.githubusercontent.com/23117175/210756287-d30eb8ec-7105-435c-a9f7-9cfda9f2f497.png)

**Comment by MRayermannMSFT** [comment] 2023-01-09 18:21
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/2189

**Closed by MRayermannMSFT** 2023-01-09 18:21 UTC
