### ISSUE TITLE
Minor GUI issue: Black Font in Dark Theme (Gremlin) - hard to read

### ISSUE THREAD

**Issue by y-dima** [microsoft/AzureStorageExplorer#3337] opened 2020-08-03 08:50 UTC
**Storage Explorer Version**: 1.14.2 
**Build Number**: 20200715.2 
**Platform/OS**: Windows 10 
**Architecture**: ia32

## Bug Description ##
When I run Gremlin queries in Storage Explorer with Dark Theme, the results are partly shown in black font on a dark background which is hard to read. 

## Steps to Reproduce ##
Run any Gremlin query that returns result, e.g.: g.V()

## Expected Experience ##
Font should be white, light-gray, blue etc.; 
black font on dark background should be avoided. 

## Actual Experience ##
Results are partly black, partly blue, partly white.

**Comment by MRayermannMSFT** [comment] 2020-08-03 17:35
duplicate of #3339

**Closed by MRayermannMSFT** 2020-08-03 17:35 UTC
