### ISSUE TITLE
Canceling search doesn't keep the same node selected

### ISSUE THREAD

**Issue by JakeRadMSFT** [microsoft/AzureStorageExplorer#33] opened 2018-04-02 21:27 UTC
**Storage Explorer Version: 1.0.0 RC 1**

**OS Version: Mac**

**Steps to Reproduce:**

1. Start Search
2. Select node you want
3. Cancel search

**Expected Experience:**
Node is still selected.

**Actual Experience:**
Node isn't selected.

**Comment by MRayermannMSFT** [comment] 2018-04-02 22:43
This is due to the selected binding change. Here are some things I tried today:

1. Let the tree div be selected, and when it is, select a node if need be, and then focus the node. Problem: you can't shift-tab when a node is selected because you'll just get sent back to the node.
2. Let the tree div be selected, and when it is, select a node if need be, but leave the div focused. Problem: NVDA reads the entire contents of the div, even though we're setting an aria-label.

**Comment by douglaswaugh** [comment] 2019-02-15 12:12
I'm here because #589 is closed as duplicate.  My problem is I can search for resources, but I can't see them in Storage Explorer either when the search is continuing (which would be nice, because searching our subscriptions never seems to end) or at the end (if I just search a particular subscription).  This is different to the behaviour shown in https://azure.microsoft.com/en-gb/resources/videos/storage-explorer-search-experience/.

Really looking forward to this being fixed.  I keep wondering what the point of the search is if I can't then go to the resource!

Thanks,
Douglas.

**Comment by MRayermannMSFT** [comment] 2021-02-09 02:53
Fixed merged into main for 1.18! @v-xianya can y'all do some verifications around not only this bug, but left hand side search as well? I really want to make sure the change for this didn't introduce any regressions.

**Closed by MRayermannMSFT** 2021-02-09 02:53 UTC
Labels: :beetle: bug, :gear: search

**Comment by v-xianya** [comment] 2021-02-09 09:57
Hi @MRayermannMSFT 
We will verified this bug and do some testing around search features tomorrow. and comment the result in here.

**Comment by v-xianya** [comment] 2021-02-10 06:04
@MRayermannMSFT 
Verified this issue on build 20210210.2. Fixed. And no issue was found.
