### ISSUE TITLE
The 'Add new clause' shows strangely in Query Builder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2495] opened 2019-12-26 09:53 UTC
**Storage Explorer Version:** 1.11.2
**Build**: [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616)
**Branch**: hotfix/1.11.2-to-master
**Language**: German / Russian
**Platform/OS**: Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Deutsche' -> Restart Storage Explorer.
3. Expand one storage account -> Tables -> Create a new table -> Open 'Query'.
4. Check the localized 'Add new clause'.

**Expect Experience:**
The ‘Add new clause’ shows in the same line.

**Actual Experience:**

1. The 'Add new clause' shows strangely.
![image](https://user-images.githubusercontent.com/54055206/71470726-137c8b00-2808-11ea-9829-d2147fa7cd25.png)
2. ENU Screenshot.
![image](https://user-images.githubusercontent.com/54055206/71470770-373fd100-2808-11ea-8246-5f9d5a4b6ba8.png)

**Comment by johnliu2016** [comment] 2019-12-27 02:50
Sending to localization for review

**Comment by johnliu2016** [comment] 2019-12-30 12:37
@craxal, is this wrapping due to some length limit?

**Comment by craxal** [comment] 2020-01-06 17:01
Duplicate of #2001.

**Closed by craxal** 2020-01-06 17:01 UTC
Labels: :gear: tables, :heavy_check_mark: duplicate, 🌐 localization, 🧪 testing
