### ISSUE TITLE
Unable to download or upload or open or do any activities on Storage Explorer

### ISSUE THREAD

**Issue by shweta777** [microsoft/AzureStorageExplorer#1218] opened 2019-03-08 08:35 UTC
Unable to download or upload or open or do any activities on Storage Explorer. Getting the below error
"Invalid IV Length"

**Comment by jinglouMSFT** [comment] 2019-03-08 20:13
Could you tell us more info?
- which version of Storage Explorer
- Which OS
- Did you sign into Azure or attach to Storage resources? or use local emulator? or use Azure Stack?
- Did you have AzCopy enabled?
- Did you try to upload/download blobs or files?
Thanks.

**Comment by RobertK73** [comment] 2019-03-14 15:29
Dont bother. They never gonna fix it. Try alternatives

**Comment by jinglouMSFT** [comment] 2019-03-14 18:49
@RobertK73 We love to hear from our customers. Before we can do anything here, we need to first understand the issues.  There was not much information in the original post. Therefore the follow up questions.  If it turns out to be a bug in the product, we likely would fix it.  If you already knew the cause of the error message shown in the original post, please help and share so we can further investigate and fix the issue(s).  Thanks.

**Comment by MRayermannMSFT** [comment] 2019-04-08 18:11
Let's just catch the IV error and if it happens make a new IV.

**Comment by MRayermannMSFT** [comment] 2019-04-10 17:21
@shweta777 can you get me some more information? 

1. Open Storage Explorer
2. Open Devtools (F12)
![image](https://user-images.githubusercontent.com/21112697/54721718-f0f26e80-4b1f-11e9-9035-c6759918e640.png)
3. Press ctrl+p
4. Type TextEncrypter.js and then hit enter
![image](https://user-images.githubusercontent.com/21112697/54721743-05cf0200-4b20-11e9-8f2a-0b5fc5a8ac81.png)
5. Set a breakpoint on line 53 by clicking on the number 53
![image](https://user-images.githubusercontent.com/21112697/54721751-12ebf100-4b20-11e9-9f64-679e2bc1c86b.png)
6. Try downloading/opening your file
7. When the breakpoint is hit, go to the console, type in ecryptionKey, press enter, and copy the resulting value to your clipboard
![image](https://user-images.githubusercontent.com/21112697/54721796-37e06400-4b20-11e9-822a-c1fc5d97fb4b.png)
8. Close the dev tools
9. Let us know if the download/open works now, and also let us know the value you copied to your clipboard.

**Comment by MRayermannMSFT** [comment] 2019-05-20 18:37
Closing due to lack of reponse.

**Closed by MRayermannMSFT** 2019-05-20 18:37 UTC
Labels: :mag: more info

**Comment by seabass223** [comment] 2020-01-27 15:40
Getting this error today. Unable to upload or download any blob.
```
Uncaught (in promise) Error: Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119)
    at new Cipheriv (internal/crypto/cipher.js:225)
    at Object.createCipheriv (crypto.js:105)
    at StringCrypto.encrypt (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\se-string-crypto\dist\StringCrypto.js:19:29)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\common\TextEncrypter.js:20:56)
    at step (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:136:27)
    at Object.next (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:117:57)
    at fulfilled (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:107:62)
    at ZoneDelegate.invoke (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:242:26)
    at Zone.run (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:113:43)
    at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:535:57
    at ZoneDelegate.invokeTask (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:275:35)
    at Zone.runTask (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:151:47)
    at drainMicroTaskQueue (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:433:35)
```

Version: 1.12.0
AzCopy Version: 10.3.3
Build Number 20200116.10

**Comment by seabass223** [comment] 2020-01-27 19:59
My network password had expired. I re-logged in and could browse all my storage accounts. I could perform all list operations but no download, delete, upload.
eventually I found the Invalid IV length was linked to the STORAGEEXPLORER/APP saved credentials from Windows Credential Manager. Apparently this did not update when I re-authenticated in Windows Azure Storage Explorer. Deleting the aforementioned credentials solved the problem.
