### ISSUE TITLE
Unable to Preview Parquet File in Azure Storage Explorer

### ISSUE THREAD

**Issue by snestler** [microsoft/AzureStorageExplorer#7402] opened 2023-10-12 23:37 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.2

### Regression From

No

### Architecture

i86

### Storage Explorer Build Number

94

### Platform

Windows

### Bug Description

Get "No data" when trying to preview a Parquet file stored in blob storage.

Here's the error shown when I click on the Details link.

{
  "name": null,
  "message": "\"invalid encoding: RLE_DICTIONARY\""
}

### Steps to Reproduce

1. Launch Storage Explorer.
2. Open a blob container node.
3. Select a Parquet file stored in the blob.
4. Click on the Preview button.
5. Observe the "No Data" error.

### Actual Experience

Get a "No data" display instead of the table I expect to see in the Preview window.

### Expected Experience

Expect to see the top left corner of the table, like I do in other file formats in Azure Storage Explorer.

**Comment by JasonYeMSFT** [comment] 2023-10-13 18:54
This encoding is not supported by the parquetjs library right now.

**Comment by MRayermannMSFT** [comment] 2023-10-16 17:22
@JasonYeMSFT can you please open an issue against parquetjs to add this capability, and then link here? :)

**Comment by JasonYeMSFT** [comment] 2023-10-16 17:24
https://github.com/LibertyDSNP/parquetjs/issues/96

**Comment by MRayermannMSFT** [comment] 2024-02-21 17:33
This might have been fixed in 1.33.0...

**Comment by MRayermannMSFT** [comment] 2024-02-22 05:59
Not fixed. But we should be able to resolve in 1.34 since upstream bug is fixed.

**Comment by MRayermannMSFT** [comment] 2024-02-23 18:59
Merged. Starting with 1.34 the parquet preview will support RLE_DICTIONARY  files.

**Closed by MRayermannMSFT** 2024-02-23 18:59 UTC
Labels: :grey_question: external

**Comment by craxal** [comment] 2024-04-08 15:28
@MRayermannMSFT Do we have a sample Parquet file we can use for testing?

**Comment by craxal** [comment] 2024-10-23 16:54
@ganbaaelmer Can you provide more details about your experience with this issue? Please include your version of Storage Explorer, platform and architecture, error messages or logs, and if possible, a sample Parquet file that reproduces the issue for you.

**Comment by ganbaaelmer** [comment] 2024-10-24 01:33
> [@ganbaaelmer](https://github.com/ganbaaelmer) Can you provide more details about your experience with this issue? Please include your version of Storage Explorer, platform and architecture, error messages or logs, and if possible, a sample Parquet file that reproduces the issue for you.

we still cant preview .parquet file at 2024.10.24

[](https://drive.google.com/file/d/1aH7SU6weH7byaROpRoqeJNNZF0PUtd1B/view?usp=sharing)

**Comment by craxal** [comment] 2024-10-24 18:03
@ganbaaelmer Please provide the following details, and we can investigate the issue further:
- Have you updated Storage Explore to version 1.36.1?
- Are you running on Windows, Mac, or Linux?
- Is your machine an x64 or ARM64 machine?
- Can you provide details about any error messages you are getting?
- Can you attach application logs from a session where you reproduce the issue?

**Comment by ganbaaelmer** [comment] 2024-10-25 02:58
> [@ganbaaelmer](https://github.com/ganbaaelmer) Please provide the following details, and we can investigate the issue further:
> 
> * Have you updated Storage Explore to version 1.36.1?
> * Are you running on Windows, Mac, or Linux?
> * Is your machine an x64 or ARM64 machine?
> * How is your Parquet file encoded/compressed?
> * Do you have a small sample file that you can share with us to test on our end?
> * Can you provide details about any error messages you are getting?
> * Can you attach application logs from a session where you reproduce the issue?

i need to see what is inside of parquet file on https://portal.azure.com/

**Comment by ganbaaelmer** [comment] 2024-10-29 07:29
![Image](https://github.com/user-attachments/assets/2c0822f1-1e88-4c88-93d1-5f8a8fbdc9de)

cant see whats inside to .parquet file

https://portal.azure.com/#view/Microsoft_Azure_Storage/BlobPropertiesBladeV2/

**Comment by craxal** [comment] 2024-10-29 17:09
@ganbaaelmer We're still unclear on some important details.

The following can be confirmed by opening the About dialog (**Help > About** or **Storage Explorer > About** menu):

* Please verify that you have updated Storage Explore to the latest version 1.36.1.
* Please verify whether you are running on Windows, Mac, or Linux.
* Please verify whether you are running x64 or ARM64.

The following can be done after following the same steps to reproduce your issue:

* Please provide details about any error messages you are getting (check the Activity Log panel or any command line output).
* Please provide your app logs (**Help > Open Logs Directory** menu, logs for current session located in the selected directory).

The following can be done using any Parquet viewing program, either online or downloaded and installed (do an internet search for "parquet viewer"):

* Please share the encoding/compression used for your Parquet file.

**Comment by ganbaaelmer** [comment] 2024-10-30 06:14
> [@ganbaaelmer](https://github.com/ganbaaelmer) We're still unclear on some important details.
> 
> The following can be confirmed by opening the About dialog (**Help > About** or **Storage Explorer > About** menu):
> 
> * Please verify that you have updated Storage Explore to the latest version 1.36.1.
> * Please verify whether you are running on Windows, Mac, or Linux.
> * Please verify whether you are running x64 or ARM64.
> 
> The following can be done after following the same steps to reproduce your issue:
> 
> * Please provide details about any error messages you are getting (check the Activity Log panel or any command line output).
> * Please provide your app logs (**Help > Open Logs Directory** menu, logs for current session located in the selected directory).
> 
> The following can be done using any Parquet viewing program, either online or downloaded and installed (do an internet search for "parquet viewer"):
> 
> * Please share the encoding/compression used for your Parquet file.
> 
> Considering that the original issue has been closed, it may be easier for you to open a new bug, so we isolate any details that differ from the original issue here.

all this on webrowser version: https://portal.azure.com/#view/Microsoft_Azure_Storage/BlobPropertiesBladeV2/

**Comment by craxal** [comment] 2024-10-30 17:15
@ganbaaelmer I think I see where our confusion is now. The link you provided goes to the Azure Portal. That is a completely different application. This is the GitHub page for Microsoft Azure Storage Explorer, a desktop application. The desktop application _does_ support previewing Parquet files. If you'd like to preview your Parquet files, you can download Storage Explorer [here](https://azure.microsoft.com/en-us/products/storage/storage-explorer/?msockid=069478ba74c86cb62fba6c9475606ddb#Download-4)
