### ISSUE TITLE
Copying accross different Azure subscriptions creates zero byte copies

### ISSUE THREAD

**Issue by dhoehne** [Microsoft/AzureStorageExplorer#976] opened 2018-12-07 10:00 UTC
**Storage Explorer Version**: 1.6.0
**Platform/OS**: Windows
**Architecture**:
**Regression From**: 1.5.0

**Bug description**
Copying of files across different Azure subscriptions is no longer working. A zero byte blob is created.

**Steps to Reproduce**
List the minimal steps clearly and concisely to reproduce the behavior:
1. Go to the source storage account of the first Azure subscription. 
2. Select the blob container.
3. Select an item from the container.
4. Hit Copy-Button
5. Change to the destination account and there the blobcontainer
6. Hit the Paste-Button
7. Result: Job starts, created element has the right name with a size of zero bytes.

**Expected Experience**
An exact copy of the source is expected.

**Actual Experience**
A zero size copy is created.

**Comment by MRayermannMSFT** [comment] 2018-12-10 19:12
Hey @dhoehne , can you try this again? I just tried it on 1.6.0, and the copy definitely worked. If it doesn't work, can you give me some more information such as:

- type of storage account you are copying from (classic, premium, etc.)
- type of storage account you are copying to (classic, premium, etc.)
- type of blob you are copying (block, page, append)
- do you think its 0 bytes because the editor shows the size as 0 bytes or because you opened it and nothing was there?

**Comment by dhoehne** [comment] 2018-12-19 22:03
Hi @MRayermannMSFT,

Error also happenend in 1.6.0 and also in version 1.6.1. Previous versions had not been affected.
Are you able to provide a download link to a previous version in the meantime?

Do you think its 0 bytes because the editor shows the size as 0 bytes or because you opened it and nothing was there?
-> the opened or downloaded file has a 0 byte size, this size is also shown in Storage Explorer. The copy process is much to fast to copy between storage accounts.

Source and destination storage account are of different subscriptions but of the same type. Both are shown as storage account (without classic), standard LRS.

I cannot say anything about the type of blob - how to find out?
I just take a file, hit on copy, navigate to the destination hit on paste there.

Any other information that could be helpful? If so, just let me know how to find out.

**Comment by manuel-74** [comment] 2018-12-20 12:03
Just upgraded to 1.6.1 and I can confirm that when copying a blob from a classic to a StorageV2 container (that is my use case, didn't test others) the file is copied immediately but if you check the CopyStatus attribute in the blob properties it shows 'pending' and if you wait long enough it changes to 'success'. So imho the only thing missing is the copying progress. I downgraded to 1.5.0 and now percentual copying progress works fine again.

**Comment by dhoehne** [comment] 2019-01-09 21:18
Issue seems to be solved with 1.6.2.

**Comment by MRayermannMSFT** [comment] 2019-01-09 21:43
Hmmmm interesting that you say that @dhoehne , we didn't change anything that would have fixed this. If you don't mind, I'd like to leave it open until we can confirm that our rewrite of copy didn't miss something. 😄

**Comment by manuel-74** [comment] 2019-01-10 16:41
In fact it's not fixed. When I copy a page blob (VHD file) from a classic storage account container to a container on a new storage account ('StorageV2', access tier 'Hot') the ASE 1.6.2 immediately tells me that the file has been copied without showing any progress bar which of course is not true and can be verified in the file properties attribute 'CopyStatus' which shows 'Pending' until the file REALLY has been copied.

**Comment by MRayermannMSFT** [comment] 2019-01-10 17:02
Yep, @manuel-74 is correct.

**Comment by MRayermannMSFT** [comment] 2019-01-29 18:03
Code to wait for longer server side copies to finish is checked in. Will be shipped in our next release.

**Closed by MRayermannMSFT** 2019-01-29 18:03 UTC
Labels: :white_check_mark: merged, 🔍 more info
