### ISSUE TITLE
Unable to delete folder with illegal characters in its name

### ISSUE THREAD

**Issue by NickLee-Arrow** [microsoft/AzureStorageExplorer#2651] opened 2020-02-19 13:03 UTC
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: macOS High Sierra 10.13.6
**Architecture**: 64
**Regression From**:  

## Bug Description ##
Un able to delete a folder that is labelled *******MASTERS. an error message displays citing illegal characters in the file path.

## Steps to Reproduce ##
 create a folder with a sub folder label the folder test, label the subfolder **delete upload the test folder. go into the test folder and try and delete the folder named **delete.

## Expected Experience ##
I was expecting the storage explorer to delete the folder labelled **delete

## Actual Experience ##
Storage explorer didn't delete the folder tabled **delete, it gave some poor excuse for failing to perform its given task in the form of an error message.

**Comment by JasonYeMSFT** [comment] 2020-03-04 17:13
This caused by use not encoding all * characters in the blob path. A fix has been merged.

**Closed by JasonYeMSFT** 2020-03-04 17:13 UTC
Labels: :beetle: bug, :heavy_check_mark: merged
