### ISSUE TITLE
Feature Request: Allow "Auto-Resolve behavior" to persist per session (and/or between sessions)

### ISSUE THREAD

**Issue by michaeldaw** [microsoft/AzureStorageExplorer#46] opened 2018-04-18 14:43 UTC
**Storage Explorer Version:**
1.0.0
**OS Version:**
Windows 10
**Steps to Reproduce:**

1. Upload a file to a File Share (as an example) that already exists

**Expected Experience:**
An "Auto-Resolve" behavior is required, but has to be specified with every action. It would be nice to have the option for the user to save their choice.
**Actual Experience:**
Must specify Auto-Resolve Behavior for every attempt.

![image](https://user-images.githubusercontent.com/8949148/38939058-4e6c2c30-42e4-11e8-8258-39357f4cda06.png)

![image](https://user-images.githubusercontent.com/8949148/38939071-5669f638-42e4-11e8-9468-841985086976.png)

**Comment by evesala** [comment] 2019-04-22 17:42
Better yet, please make the auto-resolve behavior a permanently configurable option.

**Comment by amattas** [comment] 2019-05-14 17:42
I can't even get it to persist between uploads.

**Comment by jinglouMSFT** [comment] 2019-10-11 17:52
We can make it a configurable setting in the future.  However, it does increase the probability of accidentally overwriting the files you may want to keep if you don't remember you set the setting to always overwrite.  Let us know how concern you are about the accidental overwrites.

**Comment by whit98c** [comment] 2019-10-11 18:48
Thanks for the quick reply. I’m not concerned about overwrites at all in my scenario. However, making the choice once per session is fine. If it popped up the first time and kept that choice or had a remember checkbox or something along those lines it would help me.

________________________________

**Comment by jinglouMSFT** [comment] 2019-12-14 01:41
Duplicate of #539

**Closed by jinglouMSFT** 2019-12-14 01:41 UTC
Labels: :bulb: feature request, :bulb: setting candidate
