### ISSUE TITLE
A11y_Azure Tools Storage Explorer_Use a SAS URL_Attach with SAS URL_Screen reader: Voice Over is announcing Incorrect information to the users as Dialog with13 items.

### ISSUE THREAD

**Issue by keerthiduvvuri** [microsoft/AzureStorageExplorer#7611] opened 2023-12-19 14:31 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1(96)

### Regression From

NO

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

macOS

### OS Version

MAC Version 13.6.1

### GitHub Tags:
#A11yMAS;#A11yTCS;#MAC;#DesktopApp;#A11ySev2;#BM_AzureToolsStorageExplorer_MAC_Dec2023;#Azure Tools Storage Explorer;#FTP;#Voiceover;#MAS1.3.1;#Info and Relationship;#AILimited;#Element:Dialog;

### Environment Details:
Application: Microsoft Azure Storage Explore
version: 1.32.1 (96)
Screen Reader: Voice Over

### Steps to Reproduce

1. Launch Storage Explorer
2. Tab Navigate to "Open Connect Dialog" pane present on left side of screen and hit enter.
3. Select "Storage account or service", then Tab to Next button and press enter on it.
4. In "Select Connection Method", select radio button "Shared access signature URL (SAS)", then press enter on Next button.
5. Turn on Voice over and Observe that Voice Over is announcing Incorrect information to the users.

### Actual Experience

Voice Over is announcing Incorrect information to the users as Dialog with13 items.

### Expected Experience

Voice Over should not be announcing Incorrect information to the users.

### User Impact:
Screen reader users will face difficulty if Voice Over is announcing Incorrect information to the users.

### Attachment:
![A11y_Azure Tools Storage Explorer_Use a SAS URL_Attach with SAS URL_Screen reader](https://github.com/microsoft/AzureStorageExplorer/assets/98728920/05ffd190-4aec-4af0-95ac-25187bfe1df4)

**Comment by craxal** [comment] 2024-01-04 00:39
@keerthiduvvuri I am not able to reproduce this on Sonoma 14.2.1. VoiceOver correctly announces data in the dialog. What happens if you switch on VoiceOver _before_ clicking the Next button?

**Comment by keerthiduvvuri** [comment] 2024-01-08 06:48
@Craxal when user is landing on display name edit box Voice over is announcing as dialog with 13 items and then announces Display name Edit text, actually this is incorrect there are no 13 items and it is announcing as dialog. It should only announce as Display name edit box or edit text.

**Comment by kupatkar99** [comment] 2024-01-30 07:57
Verified the issue in below environment:
Azure Tools Storage Explorer: Version: 1.33.0-dev (96)
AzCopy Version: 10.22.2
Platform: macOS
Build Number: 20240111.7
Issue is fixed. Hence Closing the bug Please find added attachment for reference.
<img width="1440" alt="7611_Fixed" src="https://github.com/microsoft/AzureStorageExplorer/assets/98530069/02b2da28-87d1-4bf5-9376-58958de3f382">

**Closed** 2024-01-30 09:44 UTC
Labels: :accessibility: accessibility, :accessibility: MAS, ♿ sev1/2
