### ISSUE TITLE
The value of the column property "Content Type" for the blob under the SAS attached blob container is not automatically changed to the same value as set in the "Shared Access Signature" dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6782] opened 2023-04-17 09:30 UTC
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230416.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one .csv file -> The content type of the file is 'text/plain'.
3. Right click the blob container -> Click 'Get Shared Access Signature...'.
4. Select all permissions -> Type 'text/csv' into the 'Content type' field.
5. Click 'Create' -> Copy the SAS URL.
6. Attach the blob container via the SAS URL. 
7. Go to the attached blob container.
8. Check whether the blob's column property **Content Type** value is the same as the value in the **Properties** dialog.

## Expected Experience ##
The value of content type is the same.

## Actual Experience ##
The value of content type is not the same.
![image](https://user-images.githubusercontent.com/41351993/232433063-568452f8-1efe-4aa4-8b8d-0a6d85a411f2.png)

## Additional Context ##
The column 'Content Type' value will change to the value in the properties dialog if execute the actions **Open the properties dialog -> Click 'Save' -> Click 'Refresh'**.
![0417](https://user-images.githubusercontent.com/41351993/232438592-e54db35c-8689-477b-85a1-472dc7fa6fa7.gif)

**Comment by richardMSFT** [comment] 2023-05-26 19:48
We use the List Blobs api to populate the data table. The content type in the response headers for List Blobs is set to `application/xml` (described [here](https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=azure-ad#response-headers)) which seems to indicate that it's the type of the response body that contains all the returned blobs. Each of these returned blobs have their own content-type property that is unmodified by the SAS content type query parameter. Therefore, the data table is displaying each blob's true content type which is by design.

When you access the property for an individual blob, the blob client will use the SAS token to properly overwrite the content-type as described by the `rsct` query parameter.

Because this is the intended behavior, we will close this issue.

**Closed by richardMSFT** 2023-05-26 19:48 UTC
Labels: 🧪 testing, :gear: blobs, :heavy_check_mark: by design, :gear: adls gen2
