### ISSUE TITLE
error storage explorer

### ISSUE THREAD

**Issue by PatriciaCSouza** [microsoft/AzureStorageExplorer#8284] opened 2024-11-07 12:27 UTC
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.2

### Architecture

x64

### Platform

Windows

### OS Version

11

### Bug Description

Não é possível recuperar recursos filho.

ProducerError:{
  "name": "Electron Net Error",
  "message": "{\"name\":\"Electron Net Error\",\"cause\":{}}"
}

### Steps to Reproduce

Expand a blob container node

### Actual Experience

Não é possível recuperar recursos filho.

ProducerError:{
  "name": "Electron Net Error",
  "message": "{\"name\":\"Electron Net Error\",\"cause\":{}}"
}

**Comment by craxal** [comment] 2024-11-07 19:03
Investigating...

Duplicate of #8277.

**Closed by craxal** 2024-11-07 19:03 UTC
Labels: :white_check_mark: duplicate
