### ISSUE TITLE
Copy Managed Disk cross two Azure China Tenant Error

### ISSUE THREAD

**Issue by nonokangwei** [microsoft/AzureStorageExplorer#2764] opened 2020-03-30 07:22 UTC
**Storage Explorer Version**: 1.12.0
**Build Number**: 10.3.3
**Platform/OS**: Windows 10
**Architecture**: x86
**Regression From**:  

## Bug Description ##
Failed to copy disk 'shcopy' in resource group 'msmjsh' to disk 'shcopy' in resource group 'chinavhub': Unable to create disk: Error:The client has permission to perform action 'Microsoft.Compute/disks/beginGetAccess/action' on scope '/subscriptions/0f53c77e-a06b-4d80-8974-9d5fe127c280/resourceGroups/chinavhub/providers/Microsoft.Compute/disks/shcopy', however the current tenant 'b362ae96-4a99-473b-9b8d-134bb79ec909' is not authorized to access linked subscription 'd88b620e-cb36-4668-8a2d-7b8aef2051b5'.

Note: the same action is work cross tenant btw global azure and china azure.

## Steps to Reproduce ##
1. add two tenant using aad identity
2. do copy a managed disk from one tenant to another tenant

## Expected Experience ##
the managed disk can copy cross the tenant under Azure China

## Actual Experience ##
Failed to copy disk 'shcopy' in resource group 'msmjsh' to disk 'shcopy' in resource group 'chinavhub': Unable to create disk: Error:The client has permission to perform action 'Microsoft.Compute/disks/beginGetAccess/action' on scope '/subscriptions/0f53c77e-a06b-4d80-8974-9d5fe127c280/resourceGroups/chinavhub/providers/Microsoft.Compute/disks/shcopy', however the current tenant 'b362ae96-4a99-473b-9b8d-134bb79ec909' is not authorized to access linked subscription 'd88b620e-cb36-4668-8a2d-7b8aef2051b5'.

**Comment by MRayermannMSFT** [comment] 2020-03-30 17:50
Duplicate of #2722

**Closed by MRayermannMSFT** 2020-03-30 17:50 UTC
