### ISSUE TITLE
There is an error info bar when opening one OAuth attached file share which already has the correct rbac role

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7820] opened 2024-03-15 07:24 UTC
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240315.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open Settings -> Check 'Enable Files OAuth Support'.
2. Select one storage account whose region is 'eastus2euap' -> Assign RBAC role 'Storage File Data Privileged Contributor' to one azure account against the storage account.
3. Expand the storage account -> File Shares.
4. Select one file share -> Copy the URL.
5. Open connect dialog -> Select 'File share' -> Select 'Sign in using OAuth'.
6. Select the azure account -> Next -> Paste the URL -> Connect the file share.
7. Check whether there is no error info bar.

## Expected Experience ##
There is no error info bar.

## Actual Experience ##
There is an error info bar.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/33f7e421-60e4-445f-b7ec-9fad99f56be4)
` RequestId:b473a782-b01a-0020-06a6-76bda7000000 Time:2024-03-15T07:02:01.4627136Z`

**Comment by MRayermannMSFT** [comment] 2024-07-09 23:45
@v-xianya can you try to repro this, but make sure at least 5min have passed after being assinged the role 'Storage File Data Privileged Contributor'?

**Comment by MRayermannMSFT** [comment] 2024-07-23 15:47
@v-xianya can you share with me the subscription and name of the storage account you reproduce this in, and the name of the share in that account as well.

**Comment by v-xianya** [comment] 2024-07-25 02:12
Hi @MRayermannMSFT I shared the information on teams.

**Comment by MRayermannMSFT** [comment] 2024-07-25 20:33
@v-xianya I understand the issue now. The problem is that we are unable to list the file share's snapshots. We are trying to do this so we can populate the snapshots drownpdown. For now, we're going to won't fix this issue. We'll wait to see if any users run into this in real life, once file share OAuth support ships.

**Closed by MRayermannMSFT** 2024-07-25 20:33 UTC
Labels: :white_check_mark: no repro, 🧪 testing, :gear: attach, :gear: files

**Comment by v-xianya** [comment] 2025-04-23 02:21
This issue has been fixed on build 20250423.1 (1.39.0-dev).
