### ISSUE TITLE
The tooltip is not localized for 'Recent locations' navigation key

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2056] opened 2019-10-11 10:22 UTC
**Storage Explorer Version:** 1.10.1
**Build:**[ 20191011.12](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3133776)
**Branch:** master
**Platform/OS:** Windows 10// Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-CN)/ Chinese (zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open Settings panel -> Preference (Locale) -> Select **Chinese (simplified)** as application language -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a new blob container -> Open this blob container.
5. Click the 'Recent locations' on the editor and observe its tooltip.

**Expect Experience:**
The 'Recent locations' navigation key is localized.

**Actual Experience:**
The 'Recent locations' navigation key is not localized.
![image](https://user-images.githubusercontent.com/54055206/66639485-7e76e680-ec49-11e9-91c7-46558609f3cd.png)

**More Info:**
1. This issue also reproduces for one file share.
2. This issue also reproduces for the information  in the tooltip brackets of the "Up/Forward/Back" navigation keys.
![image](https://user-images.githubusercontent.com/54055206/66639540-9484a700-ec49-11e9-85ce-dc0a47185eb5.png)
3. This issue also reproduces in Chinese(zh-TW).
4. Only verified this issue in Chinese(zh-CN) and Chinese(zh-TW).

**Comment by lukaschal** [comment] 2019-10-11 11:01
New string. Localized at 10/9/2019.

File: loc\en\src\Standalone\resources\Azure.json
ID: 0; "ButtonRecentLocations"
SRC: Recent locations
TGT: 最近浏览的位置

**Comment by craxal** [comment] 2019-10-11 15:31
Duplicate of #1997.

**Closed by craxal** 2019-10-11 15:31 UTC
Labels: :gear: blobs, :gear: files, 🌐 localization, 🧪 testing
