### ISSUE TITLE
Unable to delete blobs

### ISSUE THREAD

**Issue by lberny** [microsoft/AzureStorageExplorer#2603] opened 2020-02-05 15:43 UTC
**Storage Explorer Version**: 1.12 (bug also in older versions)
**Build Number**: 2020.0116.10
**Platform/OS**: Windows Server 2016
**Architecture**: x64
**Regression From**: Not sure, but I think it worked like a year ago, don't know which version

## Bug Description ##
Failure when trying to remove a blob object from Azure Storage Explorer.

## Steps to Reproduce ##
1. Right-click on file, select "Remove"
2. Validate warning message

## Expected Experience ##
I expect the file to be removed

## Actual Experience ##
The file is not removed, and error message says it can't be done, with details:
```json
{ "message": "\"failed to perform remove command due to error: nothing found to remove\"" }
```

## Additional Context ##

**Comment by JasonYeMSFT** [comment] 2020-02-05 19:24
Does it reproduce on every blob you are trying to delete or only some specific blobs? Could you please share the path to that blob to us (e.g. <container_name>/folder1/folder2/<blob_name>)?

**Comment by garimagupta25** [comment] 2020-02-05 19:50
cannot delete property files/octet streams for empty blobs even though there is no data in them. How to delete those?

**Comment by lberny** [comment] 2020-02-06 09:08
It concerns pst files, uploaded through AzCopy for O365 online archive migration process.
You want me to share the SAS URL ?

**Comment by JasonYeMSFT** [comment] 2020-02-07 05:08
@garimagupta25 Do you mean you have a blob with path `property files/octet streams` and you cannot delete it? Or do you mean blobs with path `property files/octet streams/<some_blob_name>`?

**Comment by garimagupta25** [comment] 2020-02-07 05:43
No I mean all the started/committed 0B files that are generated with a file when I write to the blob from databricks. I am unable to delete folders containing those.

**Comment by JasonYeMSFT** [comment] 2020-02-07 18:06
@lberny @garimagupta25 We have seen some issues with partially committed/corrupted data written via automated tools. Unfortunately we cannot reproduce it without knowing how the data gets committed. Could you share some documentation on how to reproduce the pipeline for committing data to storage in your scenario?

It would be super helpful if we can learn how to do it and reproduce the issue. I believe it would benefit a lot of other data automation related issues as well. Thanks.

**Comment by lberny** [comment] 2020-02-10 09:22
I don't understand the specifics you need. I'm not doing anything specific. Just copying pst files via AzCopy. And I can't delete any of them, I always get the error I opened this issue for.

**Comment by lberny** [comment] 2020-02-10 09:43
I forgot to mention the container name is ingestiondata.

**Comment by MRayermannMSFT** [comment] 2020-02-10 18:45
@lberny , how are you accessing your storage? It is it via:

- SAS URI
- Connection String
- Sign in
- Attach with RBAC

**Comment by lberny** [comment] 2020-02-10 18:48
SAS URI

**Comment by MRayermannMSFT** [comment] 2020-02-10 18:56
Can you confirm for us what permissions you have in the SAS URI? It'll be in the sp section:

REDACTED.blob.core.windows.net/$logs?st=2020-02-10T18%3A39%3A34Z&se=2020-02-11T18%3A39%3A34Z&**sp=rl**&sv=2018-03-28&sr=c&sig=REDACTED

If your SAS is using an access policy, then can you please check the access policy for what permissions it has?

**Comment by JasonYeMSFT** [comment] 2020-02-27 19:52
We have recently discovered a problem with deleting blobs with metadata `hdi_isFolder=True`. This can occur when you are using some automatic tools to upload data to your blob container. 

@lberny @garimagupta25 Could you please verify if your data with the problem has the metadata set on them?

**Comment by lberny** [comment] 2020-03-06 10:35
Sorry for late answer.
@MRayermannMSFT, there is no sp section in the SAS URI.
@JasonYeMSFT, how can I access to blob metadata ? When right-clicking, and selecting properties on blobs, I got "Forbidden" error message.

**Comment by MRayermannMSFT** [comment] 2020-03-09 18:03
If there is no `sp` section then that means your SAS was created using an access policy. Can you please find the `si` parameter, take that to your admin, and confirm what permissions the access policy grants you?

As for not being able to view properties, that is probably because your SAS does not give you the permissions needed to view properties. While talking to your admin, they can help answer @JasonYeMSFT 's question.

**Comment by lberny** [comment] 2020-03-10 18:34
This blobs container has not been created by one of our admins, we can't find it in Azure portal.
It's an automatically-created Ingestion Sas For AzCopy.

**Comment by JasonYeMSFT** [comment] 2020-03-16 17:57
According to the bug description, it is very likely that the blobs are treated as "folders" on the server. Please contact your admins to figure out if that is the case. We are working on having better support on those type of blobs but it won't be done for our 1.13.0 release. Let us know if there is an urgent need so we can look for some work around for you.

**Comment by phant0mski** [comment] 2020-04-07 18:59
@lberny as per this article the behavior is expected. 

Use network upload to import your organization's PST files to Office 365

[https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide#step-1-copy-the-sas-url-and-install-azcopy](url)

> **you can't delete PST files that you've uploaded to the Azure blob**. If you try to delete a PST file, you'll receive an error about not having the required permissions. Note that all PST files are automatically deleted from your Azure storage area. If there are no import jobs in progress, then all PST files in the ingestiondata container are deleted 30 days after the most recent import job was created.

I experienced the same issue today, but in my case I couldn't delete any file, not just PST files.

**Comment by MRayermannMSFT** [comment] 2020-06-29 18:15
@lberny since you haven't replied in a while we're going to go ahead and close this issue. If you're still having problems please open a new one.

@phant0mski can you please open an issue for yourself?

**Closed by MRayermannMSFT** 2020-06-29 18:15 UTC
