### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by maiki1222** [microsoft/AzureStorageExplorer#8281] opened 2024-11-07 02:24 UTC
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.0

### Architecture

x64

### Platform

Windows

### OS Version

Windows Server 2022 Datacenter

### Bug Description

When I try to see the blob I got the following error message

> Unable to retrieve child resources
> 
> ProducerError:{
>   "name": "Electron Net Error",
>   "message": "{\"name\":\"Electron Net Error\",\"cause\":{}}"
> }

Same anomaly in version 1.36.2

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand Blob Containers

### Actual Experience

Unable to retrieve child resources

ProducerError:{
  "name": "Electron Net Error",
  "message": "{\"name\":\"Electron Net Error\",\"cause\":{}}"
}

### Expected Experience

Unable to retrieve child resources

ProducerError:{
  "name": "Electron Net Error",
  "message": "{\"name\":\"Electron Net Error\",\"cause\":{}}"

**Comment by craxal** [comment] 2024-11-07 19:02
Investigating...

Duplicate of #8277.

**Closed by craxal** 2024-11-07 19:02 UTC
Labels: :white_check_mark: duplicate
