### ISSUE TITLE
Blob Container - Search Box - Does not work using extension Or Wildcard

### ISSUE THREAD

**Issue by rogeriorlima3** [microsoft/AzureStorageExplorer#787] opened 2018-10-22 19:52 UTC
**Storage Explorer Version**: 1.4.4
**Platform/OS Version**: Windows 10  64
**Architecture**: 
**Regression From**: No never worked 

#### Steps to Reproduce: ####
1. Just open Azure Explorer
2. Go to a Blob Container with several files    (images in my case)

#### Expected Experience: ####
Search by extension or using wildcard does not work.

#### Actual Experience: ####
Its is necessary to download all files and filter locally
![storage_error_1](https://user-images.githubusercontent.com/6772070/47315345-b3de8a80-d61a-11e8-9ff2-28bbef5d65b2.png)

**Comment by lucidltd** [comment] 2019-07-17 09:47
search need much improvement.

**Comment by craxal** [comment] 2020-01-27 19:18
Marking this as duplicate of #1667. Please add your comments there.

**Closed by craxal** 2020-01-27 19:18 UTC
Labels: :heavy_check_mark: duplicate
