### ISSUE TITLE
Opening tabel from emulator always results in 'The query condition specified in the request is invalid.'

### ISSUE THREAD

**Issue by WalsjeWouter** [microsoft/AzureStorageExplorer#7511] opened 2023-11-13 21:55 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.0 (95)

### Regression From

1.31.2 (94)

### Architecture

x64

### Storage Explorer Build Number

20231101.3

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Right after installing this new version, I've started it and start browing the tables of my localy running storage emulator.
After each first click on a table an empty vview/tab is opened and an error is shown:
The query condition specified in the request is invalid.

### Steps to Reproduce

1. launch explorer
2. expand emulator & attached node
3. expand storage accounts
4. expand (emulator - Default ports)
5. expand Tables
6. Select any table

### Actual Experience

No data is snown, I'm required to create a query in order to see data in the table.

### Expected Experience

I woul;d like to see all records in the table, just like in the previous version

**Comment by WalsjeWouter** [comment] 2023-11-13 22:00
![2023-11-13 22_49_38-cpt kayakers nl - Microsoft Visual Studio](https://github.com/microsoft/AzureStorageExplorer/assets/17477310/1105f004-6742-44b9-a4f0-31a9d5c7a87e)
![2023-11-13 22_56_37-Microsoft Azure Storage Explorer](https://github.com/microsoft/AzureStorageExplorer/assets/17477310/4a54e241-3f22-4c75-bd25-9ad19fbc379c)

**Comment by craxal** [comment] 2023-11-14 00:42
This issue has come up for several other users. We've found that this issue occurs in Azurite versions 3.24.0 and older. Please make sure your version of Azurite is up-do-date (at least 3.26.0).

Duplicate of #7485. If you feel that this is a different issue, leave a comment with additional details, and we will investigate further.

**Closed** 2023-11-20 17:36 UTC
Labels: :white_check_mark: duplicate
