### ISSUE TITLE
Copy not available in context menu for ADLS Gen2 blob with Data Contributor RBAC

### ISSUE THREAD

**Issue by janhurst** [microsoft/AzureStorageExplorer#2927] opened 2020-05-06 09:35 UTC
**Storage Explorer Version**: 1.13.0
**Build Number**: 20200430.5
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  present in 1.12. unsure if regression

## Bug Description ##
Unable to select "Copy" from right click context menu on ADLS Gen2 blob in a container with Reader and Storage Blob Data Contributor RBACs

## Steps to Reproduce ##
Create an ADLS Gen2 storage account and a container.
Grant Reader and Storage Blob Data Contributor to a user.
Open Azure Storage Explorer and navigate to the container.
Create a folder.
Right click folder.

## Expected Experience ##
Copy available in the right click context menu.

## Actual Experience ##
Copy is greyed out in the right click context menu and not selectable.

## Additional Context ##
Repro above using Visual Studio subscription and storage account in Australia East. I granted a separate Azure AD account to the creating account the RBACs listed.

I can't for the life of me figure out if this is correct for this RBAC combination. It appears if I grant a right higher than Reader to the management plane then the Copy option is not greyed out. I am not sure if I am misunderstanding the RBACs here or if this is a bug in Azure Storage Explorer.

**Comment by MRayermannMSFT** [comment] 2020-06-22 18:21
Duplicate of #1875

**Closed by MRayermannMSFT** 2020-06-22 18:21 UTC
