### ISSUE TITLE
The error information shows not clear when copying disk conflict

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2266] opened 2019-11-15 11:38 UTC
**Storage Explorer Version:** 1.11.0
**Build:** [20191115.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3247612)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.11.0)

**Steps to reproduce:**

1. Launch Storage Explorer -> Disks. 
2. Open a resource group -> Copy one disk and paste it to the resource group.
3. Check the activity log.

**Expect Experience:**
The error information is clear.
![image](https://user-images.githubusercontent.com/54055206/68938888-3dd73380-07da-11ea-99e9-b37b7dbaf1f3.png)

**Actual Experience:**
The error information is not clear.
![image](https://user-images.githubusercontent.com/54055206/68938898-416aba80-07da-11ea-97d4-e18a7e1dc065.png)

**Comment by MRayermannMSFT** [comment] 2019-11-15 17:12
Closing as by design/won't fix. This is a server error we can't control. But if you look at the two error's the gist of the message is the same. In the process of trying to make the "new" disk as part of doing the copy, we tried changing the property of an existing disk (since you pasted the "new" disk right where the "old" disk already was), and the server does't allow for that.

**Closed by MRayermannMSFT** 2019-11-15 17:12 UTC
Labels: :beetle: regression, :gear: disks, 🧪 testing
