### ISSUE TITLE
Cannot connect to previous or new storage

### ISSUE THREAD

**Issue by Erick-Arau** [microsoft/AzureStorageExplorer#6429] opened 2023-01-10 18:50 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.1

### Architecture

x64

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Cannot connect to registered storage

----

No se pueden recuperar los recursos secundarios.

Detalles:
{
  "name": "TypeError",
  "message": "Cannot read properties of undefined (reading 'version')",
  "stack": "TypeError: Cannot read properties of undefined (reading 'version')\n    at connectionIsV1 (C:\\Users\\erick_xxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\IConnectionInfo.js:8:24)\n    at C:\\Users\\erick_xxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\CustomConnectionStore.js:235:74\n    at Array.filter (<anonymous>)\n    at #sendTelemetry (C:\\Users\\erick_xxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\CustomConnectionStore.js:235:14)\n    at async CustomConnectionStore.getCustomConnectionStore (C:\\Users\\erick_xxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\CustomConnectionStore.js:44:9)\n    at async PersistentStorage.CustomConnections.getCustomConnections (C:\\Users\\erick_xxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\providers\\CustomConnectionsProvider.js:10:39)\n    at async Provider.executeOperation (C:\\Users\\erick_xxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async ElectronRendererHostProxy._handleExecuteRequest (C:\\Users\\erick_xxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\ElectronRendererHostProxy.js:213:35)\n    at async ElectronRendererHostProxy._handleMessage (C:\\Users\\erick_xxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\ElectronRendererHostProxy.js:156:24)"
}

----

Cannot add new storage, It doesn't accept the name to display

Need to downgrade to 1.27.0

### Steps to Reproduce

1. Launch Azure Storage Explorer
2. Expand Blob List
3. Get the error!

### Actual Experience

I lost all my connections. But, when downgrade to previous version, They appear again.

In the 1.27.1 version, when I tried to add a connection with user and key (for that specific storage we don't have a connectionstring), explorer doesn't accept the display name, no matter what you write in the textbox.

### Expected Experience

Preserve the current connections

**Comment by TroelsMuffThygesen** [comment] 2023-01-11 13:32
I have the exact same issue.

**Comment by craxal** [comment] 2023-01-11 17:53
Duplicate of #6399

**Closed by craxal** 2023-01-11 17:53 UTC
