### ISSUE TITLE
Cannot list containers in account (worked in 1.18)

### ISSUE THREAD

**Issue by SteveHawes** [microsoft/AzureStorageExplorer#4515] opened 2021-06-02 11:30 UTC
If I try to expand the Blob Containers node in one of my linked storage accounts I get the following error:

Unable to retrieve child resources.

Details:
{
  "name": "TypeError",
  "message": "Cannot read property 'UNKNOWN' of undefined",
  "stack": "TypeError: Cannot read property 'UNKNOWN' of undefined\n    at ContainerClient.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-blob-extension/node_modules/@azure/storage-blob/dist/index.js:20100:53)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-blob-extension/node_modules/tslib/tslib.js:143:27)\n    at Object.throw (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-blob-extension/node_modules/tslib/tslib.js:124:57)\n    at rejected (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-blob-extension/node_modules/tslib/tslib.js:115:69)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}

Expanding this node in a different storage account works fine.

**Comment by SteveHawes** [comment] 2021-06-02 11:34
Additional Info:

Right clicking the Containers node and selecting 'Open container by name...' and entering the name of one of the containers allows me to open that container with no issues.

**Comment by JasonYeMSFT** [comment] 2021-06-03 19:24
@SteveHawes When you said "linked storage account", do you mean you have a custom connection for it (using SAS, key)? Or did are you accessing from your signed in subscription? Also when you said "expanding this node in a different storage account works fine", do you mean the "Blob Containers" node in a separate storage account? Could you also try listing blob containers in Portal to see if this is just our problem or is also affecting Portal?

Since we changed our authentication library in 1.19.0, you can also try toggling back to use "Integrated Sign-in" (Settings -> Application -> Sign-in -> Sign-in with). Resign-in and see if things work again.

**Comment by SteveHawes** [comment] 2021-06-03 20:34
I am connecting using a connection string to two different storage accounts. One of them works fine but the other is giving the error. I can expand and see data in the tables node of both accounts (see screenshot):

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/23415735/120708015-edeeb900-c4b2-11eb-98ef-fcbd5bb35460.png">

As I am using a connection string then I do not sign in at all so cannot try signing in again. Using the StorageExplorer in the portal works fine and I see all 9 containers with no problems.

**Comment by JasonYeMSFT** [comment] 2021-06-04 17:03
Gotcha. I followed the error message and it seems to be raised by the Node SDK we are depending on, and it was supposed to represent an unknown error. Since the other storage account works fine, it may be due to some misconfiguration that causes problems in the SDK. Could you please open an issue in the SDK's repo showing this error message and link this issue there? We can track both issues and work with them to find the root cause.

SDK repo: https://github.com/Azure/azure-sdk-for-js

**Comment by JasonYeMSFT** [comment] 2022-10-10 17:19
I am going to close this issue since it is specific to a version that is too old. If you can repro the same bug with the latest version, please open a new issue.

**Closed by JasonYeMSFT** 2022-10-10 17:19 UTC
Labels: :gear: blobs, :grey_question: external
