### ISSUE TITLE
Copy command is not working after upgrading Azure Storage explorer (1.30.2)

### ISSUE THREAD

**Issue by mppradeesh** [microsoft/AzureStorageExplorer#7152] opened 2023-08-04 14:34 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.2

### Architecture

i86

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Cannot copy files using Azure Storage explorer  after upgrading to the latest version . This working earlier with older version . 

![image](https://github.com/microsoft/AzureStorageExplorer/assets/45394977/72de923a-b4a0-4586-8329-f81b487aade6)

above is the error i am getting  

Transfer of <FileName > to 'bitest99999," failed. O Items error: UnexpectedQuit (used SAS , disovery not
completed)

### Steps to Reproduce

1. Copy file from Azure Storage explorer 
2. Paste the file in destination folder 

### Actual Experience

1. Copy file from Azure Storage explorer 
2. Paste the file in destination folder 

Transfer of <FileName > to 'bitest99999," failed. O Items error: UnexpectedQuit (used SAS , disovery not
completed)

File is not copied from the source to destination folder

**Comment by MRayermannMSFT** [comment] 2023-08-04 16:12
@mppradeesh can you share the full AzCopy log with us? You can find it either in `<your home directory>/.azcopy/<latest .log file (assuming the failure was the last AzCopy operation you did)>`, or, simply reproduce the issue and look for "Go to AzCopy Log File" in the Activities panel. Then, once you've found the file, drag and drop it here in GitHub.

**Comment by mikecrepin** [comment] 2023-08-07 05:38
Good morning !   Here is the log file.
[2023-08-07_072858_activity-log_21148.log](https://github.com/microsoft/AzureStorageExplorer/files/12272467/2023-08-07_072858_activity-log_21148.log)

**Comment by MRayermannMSFT** [comment] 2023-08-07 17:02
@mikecrepin 

1. How are you accessing your container? Did you:
   1. Sign in, list storage accounts under a subscription, find your storage account, access the container?
   2. Attach the container?
2. Is this a non-Gen2 or Gen2 container?
3. What RBAC permissions do you have for the container/storage account/subscription?

**Comment by mikecrepin** [comment] 2023-08-08 16:36
Hello !
I access the container by Sign in, list storage accounts under a subscription, find your storage account, access the container.  Most of the container are used are even in the quick access part.
The container I'm try to use now is non-gen2.
How can I give you the RBAC permissions, where can I find that.

By the way, this functionality was working perfectly until the version 1.30.2 of the application.

**Comment by JasonYeMSFT** [comment] 2023-08-14 17:52
@mikecrepin To view your RBAC roles, you can login to [Azure Portal](https://portal.azure.com/), navigate to the control panel of the storage account/blob container, open the "Access control (IAM)" and use "View my access" to see roles assigned to you.

**Comment by MRayermannMSFT** [comment] 2023-09-11 15:26
Closing due to lack of reponse. This issue will no longer be actively monitored. If you still need help, we recommend reaching out to Azure support, via openeng a ticket in the Azure portal. Alternatively you can open a new issue here.

**Closed** 2023-09-11 15:26 UTC
