### ISSUE TITLE
Display two extra actions on the file share context menu for one attached account with SAS

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#613] opened 2018-08-29 09:49 UTC
**Storage Explorer Version**: 1.5.0 
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**:20180828.2
**Commit**: ca058b20
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Attach one account with SAS.
   **Display name:** alphaxuanacc
   **SAS Connection String:** [REDACTED]
2. Expand **'Local & Attached'** -> **Storage Accounts** -> The attached account **'alphaxuanacc**' -> **File Shares**.
3. Right click one file share then check the context menu.

#### Expected Experience: ####
These two actions 'Manage Access Policies...' and 'Get Shares Access Signature...' don't display on the context menu.

#### Actual Experience: ####
1. These two actions 'Manage Access Policies...' and 'Get Shares Access Signature...' display on the context menu.
2. An error occurs after clicking any one of the two actions.
![contextmenu](https://user-images.githubusercontent.com/34729022/44779863-2299ed00-ab70-11e8-8f14-b5a8c6d27cd9.png)
![error](https://user-images.githubusercontent.com/34729022/44780044-8b816500-ab70-11e8-80e8-4ff0b84edb3c.png)

#### More info: ####
1. This issue doesn't reproduce on blob containers.
2. This issue also reproduce on queues and tables.

**Comment by craxal** [comment] 2019-04-18 17:22
Removing these items requires I build some new node types, similar to how blobs does things. Since we're so close to releasing, I'm moving this to 1.9.0.

**Comment by v-xuanzh** [comment] 2019-05-22 07:19
Verified this issue on latest master build 20190522.1. it reproduces with different experience.

For **blob containers**, it only shows one extra action '**Get Shared Access Signature...**'
For **file shares**, same as previous behavior.
For **tables** and **queues**, there shows two extra actions '**Get Shared Access Signature...' and 'Manage Access Policies'**

**Comment by JasonYeMSFT** [comment] 2019-11-05 23:04
Won't fix. Let's wait for customer complaints.

**Closed by JasonYeMSFT** 2019-11-05 23:04 UTC
Labels: :gear: attach, :gear: sas, 🧪 testing

**Comment by v-xianya** [comment] 2020-06-02 06:06
Verified this issue on build master/20200602.3.
The behavior as below:
1. This issue doesn't reproduces for Blob Containers/ File Shares/ Queues.
2. This issue still reproduces for tables.
![image](https://user-images.githubusercontent.com/41351993/83485707-33605b00-a4da-11ea-9445-8d9ac942472b.png)
