### ISSUE TITLE
file fails to upload from O365 One Drive redirected desktop

### ISSUE THREAD

**Issue by paulehr** [Microsoft/AzureStorageExplorer#215] opened 2018-05-24 18:13 UTC
**Storage Explorer Version**: 1.1.0 
**Platform**: Windows
**Architecture**: ia32
**Build Number**: 20180507.1
**Commit**: bcc8990d

**Regression From**: N/A

#### Steps to Reproduce: ####

Upload a file from desktop that has been redirected to O365 One Drive account to a blob storage container on Azure Storage account

#### Expected Experience: ####
File is uploaded to blob container on storage account

#### Actual Experience: ####
failed with the following error - 

{
  "errno": -4071,
  "code": "EINVAL",
  "syscall": "stat",
  "path": "C:\\Users\\lbuapme\\OneDrive - Rich Products Corporation\\Desktop\\menus\\dk-steak-house[1].jpg"
}

#### Addition Notes - ####

I found if i were to try and upload the file from the local filesystem, not one being redirected to One Drive the upload succeeds

**Comment by craxal** [comment] 2018-05-25 18:30
Duplicate of #96.

**Closed by craxal** 2018-05-25 18:30 UTC
Labels: resolved: duplicate
