### ISSUE TITLE
Option to display blobs non-hierarchically

### ISSUE THREAD

**Issue by BruceForstall** [microsoft/AzureStorageExplorer#4195] opened 2021-03-10 23:36 UTC
**Is your feature request related to a problem? Please describe.**
I have a blob storage with 3-level folder hierarchy. It's often useful to view the blobs as a hierarchy, but it would be useful to also have an option to view them non-hierarchically. E.g., so I can sort the blobs overall by Last Modified Time, and multi-select across "folders" to delete.

**Describe the solution you'd like**
A view option to display all blobs non-hierarchically, in the same window. "Name" would be the full relative "path" including "folder" names. Folder names themselves would not exist in this view.

Related, it might be useful for a Folder view to display under "Last Modified Time", the last modified time of any blob within that folder.

**Comment by jinglouMSFT** [comment] 2021-03-10 23:43
Thanks for the feature request. This is a duplicate of #19

**Closed** 2021-03-15 17:29 UTC
Labels: :bulb: feature request, :bulb: setting candidate
