### ISSUE TITLE
The queue editor doesn't close after detaching the attached queue

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3127] opened 2020-06-19 09:55 UTC
**Storage Explorer Version:** 1.14.0
**Build**: 20200619.4
**Branch**: rel/1.14.0
**Platform/OS:** Windows 10/ macOS Catalina / Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Previous release(1.13.1)

**Steps to reproduce:**
1. Launch Storage Explorer (**Reload Storage Explorer or Open New Window** if it already opens).
2. Expand one storage account -> Queues.
3. Select one queue -> Attach it with SAS.
4. Detach the attached queue -> Check whether the corresponding editor is closed or not.

**Expect Experience:**
The editor is closed.

**Actual Experience:**
The editor is not closed.

**More Info:**
Record: https://web.microsoftstream.com/video/5bf1a3ff-0400-a936-6011-f1eab20cfbc6

**Comment by craxal** [comment] 2020-06-19 17:44
Duplicate of #2946. Reopening that bug.

**Comment by craxal** [comment] 2020-06-24 03:29
Reopening this bug; it is not a duplicate of #2946.

After further investigation, I found out the reason I couldn't reproduce was because my **(Local & Attached)** > **Queues** node was already expanded. Here's the root cause:

1. When a new queue connection is made, the queue extension is notified so it can produce a node in the tree.
2. The queue extension ensures that the **(Local & Attached)** > **Queues** node is expanded.
3. If the node was not yet expanded, it's children will be generated. This includes the new connection, and it will get a UID like "Node:80". **This scenario was not taken into account.**
4. The extension manually creates a node for the new connection and inserts it into the tree, which gets a UID like "Node:81".
5. Since "Node:80" and "Node:81" have the same data, and "Node:80" was created first, the tree does not display "Node:81".
6. The extension opens a new editor linked to the manually created node with UID "Node:81".
7. When the user starts the detach action, the action is associated with "Node:80". The extension deleted the connection and removes the node from the tree.
8. The extension also requests that all editors associated with "Node:80" be closed. But since there are none, no editors are closed.

A solution to this problem would be to, after ensuring the service node is expanded, query for an existing node matching the new connection. If it exists, get it's UID and path and open an editor against it. Otherwise, insert a new node manually as before.

Thanks to @v-xianya for helping me find the root cause!

**Comment by v-xianya** [comment] 2020-07-02 02:22
Hi @craxal 
This issue still reproduces on build 202007020.2. 
We will verify this issue on the later build.

**Comment by v-xianya** [comment] 2020-07-03 09:47
This issue still reproduces on build 20200703.4. So we re-open it.

**Closed** 2020-07-06 16:15 UTC
Labels: :beetle: regression, :gear: queues, :heavy_check_mark: merged, 🧪 testing
