### ISSUE TITLE
The action 'Change Access Tier…' is enabled for blobs under Classic storage accounts

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3310] opened 2020-07-29 08:22 UTC
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200729.1
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From:** Previous release (1.14.2)

**Steps to reproduce:**

1. Expand one **Classic** storage account -> Blob Containers.
2. Create a new blob container -> Upload one **Block** blob.
3. Check the blob's context menu.

**Expect Experience:**
The action 'Change Access Tier…' is disabled.
![image](https://user-images.githubusercontent.com/41351993/88774992-b63e2300-d1b6-11ea-9017-10d556344653.png)

**Actual Experience:**
The action 'Change Access Tier…' is enabled.
![image](https://user-images.githubusercontent.com/41351993/88774990-b50cf600-d1b6-11ea-846d-1af078d9e8af.png)

**More Info:**
1. This issue also reproduces for one **BlockBlobStorage** account.

**Comment by JasonYeMSFT** [comment] 2020-07-29 17:28
This is a side effect of enabling batch change access tier. I don't want to disable the action when the user have blobs that don't support access tier among their selection because currently there is no way to easily filter out those blobs in a select all scenario. The error detail is clear that access tier is not supported.

**Comment by v-xianya** [comment] 2020-07-30 00:50
Hi @JasonYeMSFT Thank you for the update!
1. For blobs under Classic storage accounts. The error detail tells that access tier is not supported.
2. For blobs under **BlockBlobStorage** accounts. The error details like below.
`<Message>Value for one of the query parameters specified in the request URI is invalid.\nRequestId:bf60c28c-501e-00a4-7e0a-66ceb6000000\nTime:2020-07-30T00:43:28.7464550Z</Message><QueryParameterName>comp</QueryParameterName>`
![image](https://user-images.githubusercontent.com/41351993/88867962-7a9c6b00-d241-11ea-8ab4-a4d533a6d681.png)

**Comment by JasonYeMSFT** [comment] 2020-08-04 17:46
We made a mistake by not saving classic account information for legacy quick access blob container nodes. Disabling this command by that will cause all quick access container nodes to lose this command. Move for re-triage.

**Comment by jinglouMSFT** [comment] 2020-08-04 17:48
Let's fix this in 1.15.0.

**Comment by v-limu** [comment] 2020-08-12 03:08
Hi @JasonYeMSFT 

 Verified on build 20200812.2. This issue has been fixed for the blobs. But it reproduces for **the folders**.
![image](https://user-images.githubusercontent.com/54055206/89970625-d1676300-dc8b-11ea-8893-f094176495f3.png)

**Comment by JasonYeMSFT** [comment] 2020-08-12 17:08
@v-limu, I am going to fix the block blob storage account scenario. For the classic storage account scenario, since the accountKind of blob containers in classic accounts are `undefined`, there is no way for us to distinguish them with the blob containers in Quick Access or local attachment that supports access tier. So that won't. be fixed.

**Comment by v-limu** [comment] 2020-08-13 01:27
Hi @JasonYeMSFT Got it. Thanks for your updates!

**Comment by v-limu** [comment] 2020-08-14 06:11
Verified on build 20200813.0. This issue has been fixed for one  BlockBlobStorage storage account. So close it.

**Closed by v-limu** 2020-08-14 06:11 UTC
Labels: :beetle: regression, :gear: blobs, 🧪 testing
