### ISSUE TITLE
It still displays two panels if split one tab and then close all the tabs in one of the panels

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8173] opened 2024-09-05 07:37 UTC
**Storage Explorer Version**: 1.36.0-dev (100)
**Build Number**: 20240905.2
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture**: arm64/x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.35.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Split the blob container tab.
3. The split tab is opened in a separate panel -> Close the split tab.
4. Check whether the separate panel disappears.

## Expected Experience ##
The separate panel disappears.

## Actual Experience ##
The separate panel doesn't disappear.
![image](https://github.com/user-attachments/assets/df46ca59-58f3-4eee-a5f9-c05dbb71c70b)

**Comment by craxal** [comment] 2024-09-06 22:05
Same root cause as #8172.

**Comment by v-kellyluo** [comment] 2024-09-10 02:01
Verified this issue on the build 20240910.1. Fixed.

**Comment by v-xianya** [comment] 2024-09-14 03:00
Verified this issue on the main build 20240914.2. Reproduce. So, we are going to reopen it.

**Comment by craxal** [comment] 2024-09-19 16:55
Fix has been merged.

**Closed** 2024-09-19 16:55 UTC
Labels: :white_check_mark: merged, 🧪 testing, :beetle: regression

**Comment by v-kellyluo** [comment] 2024-09-20 02:31
Verified this issue on the build 20240920.3. Fixed.
