### ISSUE TITLE
There is an error when clicking the copy related actions on Linux

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4275] opened 2021-03-30 08:48 UTC
**Storage Explorer Version**: 1.19.0-dev
**Build Number**: 20210330.6
**Branch**: main
**Platform/OS**: CentOS 7.6.1810 (Core)
**Architecture**: ia32/x64
**Regression From**: Previous release(1.18.1)

## Steps to Reproduce ##

1. Create a CentOS 7.6.1810 (Core) Linux OS -> Install and launch Storage Explorer.
2. Select one storage account -> Right click it -> Click 'Copy Primary Key' action.
3. Check there is no error.

## Expected Experience ##
There is no error.

## Actual Experience ##
There is an error.
![image](https://user-images.githubusercontent.com/54055206/112959948-85afee00-9176-11eb-9e8c-5bd560d87e1b.png)

## Additional Context ##

1. This issue reproduces for all copy related actions.
2. Storage Explorer crashes when performing the copy related actions on Linux Ubuntu 16.04/18.04.

**Comment by JasonYeMSFT** [comment] 2021-03-31 01:15
@v-limu I can reproduce the long hang after hitting Copy related actions. Is that what you mean by crash? As for the dependency issue, it shouldn't happen since it is one of the core C++ libraries that native modules need. There is nothing we can do if it is missing.

**Comment by v-limu** [comment] 2021-03-31 01:28
Hi @JasonYeMSFT  Yes. I hit Copy related actions on Linux Ubuntu 16.04/18.04. The result is the long hang and can't work.
On the same CentOS 7.6.1810 (Core) Linux OS. We verify this issue in the release 1.18.1. No error occurs and everything works well.

**Comment by JasonYeMSFT** [comment] 2021-03-31 04:45
Could you try manually adding the path to the lib and see if that workarounds the problem? https://unix.stackexchange.com/a/532121

**Comment by JasonYeMSFT** [comment] 2021-03-31 19:09
I merged a fix for the long hanging issue. Let's verify that. The missing Glibcxx is very likely related to our Electron upgrade which we cannot avoid. We will tell our Linux users to keep the dependencies up to date.

**Closed** 2021-04-01 02:46 UTC
Labels: :beetle: regression, :computer: linux, :heavy_check_mark: merged, 🧪 testing
