### ISSUE TITLE
Automated refresh

### ISSUE THREAD

**Issue by BobLj** [microsoft/AzureStorageExplorer#1365] opened 2019-05-12 01:26 UTC
When in blob container, whenever there is change you get the message: Would you like to refresh it, so I end up clicking on it 100 times a day, as soon as I change or update any of the files/folders. 
If would be nice not to.

**Comment by BulldogCTISolutions** [comment] 2019-05-16 23:00
+100.
I just upgraded to version 1.8.1 from 1.5, and dislike very much having to manually refresh.  Auto refresh was available in 1.5

**Comment by MRayermannMSFT** [comment] 2019-05-20 18:24
Hey y'all, thanks for opening the issue. We plan on switching back to the auto refresh soonish. We also already have an issue open for it, so I'll close this one and link it to that. Duplicate of #1012

**Closed by MRayermannMSFT** 2019-05-20 18:24 UTC
