### ISSUE TITLE
No 'Upload VHD' dialog pops up if clicking 'Upload' for one resource group which name contains non-ENU characters

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5847] opened 2022-06-17 08:20 UTC
**Storage Explorer Version**: 1.24.3
**Build Number**: 20220617.2
**Branch**: hotfix/1.24.3
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Create a resource group with name contains non-ENU characters. (Like 'CTI-Kristine颜')
2. Launch Storage Explorer -> Expand 'Disks' -> Open the resource group.
3. Click 'Upload' -> Check whether the 'Upload VHD' dialog pops up.

## Expected Experience ##
The 'Upload VHD' dialog pops up.

## Actual Experience ##
The 'Upload VHD' dialog doesn't pop up.

## Additional Context ##
This issue also reproduces when pasting one disk to one resource group which name contains Chinese characters.

**Comment by JasonYeMSFT** [comment] 2022-06-17 21:38
This bug shares the same root cause with https://github.com/microsoft/AzureStorageExplorer/issues/5789, except that the bug lives in a different SDK package. I also verified that this is not a regression from 1.23.x so we currently decide to leave it out of 1.24.3.

**Comment by MRayermannMSFT** [comment] 2022-10-14 19:00
Fix merged into main.

**Closed by MRayermannMSFT** 2022-10-14 19:00 UTC
Labels: 🧪 testing, :gear: disks

**Comment by v-kellyluo** [comment] 2022-10-17 02:09
Verified this issue on the build main/20221017.1. Fixed.
