### ISSUE TITLE
Bundle installation files to avoid installing 21,000+ loose JavaScript files

### ISSUE THREAD

**Issue by stewartadam** [microsoft/AzureStorageExplorer#4180] opened 2021-03-09 04:52 UTC
**Is your feature request related to a problem? Please describe.**
Installation, upgrade or removal of storage takes a long time even with modern SSDs because of the sheer number of small files involved. The installation package bundles over **21 thousand files**.

**Describe the solution you'd like**
Bundle the installation files to avoid littering the filesystem with 21k+ loose files.

**Describe alternatives you've considered**
N/A, but admittedly the friction pushes me to use alternatives like Cyberduck often

**Additional context**
Other electron-based MS apps do this already.

**Comment by MRayermannMSFT** [comment] 2021-03-15 22:47
Hi @stewartadam , this is already something we are actively moving towards. :)

**Comment by stewartadam** [comment] 2021-09-16 22:08
What's the status on this? Installing and upgrade remains a huge pain because of the number of small files. `brew upgrade` just spun for several minutes on storage explorer because of this.

**Comment by MRayermannMSFT** [comment] 2022-01-25 21:55
@stewartadam as an FYI, in our latest major release, 1.22, the number of files went from 18k to 13k. Between now and the end of this year, I'd love for us to get below 10k, but there's a lot of work that needs to be done for that. Unfortunately we have lots of things to do, so I can't promise anything, but please rest assured this is something we are actively working towards, even if only step by step.

**Comment by stewartadam** [comment] 2022-01-26 23:50
@MRayermannMSFT thanks for the update! This is good to hear.

I recognize I'm commenting from a user perspective with little knowledge of the codebase challenges involved - but wanted to share that even with a couple thousand, it's still going to cause long delays due to the high number of filesystem calls involved (particularly so if not on a solid state disk). Perhaps something like webpack can be used to minimize dependencies and bundle the numerous small files into a single, larger file?

**Comment by MRayermannMSFT** [comment] 2022-01-27 19:53
> Perhaps something like webpack can be used to minimize dependencies and bundle the numerous small files into a single, larger file?

@stewartadam  Yes, that is exactly what we are using! The issue is that the architecture of Storage Explorer was originally written without any concern for bundling. And unfortunately that also led to an architecture where we can't just simply start webpacking without doing anything else. So we're having to enable webpacking slower than you might expect.

**Comment by MRayermannMSFT** [comment] 2023-11-07 18:38
A quick update on this. We've made lots of progress in reducing the footprint of Storage Explorer on disk. Both by file count and overall app size. When this issue was first opened, the latest version of Storage Explorer (on Windows) took up 449.20 MB of space and had 17,943 files. Now the latest version is 397.00 MB and 8,087 files.

We're currently working on bundling the core of Storage Explorer, and then after that, I think there's just one or two sub-components which still need bundling. I'm hopeful (so no promise 🙃), that by mid next year we'll be well under 400 MB, with only a few thousand files.

**Comment by MRayermannMSFT** [comment] 2023-12-28 18:16
I'm going to go ahead and close this as completed in 1.33. 

After an almost 4 year battle, all JavaScript code that we're shipping is now bundled. There's one loose end left to clean up related to our native node modules (https://github.com/microsoft/AzureStorageExplorer/issues/7553), but cleaning those up isn't going to make a drastic change from where things sit as of today.

We've also de-duped a bunch of other file types (like images) leading to even more savings.

Here's a comparison of where we our latest dev build is at:

| Stats                           | 1.18.1 | 1.33.0-dev | Change |
|---------------------------------|--------|------------|--------|
| Total Files                     | 17,943 | 2,900      | -84%   |
| JavaScript Files                | 9,172  | 248        | -98%   |
| Size (MB, not incl. allocation) | 449.2  | 354.7      | -21%   |

Thanks all for the patience!

**Closed by MRayermannMSFT** 2023-12-28 18:16 UTC
Labels: :bulb: feature request, :white_check_mark: merged, :test_tube: engineering
