### ISSUE TITLE
Storage Explorer freezes when closed

### ISSUE THREAD

**Issue by ibuda** [microsoft/AzureStorageExplorer#4887] opened 2021-09-04 19:50 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Storage Explorer Build Number

20210720.10

### Platform

Linux

### OS Version

Ubuntu 21.04

### Bug Description

Storage Explorer always freezes when closing it after using it for a while.
I suppose this might be caused to the fact that I am using Nouveau drivers instead of Nvidia?
Although I do not see how that might affect it.

### Steps to Reproduce

1. Launch Storage Explorer (SE)
2. Leave it idle for a couple of hours
3. When closing SE, the system freezes for 1 minute and then unfreezes once  SE closes.

### Actual Experience

The system freezes, I cannot move the mouse or switch to any other application.

**Comment by MRayermannMSFT** [comment] 2021-09-14 21:11
@ibuda 
- Have you observed this in previous builds of Storage Explorer?
- Can you download and install the latest version of Storage Explorer from https://storageexplorer.com , and try that version?
- Are you using snap or .tar.gz?
- If the issue still reproduces with the latest version of Storage Explorer can you please [gather and share your logs with us](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#storage-explorer-logs)?

**Comment by JasonYeMSFT** [comment] 2021-10-05 17:09
The hang issue might relate to this https://github.com/electron/electron/issues/27084. From our log, if my linux Storage Explorer has been running for sufficiently, it takes 7 - 10 seconds between clicking the "Close window" button and the "close" event gets fired.

**Comment by MRayermannMSFT** [comment] 2021-10-11 18:10
Duplicate of 4965

**Closed by MRayermannMSFT** 2021-10-11 18:10 UTC
Labels: :computer: linux
