### ISSUE TITLE
There are strings not localized in About panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2470] opened 2019-12-20 08:11 UTC
**Storage Explorer Version:** 1.11.1
**Build:** [20191220.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3336432)
**Branch:** master
**Language:** Japanese/ Korean
**Platform/OS:** Windows 10/ CentOS 7.6.1810 /macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Navigate to localized Help menu -> Click localized About.
4. Observe the About panel.

**Expect Experience:**
All strings that need to be localized are localized.

**Actual Experience:**
There are strings not localized.
![image](https://user-images.githubusercontent.com/41351993/71239166-d19fa080-2340-11ea-9b19-78f2fcb4075f.png)

**More Info:**
This issue also reproduces in Korean.
![image](https://user-images.githubusercontent.com/41351993/71428318-0d4cb880-26fb-11ea-91fa-d61cc42577cd.png)

**Comment by johnliu2016** [comment] 2019-12-27 03:23
Sending to localization for review

**Comment by johnliu2016** [comment] 2020-01-08 06:12
"All rights reserved" is an approved term in Term Studio, not to localize for both Japanese and Korean.

**Comment by lukaschal** [comment] 2020-01-21 09:15
@v-xianya This is by design. Could you please close this issue ?

**Closed** 2020-01-21 09:34 UTC
Labels: 🌐 localization, 🧪 testing
