### ISSUE TITLE
Fail to transfer blobs when cloning one blob container contains blobs

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2606] opened 2020-02-07 09:47 UTC
**Storage Explorer Version**: 1.12.0
**Build**: [20200206.13](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3450293)
**Branch**: master
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Previous release(1.12.0)

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> **Upload one blob to it.**
3. Right click the blob container -> Click 'Clone with New Name...' -> Clone.
4. Check the result.

**Expect Experience:**
Succeed to transfer blobs.
![image](https://user-images.githubusercontent.com/54055206/74017417-32f20080-49cf-11ea-927b-2aec9b91bca4.png)

**Actual Experience:**

1. Fail to transfer blobs.
![image](https://user-images.githubusercontent.com/54055206/74017406-2cfc1f80-49cf-11ea-99b1-f6a1db0f4420.png)
2. Error details:
 'RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.'

**More Info:**
This issue also reproduces when copying one blob container.

**Comment by v-limu** [comment] 2020-02-11 02:09
Verified on build [20200210.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3458474). This issue has been fixed. So we close it.

**Comment by JasonYeMSFT** [comment] 2020-03-05 20:52
The operation fails because the azcopy command copying the blob fails. It should not relate to any of our code change. Can you try reproducing it on the old build and share the AzCopy log with us?

**Comment by v-xianya** [comment] 2020-03-06 03:08
@JasonYeMSFT 
Reproduce this issue on the build [20200206.13](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3450293)

Clone one blob container which contains 2 blobs. AzCopy Log please see the attached file:
[756df1db-888d-de45-4185-626cff9ea6d2.log](https://github.com/microsoft/AzureStorageExplorer/files/4296254/756df1db-888d-de45-4185-626cff9ea6d2.log)

**Comment by JasonYeMSFT** [comment] 2020-03-09 17:04
I checked the logs. The error is caused by missing "read" permission on the destination while setting overwrite to prompt. We should have prompted a warning message to let the user be aware of this issue. Did you see the prompt?

Also how did you clone a blob container such that there is no read permission on the destination? Since the src and the dst are under the same account, the destination should always have the read permission.

**Comment by JasonYeMSFT** [comment] 2020-03-18 01:35
This is caused by us generating SAS with incomplete permissions. It has been fixed in master.

**Closed by JasonYeMSFT** 2020-03-18 01:35 UTC
Labels: :beetle: regression, :gear: blobs, :grey_question: investigate, 🧪 testing
