### ISSUE TITLE
AuthorizationPermissionMismatch Error

### ISSUE THREAD

**Issue by amattap** [microsoft/AzureStorageExplorer#3162] opened 2020-06-30 17:20 UTC
**Storage Explorer Version**:  1.13.1, 1.14.0
**Build Number**:  20200624.3
**Platform/OS**:  Windows 10
**Architecture**:  x64
**Regression From**:   Yes but this didn't happen after I updated from one version to the next

## Bug Description ##

Every time I try to log in to my storage account, I can't access any container under any subscription. This has been happening for a couple weeks now. It was working one day. Then I closed the storage explorer and tried to open it again. I was still logged in, but I didn't have access to the containers any more. I tried closing the app, logging off and logging back in, turning my computer off and on, and updating the storage explorer version.  Nothing has worked. I am able to access all the other Microsoft desktop apps including Batch Explorer. Additionally, I can access, upload, download content on my storage account online - just not on the desktop app. I've scoured the internet but the only problems online seem deal with the roles. I know this is not my issue because I can access the account online. I also contacted help desk, and they said this was out of their scope.

## Steps to Reproduce ##

1. Open the app
2. Log in
3. Try to open any container
4. Get denied

## Expected Experience ##

I click on a container and I get access

## Actual Experience ##

I click on a container and I get the following error: AuthorizationPermissionMismatch. This request is not authorized to perform this operation using this permission. RequestID: 6637ee25-601e-00e0-44fe-4e4aae000000
## Additional Context ##

If you need extra information or know how to solve this issue, please ping me on teams or email my microsoft work email.

**Comment by JasonYeMSFT** [comment] 2020-07-06 18:03
I have contacted the platform team to get the service log and it seems that you are missing the Read permission of the resource (see the email response). Please ask the administrator of you RBAC group to look into it.

**Comment by JasonYeMSFT** [comment] 2020-07-23 17:36
Closing since the cause is not in Storage Explorer.

**Closed by JasonYeMSFT** 2020-07-23 17:36 UTC
