### ISSUE TITLE
The action is still 'Format JSON' instead of 'Restore JSON' when right clicking one formatted json file

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8252] opened 2024-10-21 08:16 UTC
**Storage Explorer Version:** 1.36.0-dev (101)
**Build Number:** 20241021.1
**Branch:** main
**Platform/OS:** Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture:** arm64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.35.0)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a .json file.
3. Select the .json file -> Click 'Preview'.
4. Right click the .json file -> Click 'Format JSON' -> Right click the .json file again.
5. Check whether the action changes to 'Restore JSON'.

## Expected Experience ##
The action changes to 'Restore JSON'.
![Image](https://github.com/user-attachments/assets/6e7be033-9939-4808-aef0-b028a506abcd)

## Actual Experience ##
The action doesn't change to 'Restore JSON'.
![Image](https://github.com/user-attachments/assets/6f3466c2-5985-485d-938c-b9d19a2b09a1)

**Comment by craxal** [comment] 2024-10-21 16:46
Duplicate of #8250

**Closed by craxal** 2024-10-21 16:46 UTC
Labels: 🧪 testing, :gear: blobs, :gear: files, :beetle: regression
