### ISSUE TITLE
Deleting multiple blob containers is slow and inefficient, allow multiple blobs to be deleted at once.

### ISSUE THREAD

**Issue by ekordd** [microsoft/AzureStorageExplorer#6546] opened 2023-02-10 15:02 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

When using azure storage explorer with ADLS gen 2 sas storage, you can end up with a long list of previously used blobs. This clutters up the UI sidebar and makes it harder to discern which ones you are using as you end up with a long list of blobs, for which deletion is a slow process.

### Desired Solution

Have more options when deleting blobs. A delete all button and the option to select multiple blobs, this could be in the form of a ui check box that appears next to each blob. This would allow you to select all, then deselect whichever ones. Whilst doing this you could also add the option to control click multiple blobs and then right-click delete. Additionally, you could have the feature to set a preselected deletion time for sas blobs. Say 1day after last used.

### Alternatives and Workarounds

At the moment the only way i can see is to go through the laborious process of deleting each blob one by one.

**Comment by MRayermannMSFT** [comment] 2023-02-13 18:49
@ekordd are you referring to your blob containers in the tree view?

**Comment by ekordd** [comment] 2023-02-14 12:02
I believe so, this is when they are viewed in the explorer tab.

**Comment by ekordd** [comment] 2023-02-14 12:03
Is there a way that i havent realised of managing this better?

**Comment by MRayermannMSFT** [comment] 2023-02-27 21:36
No, there is not a faster way. I'm going to mark this as duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/852.

**Closed by MRayermannMSFT** 2023-02-27 21:36 UTC
