### ISSUE TITLE
Downloading files from a blob that are currently opened for writing elsewhere results in HTTP 412

### ISSUE THREAD

**Issue by VivaLosDoyers** [microsoft/AzureStorageExplorer#4200] opened 2021-03-11 17:49 UTC
**Storage Explorer Version**: 1.18.0
**Build Number**: 20210304.5
**Platform/OS**: Windows 10 1903 Enterprise
**Architecture**: x64

## Bug Description ##
We are using a blob to store log files generated by an application. This application does quite a bit of debug logging, so the file is open for writing more often than not. We want to download these files from the blob at will. If the application currently has the file open for writing when we attempt to download from the blob, it seems a race condition occurs and the following error appears:

2021/03/10 18:40:49 ERR: [P#0-T#0] DOWNLOADFAILED: https://[REDACTED].blob.core.windows.net/[REDACTED].log?se=2021-04-09t18%3A40%3A09z&sig=-REDACTED-&sp=rl&sr=c&sv=2020-04-08 : 412 : 412 The condition specified using HTTP conditional header(s) is not met.. When Enqueuing chunk. X-Ms-Request-Id: [REDACTED]

## Steps to Reproduce ##
1. Application creates a file in a blob and holds it open and writes continuously
2. Connect to the blob using Azure Storage Explorer and attempt to download the file

## Expected Experience ##
A snapshot of the file downloads in the client

## Actual Experience ##
HTTP 412 error

## Additional Context ##
In the past, a developer on [this StackOverflow post ](https://stackoverflow.com/questions/5094089/azure-blob-the-condition-specified-using-http-conditional-headers-is-not-met)ran into this problem whilst developing an application that downloads files from a blob. His solution was to use a different method for reading. I'm wondering if Azure Storage Explorer has the same issue. 
Note that files that are not open for writing by the application download properly 100% of the time, so I'm fairly certain of the cause.

**Comment by JasonYeMSFT** [comment] 2021-03-11 18:59
@VivaLosDoyers Blobs are stored as blocks/pages. The download works block by block so if something overwrites in the middle of it, the download tool (AzCopy) cannot guarantee the data integrity so it simply abort. Directly use the read API without setting the control header will download something, but it won't guarantee the data integrity. A simple solution to this periodical write + occasional download scenario is to acquire a lease on the blob when you want to download it, which blocks writing. Once you downloaded the blob, you can break the lease.

There are more details in this article: https://docs.microsoft.com/azure/storage/blobs/concurrency-manage

**Comment by VivaLosDoyers** [comment] 2021-03-11 19:04
@JasonYeMSFT thanks for the reply. I suspect that if we attempt to grab the lease on the file, this would cause the upstream application to fail when it tries to append the file. Is this true?

Also, I've noticed that if I download these files manually using ```az storage azcopy blob download```, the download works every time.

So I'm curious what the behavioral difference is between a manual azcopy and what Storage Explorer is doing when downloading a file.

FWIW, the flags I pass to azcopy are --connection-string, -d, -s, and -c

**Comment by JasonYeMSFT** [comment] 2021-03-11 19:47
Yes, the upstream application won't be able to append if there is a lease. It is generally a good practice to make the upstream application handle transient failures gracefully. 

I am not sure how Azure CLI invokes AzCopy. Storage Explorer invokes an azcopy executable on your local machine, which should be identical to directly running it in the command-line. Checking for source being changed is permanently enabled for upload/download. You can try downloading the GAed AzCopy bits and execute the failed command there (get the command from "Copy AzCopy command" in Storage Explorer). Let us know if you see any difference between your local AzCopy executable and Storage Explorer.

If you decide to work with the Azure CLI azcopy extension, make sure you check for the file integrity before using the file.

**Comment by JasonYeMSFT** [comment] 2021-03-11 21:39
We get some advice from the AzCopy team. They recommended using the "snapshot" feature to take a snapshot of the blob and download the snapshot instead. That won't block the upstream application.

**Comment by JasonYeMSFT** [comment] 2021-03-18 22:15
Closing as by design.

**Closed by JasonYeMSFT** 2021-03-18 22:15 UTC
Labels: :heavy_check_mark: by design
