### ISSUE TITLE
Keep loading more than 10 mins after expanding 'Blob Containers' which containers $web for one GPV2 account

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#330] opened 2018-06-20 09:08 UTC
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Build Number**: 20180619.1
**Commit**: 3b2233d5
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription(Azure Tools Manual Testing 1) -> Storage Accounts.
2. Choose one GPV2 account like 'alphaxuantest' which is deployed to Static Website(The step is implemented on VS Code with Azure Storage extension).
3. Check the resources of the account 'alphaxuantest' in portal and make sure the blob container named '$web' displays.
4. Back to Storage Explorer then try to expand the 'Blob Containers' node under the selected GPV2 account.

#### Expected Experience: ####
The 'Blob Containers' node can be expanded successfully.

#### Actual Experience: ####
Keep loading more than 10 mins after expanding 'Blob Containers' under the account.
![expand](https://user-images.githubusercontent.com/34729022/41644966-274ddbec-745f-11e8-8274-b5686782860c.png)

**Comment by craxal** [comment] 2018-06-22 16:08
Duplicate of #223.

**Closed by craxal** 2018-06-22 16:08 UTC
Labels: :white_check_mark: duplicate, testing
