### ISSUE TITLE
The 'Yes' button is focused on the 'warn before exit' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4657] opened 2021-07-07 10:52 UTC
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210707.4
**Branch**: main
**Platform/OS**:  Linux Ubuntu 18.04
**Architecture**: x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload -> Upload Files...' -> Select several blobs then click 'Upload'.
3. Make sure the upload activity is in progress
4. Try to reload the Storage Explorer -> A dialog pops up.
5. Check whether the 'No' button is focused.
 
## Expected Experience ##
The 'No' button is focused.

## Actual Experience ##
The 'Yes' button is focused.
![image](https://user-images.githubusercontent.com/41351993/124747643-ffbee400-ded6-11eb-8fd9-dfc7503a6c50.png)

**Comment by MRayermannMSFT** [comment] 2021-07-09 22:18
Same root cause as/duplicate of #4661

**Closed by MRayermannMSFT** 2021-07-09 22:18 UTC
Labels: :computer: linux, 🧪 testing

**Comment by v-kellyluo** [comment] 2021-09-06 09:49
Hi @MRayermannMSFT,

Verified this issue on the rel/1.21.0 build 20210905.1. The warning dialog is as below, and the 'Yes' button is selected in the warning dialog on Windows & Linux.
![image](https://user-images.githubusercontent.com/87792676/132197143-035c0dd1-5d99-41eb-b364-95d87357c072.png)
