### ISSUE TITLE
Gzipping on the Fly

### ISSUE THREAD

**Issue by xbaha** [microsoft/AzureStorageExplorer#2359] opened 2019-11-30 02:28 UTC
I'd like to see Azure Storage Explorer to Gzip my files, set the property to gzip-compressed on the fly, this is for static hosting.

I am not sure if this option exist yet, but it's a must option! imagine I have 100s of CSS HTML and js, why should someone go through all the trouble for gzipping and setting the property of each!

**Comment by pharring** [comment] 2019-12-04 20:54
I have a similar request but for download. We have blobs that are stored with gzip compression and the the ContentEncoding property is set to gzip. I'd like to download them using Storage Explorer and have Storage Explorer automatically inflate the downloaded blob.

**Comment by MRayermannMSFT** [comment] 2020-04-14 23:52
AzCopy has an option to inflate gzipped files when downloading. We're going to go ahead and get this exposed in 1.14. This is what @pharring and, @icnatejackson and @nbevans from #758, were asking for.

@xbaha , for you though are you saying that you have the desire for us to deflate/compress to gzip on upload?

**Comment by MRayermannMSFT** [comment] 2020-05-11 16:49
A setting has been added for 1.14.0 that will expose the decompress flag:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/21112697/81587935-98f27900-936c-11ea-9333-668b0187c62c.png">
@xbaha , I'm going to go ahead and close this issue. If you are also looking for gzip/compress on upload, please open a new issue and we can discuss it there. Thanks!

**Closed by MRayermannMSFT** 2020-05-11 16:49 UTC
Labels: :bulb: feature request, :gear: azcopy

**Comment by th0ger** [comment] 2020-11-02 10:53
I enabled the settings, but could not get it decompress on download.

My content type is "application/x-gzip" as displayed in the "Content Type" column of ASE.
The files were created with 7z (windows) and gzip (linux), and both create x-gzip.
I've read that x-gzip and gzip should be equivalent.

Is the x-gzip encoding unsupported, or am I missing something else?

**Comment by pharring** [comment] 2020-11-02 17:57
Works for me with ContentEncoding gzip

Just to clear up any confusion: This doesn't work with .zip or .tar archives. It works for individual files compressed with the "gzip" or "deflate" algorithms.

Also, I don't think it matters for decompression, but really you should set the ContentType to the type of the original, decompressed file (e.g. text/plan, application/json, application/octet-stream, etc.). If you've ever had to serve static content from web sites, this should be familiar.

**Comment by th0ger** [comment] 2020-11-03 06:40
Thanks @pharring . I simply do:
`gzip file.log` (ContentType `text/plain; charset=utf-8`) -> `file.log.gz` (ContentType `application/x-gzip`)
I don't see any flags for setting ContentType or ContentEncoding for gzip. The same goes for 7z.

I've tried to set  ContentType `text/plain; charset=utf-8` and ContentEncoding `gzip` after upload to Storage Explorer, as per your suggestion. No luck.

Btw, I'm running Windows 10 (and gzip on WSL).

**Comment by pharring** [comment] 2020-11-03 16:46
Well, it works for me using the same set-up as long as I set the ContentEncoding to gzip after upload. Are you sure you set the "Decompress Files" option in Storage Explorer's settings? (In the "Transfer" section)
![image](https://user-images.githubusercontent.com/9952654/98014804-f06c2180-1db0-11eb-940c-3c31ba761306.png)

**Comment by th0ger** [comment] 2020-11-06 18:02
After some debugging, we found that the "Decompress Files" flag is not always saved correctly. We saw this on another pc as well, but could not reproduce it consistently.

When the setting is saved, and we set ContentEncoding to gzip, it works.
