### ISSUE TITLE
Display a confused notification message on one empty resource group editor

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1794] opened 2019-09-05 09:54 UTC
**Storage Explorer Version:** 1.10.0
**Build:** 20190905.11
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Disks' node -> Open one empty resource group.
2. On the opened editor, check the shown message on the bottom of left.

**Expect Experience:**

There shows 'Showing 0 to 0 of 0 **disks**'
![image](https://user-images.githubusercontent.com/34729022/64331310-2115c700-d005-11e9-9062-a8079e207f6f.png)

**Actual Experience:**

There shows 'Showing 0 to 0 of 0 **entitries**'
![image](https://user-images.githubusercontent.com/34729022/64331302-1e1ad680-d005-11e9-9b46-fd0caadb1cac.png)

**Comment by craxal** [comment] 2019-09-05 18:33
Duplicate of #1697.

**Closed by craxal** 2019-09-05 18:33 UTC
Labels: :gear: disks, 🧪 testing
