### ISSUE TITLE
Show Queue metadata

### ISSUE THREAD

**Issue by csalgo70** [microsoft/AzureStorageExplorer#681] opened 2018-09-20 04:08 UTC
**Storage Explorer Version**:  1.4.1 
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: NA

#### Expected Experience: ####
Currently there seems to be no option to view a Queue's metadata. Would be nice to show that under properties section when the queue is selected.

**Comment by JasonYeMSFT** [comment] 2020-08-28 18:14
Related to #2664

**Comment by MRayermannMSFT** [comment] 2020-09-08 17:22
Duplicate of 2664

**Closed by MRayermannMSFT** 2020-09-08 17:22 UTC
Labels: :white_check_mark: duplicate
