### ISSUE TITLE
Ability to rename tabs

### ISSUE THREAD

**Issue by cpwood** [microsoft/AzureStorageExplorer#2679] opened 2020-02-28 17:24 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes I end up with multiple tabs with the exact same name - perhaps from different databases, hosts or subscriptions. I then can't identify which is which without hovering over the tab to see the full path to the "thing" I'm looking at (e.g. Storage Table, Cosmos collection, etc).

I also might have multiple query tabs - it would help to be able to describe the query in the tab name - e.g. "Customers in the UK".

**Describe the solution you'd like**
The ability to rename a tab to something that's more useful / reflective of my needs.

**Describe alternatives you've considered**
Different coloured tabs according to the database, host, subscription - though quite how you'd keep track of what colour is what is not clear. Don't like this as an approach.

**Comment by saryeHaddadi** [comment] 2023-08-13 10:40
For the record, when pinned to Quick Access, we are able to rename containers, but the tabs display the original name, not the alias. I would also appreciate if the tabs could display the alias.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/51054901/8ba90a77-c97f-43bc-8511-6fad3e47881f)

**Comment by MRayermannMSFT** [comment] 2024-05-20 23:05
Closing as dupe of https://github.com/microsoft/AzureStorageExplorer/issues/4

**Closed by MRayermannMSFT** 2024-05-20 23:05 UTC
Labels: :bulb: feature request
