### ISSUE TITLE
'Paste' should be removed from the blob context menu

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#122] opened 2018-05-02 10:27 UTC
**Storage Explorer Version**: 1.1.0 RC
**Platform**: Windows/Linux/Mac
**Architecture**: x64
**Build Number**: 20180501.4
**Commit**: 754b96f7
**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand storage accounts.
2. Open one blob container and right click one blob.
3. Check the context menu.

#### Expected Experience: ####
'Paste' doesn't display on the context menu.

#### Suggestion: ####

All the actions on the context menu are the behavior of the selected items, Actually 'Paste' belongs to the current container/folder operation. 
So the 'Paste' should be removed from the blob context menu.

**Comment by MRayermannMSFT** [comment] 2018-05-10 18:43
Closing as by design/won't fix.

**Closed by MRayermannMSFT** 2018-05-10 18:43 UTC
Labels: feature request, resolved: won't fix, testing
