### ISSUE TITLE
The description '(inferred)' of Access Tier doesn't display for one uploaded blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1743] opened 2019-08-29 09:54 UTC
**Storage Explorer Version**: 1.9.0
**Build:** master_20190828.15
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Make sure AzCopy is unchecked.
2. Expand one StorageV2 account -> Blob Containers.
3. Create a new blob container -> Upload one blob.
4. Check the value of the blob's Access Tier in the editor.

**Expect Experience:**

The description '(inferred)' displays in the editor.
![image](https://user-images.githubusercontent.com/54055206/63930202-6e35ee00-ca85-11e9-8cb5-9280c8cb2831.png)

**Actual Experience:**

The description '(inferred)' doesn't display in the editor.
![image](https://user-images.githubusercontent.com/54055206/63930109-48104e00-ca85-11e9-95f9-b7992516d384.png)

**More Info:**
1. The description '(inferred)' displays after refreshing manually.
2. This issue doesn't reproduce when AzCopy is checked.

**Comment by MRayermannMSFT** [comment] 2019-09-23 18:34
Won't fix since "This issue doesn't reproduce when AzCopy is checked."

**Closed by MRayermannMSFT** 2019-09-23 18:34 UTC
Labels: :gear: blobs, 🧪 testing
