### ISSUE TITLE
Storage account with static website hosting enabled doesn't open blob containers

### ISSUE THREAD

**Issue by shahiddev** [Microsoft/AzureStorageExplorer#370] opened 2018-06-29 13:39 UTC
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows/ Windows 10 1803 (Version	10.0.17134 Build 17134)
**Architecture**: ia32
**Regression From**:  n/a

#### Steps to Reproduce: ####
1. Connect to storage account (GPv2) using storage key or connection string with **website hosting enabled**
2. Expand node for blob containers

#### Expected Experience: ####
Blob containers node should expand and display containers (in this case just the $web container)

#### Actual Experience: ####
Blob containers node doesn't show containers just spins with Loading... forever
![image](https://user-images.githubusercontent.com/11890711/42095287-15d55aa0-7baa-11e8-9688-e566fd2bce2e.png)

Relevant log error
```
Uncaught SyntaxError: Container name format is incorrect.
    at getNameError (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\azure-storage\lib\common\util\validate.js:186:12)
    at ArgumentValidator.exports.containerNameIsValid (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\azure-storage\lib\common\util\validate.js:204:19)
    at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\azure-storage\lib\services\blob\blobservice.core.js:2357:7
    at Object.validateArgs (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\azure-storage\lib\common\util\validate.js:556:3)
    at Object.BlobService.getUrl (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\azure-storage\lib\services\blob\blobservice.core.js:2355:12)
    at createAzureStorageResource (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\Azure\AzureStorage\BlobManager.js:424:47)
    at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\Azure\AzureStorage\BlobManager.js:356:45
    at Array.forEach (<anonymous>)
    at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\Azure\AzureStorage\BlobManager.js:354:25
    at finalCallback (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\azure-storage\lib\services\blob\blobservice.core.js:407:7)
    at postProcessWrapper (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\Azure\AzureStorage\StorageFilters.js:34:17)
    at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\azure-storage\lib\common\services\storageserviceclient.js:788:17
    at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\azure-storage\lib\common\filters\retrypolicyfilter.js:187:13
    at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\azure-storage\lib\common\services\storageserviceclient.js:788:17
    at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1000:11
```

**Comment by shahiddev** [comment] 2018-06-29 13:40
I should point out that the "hosted" storage explorer in the portal seems to see the $web container fine and allows uploads as expected

**Comment by JasonYeMSFT** [comment] 2018-06-29 16:03
Hi @shahiddev, the static website is a new feature added to the Azure Storage service after our last release. Our last release doesn't include the necessary changes to adapt this feature. We will include this feature in the next release. Sorry for the inconvenience.

**Comment by craxal** [comment] 2018-06-29 18:03
Duplicate of #223. @shahiddev, if you feel your issue is different, let us know how, and we'll reopen for investigation.

**Closed by craxal** 2018-06-29 18:03 UTC
Labels: :x: bug
