### ISSUE TITLE
Windows Portable version

### ISSUE THREAD

**Issue by baltuonis** [microsoft/AzureStorageExplorer#2619] opened 2020-02-11 16:30 UTC
**Is your feature request related to a problem? Please describe.**
Current windows build (setup) requires administrator rights. This is a problem when working on limited access machines.

**Describe the solution you'd like**
Provide a portable standalone build for windows (like we have in Linux)

**Describe alternatives you've considered**
Tried to manually extract the setup, but that did not work.

**Additional context**

**Comment by MRayermannMSFT** [comment] 2020-02-18 22:15
Duplicate of #1108

**Closed by MRayermannMSFT** 2020-02-18 22:15 UTC
