### ISSUE TITLE
Auto open two tabs when attaching one blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2996] opened 2020-05-18 09:35 UTC
**Storage Explorer Version:** 1.14.0-dev
**Build**: [20200518.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3736141&view=results)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture**: ia32/x64
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Attach it via SAS.
3. Check the result.

**Expect Experience:**
Open one tab.

**Actual Experience:**
Open two tabs.
![image](https://user-images.githubusercontent.com/54055206/82196955-ee122a00-992c-11ea-9417-601055ded6eb.png)

**More Info:**
This issue doesn't reproduce for one file share /queue /table.

**Comment by JasonYeMSFT** [comment] 2020-05-18 19:05
I cannot reproduce the issue. Could you please take a screen recording for the issue?

**Comment by v-limu** [comment] 2020-05-19 06:39
Hi @JasonYeMSFT  Verified on build [20200519.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3738672&view=results). This issue still reproduces. Please see the below.

https://web.microsoftstream.com/video/d72ca4ff-0400-96d4-9ba6-f1ea9979836a

**Comment by v-xianya** [comment] 2020-05-20 09:36
This issue is fixed on build master/[20200520.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3742543&view=results). So we close it.

**Closed by v-xianya** 2020-05-20 09:36 UTC
Labels: :beetle: regression, :gear: attach, :gear: blobs, 🧪 testing
