### ISSUE TITLE
Warn if upgrading Storage Explorer will require a Storage Emulator upgrade

### ISSUE THREAD

**Issue by brianbrane** [Microsoft/AzureStorageExplorer#509] opened 2018-07-27 12:25 UTC
**Storage Explorer Version**: 1.3.1:
**OS/Platform**: Windows 10
**Storage Emulator Version**: 5.4.0.0

#### Steps to Reproduce: ####
1. I upgraded to version 1.3.1
2. When I try to open blobs or tables from local storage, I get error: The REST version of this request is not supported by this release of the Storage Emulator. Please upgrade the storage emulator to the latest version.

#### Expected Experience: ####
Ideally, Storage Explorer should be backward compatible with Storage Emulator. Otherwise, the installation should warn that Storage Emulator will have to be upgrade.

#### Actual Experience: ####
I can't view my local data without upgrading Storage Emulator, which deletes the local data that I want to see. Therefore, I'll have to downgrade Storage Explorer for now.

**Comment by craxal** [comment] 2018-07-27 20:30
Duplicate of #459.

**Closed by craxal** 2018-07-27 20:30 UTC
Labels: :gear: emulator, :white_check_mark: duplicate
