### ISSUE TITLE
An error info bar pops up after using proxy with the fiddler configured correctly

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6640] opened 2023-03-03 10:23 UTC
**Storage Explorer Version** : 1.29.0-dev
**Build Number** : 20230302.17
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce 

1. Install Storage Explorer -> Run at least once -> Close Storage Explorer.
2. Install Fiddler -> Configure the fiddler -> Open Storage Explorer.
3. Click 'Edit -> Configure Proxy' -> Select 'Use app proxy settings' -> Set the URL: 'http://localhost' Port: '8888' -> Click 'OK'.
4. Restart Storage Explorer.
5. Check whether no error info bar pops up.

## Expected Experience 
No error info bar pops up.

## Actual Experience ##
An error info bar pops up.
![image](https://user-images.githubusercontent.com/122582307/222694545-10d2f8f1-4ad5-4490-9aa0-eb0bf86c0bc3.png)
Error:
`Unable to establish connection using current proxy settings. Please verify current settings by accessing the proxy dialog in the toolbar.`

## Additional Context ##
1. This issue also reproduces when selecting proxy 'Use environment variables'.
2. This issue doesn't reproduce when selecting proxy 'Use system proxy (preview)'.

**Comment by JasonYeMSFT** [comment] 2023-03-04 00:54
I believe this issue is due to localhost being resolved to ::1, the ipv6 version of 127.0.0.1. I can reproduce it and workaround it by switching to use 127.0.0.1.

**Comment by JasonYeMSFT** [comment] 2023-03-06 21:41
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V17.md
(SEMVER-MAJOR) dns: default to verbatim=true in dns.lookup() (treysis)

**Comment by JasonYeMSFT** [comment] 2023-03-06 23:00
I am going to workaround this issue. Once the workaround is merged Fiddler should start working again.

**Comment by v-sunnsun** [comment] 2023-03-08 01:49
Verified this issue on the build main 20230307.6. Fixed. So, we are going to close it.

**Closed** 2023-03-08 01:50 UTC
Labels: :heavy_check_mark: merged, 🧪 testing, :gear: proxy, :beetle: regression
