### ISSUE TITLE
No activity log shows when acquiring/ breaking lease for one regular blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2434] opened 2019-12-13 09:54 UTC
**Storage Explorer Version:** 1.11.2
**Build:** [20191213.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3318376)
**Branch:** hotfix/1.11.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous build ([20191212.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3315517&view=results))

**Steps to reproduce:**
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one file.
3. Acquire lease for the uploaded blob.
4. Check the Activities panel.

**Expect Experience:**
Show activity log.

**Actual Experience:**
No activity log shows.

**More Info:**
1. No activity log shows when breaking lease for one regular blob.
2. This issue doesn't reproduce for one ADLS Gen2 blob container/ blob.
3. No activity log shows when acquiring/ breaking lease for one regular blob Container( related bug: [2422](https://github.com/microsoft/AzureStorageExplorer/issues/2422)).

**Comment by MRayermannMSFT** [comment] 2019-12-13 17:00
Since the tested build is a hotfix of 1.11.1, this bug is expected to reproduce. It has already been fixed on master though for 1.12.0.

**Closed by MRayermannMSFT** 2019-12-13 17:00 UTC
Labels: :beetle: regression, :gear: blobs, 🧪 testing
