### ISSUE TITLE
Unable to delete a file with hash "#" in the name

### ISSUE THREAD

**Issue by steve-torchia** [Microsoft/AzureStorageExplorer#7995] opened 2024-06-10 13:34 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.1

### Architecture

x64

### Storage Explorer Build Number

20240410.2

### Platform

All

### OS Version

Windows 11

### Bug Description

Using storage explorer, I am unable to delete a file that has the hash (#) character in it.  When I try, I get the following error:

> 2024/06/10 13:24:20 ERR: [P#0-T#0] https://xxxxxxx.dfs.core.windows.net/xxxxxx/xxxxxxx/ERCOT%23SPP.HB_NORTH.RTM_HU--20240402_20240531_15Mins~raw~20240531T195911.csv: 404: DELETE ERROR -404 The specified path does not exist.. X-Ms-Request-Id:bc6dfd78-301f-006c-3a39-bb7dea000000

I am able to save/preview/edit those files using Storage Explorer

I am able to delete these files using the **Azure Portal's Storage Browser** for the same storage account.  

### Steps to Reproduce

Launch Storage explorer
upload a file to a container/folder/etc...   i.e. #MyTestFile.txt
Try to delete that file
>> Error as mentioned in description

### Actual Experience

see steps to repro

### Expected Experience

File should be able to be deleted

**Comment by craxal** [comment] 2024-06-10 18:19
@steve-torchia This should have been fixed in 1.34.0. Please update and try again.

Duplicate of #7916.

**Closed as not planned by craxal** 2024-06-10 18:19 UTC
Labels: :white_check_mark: duplicate
