### ISSUE TITLE
Cannot reorder a message whose size is 0 B

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6859] opened 2023-05-05 07:04 UTC
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230505.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a queue -> Add one message with 0 B.
3. Add another message with content.
4. Reorder the two messages by size.
5. Check whether succeeds to reorder the two messages.

## Expected Experience ##
Succeeds to reorder the two messages.

## Actual Experience ##
Fail to reorder the two messages.

## Additional Context ##
A message of size 0 B defaults to being the last message.

**Comment by JasonYeMSFT** [comment] 2023-05-08 18:06
@craxal Please investigate the cause of the bug and see if it needs a hot fix?

**Comment by craxal** [comment] 2023-05-08 22:30
Cause is due to a test that mistakes 0 for null or undefined, and null/undefined items are ordered after all defined items. To fix, thee code just needs to test more specifically for null or undefined instead of falsy values.

**Comment by v-kellyluo** [comment] 2023-05-09 02:23
Verified this issue on the build 20230509.5. Fixed. So, we are going to close it.

**Closed by v-kellyluo** 2023-05-09 02:23 UTC
Labels: :heavy_check_mark: merged, 🧪 testing, :gear: queues, :beetle: regression
