### ISSUE TITLE
Only the subscription of one azure account displays if running 'Search From Here' for it when there are two azure accounts with the same subscription

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6145] opened 2022-10-09 09:48 UTC
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20221006.3
**Branch**: feature branch
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.26.0)

## Steps to Reproduce ##
1. Sign in two Azure accounts (A and B) that have the same subscription (like: '**subscription1**').
2. Check '**subscription1**' for the two accounts -> Click 'Open Explorer'.
3. Click 'Collapse all'.
4. Right click the '**subscriptioin1**' for account A -> Click 'Search From Here'.
5. Check whether '**subscription1**' of the two accounts display.

## Expected Experience ##
The **subscription1** of the two accounts display.
![image](https://user-images.githubusercontent.com/41351993/194748689-d763032e-1c45-44c6-b264-0fecb38b3cb7.png)

## Actual Experience ##
The **subscription1** of the account A displays.
![image](https://user-images.githubusercontent.com/41351993/194748693-6b150781-f915-4998-b92d-6693f2967230.png)

**Comment by MRayermannMSFT** [comment] 2022-10-10 16:21
Going to close this one as by design. The "search from here" action now works only for the node you executed the action on. This was done to decrease the amount of time it takes to scope the tree after executing the action. Both nodes will show up though if you manually type/paste the path into the search box and click on the search button/icon.

**Closed by MRayermannMSFT** 2022-10-10 16:21 UTC
Labels: 🧪 testing, :beetle: regression
