### ISSUE TITLE
[sprintf] expecting number but found string

### ISSUE THREAD

**Issue by brian-miller2019** [microsoft/AzureStorageExplorer#5896] opened 2022-07-01 17:51 UTC
I'm getting this error now anytime I filter blob storage results -> select all cached-> delete. This was working fine prior to the current version which I just upgraded to. This is on a classic storage account. I can still delete a single page worth of objects.

**Comment by MRayermannMSFT** [comment] 2022-07-11 21:54
@brian-miller2019 can you give/show an example of how you are filtering? Are you filtering by prefix or by tag? Please feel free to share screenshots. I am asking because I am so far unable to reproduce this. Thanks!

**Comment by brian-miller2019** [comment] 2022-07-11 23:04
Hi~

I'm filtering by prefix:
[image: image.png]

After the filter is applied I make sure I've gone to the very last page:
[image: image.png]

And then I 'select all cached'
[image: image.png]

then when I click on the 'Delete' button I see this screen:
[image: image.png]

instead of what I'd expect to see, such as this:
[image: image.png]

I'm guessing that it's having some problem passing in the total number of
items to delete into the message box...

About screenshot:
[image: image.png]

I did a couple of other multi-page 'select all cached' deletes and those
went fine but they were only about 2 pages in total, so there weren't as
many objects to delete, compared to the 1,500-ish I'm trying to delete at
once when I receive this error.

If I can give you any other information just let me know, thanks!

~Brian

**Comment by formula349** [comment] 2022-07-12 16:08
I'm getting the same error. Filtering by prefix, selecting all cached, delete. Trying to delete the first 1,000 cached.

**Comment by brian-miller2019** [comment] 2022-07-12 17:19
I updated my comment, not sure why the images aren't showing in-line for me at the moment, but at least you can click on the links to view the screen grabs. Let me know if you need any others.

**Comment by brian-miller2019** [comment] 2022-07-12 18:41
I'm good with waiting until 1.25, I've no rush on this, thank you!

**Comment by MRayermannMSFT** [comment] 2022-07-19 17:28
Merged everything needed to fix this.

**Closed by MRayermannMSFT** 2022-07-19 17:28 UTC
Labels: :beetle: bug
