### ISSUE TITLE
Actually, all files have been successfully deleted, but after expanding the deleted group, the process still displays the queue.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/AzureStorageExplorer#2217] opened 2019-11-05 10:48 UTC
**Storage Explorer Version:** 1.11.0
**Build Number:** 20191102.1
**Platform/OS:** macOS High Sierra
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)
**Regression From:** Not a regression

**Steps to reproduce:**

1. Open ASE
2. Sign in to Azure
3. Expand the Data Lake Storage Gen1 (Preview) node
4. Select all files and delete
5. Check the Activities
6. Expand the Deleted Group
7. Check the process status

**Expect Experience:**
Display deleted successfully.

**Actual Experience:**
Still displays the queue.
![image](https://user-images.githubusercontent.com/40199316/68201460-c4cb2580-fffc-11e9-942d-5c0f8b7e1c01.png)

**Comment by jinglouMSFT** [comment] 2019-11-05 18:46
This doesn't look like Mac specific.  If this is not a regression, it means the bug has been there since Gen1 was supported. It's unfortunate that the team used to own it didn't fix the issue, but since this is purely cosmetic and Gen1 is being deprecated. I'd vote won't fix.

**Closed by jinglouMSFT** 2019-11-05 18:46 UTC
