### ISSUE TITLE
Stop signing in for every tenant the identity is connected to.

### ISSUE THREAD

**Issue by isaacabraham** [microsoft/AzureStorageExplorer#4038] opened 2021-01-31 00:51 UTC
I'm always frustrated when I load Azure Storage Explorer.

Every few weeks the auth token expires (I assume) and I need to re-authenticate again. That in itself would be tolerable, except the same login dialog appears for *every single tenant* that my identity is connected to. Since I have many customers on Azure, this can be anywhere between 5-20 tenants. I have no clue which tenant it's logging in for - I auth, the login box disappears, then reappears. Every time, the password field is empty so I need to type it in again.

Because most of our customers (and we ourselves) use 2FA, I have to either use the app or get SMSes to the phone. Today, I actually couldn't finish the sign up process because Azure told me it had sent me too many SMS codes in a short space of time.

**Describe the solution you'd like**
I would like to not have to re-authenticate in ASE every few weeks (why does this happen?). And if I *do* need to re-authenticate, then that process should take < 10 seconds. Currently, this is not possible: the above process took around 5 minutes, after which time I was simply so frustrated that I just gave up.

**Describe alternatives you've considered**
Alternatives include using other Azure Storage tools e.g. VS Code's add-in or the portal, or storing data in a different cloud, such as AWS S3.

**Comment by MRayermannMSFT** [comment] 2021-02-01 18:14
Duplicate of #460 

Hi Isaac, thanks for opening this issue. We are aware of the increasing number of people using Storage Explorer who have access to many many tenants, especially ones with strict login requirements (MFA, often having to re-authenticate, etc.). This past milestone we spent some time working on a design to improve the UI/UX for this scenario, and we are prioritizing that work for our next release. Sorry to not have something better for you in this immediate moment, but feel free to follow that issue I linked above. I think as we start implementing the design, we'll see if anyone wants to try it out and share feedback on it.

Thanks!

**Closed by MRayermannMSFT** 2021-02-01 18:14 UTC
Labels: :heavy_check_mark: duplicate, :gear: sign-in
