### ISSUE TITLE
Only one file displays when uploading two files in one ADLS Gen1 account if Storage Explorer is installed by snap on Ubuntu 20.04

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6545] opened 2023-02-10 09:35 UTC
**Storage Explorer Version:** 1.28.0
**Build Number:** 20230209.2
**Branch:** rel/1.28.0
**Platform/OS:** Linux Ubuntu 20.04
**Architecture:** x64
**How Found:** From running test case
**Regression From:** Not a regression

## Bug Description ##

1. Only one file displays when uploading two files.
2. Folders display when uploading more than two files.

## Steps to Reproduce ##

1. Install Storage Explorer by snap on Ubuntu 20.04.
2. Expand the node 'Data Lake Storage Gen1' node -> Open one adls gen1 account.
3. Click 'Upload -> Upload Files...'.
4. Select two files -> Click 'Open'.
5. Check whether two files display in the explorer.

## Expected Experience ##
Two files display.
![image](https://user-images.githubusercontent.com/87792676/218054674-96de1728-4877-499b-b33d-b9c81adc9684.png)

## Actual Experience ##
Only one file displays.
![image](https://user-images.githubusercontent.com/87792676/218053496-8fb1b50d-44c8-4949-b792-109d57888aa7.png))

## Additional Context ##

1. This issue doesn't reproduce when Storage Explorer is installed by tar.gz.
2. This issue doesn't reproduce on Ubuntu 22.04.

**Comment by MRayermannMSFT** [comment] 2023-02-13 19:04
Gen1 is going away imminently. Going to won't fix since the reproduction is so specific.

**Closed by MRayermannMSFT** 2023-02-13 19:04 UTC
Labels: :heavy_check_mark: won't fix, 🧪 testing, :computer: linux, :gear: adls gen1, :package: snaps
