### ISSUE TITLE
Storage explorer issue when accessing ADLS containers

### ISSUE THREAD

**Issue by madanmohansatna** [microsoft/AzureStorageExplorer#3921] opened 2020-12-21 11:43 UTC

**Comment by JasonYeMSFT** [comment] 2020-12-21 17:58
Could you please describe at which step are you encountering the issue and what the issue is?

**Comment by madanmohansatna** [comment] 2020-12-21 18:08
Hi,

I am successfully logged in and when expanding blob container, I am
getting the following error

**Comment by JasonYeMSFT** [comment] 2020-12-21 18:18
The picture cannot be posted through phone. You can login to Github in a browser to post the picture.

**Comment by MRayermannMSFT** [comment] 2021-01-04 19:16
Also, please clarify if this is for ADLS Gen1 or Gen2, and let us know your storage explorer version and what OS you are on. Thanks.

**Comment by MRayermannMSFT** [comment] 2021-01-19 18:54
Closing due to lack of followup. If you are still having this problem, then please open a new issue. Thanks!

**Closed by MRayermannMSFT** 2021-01-19 18:54 UTC
