### ISSUE TITLE
All dialog cannot be moved to elsewhere

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1247] opened 2019-03-20 09:12 UTC
**Storage Explorer Version:** 1.7.0_20190319.1
**Platform/OS:** Linux Ubuntu 18.04
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce**:
1. Open any one dialog -> Try to move this dialog to elsewhere.

**Expect Experience:**
This dialog can be moved.

**Actual Experience:**
This dialog cannot be moved.

**More info:**
This issue doesn't reproduce on Ubuntu 16.04/Windows/Mac.

**Comment by MRayermannMSFT** [comment] 2019-06-20 22:09
We believe this by design behavior on ubuntu 18.04. Closing.

**Closed by MRayermannMSFT** 2019-06-20 22:09 UTC
Labels: :computer: linux, 🧪 testing

**Comment by MRayermannMSFT** [comment] 2019-06-20 22:10
https://askubuntu.com/questions/555847/moving-save-dialog-for-pdfs-moves-the-entire-background-firefox-screen
