### ISSUE TITLE
Unable to download files to local folder from blob container

### ISSUE THREAD

**Issue by vats-ashish** [microsoft/AzureStorageExplorer#5575] opened 2022-03-30 09:38 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Regression From

1.19.0

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I am unable to perform operations on any of the files. neither copy- paste nor download. Even the explorer's own functions are not working.

### Steps to Reproduce

1. launch SE
2. open the attached storage accounts tab
3. select the Storage account to view its container
4. open the blob container
5. select all the files
6. click on the download
7. nothing happens

### Actual Experience

1. launch SE
2. open the attached storage accounts tab
3. select the Storage account to view its container
4. open the blob container
5. select all the files
6. click on the download
7. nothing happens
8.
I am unable to perform operations on any of the files. neither copy- paste nor download. Even the explorer's own functions are not working.

1.clicked on Help
2. clicked on about
3. nothing happens

### Expected Experience

I should be able to download, copy-paste the files from the container to my local or from container to container.

I should be able to see the About info.

**Comment by JasonYeMSFT** [comment] 2022-03-30 17:21
Are you seeing the buttons disabled or they are enabled but nothing happens after you click them? When you click the download button, does it bring up any dialog to let you choose the download destination? If you click the copy button and try to paste in your local text editor, does it show you anything that seems to be put by Storage Explorer?

**Comment by vats-ashish** [comment] 2022-03-30 18:02
nothing happens at all. sometimes it just shows up as some error message

"Unable to retrieve child resources.

Details:
Invalid initialization vector"

**Comment by MRayermannMSFT** [comment] 2022-04-04 16:47
@vats-ashish I'm going to close this as a duplicate of #5537. Please refer to that issue for now. Thanks!

**Closed by MRayermannMSFT** 2022-04-04 16:47 UTC
