### ISSUE TITLE
IoT Blob storage list error

### ISSUE THREAD

**Issue by tickledblue3** [microsoft/AzureStorageExplorer#4403] opened 2021-04-29 12:47 UTC
After successful connection to blob storage on an IoT Edge device (Raspberry Pi), get error when trying to expand the Blob Containers.   The details are attached.   Seems like the error is associated with the accountName; however, I've verified that it is correct.

[MSASE-error.txt](https://github.com/microsoft/AzureStorageExplorer/files/6398602/MSASE-error.txt)

Using version Azure Storage Explorer version 1.19.0

**Comment by MRayermannMSFT** [comment] 2021-05-03 17:46
@tickledblue3 yes, this typically means either your name or key is wrong. Please double verify the correctness of those values.

Additionally, we have seen issues when trying to use the latest (at the time) versions of Storage Explorer with blobs IoT. Sometimes they can be a bit behind on API versioning. Feel free to try some older versions to see if those work: https://github.com/microsoft/AzureStorageExplorer/releases

In the meantime, we will forward this issue to the blobs IoT team and see if they can chime in with any additional help.

**Comment by JasonYeMSFT** [comment] 2021-06-22 20:51
@tickledblue3  You are right, this is a regression from a very early version. There are multiple changes that lead to it being broken. We recently discovered the root cause when investigation #4099 and we are trying to address it asap, hopefully in our next release 1.21.0.

**Comment by JasonYeMSFT** [comment] 2021-06-22 20:53
We will close this issue and track the progress of addressing all blob edge related issues in #4099 since it is the earliest one.

**Closed** 2021-06-22 20:53 UTC
Labels: :gear: blobs, :heavy_check_mark: duplicate

**Comment by shoop** [comment] 2021-06-28 12:51
FYI version 1.17.0 can connect and list blob containers and their contents on the Edge device. The error in #4099 is however indeed present in that version.
