### ISSUE TITLE
A JavaScript error occurred in the main process (MacOS Arm64 Preview)

### ISSUE THREAD

**Issue by mikejohanson** [microsoft/AzureStorageExplorer#6688] opened 2023-03-21 07:47 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.0

### Architecture

x64

### Storage Explorer Build Number

20230214.4

### Platform

macOS

### OS Version

Ventura 13.2.1

### Bug Description

<img width="505" alt="Screenshot_3_21_23__12_39_AM" src="https://user-images.githubusercontent.com/9046277/226544312-416d5e0f-6572-4506-a0c9-506474bfc5a9.png">

### Steps to Reproduce

1. Launch Storage Explorer 
2. Wait 7-10 Seconds and the error shows

### Actual Experience

This message comes up everytime I launch it. Nothing seems to be non functional due to the error. Just a minor annoyance thus far.  I will update back if I notice any functional issue.

### Expected Experience

No Error :)

**Comment by jeffwilcox** [comment] 2023-03-23 15:23
Also seeing this.

**Comment by MRayermannMSFT** [comment] 2023-03-27 18:23
@mikejohanson @jeffwilcox can you please enable debug logging, reproduce the issue, and then share your logs here? More instructions on this can be found here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting#storage-explorer-logs

**Comment by mikejohanson** [comment] 2023-03-27 18:31
[2023-03-27_112901.zip](https://github.com/microsoft/AzureStorageExplorer/files/11081907/2023-03-27_112901.zip)

I quit the application after the warning/error showed up.

**Comment by MRayermannMSFT** [comment] 2023-03-27 21:07
Seems the issue was a remote error on our side. Should be fixed now.

**Comment by mikejohanson** [comment] 2023-03-30 18:17
Thanks @MRayermannMSFT for getting back, confirmed not seeing it anymore. Going to close the issue.

**Comment by AlexKulpa** [comment] 2023-03-30 19:55
> @AlexKulpa can you help explain your thumbs down reaction? If you're still seeing the error when trying to update the ARM64 preview it'd be helpful to know. On the other hand, if you are reacting negatively to the fact there was an error in the first place, that's fine too. Just please let us know.

Yeah I've still seen this error that's why I gave thumb down

**Comment by MRayermannMSFT** [comment] 2023-03-30 21:23
@AlexKulpa thanks for getting back to us so quickly. When was the last time you saw the error? I fixed the remote problem about 30min before posting the comment. If possible, can you try reproducing it again? I'm wondering if you just barely missed the remote fix because at this point I cannot reproduce it anymore. If you do reproduce it please share a screenshot/s of any error dialog/s you see. Thank you.

**Comment by MRayermannMSFT** [comment] 2023-03-30 22:44
Huzzah. That's great. Probably was just a case of bad timing then. Thanks again for coming back to explain things.

**Closed by MRayermannMSFT** 2023-03-30 22:44 UTC
Labels: :computer: mac, :gear: arm64, :computer: M1 mac

**Comment by patelamit06** [comment] 2023-11-14 11:35
What is done to fix this issue facing this issue when installed in windows 11
