### ISSUE TITLE
failed to perform copy command due to error: cannot start job due to error: cannot scan the path \\\\\\\\?

### ISSUE THREAD

**Issue by denilsongrupp** [microsoft/AzureStorageExplorer#3001] opened 2020-05-18 15:33 UTC
I can't copy a csv in the new version of the azure storage exploter:
error

 "message": "\"failed to perform copy command due to error: cannot start job due to error: cannot scan the path \\\\\\\\? my path

please verify that it is a valid.\\n\""

**Comment by MRayermannMSFT** [comment] 2020-05-18 17:38
@denilsongrupp , a few questions.
Can you elaborate on some repro steps? E.g. give us exact detailed steps to reproduce this issue. Include information such as:

- your OS
- your storage explorer version
- what storage service you are working with (blobs, file shares, etc.)
- what operation are you doing
- what are the paths and names of files you are working with

Thanks.

**Comment by arome** [comment] 2020-05-29 21:05
I had the same issue. It turns out I got this message when I was trying to upload a .txt (blob) to a directory and the file was open in another program. After closing the file the upload worked fine.

**Comment by MRayermannMSFT** [comment] 2020-06-01 17:48
@denilsongrupp , is it possible what arome said also was happening to you?

**Comment by MRayermannMSFT** [comment] 2020-06-22 18:09
@denilsongrupp , I'm going to close this issue now. Please open a new one if you are still having this issue occur.

**Closed by MRayermannMSFT** 2020-06-22 18:09 UTC
