### ISSUE TITLE
Unlocalized files

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#1684] opened 2019-08-19 20:21 UTC
RenameCommand for
1. Blobs
2. FileSystem
3. ~~AzureDataLakeStore~~

**Comment by craxal** [comment] 2019-08-20 15:36
Azure Data Lake is intentionally left unlocalized. That needs to be done by the team who owns that feature.

**Comment by craxal** [comment] 2019-08-29 16:15
Duplicate of #1695.

**Closed by craxal** 2019-08-29 16:15 UTC
Labels: :globe_with_meridians: localization, :heavy_check_mark: duplicate
