### ISSUE TITLE
Inconsistent displaying of existing files and folders. 

### ISSUE THREAD

**Issue by laserljy** [microsoft/AzureStorageExplorer#926] opened 2018-11-29 20:14 UTC
**Storage Explorer Version**:
**Platform/OS**:
**Architecture**:
**Regression From**:

**Bug description**
Inconsistent displaying of existing files and folders. 

**Steps to Reproduce**
The problem is that the behavior is not consistent. One day I can see 14 folders in a parent folder, the next day I can only see 11 folders. Then if I go to the next pages and come back to the 1st page, I can again see 14 folders. These inconsistent displaying of files or folders makes me unsure of whether the file exists or not, I have to write a  program to figure out the existing files or folders by printing out them. But this is a pain if the number of files or folders gets really large.

**Expected Experience**
I expect to see a comprehensive list of files and folders, just like the experience with Windows folders explorer.

**Actual Experience**
Please see the description the **Steps to Reproduce**

**Additional Context**

**Comment by laserljy** [comment] 2018-11-29 22:10
Hi there,

The problem is that the behavior is not consistent so it is hard to repeat,
here is some snapshot I have.

First I can see only 11 folders (see first.PNG attached)

Then, after going to some pages behind and come back to the 1st page, I can
see all 14 folders (see second.PNG attached).

I am working at B44, and my alias is jiyili, could we talk on Teams?

Thanks,
Jiying

**Comment by craxal** [comment] 2018-12-17 20:51
@laserljy, your attached images did not show up on the thread. Can you send them through GitHub instead of attaching them to an email?

**Comment by MRayermannMSFT** [comment] 2019-08-05 18:24
@laserljy we're going to close this since you haven't replied in a while and we cannot repro the problem. If you're still having issues feel free to setup an in person meeting with us. Thanks!

**Closed by MRayermannMSFT** 2019-08-05 18:24 UTC
Labels: :grey_question: more info

**Comment by guisantos** [comment] 2020-05-01 10:14
This issue persists, I have some evidences too, 
I'm using azure storage explorer to get files from my blob storage.

I'm uploading blockblobs from my application. I think the issue is on the query, it's not sorting properly.

![20200501_094238](https://user-images.githubusercontent.com/14335913/80798482-d9871100-8b7a-11ea-85e3-59f5aaa8f34c.gif)
