### ISSUE TITLE
Search exact name in tables

### ISSUE THREAD

**Issue by KondzioSSJ4** [microsoft/AzureStorageExplorer#4450] opened 2021-05-12 17:05 UTC
Hi

My storage account has 10k+ of different tables
I know the name of what table I'm interested in search
but when I put something like:
`/Local & Attached/Storage Accounts/STORAGE_ACCOUNT_NAME/Tables/FilesX6802X150f4d645e5247e7861732a5f3ad7c7b`
then the search is executing ("Searching..." is showing)
but after even after few minutes I don't receive any result (still "searching")

When I go into Azure Portal and try to find `FilesX6802X150f4d645e5247e7861732a5f3ad7c7b` in theirs explorer I will get table instantly

Could you:
- Fix searching to allow find tables in less than ~30 sec?
- Add possibility to open table even if such table is not visible? (e.g. right button on table and there can be "Open exact" and I would like put exact name e.g. `FilesX6802X150f4d645e5247e7861732a5f3ad7c7b` and that should open it without any searching, of course that required to check if such table exists)

**Comment by MRayermannMSFT** [comment] 2021-05-17 18:12
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/4168

**Closed by MRayermannMSFT** 2021-05-17 18:12 UTC
Labels: :gear: tables
