### ISSUE TITLE
Storage Explorer vs. MAX_path issue (260 character) when double clicking files

### ISSUE THREAD

**Issue by yuhaii** [Microsoft/AzureStorageExplorer#902] opened 2018-11-27 03:30 UTC
#### Issue description: ####
Azure Storage Explorer creates two weird GUID folders within each other under temp before downloading the file including the folder structure containing the file.
This appears to be an issue often for users. Why have to folders with long GUIDs that only leave limited space for the folder structure and filename? 
Users double click files in Azure Storage Explorer and expect the files to open in either Adobe Acrobat or Word, but nothing happens as the path exceed the allows 260 chars within Windows 

#### Information: ####
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10 Enterprise v1809
**Architecture**: ia32
**Regression From**: not sure

#### Steps to Reproduce: ####
1. 
    1) Create a pdf file with long name. Like "Soft Skills-2017-12-04Soft Skills-2017-12-04Soft Skills-2017-12-04Soft Skills-2017-12-04Soft Skills-2017-12-04Soft Skills-2017-12-04Soft Skills-2017-12-04Soft Skills-2017-12-04Soft Skills-2017-12-04Soft Skills-2017-12-04.pdf".

    2) Upload this file onto blob storage with "Azure Storage Explorer" tool:
![image](https://user-images.githubusercontent.com/39817657/49056365-729f5300-f236-11e8-92ba-873dcc9f12d4.png)

    3) Double click this long name PDF file on "Azure Storage Explorer" .  
![image](https://user-images.githubusercontent.com/39817657/49056354-62877380-f236-11e8-8d0e-ec4533e11371.png)

       This pdf file will be opened by Edge browser and get error:
       
![image](https://user-images.githubusercontent.com/39817657/49056426-a8dcd280-f236-11e8-901f-331947c8bca9.png)

   4) Click "open folder" button on "Azure Storage Explorer", we can see the folder have a very long path : "C:\Users\yuhai\AppData\Local\Temp\31c46eb1d42b9769d500ee58062c7ecbbf63890e62277f7f62e7863d65a49a04".

   5) If we double click the long name pdf under folder : "C:\Users\yuhai\AppData\Local\Temp\31c46eb1d42b9769d500ee58062c7ecbbf63890e62277f7f62e7863d65a49a04". It also can't be correctly opened by Edge

    6) If we copy the long name PDF file to "C:\Users\yuhai\Desktop" folder. This long name PDF file can be open correctly under this shot path folder.
        

#### Expected Experience: ####
Long name PDF file can be opened by Edge correctly

#### Actual Experience: ####

Long name PDF file can't be opened by Edge

**Comment by PeterSelchDahl** [comment] 2018-11-27 10:32
Thanks for adding the issue. I also created a uservoice on Azure Feedback for this issue: https://feedback.azure.com/forums/217298-storage/suggestions/36102955-storage-explorer-vs-max-path-issue-260-character

**Comment by yuhaii** [comment] 2018-11-30 06:48
Hello Team, do you have any update on this issue? Thank you!

**Comment by craxal** [comment] 2018-12-04 16:51
Apologies for the late reply. We've been swamped lately.

The GUID folders are designed to avoid file conflicts during downloads. Though I believe the long path name is a known issue. We can look into fixing this. In the meantime, is it possible to rename your blob something shorter to get around this issue?

**Comment by yuhaii** [comment] 2018-12-05 04:43
Hello Craig,

Thanks for your reply!
We already notify customer to rename the blob name shorter or download to other folder as a workaround.
Please help keeping us posted of your fixing progress. Thank you very much for your help!

Best regards,

Hai Yue | Support Engineer | Customer Service & Support, Microsoft
[说明: cssbar]
•Phone: +86 21 5263 8087

My normal working hours are Mon-Fri 9:00-18:00 UTC+8.  If you prefer to work with an Azure support engineer in another time zone, or need assistance outside of my working hours, please forward this email to azbackup@microsoft.com<mailto:azbackup@microsoft.com> with a brief explanation.  One of my colleagues will gladly continue working on this issue.

**Comment by craxal** [comment] 2018-12-06 23:22
Duplicate of #93.

**Closed by craxal** 2018-12-06 23:22 UTC
Labels: :computer: windows, :gear: blobs

**Comment by yuhaii** [comment] 2018-12-10 01:58
Hello Matthew and Craig,

I see that the fix of issue https://github.com/Microsoft/AzureStorageExplorer/issues/93  have merged into hotfix branch.
May I know when the new version of ASE with this fix been released? Thank you!

Best regards,

Hai Yue | Support Engineer | Customer Service & Support, Microsoft
[说明: cssbar]
•Phone: +86 21 5263 8087

My normal working hours are Mon-Fri 9:00-18:00 UTC+8.  If you prefer to work with an Azure support engineer in another time zone, or need assistance outside of my working hours, please forward this email to azbackup@microsoft.com<mailto:azbackup@microsoft.com> with a brief explanation.  One of my colleagues will gladly continue working on this issue.

**Comment by yuhaii** [comment] 2018-12-18 08:48
Hello Matthew and Craig,

I hope everything is fine with you!
Could you please update me with the current status? When the new version of ASE with this fix been released? Thank you!

Best regards,

Hai Yue | Support Engineer | Customer Service & Support, Microsoft
[说明: cssbar]
•Phone: +86 21 5263 8087

My normal working hours are Mon-Fri 9:00-18:00 UTC+8.  If you prefer to work with an Azure support engineer in another time zone, or need assistance outside of my working hours, please forward this email to azbackup@microsoft.com<mailto:azbackup@microsoft.com> with a brief explanation.  One of my colleagues will gladly continue working on this issue.

From: Hai Yue
Sent: Monday, December 10, 2018 9:58 AM
To: 'Microsoft/AzureStorageExplorer' <reply@reply.github.com>; Matthew Rayermann <marayerm@microsoft.com>
Cc: Author <author@noreply.github.com>; Microsoft/AzureStorageExplorer <AzureStorageExplorer@noreply.github.com>
Subject: RE: [Microsoft/AzureStorageExplorer] Storage Explorer vs. MAX_path issue (260 character) when double clicking files (#902)

Hello Matthew and Craig,

I see that the fix of issue https://github.com/Microsoft/AzureStorageExplorer/issues/93  have merged into hotfix branch.
May I know when the new version of ASE with this fix been released? Thank you!

Best regards,

Hai Yue | Support Engineer | Customer Service & Support, Microsoft
[说明: cssbar]
•Phone: +86 21 5263 8087

My normal working hours are Mon-Fri 9:00-18:00 UTC+8.  If you prefer to work with an Azure support engineer in another time zone, or need assistance outside of my working hours, please forward this email to azbackup@microsoft.com<mailto:azbackup@microsoft.com> with a brief explanation.  One of my colleagues will gladly continue working on this issue.

**Comment by jinglouMSFT** [comment] 2018-12-18 20:32
Expecting a fix release in a day or two.

**Comment by yuhaii** [comment] 2018-12-19 01:36
Got it. Thanks for your confirmation!

Best regards,

Hai Yue | Support Engineer | Customer Service & Support, Microsoft
[说明: cssbar]
•Phone: +86 21 5263 8087

My normal working hours are Mon-Fri 9:00-18:00 UTC+8.  If you prefer to work with an Azure support engineer in another time zone, or need assistance outside of my working hours, please forward this email to azurebu@microsoft.com<mailto:azurebu@microsoft.com> with a brief explanation.  One of my colleagues will gladly continue working on this issue.

**Comment by jinglouMSFT** [comment] 2018-12-19 01:58
The release is available now. Go to the release tab here in Github and download the bits for v1.6.1 build 20181218.1.  The same bits will be available from the normal download page (storageexplorer.com) as well.  It's in the process of being propagated as we speak.

**Comment by yuhaii** [comment] 2018-12-19 02:05
Got it. Thank you!

Best regards,

Hai Yue | Support Engineer | Customer Service & Support, Microsoft
[说明: cssbar]
•Phone: +86 21 5263 8087

My normal working hours are Mon-Fri 9:00-18:00 UTC+8.  If you prefer to work with an Azure support engineer in another time zone, or need assistance outside of my working hours, please forward this email to azurebu@microsoft.com<mailto:azurebu@microsoft.com> with a brief explanation.  One of my colleagues will gladly continue working on this issue.
