### ISSUE TITLE
"Error loading property" happens with Azure Storage Explorer 1.24.0 when connecting to Azure China Subscriptions

### ISSUE THREAD

**Issue by riiikawang** [microsoft/AzureStorageExplorer#5704] opened 2022-05-11 09:07 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.0

### Regression From

1.19.0

### Architecture

x64

### Storage Explorer Build Number

1.24.0

### Platform

Windows

### OS Version

Windows 10

### Bug Description

On ASE 1.24.0, when we connected to Azure China Subscription and browsed storage accounts under it, error "error loading property" would happen. This error could be reproduced stably:
![image](https://user-images.githubusercontent.com/77219080/167812417-ed75a085-f55e-4b36-8774-92114f56e82e.png)

If checking into log "storage-account-extension", it shows the API call was sent to Global Azure endpoint instead of China Endpoint:
![image](https://user-images.githubusercontent.com/77219080/167812656-4c441e0d-8b13-4855-92fd-d493a3aec256.png)

So I guess this is the problem cause, pls help to fix.

### Steps to Reproduce

1. Launch Storage Explorer
2. Select Azure China for connected subscription
3. Log in an Azure China user
4. After the successful log in, open any storage account, then error happened.

### Actual Experience

see bug description

### Expected Experience

The API call should be sent to Azure China endpoint management.chinacloudapi.cn  to fetch the storage account, instead of to global endpoint management.azure.com

**Comment by MRayermannMSFT** [comment] 2022-05-16 17:24
@riiikawang yes this was an issue with 1.24.0. We just shipped a hotfix on Friday that addresses it: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.24.1

Please download and use that version. Thanks.

**Comment by MRayermannMSFT** [comment] 2022-05-17 16:40
Ok...closing as duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/5699

**Closed by MRayermannMSFT** 2022-05-17 16:40 UTC
Labels: :heavy_check_mark: duplicate
