### ISSUE TITLE
The address bar is inconsistent between split tabs on the snapshots/version view for one blob which has parent folders under flat mode

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5720] opened 2022-05-13 08:06 UTC
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220513.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Monterey 12.3 (MacBook Air M1 2020)
**Architecture** ia32\x64
**Azurite version** 3.17.1
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Create a new folder -> Upload one blob to the folder.
3. Switch to root -> Change the list mode to 'Flat'.
4. Right click the blob container -> Click 'Manage History -> Manage Versions/Snapshots'.
5. Split the tab -> Observe the address bar in the split tabs.
6. Check whether the address bar is consistent.

## Expected Experience ##
The address bar is consistent.

## Actual Experience ##
The address bar is inconsistent.
![image](https://user-images.githubusercontent.com/41351993/168236654-82b4d012-84de-4a5c-90bb-c68e66081e96.png)

**Comment by JasonYeMSFT** [comment] 2022-05-18 21:46
This is by design. The new address is computed from the address string of the current location, which will contain all the directories to the location. I am going to won't fix this for now since we don't necessarily need the two addresses to be exactly identical.

**Closed by JasonYeMSFT** 2022-05-18 21:46 UTC
Labels: 🧪 testing, :gear: blobs
