### ISSUE TITLE
409 Copy source blob has been modified.. When Put Blob from URL

### ISSUE THREAD

**Issue by letmaik** [microsoft/AzureStorageExplorer#7038] opened 2023-07-06 17:02 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

x64

### Storage Explorer Build Number

20230609.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

I was copying a container from one storage account to another storage account and at the end most blobs had been successfully copied but many (not all) small ones failed. In the log I can see "409 Copy source blob has been modified.. When Put Blob from URL.", however the source blob has definitely not been modified. The ones that failed were as small as 64 bytes but also others with 130 KiB. The successful blobs were typically much larger (gigabytes) and I can see that for those the "Put Block From URL" API is used instead of "Pub Blob From URL".

Some searching revealed https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-use-azcopy-troubleshoot#known-temporary-issues which says:
> There's a service issue impacting AzCopy 10.11 and later versions that are using the [PutBlobFromURL API](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob-from-url) to copy blobs smaller than the given block size (whose default size is eight mebibytes (MiB)). If the user has any firewall (VNet/IP/PL/SE Policy) on the source account, the PutBlobFromURL API might mistakenly return the message "409 Copy source blob has been modified". The workaround is to use AzCopy 10.10.

Neither the source account nor the destination account have a firewall (both have "Public network access: Enabled from all networks") so it doesn't seem to apply but I thought I mention it anyway.

### Steps to Reproduce

1. Create two storage accounts (East US). Source is Premium storage, destination is Standard, if it matters.
2. Create a container in the source account.
3. Upload blobs of various sizes to the source container. (10 KiB, 10 MiB)
4. Select all files in the source container, click copy, and paste into the destination container.

### Actual Experience

Some small files cause errors: 409 Copy source blob has been modified.. When Put Blob from URL.
Retrying the transfer while ignoring existing files typically transfers the remaining ones successfully, so it seems like a transient issue. But I've seen it for multiple transfers of large numbers of files (100k).

**Comment by mawarren642** [comment] 2023-08-18 00:30
I'm also having this exact same issue with transient failures reporting this error code while there is absolutely and definitively no way the file / blob in question is actually being manipulated by third parties. In this case, it is for a file share to a blob container. I have extensive logs I can share.

Please let me know what type of information from the logs would be most helpful. The total volume of logging data I can share exceeds several Gb!

**Comment by mortenjoenby** [comment] 2023-08-18 07:48
I see the same problem when using Storage Explorer 1.31.0 which uses AzCopy v10.20.1.
I know the source files are not being changed, but a transfer results in this:
"complete with errors: 2.046 items transferred, 46 items failed"

`2023/08/18 07:35:48 ==> REQUEST/RESPONSE (Try=1/33.2087ms, OpTime=33.2087ms) -- RESPONSE STATUS CODE ERROR
   PUT https://yyyy.blob.core.windows.net/pacacust02wetestorablob-backup/xxxxxx/archivelog/2023-08-07_1330_STEP_100757_1_cl237hir_20230807.arc?blockid=MDAwMDCOz255XNJEc3sZGleH8WvKMDAwMDAwMTI0ODAwMDAx&comp=block&se=2023-09-17T07%3A35%3A18Z&sig=-REDACTED-&sp=rwlt&sr=c&sv=2021-10-04&timeout=901
   Content-Length: [0]
   User-Agent: [Microsoft Azure Storage Explorer, 1.31.0, win32, azcopy-node/3.1.0-rc.3 (win32)  AzCopy/10.20.1 Azure-Storage/0.15 (go1.19.12; Windows_NT)]
   X-Ms-Client-Request-Id: [fbcc3e85-cd3a-40b7-6b16-4a41f91ae2e9]
   X-Ms-Copy-Source: [https://xxxx.file.core.windows.net/xxxxx-backup/step/archivelog/2023-08-07_1330_STEP_100757_1_cl237hir_20230807.arc?se=2023-08-25T07%3A20%3A13Z&sig=-REDACTED-&sp=rl&sr=s&st=2023-08-18T07%3A20%3A13Z&sv=2023-01-03]
   X-Ms-Source-Range: [bytes=8388608-16777215]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 503 The server is busy.
   Content-Length: [210]
   Content-Type: [application/xml]
   Date: [Fri, 18 Aug 2023 07:35:47 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [fbcc3e85-cd3a-40b7-6b16-4a41f91ae2e9]
   X-Ms-Error-Code: [CannotVerifyCopySource]
   X-Ms-Request-Id: [aa229fc1-b01e-0048-02a6-d153b5000000]
   X-Ms-Version: [2020-10-02]
Response Details: ï»¿<Code>CannotVerifyCopySource</Code><Message>The server is busy. </Message>`

**Comment by JasonYeMSFT** [comment] 2023-08-28 16:48
> I see the same problem when using Storage Explorer 1.31.0 which uses AzCopy v10.20.1. I know the source files are not being changed, but a transfer results in this: "complete with errors: 2.046 items transferred, 46 items failed"
> 
> ```
> 2023/08/18 07:35:48 ==> REQUEST/RESPONSE (Try=1/33.2087ms, OpTime=33.2087ms) -- RESPONSE STATUS CODE ERROR
>    PUT https://yyyy.blob.core.windows.net/pacacust02wetestorablob-backup/xxxxxx/archivelog/2023-08-07_1330_STEP_100757_1_cl237hir_20230807.arc?blockid=MDAwMDCOz255XNJEc3sZGleH8WvKMDAwMDAwMTI0ODAwMDAx&comp=block&se=2023-09-17T07%3A35%3A18Z&sig=-REDACTED-&sp=rwlt&sr=c&sv=2021-10-04&timeout=901
>    Content-Length: [0]
>    User-Agent: [Microsoft Azure Storage Explorer, 1.31.0, win32, azcopy-node/3.1.0-rc.3 (win32)  AzCopy/10.20.1 Azure-Storage/0.15 (go1.19.12; Windows_NT)]
>    X-Ms-Client-Request-Id: [fbcc3e85-cd3a-40b7-6b16-4a41f91ae2e9]
>    X-Ms-Copy-Source: [https://xxxx.file.core.windows.net/xxxxx-backup/step/archivelog/2023-08-07_1330_STEP_100757_1_cl237hir_20230807.arc?se=2023-08-25T07%3A20%3A13Z&sig=-REDACTED-&sp=rl&sr=s&st=2023-08-18T07%3A20%3A13Z&sv=2023-01-03]
>    X-Ms-Source-Range: [bytes=8388608-16777215]
>    X-Ms-Version: [2020-10-02]
>    --------------------------------------------------------------------------------
>    RESPONSE Status: 503 The server is busy.
>    Content-Length: [210]
>    Content-Type: [application/xml]
>    Date: [Fri, 18 Aug 2023 07:35:47 GMT]
>    Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
>    X-Ms-Client-Request-Id: [fbcc3e85-cd3a-40b7-6b16-4a41f91ae2e9]
>    X-Ms-Error-Code: [CannotVerifyCopySource]
>    X-Ms-Request-Id: [aa229fc1-b01e-0048-02a6-d153b5000000]
>    X-Ms-Version: [2020-10-02]
> Response Details: ï»¿<Code>CannotVerifyCopySource</Code><Message>The server is busy. </Message>
> ```

Your error is different from the original author's. Since it's a server busy error, I recommend you to keep the source files a little longer and retry the failed transfers. I also recommend you to double check the file integrity of such files after a successful retry.

**Comment by JasonYeMSFT** [comment] 2023-09-21 22:47
I just hear back from AzCopy team that the 409 issue is no longer a thing. The documentation is out dated and that section of text needs to be removed. If there were still 409 errors, very likely they are due to other transient issues and downgrading to AzCopy 10.10 shouldn't help in that case. If you can reproduce it the next time, please grab the AzCopy logs and open an issue in the [AzCopy repo](https://github.com/Azure/azure-storage-azcopy) asap so they can take a deeper look of what's going on.

**Closed by JasonYeMSFT** 2023-09-21 22:47 UTC
Labels: :grey_question: investigate
