### ISSUE TITLE
Requeue Message on deleted message does nothing, used to requeue

### ISSUE THREAD

**Issue by abatishchev** [microsoft/AzureStorageExplorer#3173] opened 2020-07-01 21:41 UTC
**Storage Explorer Version**: 1.14.0
**Build Number**: 20200624.3 
**Platform/OS**: Windows 10 x64
**Architecture**: ia32
**Regression From**:  Yes, it was working in 1.13.0

## Bug Description ##

Clicking Requeue Message on a queue message that was already consumed and deleted from the queue does nothing. In previous version it used to requeue its "cached" (currently displayed) version from the memory.

## Steps to Reproduce ##

1. Enqueue a message
2. Refresh to see it in the list
3. Consume the message programmatically
4. Do not refresh! Otherwise it'll be gone
5. Press right click ->Requeue Message

## Expected Experience ##

The message is requeued to the queue

## Actual Experience ##

Nothing happens. Pressing Refresh clears up the list.

## Additional Context ##

Worked as expected in the previous version.

**Comment by CurtMiller66** [comment] 2020-07-03 18:10
I have seen the same issue.  Frustrating regression.  I really got used to it working.

**Comment by MRayermannMSFT** [comment] 2020-07-06 17:26
Thanks for reporting this. We'll look into fixing this for our hotfix of 1.14

**Comment by MRayermannMSFT** [comment] 2020-07-06 20:49
@CurtMiller66 I talked with Alex separately. Turns out he was working against the storage emulator. Are you working with the emulator as well?

**Comment by CurtMiller66** [comment] 2020-07-07 03:58
Requeue issue is against the emulator.  I use it for development/testing.


Curt

**Comment by MRayermannMSFT** [comment] 2020-07-07 16:49
@CurtMiller66, ah ok. That's a known issue for version 1.14.0. The .NET emulator has issues when we try to requeue something whose time to live is greater than 7 days, and in 1.14.0, we changed default time to live for new messages to be infinite (none/no time to live).

So for now you can either:

- when adding new messages, change time to live to not be infinite (none/no time to live)
- switch to using Azurite
- downgrade to Storage Explorer 1.13.x

And then in 1.14.1, which should be going out next week, we will be reverting to having the default time to live be 7 days. That way if you're using the .NET emulator, we don't put in you in a position where it'll be easy to run into issues. 

Let me know if you have any questions.

**Comment by MRayermannMSFT** [comment] 2020-07-10 23:42
Fix was merged into the hotfix branch.

**Closed by MRayermannMSFT** 2020-07-10 23:42 UTC
