### ISSUE TITLE
There is a failed activity log when clicking 'Play in Browse' in one file share which has the correct RBAC role

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8229] opened 2024-10-10 09:01 UTC
**Storage Explorer Version:** 1.36.0 (101)
**Build Number:** 20241009.1
**Branch:** rel/1.36.0
**Platform/OS:** Windows 10/Windows 11/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture:** x64/arm64/x64/arm64
**How Found:** Exploratory testing
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Select one storage account.
2. Assign RBAC roles 'Storage File Data Privileged Contributor' and 'Reader' to an azure account.
3. Sign into storage explorer using the azure account.
4. The storage account displays under the subscription.
5. Expand the storage account -> File Shares.
6. Open one file share -> Upload a .mp4 file -> Select the file -> Click 'Play in Browser'.
7. Check whether succeeds to play the file in browser.
## Expected Experience ##
Succeed to play the file in browser.

## Actual Experience ##
There is a failed activity log.
![Image](https://github.com/user-attachments/assets/8b809f45-7e6c-40ba-a6f9-8e3a6516aa3c)

## Additional Context ##

1. This issue also reproduces for other video files.
2. This issue doesn't reproduce for blob containers.

**Comment by craxal** [comment] 2024-10-10 22:58
@v-kellyluo Can you share more information about the error? Is it an access error?

**Comment by v-kellyluo** [comment] 2024-10-11 02:43
@craxal , it isn't an access error, I can preview csv/parquet/avro files, only fails to open video files in browser.
1. Here is the logs:
[2024-10-11_022927.zip](https://github.com/user-attachments/files/17336886/2024-10-11_022927.zip)
2. Here is the record:
![Image](https://github.com/user-attachments/assets/565b7826-a697-4581-b3fa-3984409e75d2)

**Comment by richardMSFT** [comment] 2024-10-28 23:07
After investigating, seems like this is not a regression. In 1.35.0 file shares could not be accessed with those roles due to credentials not being suitable. In 1.36.0 when trying to play in browser a .mp4 file the error being thrown is that "File Share requires storage account key to generate SAS". So it looks like that File Shares don't support user delegated SAS.

The fix is that we can expose the error in the activity log and this would be a fix that falls under "better UX".

**Comment by JasonYeMSFT** [comment] 2024-12-07 00:23
I merged a change to disable this button when the file share explorer doesn't have key or SAS credentials.

**Closed by JasonYeMSFT** 2024-12-07 00:23 UTC
Labels: 🧪 testing, :gear: files

**Comment by v-kellyluo** [comment] 2024-12-09 02:14
Verified this issue on the build 20241207.4. Fixed.
![Image](https://github.com/user-attachments/assets/98ba28c2-1874-44e1-becc-40c698b2f520)
