### ISSUE TITLE
Extra actions show in file shares context menu under attached accounts by SAS

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#947] opened 2018-12-04 09:54 UTC
Storage Explorer Version: 1.6.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181204.3
Commit: 6ae5640a
Regression From: Not a Regression

#### Steps to Reproduce: ####
1. Choose an account then try to attach it with SAS URI.
Account Name: lcltyantest
SAS URI: SharedAccessSignature=sv=2018-03-28&ss=bfqt&srt=sco&sp=rwdl&st=2018-12-04T09%3A34%3A18Z&se=2018-12-07T09%3A34%3A00Z&sig=ZjHwZf6X2lLX91UCJxrnkLhlg5P1c8UuJB58CQ172ec%3D;BlobEndpoint=https://lclyantest.blob.core.windows.net/;FileEndpoint=https://lclyantest.file.core.windows.net/;QueueEndpoint=https://lclyantest.queue.core.windows.net/;TableEndpoint=https://lclyantest.table.core.windows.net/;
2. Expand 'Local & Attached' -> Storage Accounts -> The attached account -> File shares node.
3. Right click a file share -> Check its context menu.

#### Expected Experience: ####
No 'Get Shared Access Signatures...' & 'Manage Access Policies...' show in context menu.

#### Actual Experience: ####
1. Extra actions 'Get Shared Access Signatures...' & 'Manage Access Policies...' show in context menu.
![image](https://user-images.githubusercontent.com/41351993/49432718-444be580-f7eb-11e8-8258-f6e3383e68bd.png)
2. Prompt error dialogs when trying to click 'Get Shared Access Signatures...' & 'Manage Access Policies...'.
![image](https://user-images.githubusercontent.com/41351993/49433556-53339780-f7ed-11e8-9ae2-f92ec2f92fa2.png)
![image](https://user-images.githubusercontent.com/41351993/49433617-6a728500-f7ed-11e8-9cc4-b314cb4ef798.png)

**More Info**
This issue also reproduces for queues & tables.

**Comment by craxal** [comment] 2019-04-03 22:14
Duplicate of #613.

**Closed by craxal** 2019-04-03 22:14 UTC
Labels: :gear: attach, :gear: sas, 🧪 testing
