### ISSUE TITLE
Delete selected files only deletes the ones visible in the window

### ISSUE THREAD

**Issue by golfalot** [microsoft/AzureStorageExplorer#2072] opened 2019-10-12 20:10 UTC
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  First time user

## Bug Description ##
Using Storage Account V2 with Data Lake Storage enabled.
Have a list of 30 files in a folder, longer than can be displayed for the windows size (i.e. need to scroll down)
 
CTRL+A to select all files, then Delete button. It only deletes the files that were displayed in the window.

## Steps to Reproduce ##
Small window, long file list that requires scrolling to list all.

## Expected Experience ##
Delete all files in folder

## Actual Experience ##
Deletes all files visible in window only

## Additional Context ##
Azure VM Remote Desktop

**Comment by craxal** [comment] 2019-10-14 18:40
@golfalot Just want to make sure we understand what you're experiencing. You have 30 files on the current page, but only, say, 15 items are visible at any time because your window size can't display them all. Ctrl+A selects all items, but Delete only deletes the 15 or so items currently visible?

Does it work as expected when working on the machine directly (not using Remote Desktop).

**Comment by MRayermannMSFT** [comment] 2019-11-18 19:11
Closing due to lack of reply/this is by design.

**Closed by MRayermannMSFT** 2019-11-18 19:11 UTC
Labels: :gear: adls gen2
