### ISSUE TITLE
metadata name not respecting case.

### ISSUE THREAD

**Issue by socialcpf** [microsoft/AzureStorageExplorer#4952] opened 2021-09-21 16:31 UTC
When create new or viewing existing blob metadata the case of the name is not being respected.  For example if I create a new metadata attribute "Metadata1" with a value of "vAlue" (case sensitive), the ui is not maintaining or reflecting the case of the name.  It seems to cast the name to lowercase. According to the documentation [here](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata) the case of metadata tags should be maintained.  It also appears that cloning a blog also casts these to lowercase.

**Comment by JasonYeMSFT** [comment] 2021-09-21 18:17
Duplicate of #2573.

This is a known issue of two of our dependencies that handles writing metadata to Azure, @azure/storage-blob node module and AzCopy. In short, the underlining network library doesn't allow us set http headers names with arbitrary casing. You can read more details in this issue.

https://github.com/Azure/azure-sdk-for-js/issues/8117

**Closed by JasonYeMSFT** 2021-09-21 18:17 UTC
Labels: :heavy_check_mark: duplicate

**Comment by socialcpf** [comment] 2021-09-21 18:19
Thanks Jason!  Didn't catch the original.
