### ISSUE TITLE
The path of the cloned file share is incorrect when cloning the original one under Quick Access

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2817] opened 2020-04-09 09:28 UTC
**Storage Explorer Version:** 1.13.0
**Build**: [20200409.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3625874&view=logs)
**Branch**: rel/1.13.0
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**
1. Add one file share to Quick Access.
2. Right click the file share under QA -> Click 'Clone with New Name...' -> Clone.
3. Check the path of the cloned file share.

**Expect Experience:**
The path is correct.
![image](https://user-images.githubusercontent.com/54055206/78879121-0e291080-7a86-11ea-9bb2-09e51af0a441.png)

**Actual Experience:**
The path is incorrect.
![image](https://user-images.githubusercontent.com/54055206/78879248-36187400-7a86-11ea-88b7-50bd7db6c8df.png)

**Comment by JasonYeMSFT** [comment] 2020-04-09 21:10
Version older than 1.12.0 doesn't open the editor on creation of the new container so this is not a regression. 

We think it is a bigger issue if we don't open the editor because then the user has to go into the tree to find the new node. Your expected behavior is sometimes not possible since we cannot figure out the subscription/account/container node path when action is performed from Quick Access. For Quick Access nodes, we are considering alternative actions to better meet user needs. #2819 

Won't fix for 1.13.0. Move to 1.14.0.

**Closed** 2020-06-01 18:24 UTC
Labels: :gear: files, :gear: quick access, 🧪 testing
