### ISSUE TITLE
Sort files by Last Modified not working with large numbers of files (>10,000)

### ISSUE THREAD

**Issue by nickstokes** [microsoft/AzureStorageExplorer#134] opened 2018-05-03 16:12 UTC
**Storage Explorer Version**: 1.0.0
**Platform**: Windows
**Architecture**: ia32
**Build Number**: 20180415.2
**Commit**: 5d603052
**Regression From**: unknown

#### Steps to Reproduce: ####

1. Have a blob container with a large number of files (10,007 in my case)
2. Sort by Last Modified descending

#### Expected Experience: ####
The most recent files show at the top of the list.

#### Actual Experience: ####
The most recent files aren't shown at the top of the list.
If I click all the way through to page 101, then go back to the first page and sort descending again, then they do show up.

**Comment by MRayermannMSFT** [comment] 2018-05-10 18:34
Let's (Storage Explorer team) follow-up with the platform team about having sorting options when listing blobs/files.

**Comment by MRayermannMSFT** [comment] 2019-05-29 18:34
To be clear, this bug is by design (albeit, a less than ideal design...).

The APIs available to list blobs and files don't have any options for sorting. So to provide column sorting we had/have two options:

1. Get ALL of your blobs/files and then sort
2. Sort on what blobs/files we've currently gotten (cached) and sort that

We ended up going with 2 as solution 1 would have performance implications for people with lots of blobs/files. We've been asking the platform team for a server side sort for a while now, but unfortunately nothing has been committed to us yet. Please continue to 👍 the original issue if my explanation annoys you! Being able to show the number of 👍's to the platform team is a great way to convince them that y'all want something. 🙂

**Comment by jinglouMSFT** [comment] 2019-06-10 23:50
Same issue with Table.  https://msazure.visualstudio.com/One/_workitems/edit/3011494

**Comment by zerweck** [comment] 2019-07-04 09:46
In the meantime, could this be made a bit clearer to the user? Maybe a solution would be to add an option to request the full file list including a waiting bar until everything is loaded.

**Comment by gmalacarne** [comment] 2019-10-24 11:18
hope there will be a resolution for this, have had to go with an alternative software to access files by last modified date, but the rest of the UI is better in ASE

**Comment by apsarpasha** [comment] 2020-02-12 05:00
Do we have any ETA for the fix.  It would be good, if you could share with us.

**Comment by Meekohi** [comment] 2021-04-13 17:54
tbh you should disable sorting by columns or at least show a warning in this situation - it is incorrect behavior.

**Comment by jaltin** [comment] 2021-06-04 09:25
Is this issue getting any attention from the platform team or a dead issue? Would be REALLY helpful for us to be able to sort on date (and other columns too).

**Comment by ygeelen-tb** [comment] 2021-07-19 18:39
See also https://github.com/microsoft/AzureStorageExplorer/issues/4692
The API doesn't have to return all blob metadata to sort by date, the API just needs a way to fetch the most recent blob metadata first (regardless of which data is in the cache) and then paginate through it from recent to older.

We use Blob Containers to store logs so usually we are mainly interested in the most recent entries.
Now we end up clicking "Load more" many, many times until all entries are cached, just to be able to sort by date.
And we need to do this every time because we need the newest entries.

**Comment by GregWoods** [comment] 2021-08-25 10:21
Three years on and no update?
ORDER BY Date DESC feels a core requirement of any API which can list a lot of data.

**Comment by AMArostegui** [comment] 2021-09-06 16:48
Same here. Suprising to see a feature most websites have is not supported by Azure Storage Explorer.

In my case, I have to click 'next' like 20 times, until everything is loaded, and then I can sort by date in the last page.

**Comment by Meekohi** [comment] 2021-09-06 17:22
This isn't the right place to complain -- this is an issue with Azure Blob Storage's API not with StorageExplorer. As @MRayermannMSFT said in the other thread there are only two options:

> 1. Get ALL of your blobs/files and then sort
> 2. Sort on what blobs/files we've currently gotten (cached) and sort that

1 is obviously infeasible, with many files this could take an indefinite amount of time; so StorageExplore has opted for 2 instead.

Personally my suggestion is: 3. Disable sorting by date completely -- don't pretend to support a feature that isn't possible with the underlying technology.

**Comment by MRayermannMSFT** [comment] 2021-09-14 21:46
> Personally my suggestion is: 3. Disable sorting by date completely -- don't pretend to support a feature that isn't possible with the underlying technology.

Yes, we agree (now) too. In fact this issue is the reason we changed our minds a while back towards what you say. 🙃  We're now much more conscientious about implementing features, especially complex ones, that aren't really supported by the service APIs. Nine times out of ten, it just leads to situations like this where the solution is sub-optimal, and y'all get something which is either only sort of helpful or confusing.

That said, we also do not like doing feature take back, so for that reason we have not removed this feature.

**Comment by mar72vin** [comment] 2021-10-14 23:50
It would be great if this could be resolved.

**Comment by devjam1** [comment] 2022-01-21 17:37
It would be very helpful to have the files list sorted by Last Modified right after the list is loaded.
For my use case, there is no point in exploring ancient files.

**Comment by JusticeForBeyonce** [comment] 2022-09-07 09:46
This is all absolute nonsense "Oh we can't fix it because of the API".

There's a very simple solution - give us a load all button.

Even better, the option to change how many files are initially loaded and how many extra files are loaded when the Load More button is pressed. That way those of us who need the sort function don't have to keep clicking load more dozens of times, and everyone else is unaffected.

I was very concerned by the message above suggesting that the sort function be removed rather than fix the problem. I'd always rather have a half functioning feature than no feature at all. Being able to do my job is always preferable to not being able to do it at all. At present

@MRayermannMSFT - Are you able to give us an update on whether there's been any progress on this issue. There may not be that many people commenting on this thread, but I'm certain that a lot more people have fallen foul of this issue.

This is my first time using Azure Storage Explorer, and I immediately run into a bug. That seems to happen to me with almost every Microsoft product, and it's always a bug that was reported years ago and never been addressed. Very disappointing.

**Comment by jstrassmayr** [comment] 2022-11-09 10:34
This problem hurts so bad, it's hard to describe.
Probably not more people raise their voice here because everyone thinks "This must be clear to MS and they'll fix it in the next update for sure"...

**Comment by JusticeForBeyonce** [comment] 2022-11-09 10:43
> This problem hurts so bad, it's hard to describe.
> Probably not more people raise their voice here because everyone thinks "This must be clear to MS and they'll fix it in the next update for sure"...

I think more likely they’ve given up on it ever getting fixed. I asked for an update 3 months ago and got nothing back. No point shouting into the void, you’re just wasting your breath I’m afraid.

**Comment by weber-chris** [comment] 2022-11-23 14:28
Not an explorer solution, but you can list all entries via Azure CLI (Only tested with a few dozen entries, not 1000s).

`az storage blob list --container-name <container-name>  --account-name <account-name> --auth-mode login --query "sort_by([], &properties.lastModified)[*].{name: name, lastModified: properties.lastModified}"`

[Documentation of az storage blob list](https://learn.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-list)

Use https://jmespath.org/ for the query syntax. With `--include v` you can also use the same logic to sort/show different blob versions.

**Comment by KirillOsenkov** [comment] 2023-03-27 18:20
This is incredibly painful. 

Very easy fixes that the Storage Explorer team can do to alleviate the pain:

1. display a clear message that only the first 1,000 items were fetched.
2. make that limit configurable, so that users could bump it to 10,000.
3. persist the column sorting options

However I'd prefer that we get together and just fix the issue properly, since, as someone mentioned above, the portal supports this. It's clearly causing a lot of pain and frustration for many people. The worst about this issue is that you don't notice when you hit the limit, and the symptoms are "blobs stopped being added to the storage". So you are sent on a wild goose chase debugging why blobs are no longer uploading, reset and redeploy your systems, only to get the bright idea many hours later to try the API or the portal, which will show that Storage Explorer has been lying to you all along.

**Comment by zerweck** [comment] 2023-08-29 10:56
Hey @MRayermannMSFT, it seems like your recent release August 2023 (Version 1.31.1) fixed this?
![image](https://github.com/microsoft/AzureStorageExplorer/assets/5678151/b81dfa15-3705-4b02-9603-a5178291c9c2)

**Comment by jaltin** [comment] 2023-08-29 12:01
@zerweck, I think you are referring to a sorting feature for tables. This issue is related to sorting of blobs.

**Comment by JasonYeMSFT** [comment] 2023-10-17 19:57
Starting with 1.32.0, we will support global sort in Blob explorer and File Share explorer as well. The new behavior is also under the "global sort" setting that used to be for Table only. By clicking on the column header to sort, Storage Explorer will retrieve all the items and then sort all the items retrieved.

**Closed** 2023-10-17 19:58 UTC
Labels: :bulb: feature request, :gear: blobs, :bulb: setting candidate

**Comment by KirillOsenkov** [comment] 2023-10-17 21:39
Is the sort setting persisted? I'd love for it to remember the sort setting I last chose. Either global or individual per particular resource (even better)

**Comment by JasonYeMSFT** [comment] 2023-10-17 21:43
It is. In other words, once you enabled "Global Sort", if you close Storage Explorer and re-open it, the sort will still be doing global sort.

**Comment by jejass** [comment] 2023-10-18 02:09
@JasonYeMSFT thanks for your information, this is exciting news. May I know when will 1.32.0 be released?

**Comment by JasonYeMSFT** [comment] 2023-10-18 02:26
We are targeting Oct. 27th.
