### ISSUE TITLE
Persist storage blob column grid order

### ISSUE THREAD

**Issue by bjohnsonphpni** [microsoft/AzureStorageExplorer#6620] opened 2023-02-28 19:56 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

When reviewing files in a blob container, it's annoying to have to reorder the columns when changing tabs/containers or splitting the view.

### Desired Solution

It would be an improvement to have the column order be static between tabs of the same type (i.e., Blob Containers, File Shares, etc.).

### Alternatives and Workarounds

An alternative would be to have selective column visibility by subtype (Blob Containers, Queues, Tables, File Shares).

**Comment by MRayermannMSFT** [comment] 2023-03-06 18:51
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/5578

**Closed by MRayermannMSFT** 2023-03-06 18:51 UTC
Labels: :bulb: feature request

**Comment by bjohnsonphpni** [comment] 2023-03-06 19:12
How is this request a duplicate of [#5578](https://github.com/microsoft/AzureStorageExplorer/issues/5578), which is column sorting and not display order?

**Comment by KirillOsenkov** [comment] 2023-03-27 00:22
Yes, this is a separate issue (even if related). Please reactivate. Thanks.
