### ISSUE TITLE
Show an unmatched notification in one empty file share's editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1604] opened 2019-07-31 08:58 UTC
**Storage Explorer Version:** 1.9.0
**Build:** [20190731.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2898642)
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create a new file share -> Check its editor.

**Expected Experience:**
Display 'No data available in this **file share**'.

**Actual Experience:**
Display 'No data available in this **blob container**'.
![image](https://user-images.githubusercontent.com/41351993/62196711-16866300-b3b1-11e9-940a-2f0ad467617d.png)
**More Info:**
This issue also reproduces for one empty queue.
![image](https://user-images.githubusercontent.com/41351993/62196758-2d2cba00-b3b1-11e9-85df-4c34b7df2eb3.png)

**Comment by JasonYeMSFT** [comment] 2019-11-05 22:39
Duplicate of #1697

**Closed by JasonYeMSFT** 2019-11-05 22:39 UTC
Labels: :gear: files, :triumph: easy, 🧪 testing
