### ISSUE TITLE
With a large tree of subscriptions search is not usable  

### ISSUE THREAD

**Issue by jvanschuyver** [microsoft/AzureStorageExplorer#685] opened 2018-09-20 13:15 UTC
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: unknown

#### Steps to Reproduce: ####
1. Have a large tree of subscriptions  (I have 77) in Azure Government and be authenticated.
2. Search for a string in a subscription name not available on the current window.
3. Search quickly finds the string and displays it in search results.
4. While search continues to run,  select the found subscription and try to use it or keep it selected.
5. If you stop the search you loose the search results.
6. The result is you can not use the search to find and use the results 

#### Expected Experience: ####
While displaying search results if you click to select a result you should be able to maintain that selected subscription when search is canceled. Or when you select a result search should stop.

#### Actual Experience: ####
1. Search for a term
2. Be able to select the search result you want and preform expand and all other operations

**Comment by ckarras** [comment] 2019-05-12 15:07
I have the same issue in Azure Storage Explorer 1.7.0, in public Azure (not Azure Government). I search for a storage account and it is quickly found. However, the storage containers under that account are also filtered by my search criteria. So it only works if the storage account and storage container both contain the string I was searching for. Most of the times, after selecting my storage account, I therefore have to cancel the search (to remove any filter). But my expectation is that once I cancel the search, the selected item should remain the one that I selected before canceling the search.

Search is useless with this behavior. Is thee any progress on fixing this?

**Comment by ishepherd** [comment] 2019-08-19 03:58
Ping.

Perhaps the newish Azure Resource Graph search would let you implement a faster & more powerful search?

**Comment by ckarras** [comment] 2019-08-23 13:10
@ishepherd This issue is not about performance, but about a bad UI design. The search performance is adequate ("search quickly finds the string and displays it in search results"), but the issue is that it's not possible to do anything useful with the search results, because the user has to stop the search to use the results, but by stopping the search, the user also loses the search results.

**Comment by ishepherd** [comment] 2019-08-24 03:46
Got it - I should raise a separate issue

**Comment by MRayermannMSFT** [comment] 2020-03-09 18:06
Duplicate of #1790

**Closed by MRayermannMSFT** 2020-03-09 18:06 UTC
Labels: :gear: search

**Comment by ckarras** [comment] 2020-03-09 18:09
Hi @MRayermannMSFT, this is not a duplicate of a performance-related issue, see my previous comment: https://github.com/microsoft/AzureStorageExplorer/issues/685#issuecomment-524309368
