### ISSUE TITLE
Upgrade Electron

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#4530] opened 2021-06-08 00:13 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Electron 10 has reached end of support

### Desired Solution

Upgrade to the highest Electron version possible.

**Comment by craxal** [comment] 2021-06-21 18:46
Duplicate of #4336.

**Closed by craxal** 2021-06-21 18:46 UTC
Labels: :heavy_check_mark: duplicate
