### ISSUE TITLE
 reason: connect ECONNREFUSED 127.0.0.1:10000"

### ISSUE THREAD

**Issue by MianAyazYounis** [microsoft/AzureStorageExplorer#3613] opened 2020-09-22 13:19 UTC
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Bug Description ##
 Unable to retrieve child resources.

Details:
["FetchError:request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000"].

**Comment by MRayermannMSFT** [comment] 2020-09-28 17:52
@MianAyazYounis is your emulator running?

**Comment by anuragrepaka21** [comment] 2020-10-02 16:38
> @MianAyazYounis is your emulator running? Do you have either HTTP_PROXY or HTTPS_PROXY environment variables set at the OS level?

Thanks, faced same issue. Running Azure storage emulator worked.

**Comment by MRayermannMSFT** [comment] 2020-10-26 18:10
Closing due to lack of reply. Please open a new issue if you continue having problems. Thanks.

**Closed by MRayermannMSFT** 2020-10-26 18:10 UTC
Labels: :gear: emulator, retrieve child resource error

**Comment by jonmcco** [comment] 2020-11-03 20:39
I am also being affected by this. I get the following error:

> Unable to retrieve child resources.
> 
> Details:
> ["FetchError:request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000"]

Then about 10 seconds later I get another pop up that says this:
![image](https://user-images.githubusercontent.com/45805678/98037805-fbcf4500-1dd0-11eb-94b4-8920b1d0793a.png)

**Reproduction Steps:**
I open Azure Storage Explorer, extend "Local & Attached" -> "Storage Accounts" -> "Blob Containers" and it will take a long time, then fail, then 10 seconds later I get the additional error message.

I tried deleting the %AppData%StorageExplorer, no luck. I uninstalled Azure Storage Emulator and installed it again (but it did not ask me to sign in which I believe I didn't actually delete the saved configuration then).
Now, unfortunately, my Visual Studio cannot start my Azure Function because it cannot find the executable for the Storage Explorer.

**Comment by rakesh-shrivastav** [comment] 2020-11-07 13:38
**Storage Explorer Version: ** 1.15.1
**Storage Emulator Version: ** 5.10.0.0


This is what worked for, and hope helps others.
I found few other links, though they didn't work for me. For example: [https://stackoverflow.com/questions/54176192/unable-to-connect-to-local-azure-storage-account](url)

Here's what I did:
1. Use connect to storage option
![image](https://user-images.githubusercontent.com/25687552/98442627-8f6c8280-20fd-11eb-998b-49c904f611d0.png)

2. Click Attach to a local emulator and click next
![image](https://user-images.githubusercontent.com/25687552/98442645-aca15100-20fd-11eb-9837-e85fba43e7cd.png)

3. click next, with default options. You can always change Display name from local-1 to anything that works for you and click "Next". It will show you summary and click Connect. Voila, it worked for me.

![image](https://user-images.githubusercontent.com/25687552/98442658-cb074c80-20fd-11eb-95cb-d750e72f3429.png)

4. Final connected output
![image](https://user-images.githubusercontent.com/25687552/98442681-f1c58300-20fd-11eb-892d-574ce86f4511.png)


**Once you have local-1 done as per step 4, then Emulator will also start to work**

![image](https://user-images.githubusercontent.com/25687552/98442716-410bb380-20fe-11eb-9c65-bfa3c37029e7.png)
