### ISSUE TITLE
The opened attached file shares tab displays well after deleting the original one

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2881] opened 2020-04-27 07:38 UTC
**Storage Explorer Version:** 1.13.0
**Build**:[ 20200426.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3676579&view=results)
**Branch**: rel/1.13.0
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/macOS Mojave
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Select one file share -> Attach it via SAS.
3. Delete the file share under subscriptions -> Close the opened tab of attached file share.
4. Open the SAS attached file share -> Check the result.

**Expect Experience:**
1. Pop up a notification message.
2. The opened tab closed after closing the notification message.
![image](https://user-images.githubusercontent.com/41351993/80343956-5bd0b600-8899-11ea-9d9a-2178fa1494df.png)

**Actual Experience:**
1. Pop up a notification message.
2. The opened tab displays well after closing the notification message.
![image](https://user-images.githubusercontent.com/41351993/80343956-5bd0b600-8899-11ea-9d9a-2178fa1494df.png)

**More Info:**
This issue doesn't reproduce for one blob container/ queue/ table.

**Comment by MRayermannMSFT** [comment] 2020-05-04 18:27
Overall, we need to fix **this** experience:
1. be in an explorer
2. navigate somewhere bad, bad being it doesn't exist anymore, you don't have permissions for it, etc.
3. **info bar pops up and tab closes**

**Comment by v-xianya** [comment] 2020-05-19 07:24
@MRayermannMSFT 
Verified this issue on build 1.14.0-dev 20200519.2.
This issue reproduces for File Share & **Queue**.

**Comment by MRayermannMSFT** [comment] 2020-11-06 19:51
Not closing the tab is now by design. Though we still need to work on the overall experience of "error happens while navigating in a tab"

**Closed by MRayermannMSFT** 2020-11-06 19:51 UTC
Labels: :gear: files, 🧪 testing
