### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "DestinationDir"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1785] opened 2019-09-04 12:52 UTC
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help, please?
Thanks!

Source:
and the destination directory.

File Name:
loc\en\src\components\se-az-copy-extension\resources\UploadBlobsDlg.json

Resource ID:
0; "DestinationDir"

Query:
This string seems to be preceded by something. Can you please provide us with the whole sentence, so we can re-check the syntax of this portion?
This issue of possibly incomplete strings also applies to the following ResIDs:
0; "TypeOfBlobToUpload"
0; "MessageExpandForMore"
0; "CaseInsensitiveError"
0; "CaseSensitiveError"

**Comment by craxal** [comment] 2019-09-18 23:16
Duplicate of #1786.

**Closed by craxal** 2019-09-18 23:16 UTC
Labels: :heavy_check_mark: duplicate

**Comment by PDostalek** [comment] 2019-09-23 08:41
paste issue, please correct @craxal , THanks.

**Comment by PDostalek** [comment] 2019-10-02 11:26
@craxal are those strings preceded with another ones ?

**Comment by craxal** [comment] 2019-10-02 16:47
@PDostalek The original string IDs you posted here are no longer valid. We reviewed these strings in and concluded they were not written to localize/translates well, so we replaced them with new strings (including new IDs). If you examine the file today, you'll see that the old strings are gone and replaced the new strings.
