### ISSUE TITLE
[Feature Request] Add favorites folder path for quick access 

### ISSUE THREAD

**Issue by miaoichi** [microsoft/AzureStorageExplorer#4314] opened 2021-04-12 07:17 UTC
**Is your feature request related to a problem? Please describe.**

Every time I need to click 6 or 7 levels of folder to upload or download file from ASE. 

**Describe the solution you'd like**

If we have a button can add to favorites which same as file explorer on windows.

**Describe alternatives you've considered**

**Additional context**

**Comment by MRayermannMSFT** [comment] 2021-04-12 17:29
Duplicate of #2710

**Closed by MRayermannMSFT** 2021-04-12 17:29 UTC
