### ISSUE TITLE
AzCopy quit unexpectedly uploading files other than pictures into Blob Storage

### ISSUE THREAD

**Issue by hulkje** [microsoft/AzureStorageExplorer#1228] opened 2019-03-12 17:11 UTC
**Storage Explorer Version**: 1.7.0
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: No

**Bug description**
When uploading files other than pictures into my Azure Blob Storage using Azure Storage Explorer, AzCopy quits unexpectedly all the time, whether I try to upload a complete Folder or just a File. PNG, JPEG, uploads fine, but CSV, JSON, XML, XLSX, all fail... with the new version 1.7.0 I had hoped the problem would have been solved, but it still remains. I only started using Azure Storage Explorer recently and this has never worked for me. Loading files in File Storage and Table Storage does work. It is a Blob Storage on a Azure Data Lake Storage Gen2.

Transfer from 'C:\Users\*****' to 'powerbi/TestFolder/' complete with errors: 0 completed, 0 failed (used name and key, discovery not completed), error: AzCopy quit unexpectedly

**Steps to Reproduce**
1. Select the Blob Storage in your Blob Container using Azure Storage Explorer
2. Select from the menu above: 'Upload' and then 'Upload Files...'
3. Select a file from my local drive
4. Click 'Upload'

**Expected Experience**
I expect a Transfer completed (used name and key)

**Actual Experience**
Transfer failed with error message complete with errors: 0 completed, 0 failed (used name and key, discovery not completed), error: AzCopy quit unexpectedly
 
**Additional Context**
None that I see relevant...

**Comment by hulkje** [comment] 2019-03-12 18:15
This is awkward... when selecting files from my local drive that are a sync of my OneDrive it gives the described error except when being pictures and pdf, but when I load from my C:\Documents folder it does load. Very strange... I guess I found a workaround for myself, but I wonder if this behavior is to be expected...

**Comment by springcomp** [comment] 2019-03-14 08:04
I have the same error. The command-line that StorageExplorer creates to run AzCopy is incorrect. Mine looks like so:

$env:AZCOPY_CRED_TYPE = "Anonymous";
./azcopy copy "https://account.blob.core.windows.net/container/*?shared_access_key" "C:\Users\name\Downloads" --overwrite=false --recursive --fromTo=BlobLocal --list-of-files "C:\Users\name\AppData\Local\Temp\stg-exp-azcopy-202dd503-8552-4725-8577-17c6e8ee9317.json"
$env:AZCOPY_CRED_TYPE = "";

Notice the lack of space or semi-colon immediately after the ".json" file and the reset of the environement variable at the end. If I add a semi-colon and a space to separate those two instructions, the command-line runs correctly.

Hope this helps.

**Comment by hulkje** [comment] 2019-03-14 08:28
Thanks for the tip springcomp, but when comparing the AzCopy command generated by Azure Storage Explorer, between the file upload from my local C: drive and my C:\Users\me\OneDrive then both miss the semicolon and space, but the first one is working and the second one causes AzCopy to quit unexpectedly...
How can I modify the AzCopy command in Azure Storage Explorer and run it again?

**Comment by springcomp** [comment] 2019-03-14 21:50
I think we need a PR to fix this error. I'm not knowledgeable enough in electron/JavaScript to do this though...

**Comment by MRayermannMSFT** [comment] 2019-04-17 17:55
Hey y'all, we recently updated the integrated AzCopy version. If y'all are willing could you give it a try and let us know if you're still having issues? Here's a link to a private build of Storage Explorer:

- macOS: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/AzCopy-v10-0-9/StorageExplorer-darwin-x64.zip
- Windows https://storageexplorerpublish.blob.core.windows.net/privatebuilds/AzCopy-v10-0-9/StorageExplorer-ia32.exe
- Linux: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/AzCopy-v10-0-9/StorageExplorer-linux-x64.tar.gz

Let us know if AzCopy works for you now. If not, we can take a look at your AzCopy logs to find out more.

**Comment by hulkje** [comment] 2019-04-18 05:38
Hi M, thanks for the update. I ran the installation and at finish, launched the application. Unfortunately it still gives an error, although a different one this time...

{
  "message": "\"failed to perform copy command due to error: cannot start job due to error: nothing can be uploaded, please use --recursive to upload directories.\\n\""
}

It still does upload files from my local C: drive, but nothing from any of the synced OneDrive or SharePoint folders yet...
Hope this will help you fix the issue further.
Regards,
Hilko

**Comment by springcomp** [comment] 2019-04-18 07:24
Hi @MRayermannMSFT  thank you very much for this private build.
Unfortunately, no, it does not work.
Now I get the following error:

![image](https://user-images.githubusercontent.com/8488398/56343686-b8e05900-61bb-11e9-9a6f-6fb22e535d67.png)

**Comment by MRayermannMSFT** [comment] 2019-04-18 18:26
Ok, let's work through these then!

@hulkje 
If you're uploading multiple items then copy the AzCopy command to your clipboard. Paste it into a text editor (ideally not Notepad because Notepad handles new lines weirdly) and look for something like this: 

`--list-of-files "C:\Users\matt\AppData\Local\Temp\stg-exp-azcopy-29a381c8-64f8-481b-9eed-cf579cd4633d.json"`.

Drag and drop that file here Feel free to redact file and folder names in it, I just want to make sure it looks right.

Also, regardless of how many things you are uploading, can you share the log file with me? You'll find it at `C:\Users\<your username>\.azcopy`. If there's lots of logs in there, then just delete all of them, reproduce the failure, and then copy the single log that is now in the folder. **Please read through the log and redact any sensitive information you do not want others to see (account keys, account names, etc.) before uploading the log file.**

@springcomp , I think your issue should be a little easier to diagnose and fix. If you could do the following steps that'd be great:

1. Open Storage Explorer
2. Open Dev Tools (F12 or via the Help menu)
3. Reproduce your issue
4. Go to the dev tools and open the console
![image](https://user-images.githubusercontent.com/21112697/56382361-11b7ed80-61cc-11e9-8daf-dc2f9fc6852a.png)
5. In the filter field, put in `"AzCopy.Blob.uploadBlobs"`, after doing show, the console should have much fewer things in it.
6. Look for a message that looks like this:
`FROM CHILD PROCESS 16812: {"id":"MessagePassingProviderProxy4353","args":{"type":"UploadFiles","defaultDestinationBlobFolder":"","connection":{"type":"blobContainer","serviceEndpoint":"https://REDACTED.blob.core.windows.net/","container":"1millionblobsdivided","credentials":[{"type":"key","accountKey":"REDACTED","accountName":"stgexp"},{"type":"auth","accountId":"REDACTED","tenantId":"REDACTED"}]}},"messageType":"FunctionCall","providerNamespace":"se-az-copy-extension","functionNamespace":"AzCopy.Blob.uploadBlobs"}`
7. Copy and paste that to a reply to me.

**Important**: Please redact sensitive information before clicking "Comment." It is likely that what I'm having you paste includes things such as storage account name, account key, tenant ID, AAD account ID, etc. In my above example, you can see how I replaced those items with REDACTED. I advise you to do the same/similar. Thanks!

**Comment by springcomp** [comment] 2019-04-19 13:30
@MRayermannMSFT 

Hum, I don't know if you have enough information from this log, but here goes:

`
FROM CHILD PROCESS 14932: Received a message in the child:
FROM CHILD PROCESS 14932: {"id":"MessagePassingProviderProxy20","args":{"blobs":[{"name":"processed/07eafd37c9cb463a9237c5c91ff23eb3.csv"}],"connection":{"type":"blobContainer","container":"processing","credentials":[{"type":"key","accountKey":"__account_key__","accountName":"__account_name__"}]}},"messageType":"FunctionCall","providerNamespace":"se-az-copy-extension","functionNamespace":"AzCopy.Blob.downloadBlobs"}
FROM CHILD PROCESS 14932: Sending a message from the child:
FROM CHILD PROCESS 14932: {"id":"MessagePassingHostProxy6","args":{"message":"Select a folder to download your blobs into","browseForFolder":true,"allowMultiSelect":false},"messageType":"FunctionCall","functionNamespace":"Environment.Dialogs.getOpenFileDialogResult"}
FROM CHILD PROCESS 14932: Received a message in the child:
FROM CHILD PROCESS 14932: {"id":"MessagePassingHostProxy6","messageType":"FunctionResponse","response":{"type":"result","result":["C:\\Users\\me\\Downloads"]}}
FROM CHILD PROCESS 14932: Sending a message from the child:
FROM CHILD PROCESS 14932: {"id":"MessagePassingHostProxy7","args":{"title":"Failed to start transfer: Cannot read property 'slice' of undefined","message":"","sortOrder":1,"status":3,"actions":[]},"messageType":"FunctionCall","functionNamespace":"ActivityManager.add"}
FROM CHILD PROCESS 31612: Received a message in the child:
FROM CHILD PROCESS 31612: {"id":"MessagePassingProviderProxy21","args":{"title":"Failed to start transfer: Cannot read property 'slice' of undefined","message":"","sortOrder":1,"status":3,"actions":[]},"messageType":"FunctionCall","providerNamespace":"ActivityProvider","functionNamespace":"ActivityManager.add"}
FROM CHILD PROCESS 31612: Sending a message from the child:
FROM CHILD PROCESS 31612: {"id":"MessagePassingHostProxy2","args":{"entryRef":{"id":"b3gD9rvrGhe9AH1R"}},"messageType":"EventCall","functionNamespace":"ActivityManager.onAddEvent"}
FROM CHILD PROCESS 31612: Sending a message from the child:
FROM CHILD PROCESS 31612: {"id":"MessagePassingProviderProxy21","messageType":"FunctionResponse","providerNamespace":"ActivityProvider","functionNamespace":"ActivityManager.add","response":{"type":"result","result":{"id":"b3gD9rvrGhe9AH1R"}}}
FROM CHILD PROCESS 14932: Received a message in the child:
FROM CHILD PROCESS 14932: {"id":"MessagePassingHostProxy7","messageType":"FunctionResponse","response":{"type":"result","result":{"id":"b3gD9rvrGhe9AH1R"}}}
FROM CHILD PROCESS 31612: Received a message in the child:
FROM CHILD PROCESS 14932: Sending a message from the child:
FROM CHILD PROCESS 31612: {"id":"MessagePassingHostProxy2","messageType":"EventResponse","response":[null]}
FROM CHILD PROCESS 14932: {"id":"MessagePassingProviderProxy20","messageType":"FunctionResponse","providerNamespace":"se-az-copy-extension","functionNamespace":"AzCopy.Blob.downloadBlobs","response":{"type":"result"}}
FROM CHILD PROCESS 31612: Received a message in the child:
FROM CHILD PROCESS 31612: {"id":"MessagePassingProviderProxy22","args":{"id":"b3gD9rvrGhe9AH1R"},"messageType":"FunctionCall","providerNamespace":"ActivityProvider","functionNamespace":"ActivityManager.get"}
FROM CHILD PROCESS 31612: Sending a message from the child:
FROM CHILD PROCESS 31612: {"id":"MessagePassingProviderProxy22","messageType":"FunctionResponse","providerNamespace":"ActivityProvider","functionNamespace":"ActivityManager.get","response":{"type":"result","result":{"title":"Failed to start transfer: Cannot read property 'slice' of undefined","message":"","sortOrder":1,"status":3,"actions":[],"_lastModified":"2019-04-19T13:25:44.611Z","_id":"b3gD9rvrGhe9AH1R","numChildren":0}}}

`

**Comment by MRayermannMSFT** [comment] 2019-04-19 15:56
Perfect! Ok, what I thought is indeed the case (there isn't a blob service endpoint in the args to our azcopy code). I will get a fix for this in for 1.8.0.

**Comment by MRayermannMSFT** [comment] 2019-04-19 23:20
Ok checked in the fix today. You can try it here:
- macOS: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.8.0-RC1/StorageExplorer-darwin-x64.zip
- Windows https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.8.0-RC1/StorageExplorer-ia32.exe
- Linux: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.8.0-RC1/StorageExplorer-linux-x64.tar.gz

Hopefully that gets things working for you @springcomp 🤞

**Comment by hulkje** [comment] 2019-04-23 05:58
Hi M, sorry for the late reply.

The AzCopy command for a single file is like this:
./azcopy.exe copy "C:\Users\Hilko\OneDrive\Project\Data Lake\Azure_BlobFiles\SalesLT.Customer.csv"

or this when selecting a whole foler:
./azcopy.exe copy "C:\Users\Hilko\OneDrive\Project\Data Lake\Azure_BlobFiles\"

When I look in that log folder you mention, I only see another folder called 'plans'. In here I have only one file of the type STEV6... is that what you are looking for?

Thanks again for your support.
Regards,
Hilko

**Comment by MRayermannMSFT** [comment] 2019-04-23 17:00
@hulkje ,some follow-ups:

1. Do you have issues if you move what you're trying to upload out of your onedrive folder? 
2. Are the files sync'ed to be on your machine? Or more specifically, if you go and look at say SalesLT.Customer.csv in file explorer, which of these three icons does it have?
![image](https://user-images.githubusercontent.com/21112697/56600593-e65b4700-65ad-11e9-9128-8a54a8ccaced.png)
3. Are you able to open the files if you double click on them in File Explorer?
4. The commands you copied, is that the entire command, or did you trim off some parts? Because the command should have looked something like: 
`./azcopy.exe copy "C:\Users\Hilko\OneDrive\Project\Data Lake\Azure_BlobFiles\SalesLT.Customer.csv" "https://someaccount.blob.core.windows.net/somecontainer/?SASCREDENTIAL" --overwrite=false --follow-symlinks --recursive --fromTo=LocalBlob --blobType=BlockBlob`

And no, that folder should be filled with text files:
![image](https://user-images.githubusercontent.com/21112697/56600847-8add8900-65ae-11e9-9fd7-28ead02c3673.png)

**Comment by hulkje** [comment] 2019-04-24 06:05
Hi Matt,

1. Hope I read your question right, but yes, I can move files from the OneDrive folder on my local machine to another non-OneDrive folder on my machine. 
2. That does not seem to matter. As soon as I select a file with the cloud pictogram it downloads it first to my local machine before I can start the upload to the Blob storage. In neither case does it works. 
3. Yep, files open fine in their application
4. Sorry, you are right. This is the complete command. 
./azcopy.exe copy "C:\Users\Hilko\OneDrive\Project\Data Lake\Azure_BlobFiles\SalesLT.Customer.csv" "https://datalake.dfs.core.windows.net/testblobcontainer/SalesLT.Customer.csv" --overwrite=false --follow-symlinks --recursive --from-to=LocalBlobFS --put-md5;

Hmmm, I am afraid no log files appear in that C:\Users\Hilko\.azcopy folder...

Hope this information helps.
Regards,
Hilko

**Comment by MRayermannMSFT** [comment] 2019-04-24 16:32
Bit of miscommunication on question #1. I wanted to know if you could upload your SalesLT.Customer.csv file from a non-OneDrive location. So for example, if you placed SalesLT.Customer.csv on your desktop, does the upload work? Also I tried replicating your upload today and unfortunatley I'm still not seeing any issue. ☹
Command I ended up trying:
./azcopy.exe copy "C:\Users\matthew\OneDrive\Project\Data Lake\Azure_BlobFiles\SalesLT.Customer.csv" "https://dfsdfstest01.dfs.core.windows.net/fstest/SalesLT.Customer.csv" --overwrite=false --follow-symlinks --recursive --from-to=LocalBlobFS --put-md5

Let me contact the AzCopy folks and see if they have any ideas. Unfortunatley I'm out of ideas at this point.

**Comment by hulkje** [comment] 2019-04-25 06:08
Ah, ok, yes this works fine. I found out later and mentioned this in my second comment on this post. 
Maybe the problem is with my laptop or the way our OneDrive / Office 365 is configured...?

**Comment by MRayermannMSFT** [comment] 2019-04-26 18:50
Yes, something weird is going on with OneDrive unfortuately. The AzCopy team is looking into this.

**Comment by springcomp** [comment] 2019-05-06 08:35
@MRayermannMSFT

Sorry for the delayed answer, I was on vacation :-).
Yes, the latest private build works correctly with AzCopy.
Thank you very much.

**Closed** 2019-05-20 18:31 UTC
Labels: :mag: investigate, private build sent

**Comment by ticklen** [comment] 2019-07-29 13:51
Is this latest private build a part of the 1.9.0 release?  I have just taken that release but am receiving failuer when performing an upload:  

{
  "message": "\"failed to perform copy command due to error: cannot start job due to error: nothing can be uploaded, please use --recursive to upload directories.\\n\""
}

**Comment by jinglouMSFT** [comment] 2019-07-29 19:26
@ticklen Could you tell us a bit more on what you were trying to do when the error occured?  Thanks.

**Comment by ticklen** [comment] 2019-07-29 19:36
Move an excel spreadsheet from my onedrive folder into gen2 blob storage.

Nancy Tickle – Enterprise Architect
Work: (804) 796-7083 | Email: ticklen@chesterfield.gov<mailto:ticklen@chesterfield.gov>

**Comment by MRayermannMSFT** [comment] 2019-08-05 16:36
@ticklen can you share with us the AzCopy log file. There should be an action in the activity log to go to it. You can then attach it to a new comment on this issue.
