### ISSUE TITLE
Using Ctrl+Shift+CursorKey in "search by prefix" field does not jump-highlight

### ISSUE THREAD

**Issue by untilted-document** [microsoft/AzureStorageExplorer#3230] opened 2020-07-14 12:09 UTC
**Storage Explorer Version**: 1.14.0
**Build Number**: 20200624.3
**Platform/OS**: W10
**Architecture**: x64
**Regression From**:  Don't know

## Bug Description ##
In text boxes on windows I can position the caret, hold shift and control and press cursor keys. The SHIFT makes the selection highlight occur when the caret moves, and the CTRL makes the caret jump word by word, so CTRL+SHIFT+CURSOR is faster way of selecting than SHIFT+CURSOR

The caret does not move when CTRL+SHIFT+CURSOR is pressed in this field

## Steps to Reproduce ##
1. Paste or write some long thing into the search field, such as "lorem ipsum dolor blah"
2. The caret is at the end of the box
3. Hold ctrl+shift. press LEFT cursor
4. Nothing happens

## Expected Experience ##
1 I expect "blah" to be highlighted". If I press LEFT again, I expect "dolor" to be highlighted, etc

## Actual Experience ##
1. The cursor remains flashing away at the end of the box, not moving, not highlighting

## Additional Context ##
1. Each on their own, CTRL+CURSOR causes the caret to jump. SHIFT+CURSOR causes selection of one character. CTRL+CHIFT+CURSOR is a no-op

**Comment by untilted-document** [comment] 2020-07-16 09:25
And bizarrely... today I find that pressing CTRL+SHIFT+CURSOR in that "search prefix" box causes ASE to navigate up and down the "folder hierarchy", pressing LEFT goes to parent dir, pressing RIGHT goes to the subdir I was in before I pressed LEFT

Some key combo overriding default text box behaviour? Had I not navigated anywhere yesterday and hence no nav was possible so my pressing was a non op?

The `<-` and `->` arrows to the left of the "active blobs" drop down behave the same way.. but I note their tooltip says ALT+LEFT/RIGHT, not CTRL+SHIFT+L/R

(I'd like normal textbox behavior when in the textbox, regardless of app-wide nav hotkeys..)

**Comment by MRayermannMSFT** [comment] 2020-12-09 02:37
This won't be fixed in 1.17 unfortunately, but I've started looking into finding the root cause.

**Comment by MRayermannMSFT** [comment] 2021-01-15 21:44
This should be fixed in 1.18. I have found the offending code (I didn't write it! :P) and am working on a fix.

**Comment by MRayermannMSFT** [comment] 2021-01-27 00:23
Fix merged into main for 1.18 release

**Closed by MRayermannMSFT** 2021-01-27 00:23 UTC
Labels: :beetle: bug
