### ISSUE TITLE
"Pin to Taskbar" shortcut opens windows as a separate Taskbar button

### ISSUE THREAD

**Issue by Jehoel** [microsoft/AzureStorageExplorer#2238] opened 2019-11-07 11:26 UTC
**Storage Explorer Version**: 1.10.1 (I just updated to version 1.11.0 and the issue is still present)
**Build Number**: 20190912.2 (and 20191105.2)
**Platform/OS**: Windows 10, 1809
**Architecture**: x64
**Regression From**:  I remember it working earlier this year

## Bug Description and Steps to Reproduce  ##

1. Right-click the Azure Storage Explorer shortcut added to the Start menu > All Programs menu.
2. Choose "Pin to Taskbar".
3. Observe the shortcut is added to the Taskbar.
4. Right-click the pinned taskbar shortcut > Right-click on "Azure Storage Explorer" > Properties
5. Observe the shortcut is the main executable (`"C:\Program Files (x86)\Microsoft Azure Storage Explorer\StorageExplorer.exe"`) and not anything like an "advertised" Windows Installer shortcut (which always seem to misbehave for me.  
    ![image]( https://user-images.githubusercontent.com/1693078/68385395-858cf980-010e-11ea-8e62-275f2b1695e6.png )

6. Left-click the pinned shortcut on the taskbar.
7. Observe that Azure Storage Explorer's window opens with a separate taskbar button that does not use the pinned taskbar shortcut button.

## Expected Experience ##
I expected the pinned shortcut to expand when opened into a main window button, instead of being added to the taskbar as a separate button.

## Actual Experience ##
Azure Storage Explorer's windows did not take the place of the pinned button but instead appeared as a separate button.

## Additional Context ##
Probably a bug in Electron, but my other Electron apps behave correctly (like Slack, Visual Studio Code, GitKraken, etc).

## Screenshot ##

![image](https://user-images.githubusercontent.com/1693078/68385303-54acc480-010e-11ea-9664-54578e91dfd5.png)

**Comment by MRayermannMSFT** [comment] 2020-07-24 19:09
@Jehoel  are you still reproducing this?

**Comment by Jehoel** [comment] 2020-07-25 01:29
@MRayermannMSFT Yup:

Screenshot taken just now, running Azure Storage Explorer 1.14.2 on Windows 10 version 1809.

My pinned taskbar shortcut is generated from the official start-menu shortcut via "Pin to Taskbar" and is still repros when I create a manual `*.lnk` to the Storage Explorer program.

![image](https://user-images.githubusercontent.com/1693078/88446006-756f9400-cddb-11ea-9e51-dcd264ad2138.png)

**Comment by JasonYeMSFT** [comment] 2020-08-04 20:29
@Jehoel There is a work around for it. You can open Storage Explorer and on the running instance's taskbar tab, right click and select "pin to taskbar". And then you can remove the original taskbar tab pinned from the Start Menu. If you open Storage Explorer (or open new window for Storage Explorer) from the new taskbar tab, the tabs will be correctly stacked.

**Comment by Jehoel** [comment] 2020-08-05 00:07
@JasonYeMSFT

That doesn't work for me because Windows reports that the *second* Azure Storage Explorer shortcut is already pinned:

![image](https://user-images.githubusercontent.com/1693078/89357330-031d7000-d675-11ea-8835-2edecc610632.png)

**Comment by MRayermannMSFT** [comment] 2020-08-11 18:46
@Jehoel , ok I was able to reproduce by:
1. search in start menu
2. click pin to start
![image](https://user-images.githubusercontent.com/21112697/89935805-9f8cc880-dbc7-11ea-88f9-a4929300cba9.png)
I'm not sure why doing it that way causes this issue. There's nothing odd about the shortcut, it looks correct.

But anyways, to do @JasonYeMSFT's suggestion, you'll need to:
1. Unpin whatever you have in the taskbar
2. Start storage explorer.
3. Once the main window is running, pin the icon to the taskbar

**Comment by MRayermannMSFT** [comment] 2020-08-11 18:47
(also, nice desktop background 😀)

**Comment by MRayermannMSFT** [comment] 2020-09-29 17:54
@Jehoel it's been well over a month since you last replied. I'm going to go ahead and close this issue now.

**Closed by MRayermannMSFT** 2020-09-29 17:54 UTC
