### ISSUE TITLE
1.11 Cannot open DataLake folder at sub folder level - 2 levels down from container

### ISSUE THREAD

**Issue by petarvucetin** [microsoft/AzureStorageExplorer#2245] opened 2019-11-08 17:38 UTC
**Storage Explorer Version**: 1.11.0
**Build Number**: 1.11.0
**Platform/OS**: Windows 10
**Architecture**:  x64
**Regression From**:  1.10

## Bug Description ##

Clicking folder that is 2nd level deep from container in DataLake Gen 2 errors out.

container/Folder1/Folder2 <- error

## Steps to Reproduce ##

Gen 2 Data Lake using KeyVault with certificate
Navigate 2 levels from container 

<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist. RequestId:f0103704-001e-012b-7c5a-966bee00000

## Expected Experience ##

Expected to see subfolders and files 

## Actual Experience ##

https://ibb.co/gTx8pQg
Blank screen with error above

## Additional Context ##

Data lake is encrypted with custom certificate in KV

**Comment by jinglouMSFT** [comment] 2019-11-08 22:28
You might have hit a platform bug we just discovered today.  The platform team is fixing the issue. If you are blocked, please consider going back to 1.10.1.  You can find the build here in the Release tab.

**Comment by MRayermannMSFT** [comment] 2019-12-16 19:19
Closing due to lack of reply.

**Closed by MRayermannMSFT** 2019-12-16 19:19 UTC

**Comment by yuttakon-cvx** [comment] 2019-12-26 06:11
Have the same issue,

Version. 1.11.2
The "The specified resource does not exist" seems to apply for exception when it try to access attribute resultOrError.error.
![image](https://user-images.githubusercontent.com/59244520/71460738-ba98fc80-27df-11ea-82a9-8f1e98ae0229.png)

- We have the access to the folder (via a member of Azure AD's group, confirmed by accessibility on version 1.9.0)
- We are owner of the folder, not container
- Seems like an attempt to use marshaler or Promise lib cause the error here
