### ISSUE TITLE
Azure File Share Used Capacity and Quotas measures are displayed on GB instead GiB

### ISSUE THREAD

**Issue by aamorale** [microsoft/AzureStorageExplorer#3437] opened 2020-08-20 15:24 UTC
Used capacity and quotas are displayed in GB however the information doesn't match with the same information observed from the portal because the correct measure type should be GiB this mismatch information cause confusion on customers.

Please update this measure type on further Storage Explorer versions.

**Comment by MRayermannMSFT** [comment] 2020-08-24 17:50
Duplicate of #2840

**Closed by MRayermannMSFT** 2020-08-24 17:50 UTC
