### ISSUE TITLE
Search box in storage container tab does not support copy&paste

### ISSUE THREAD

**Issue by andreacassioli** [microsoft/AzureStorageExplorer#3382] opened 2020-08-11 11:27 UTC
I have noticed that the search box in the storage Blob containers tab does not support standard copy and paste operations (including select all for instance). This is quite annoying and limiting. 

In my use case, I often paste a UUID from an application deeplink to retrieve data from a blob storage folder, whose name is the UUID. If I need to search twice, tthe search box force me to manually delete the first UUID I searched for.

I am running on

```
Version: 1.14.2
AzCopy Version: 10.5.0

Platform: macOS
Architecture: x64 
Build Number: 20200715.2 
Commit: c8e3bc3d2 
```

**Comment by MRayermannMSFT** [comment] 2020-08-17 17:57
@andreacassioli are you trying to copy and paste via context menu or keyboard shortcut?

On our end, on macOS, using shortcuts (cmd+c, cmd+v, cmd+x) works fine. We did notice that select all (cmd+a) isn't working. Also on our end, we confirm that right clicking doesn't bring up a context menu.

**Comment by andreacassioli** [comment] 2020-08-17 20:18
Hi @MRayermannMSFT 
thanks for getting back. I confirm your findings: cmd+a and right click not working, while cmd+c, cmd+v, cmd+x do.

**Comment by MRayermannMSFT** [comment] 2020-08-24 18:17
@andreacassioli is that good enough for you or are you looking for additional support, beyond cmd+c, v, and x?

**Comment by andreacassioli** [comment] 2020-08-24 18:58
Both cmd+a and right click support are standard support I do expect on any GUI. For my personal use case, cmd+a is fundamental.

**Comment by MRayermannMSFT** [comment] 2023-10-09 15:52
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/4205

**Closed by MRayermannMSFT** 2023-10-09 15:52 UTC
Labels: :bulb: feature request
