### ISSUE TITLE
Storage Explorer doesn't do anything when you try to create a shared access signature (SAS) without a start time for a Storage Account

### ISSUE THREAD

**Issue by kczelusniak** [Microsoft/AzureStorageExplorer#95] opened 2018-04-26 20:34 UTC
**Storage Explorer Version:** `1.0.0`

**OS Version:** `Windows 7 Professional`

**Steps to Reproduce:**
1. Right click on a Storage Account
2. Click `Get Shared Access Signature...`
3. Scroll over `Start time` input box
4. Click `X` to remove the start time
5. Click `Create`

![image](https://user-images.githubusercontent.com/1730871/39330428-3bb38aa0-4967-11e8-9f0e-b0ca52c1950e.png)
![image](https://user-images.githubusercontent.com/1730871/39330364-04b5efb6-4967-11e8-824e-2fa8a94b3522.png)

**Expected Experience:**
Storage Explorer should create a shared access signature (SAS). The start time for an SAS is [optional](https://docs.microsoft.com/en-us/azure/storage/common/storage-dotnet-shared-access-signature-part-1#parameters-common-to-account-sas-and-service-sas-tokens).

**Actual Experience:**
Nothing happens.

**Comment by craxal** [comment] 2018-04-26 20:56
Duplicate of #77.

**Closed by craxal** 2018-04-26 20:56 UTC
Labels: bug, duplicate
