### ISSUE TITLE
It is no longer possible to work with blob names containing colons

### ISSUE THREAD

**Issue by sgryt** [microsoft/AzureStorageExplorer#2578] opened 2020-01-27 12:32 UTC
Until quite recently, the storage explorer could download blobs with colons in their name, and it was possible to download (and edit) the blobs to a local file (where the name would be an encoded version of the blob name). When the local copy was subsequently changed and saved, the storage explorer would present some options about snapshotting, overwriting or  ignoring the change. If one chose snapshot or overwrite, the blob in storage would then be modified accordingly.

This is no longer possible - the download stage is broken. The error message in the Activities tab is something along the lines of: `Transfer from 'tenants/' to '%AppData%\Local\Temp\15801277704550' failed: 0 items transferred, 1 item failed (used SAS, discovery completed)`

Looking into the AzCopy logs, it seems that the filename deduced from the blob name is no longer being transformed into a filesystem-friendly version (slightly redacted log entry follows):

2020/01/27 12:22:51 ERR: [P#0-T#0] DOWNLOADFAILED: https://XYZ.blob.core.windows.net/tenants/urn:grn:development:localhost.domains?se=2020-02-26t12%3A22%3A50z&sig=-REDACTED-&sp=rl&sr=c&sv=2018-03-28 : 000 : File Creation Error The filename, directory name, or volume label syntax is incorrect.
   Dst: %5C%5C?\%AppData%\Local\Temp\15801277704550\urn:grn:development:localhost.domains

Please restore the ability to work with blob names that are valid in Azure.

**Comment by nerddtvg** [comment] 2020-01-27 13:54
Thanks for opening this. It is similar, or possibly a regression, to #1350. I tried both 1.11.2 and 1.12.0 and had issues.

Simply having the ability to set blob names on download would be awesome as well.

**Comment by MRayermannMSFT** [comment] 2020-01-27 18:37
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/2297

We're aware of this regression and the AzCopy team is working on a fix.

**Closed by MRayermannMSFT** 2020-01-27 18:37 UTC
