### ISSUE TITLE
Option to Upload PageBlobs to BlockBlobStorage and BlobStorage Accounts

### ISSUE THREAD

**Issue by jcrobins** [Microsoft/AzureStorageExplorer#1170] opened 2019-02-28 01:27 UTC
**Storage Explorer Version**: 1.6.2
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: N/A

#### Steps to Reproduce:
1. Create a Premium BlockBlobStorage (or Standard BlobStorage) storage account.
2. Select the created storage account in Storage Explorer.
3. Select a container in this account in Storage Explorer and select **Upload** > **Upload Files...** to view the **Microsoft Azure Storage Explorer - Upload Files to Blob Container** dialog.

#### Expected Experience:
**Page Blob** should not be a selectable option in the **Blob type** drop-down.
The "Upload .vhd/vhdx files as page blobs (recommended)" checkbox should not be available.

#### Actual Experience:
**Page Blobs** are a selectable option in the **Blob type** drop-down.
The "Upload .vhd/vhdx files as page blobs (recommended)" checkbox is available.

**Comment by jcrobins** [comment] 2019-02-28 01:28
Related to https://github.com/Microsoft/AzureStorageExplorer/issues/1171

**Comment by jcrobins** [comment] 2019-02-28 01:42
Also Semi-Related:
https://github.com/Microsoft/AzureStorageExplorer/issues/1172

**Comment by MRayermannMSFT** [comment] 2019-03-06 19:34
Essentially a duplicate of #1171. Simply asking for upload dialog to not offer blob types that won't work with the current Storage Account type.

**Closed by MRayermannMSFT** 2019-03-06 19:34 UTC
