### ISSUE TITLE
An error info bar pops up when attaching one file share at the first time using SAS which generated with access policy

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3996] opened 2021-01-21 07:46 UTC
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210120.8
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Right click the file share -> Select 'Manage Access Policies...'.
3. Add one access policy -> Click 'Save'.
4. Create a SAS for the file share by selecting the access policy.
5. Attach the file share using the SAS -> Check no error info bar pops up.

## Expected Experience ##
No error info bar pops up.

## Actual Experience ##
An error info bar pops up.
![image](https://user-images.githubusercontent.com/41351993/105315104-d1d03680-5bf9-11eb-9018-13cca67283f3.png)
`Authentication error: SAS identifier cannot be found for specified signed identifier.`

## Additional Context ##
This issue can't be consistently reproduced.

**Comment by MRayermannMSFT** [comment] 2021-02-01 18:52
@v-xianya what permissions are you using for the access policy, and is it being used before the expiration of the policy/what is the expiration date?

**Comment by v-xianya** [comment] 2021-02-03 09:15
@MRayermannMSFT The access policy as below: [This issue can not be reproduced consistently, This issue also can be reproduced when the access policy with full permissions]
![image](https://user-images.githubusercontent.com/41351993/106723253-dfe27600-6641-11eb-9fec-d4c102c8275e.png)

![test](https://user-images.githubusercontent.com/41351993/106723073-b295c800-6641-11eb-98b1-f6c4ef101a91.gif)

**Comment by JasonYeMSFT** [comment] 2021-02-03 21:43
I managed to reproduce it by creating a new file share, create a new access policy and then attach immediately. It seems like the bug is due to some timing issue when the new access policy isn't applied yet.

**Comment by JasonYeMSFT** [comment] 2021-02-08 22:30
I am going to close this issue since this is rare to hit and there aren't anything we can do.

**Closed by JasonYeMSFT** 2021-02-08 22:30 UTC
Labels: :gear: files, :gear: sas, 🧪 testing
