### ISSUE TITLE
Miss colon next to the string 'Please specify the new name' in Rename dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2429] opened 2019-12-13 09:08 UTC
**Storage Explorer Version:** 1.11.2
**Build:** [20191213.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3318376)
**Branch:** hotfix/1.11.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous build([20191212.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3315517&view=results))

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Select one blob container and right click it -> Click 'Rename...'.
3. Check whether there shows a colon next to the string 'Please specify the new name' in Rename dialog or not.

**Expect Experience:**
Show a colon next to the string 'Please specify the new name'.
![image](https://user-images.githubusercontent.com/41351993/70788026-f0df8080-1dca-11ea-94c9-be408730d41a.png)

**Actual Experience:**
No colon shows next to the string 'Please specify the new name'.
![image](https://user-images.githubusercontent.com/41351993/70786135-e58a5600-1dc6-11ea-9779-3c9c6f67b8e5.png)

**More Info:**
1. This issue also reproduces for one file share/ table.

**Comment by MRayermannMSFT** [comment] 2019-12-13 16:58
Since the tested build is a hotfix of 1.11.1, this bug is expected to reproduce. It has already been fixed on master though for 1.12.0.

**Closed by MRayermannMSFT** 2019-12-13 16:58 UTC
Labels: :beetle: regression, 🧪 testing
