### ISSUE TITLE
Is the source fpr Azure Storage Explorer available anywhere ?

### ISSUE THREAD

**Issue by jlongo62** [microsoft/AzureStorageExplorer#7407] opened 2023-10-14 02:22 UTC

**Comment by jlongo62** [comment] 2023-10-14 02:23
I would like to use the source for another project. Is it available in another repo ?

**Comment by MRayermannMSFT** [comment] 2023-10-16 17:23
Unfortunately it is not available at this time. However, if there you have a question about how storage explorer does something, we may be able to answer. Just let us know. I'll try to look back at this issue at least once again later this week to see if you ask something.

Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/138

**Closed by MRayermannMSFT** 2023-10-16 17:23 UTC

**Comment by jlongo62** [comment] 2023-10-16 17:34
I actually wanted to modify the source for an internal project.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
