### ISSUE TITLE
Remove the red border on the Rename Blob dialog 	

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#989] opened 2018-12-11 09:06 UTC
**Storage Explorer Version**: 1.6.1
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181211.1
**Commit**: 2455da61
**Regression From**: Previous release 1.6.0

#### Steps to Reproduce: ####
1. Expand anyone account -> Blob Contains node.
2. Open one blob container which contains one blob at least -> Right click one blob then select 'Rename...'.
3. Check the Rename dialog.

#### Expected Experience: ####
1. There is no red border on the Rename dialog.
2. 'OK' button is disabled.

#### Actual Experience: ####
1. There shows a red border on the Rename dialog.
2. 'OK' button is disabled.
![rename](https://user-images.githubusercontent.com/34729022/49789387-d5303d00-fd66-11e8-88b5-4c6375e69506.png)

#### More info: ####
This issue doesn't reproduce on Rename File dialog for file shares.

**Comment by MRayermannMSFT** [comment] 2018-12-13 00:51
This still hasn't been merged. Reopening.

**Comment by v-xuanzh** [comment] 2018-12-13 05:03
This issue has been fixed on the build 20181213.1. Could you help to resolve it?

**Comment by MRayermannMSFT** [comment] 2018-12-13 17:01
Oh, guess it was then. :)

**Closed by MRayermannMSFT** 2018-12-13 17:01 UTC
Labels: :gear: blobs, :white_check_mark: merged, :x: regression, testing

**Comment by craxal** [comment] 2018-12-13 17:47
@v-xuanzh, this is now by design. We don't think it should be considered an error to use the same name in the dialog. We detect after the dialog is closed if the name is identical. We only perform the rename if the name is actually different.
