### ISSUE TITLE
Hitting spacebar/enter on toolbar buttons doesn't execute buttons

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#4743] opened 2021-08-02 17:42 UTC
😢 Observed on main, commit da530cb6a38c9ef7d3c6ed14d993f1f49f3b1596

**Comment by craxal** [comment] 2021-08-02 17:56
I'm marking this as a regression, because this was definitely working before. It might be due to the Electron update, but I'm not sure why default `<button>` behavior would suddenly stop working.

**Closed** 2021-08-10 21:32 UTC
Labels: :heavy_check_mark: merged, :wheelchair: accessibility, :beetle: regression
