### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by CanadianThistle** [microsoft/AzureStorageExplorer#6388] opened 2022-12-22 15:16 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.1

### Regression From

yes, not sure which version, worked on 12-19-2022

### Architecture

i86

### Storage Explorer Build Number

20221220.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "TypeError",
  "message": "Cannot read properties of undefined (reading 'version')",
  "stack": "TypeError: Cannot read properties of undefined (reading 'version')\n    at connectionIsV1 (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\IConnectionInfo.js:8:24)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\CustomConnectionStore.js:235:74\n    at Array.filter (<anonymous>)\n    at #sendTelemetry (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\CustomConnectionStore.js:235:14)\n    at async CustomConnectionStore.getCustomConnectionStore (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\CustomConnectionStore.js:44:9)\n    at async PersistentStorage.CustomConnections.getCustomConnections (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\providers\\CustomConnectionsProvider.js:10:39)\n    at async Provider.executeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async ElectronRendererHostProxy._handleExecuteRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\ElectronRendererHostProxy.js:213:35)\n    at async ElectronRendererHostProxy._handleMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\ElectronRendererHostProxy.js:156:24)"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Click on Emulator & Attached > try to expand the Storage Accounts item
3. Get the error 'Unable to retrieve child resources.'
4. I then tried the Connect to Azure Storage modal, entered my connection string, and instead of automatically populating a display name, there was none. When I typed one in, the file got a red box around it, so I could not proceed.  

NOTE: Architecture info says it's: ia32. (Only options in ddl above are i86 and x64)

### Actual Experience

see above

### Expected Experience

see above

**Comment by craxal** [comment] 2023-01-09 18:50
Duplicate of #6399

**Closed by craxal** 2023-01-09 18:50 UTC
