### ISSUE TITLE
Large uploads still stalling at a random percentage.

### ISSUE THREAD

**Issue by SammMoney** [microsoft/AzureStorageExplorer#8248] opened 2024-10-17 17:54 UTC
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.0

### Regression From

1.32.1

### Architecture

x64

### Storage Explorer Build Number

20241012.1

### Platform

Windows

### OS Version

Windows 10/Windows 11

### Bug Description

Uploading files to Azure Blob, generally after transferring large datasets storage explorer stops at a random percentage.  However, the software still says "Transferring"  No bandwidth limits set.

I am not skilled enough to run AzCopy I would need precise directions on how to do so.  Where to install it, how to run it, etc.

Smaller datasets upload fine, and going back to version 1.32.1 the problem is non-existent. This happens with my entire team.

### Steps to Reproduce

1. Open storage explorer.
2. Upload large number of files.  In this case, I'm uploading 550GB of data.
3. Stops mid upload

### Actual Experience

![Image](https://github.com/user-attachments/assets/d5ac14bf-79f4-40de-96bf-cbfd74a8ac1d)

### Expected Experience

Data to completely upload.

**Comment by craxal** [comment] 2024-10-18 23:16
This is a known issue, and we've had several reports already. We are working with AzCopy to get a fix for this soon.

Duplicate of #8200.

**Closed by craxal** 2024-10-18 23:16 UTC
Labels: :white_check_mark: duplicate
