### ISSUE TITLE
Files are not being uploaded to Azure file shares via Storage Explorer

### ISSUE THREAD

**Issue by manishjha2088** [microsoft/AzureStorageExplorer#3209] opened 2020-07-09 20:02 UTC
**Storage Explorer Version**:  1.14.0
**Build Number**: 20200624.3
**Platform/OS**:  Windows
**Architecture**: x64
**Regression From**: Not sure 

## Bug Description ##
While trying to copy Multiple file to Azure file share the upload is always failing 

```
2020/07/01 10:02:05 ERR: [P#0-T#4] UPLOADFAILED: %5C%5C?\C:\Users\Manish.Jha\Desktop\New folder\230808.jpg : 404 : 404 The specified resource does not exist.. When Uploading range. X-Ms-Request-Id: fc4e03b8-501a-00f7-518e-4f66ad000000

   Dst: https://enableqastorage.file.core.windows.net/msh-qa-cifs/QA/DamDrop/230808.jpg?se=2020-07-31t10%3A01%3A25z&sig=-REDACTED-&sp=rwl&sr=s&sv=2018-03-28
2020/07/01 10:02:05 ==> REQUEST/RESPONSE (Try=1/1.6235043s, OpTime=1.6235043s) -- RESPONSE STATUS CODE ERROR
   DELETE https://enableqastorage.file.core.windows.net/msh-qa-cifs/QA/DamDrop/230610.jpg?se=2020-07-31t10%3A01%3A25z&sig=-REDACTED-&sp=rwl&sr=s&sv=2018-03-28&timeout=121
   User-Agent: [Microsoft Azure Storage Explorer, 1.13.1, win32,  AzCopy/10.4.2 Azure-Storage/0.7.0 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [9ca46a95-bfcb-42d2-63cf-61bee5ed89e4]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Content-Length: [279]
   Content-Type: [application/xml]
   Date: [Wed, 01 Jul 2020 10:02:03 GMT]
   Server: [Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [9ca46a95-bfcb-42d2-63cf-61bee5ed89e4]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [e651d4dc-e01a-0090-6b8e-4f7651000000]
   X-Ms-Version: [2019-02-02]
Response Details: ﻿<Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission. </Message>
```

## Steps to Reproduce ##

1) Create an Azure file share 

2) have a job running in the background to automatically move the file to a different location, in my case its the application which picks up the file from this location for processing , this is a continuous job as soon as file is dropped at this location, it takes it up for processing 

3) drop multiple files , in my case i am trying to upload 50 images  with the total size of the files 150 MB, this is where we would notice the failure

**Note**: I am connecting to Storage Explorer via Storage account admin key , it works fine for the other folder where we dont have the property to move the files

## Expected Experience ##
The files should be uploaded successfully

**Comment by MRayermannMSFT** [comment] 2020-07-13 18:10
@manishjha2088 a couple of questions for you:
- You say "have a job running in the background to automatically move the file to a different location". Can you elaborate on this? Are you saying that there is another program besides Storage Explorer which is moving your files to your file share?
- Can you share the full AzCopy log file with us?
- Are the files you are trying to upload with Storage Explorer the same files as the ones being processed by the "job running in the background"?

**Comment by manishjha2088** [comment] 2020-07-13 19:34
You say "have a job running in the background to automatically move the file to a different location". Can you elaborate on this? Are you saying that there is another program besides Storage Explorer which is moving your files to your file share?

My apologies if the problem statement was not clear , so we have a folder named as "DAMdrop" which is on Azure file share there is a Master Data management application that is continuously running in the background. what happens in the background is that as soon as the Files are uploaded to this folder an application level job moves triggers in and the files which have been uploaded to the Damdrop folder would be moved to  "Import" folder.

Can you share the full AzCopy log file with us?

Sure ,I have attached a couple of log files
[06a0ff37-6a6b-ba4c-77c0-b61d89211738.log](https://github.com/microsoft/AzureStorageExplorer/files/4914667/06a0ff37-6a6b-ba4c-77c0-b61d89211738.log)

[2dbb38ae-86b5-ce42-42c9-e4553e6401f1.log](https://github.com/microsoft/AzureStorageExplorer/files/4914665/2dbb38ae-86b5-ce42-42c9-e4553e6401f1.log)


Are the files you are trying to upload with Storage Explorer the same files as the ones being processed by the "job running in the background"? 

The processing happens from a different folder named as Import but as soon as the files are being dropped at the DAMdrop it gets moved to the Import files folder and from there the files starts getting processed

[1ee9d099-9303-1f47-5f5e-522a2074776c.log](https://github.com/microsoft/AzureStorageExplorer/files/4914662/1ee9d099-9303-1f47-5f5e-522a2074776c.log)

**Comment by manishjha2088** [comment] 2020-07-20 11:01
@MRayermannMSFT  Any update ?

**Comment by MRayermannMSFT** [comment] 2020-08-05 17:34
When you say files are "moved" do you mean that the files are copied to the new folder ("Import")
 and then deleted from the original folder ("DAMdrop")?

**Comment by manishjha2088** [comment] 2020-08-12 07:13
@MRayermannMSFT  its a move operation , the files does not deleted but gets moved 

At this point of time, I tried a workaround, I created another folder ( lets say "Demo" ) in Azure files and then I am dropping the files at this location, used a scheduled task to pick the files from this folder and then drop it in the original  folder where it should have been  ("DAMdrop") from where the application picks the files for processing 

So far this does not seems to work. So not sure if it has something to do with the Storage Explorer or within the App which was causing the issue

**Comment by manishjha2088** [comment] 2020-09-03 19:14
Hey @MRayermannMSFT  any update on the issue ?

**Comment by JasonYeMSFT** [comment] 2020-10-05 18:34
I have looked at the log files. The actual failure is that "the specified resource doesn't exist". All other errors are false alarms and don't matter. If the files do exist there, there might be something wrong with our listing logic.

**Comment by JasonYeMSFT** [comment] 2020-10-28 20:44
I did some investigation using that 1.14.0 and our latest 1.15.1 but unfortunately I wasn't able to reproduce this issue. From the AzCopy log, the error shows up under this condition:
1. AzCopy sends an initial PUT request to create the blob at the destination
2. AzCopy thinks it is done and then send another PUT request to upload the data
3. Somehow step 1 isn't done yet so the 2nd request gets a 404 error.

**Comment by JasonYeMSFT** [comment] 2023-03-30 16:50
I am going to close this issue since the root cause is the background application interrupting AzCopy operation. If you have suggestions on how this could be improved, please open a new feature request.

**Closed by JasonYeMSFT** 2023-03-30 16:50 UTC
Labels: :gear: azcopy
