### ISSUE TITLE
Can't expand subscription to view resources when searching for the subscription

### ISSUE THREAD

**Issue by juliusl** [Microsoft/AzureStorageExplorer#589] opened 2018-08-20 17:54 UTC
[Window Title]
Microsoft Azure Storage Explorer

[Main Instruction]
Microsoft Azure Storage Explorer

[Content]
Version: 1.4.0

Platform: Windows
Architecture: ia32
Build Number: 20180803.3
Commit: c5bc8f60
Support Id: 2f5b2624-a8e5-94df-f0a1-ad5fe1308f84

Copyright © 2018 Microsoft. All rights reserved.

[OK]

#### Steps to Reproduce: ####
1. Search for a subscription.
2. When it is found, the expand glyph is not there. 

#### Expected Experience: ####
Expect to be able to expand the glyph once I click on the subscription.

#### Actual Experience: ####
Can't expand resources must click on the x to clear the search box.
Also, spinning icon doesn't seem to resolve.

![image](https://user-images.githubusercontent.com/5741075/44357575-3b671c00-a467-11e8-99b8-3f135a75fddd.png)

**Comment by MRayermannMSFT** [comment] 2018-08-20 18:00
Spinning icon doesn't go away because we are still searching all of your resources. Also, not being able to expand search results is by design. It used to be that you could click your result, click X, and then the normal tree view would have what you selected focused. But that got broken back in April (#33 ) due to trying to find a workaround for an accessibility bug. Currently 1.8.0 is when we plan on revisiting search, to try and resolve pain points such as the 2 or 3 you're running into. :( So, I'm going to go ahead and close this as duplicate as I feel it falls under #33.

**Closed by MRayermannMSFT** 2018-08-20 18:00 UTC
