### ISSUE TITLE
There is a conflict dialog when pasting one file share which contains a non-empty folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5842] opened 2022-06-15 10:05 UTC
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220615.6
**Branch**: main
**Platform/OS**: Windows 10
**Architecture** ia32
**How Found**: From running test cases
**Regression From**: Previous release (1.24.2)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Click 'Upload -> Upload Files...'.
3. Select files -> Type '/folder1/folder2' to the 'Destination directory'.
![image](https://user-images.githubusercontent.com/41351993/173798247-f2764d8f-6f8c-4935-a26d-f4ed60f4c932.png)
4. Click 'Upload'.
5. Copy the file share -> Paste it to another storage account.
6. Check there is no conflict dialog.

## Expected Experience ##
There is no conflict dialog.

## Actual Experience ##
There is a conflict dialog.
![image](https://user-images.githubusercontent.com/41351993/173799573-5cf9c247-3ada-4234-9d0b-60a15555908a.png)

## Addition Context ##
1. This issue can't be reproduced consistently.
2. For now, we only met this issue on Windows.
3. Here is the screenshot if selecting 'Do not paste -> Apply to All Conflicts'. 
![image](https://user-images.githubusercontent.com/41351993/173799867-87d62dfc-6468-4178-8d0c-744591b6e5d4.png)

**Comment by JasonYeMSFT** [comment] 2022-06-15 23:36
Could you please get us the AzCopy log if you can reproduce it one more time? I suspect it's due to AzCopy ordering the transfers incorrectly.

**Comment by v-xianya** [comment] 2022-06-16 02:56
Got it. Will share the AzCopy log if this issue reproduces again.

**Comment by JasonYeMSFT** [comment] 2022-07-08 20:07
Given it's been long enough that this issue hasn't be reproduced. Let's close this issue. If it reproduces, we can open a new one and investigate.

**Closed by JasonYeMSFT** 2022-07-08 20:07 UTC
Labels: 🧪 testing, :gear: files, :beetle: regression
