### ISSUE TITLE
Sign in using Mooncake AAD account but canot load subscription both in the admin and tennat

### ISSUE THREAD

**Issue by supervicky42** [Microsoft/AzureStorageExplorer#516] opened 2018-07-31 02:34 UTC
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: win10

#### Steps to Reproduce: ####
1. Install the 1.4.0 version Storage Explorer ,Import the certificate.
2. Sign in use Mooncake AAD account.

#### Expected Experience: ####
The account will display its' all subscription.

#### Actual Experience: ####
None.

**Comment by MRayermannMSFT** [comment] 2018-08-10 00:09
This was due to the account being deployed to too many Azure Stack instances. Closing as by design.

**Closed by MRayermannMSFT** 2018-08-10 00:09 UTC
Labels: testing
