### ISSUE TITLE
DateTime properties getting truncated when entity is update in Explorer

### ISSUE THREAD

**Issue by sausriva-msft** [microsoft/AzureStorageExplorer#3235] opened 2020-07-14 23:32 UTC
**Storage Explorer Version**: 1.14.1
**Build Number**: 20200711.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  No, N/A

## Bug Description ##
Upon entity update for storage table using the the tool, all properties stored in DateTime format are truncated and nanoseconds granularity is lost

## Steps to Reproduce ##
1. Create new test table, add entity which PK and RK of choice. 
2. Update entity programmatically to add new DateTimeOffset EntityProperty (lets say 'testDate') to the entity. 
Please note to have nanosenconds level granularity to the datetimeoffset property added. 
Example: var value = new DateTimeOffset(637303659853204411, new TimeSpan(0));
3. Update entity through Storage Explorer (add new property, don't update initially added property from Step 2).
4. Fetch entity programmatically and check 'testDate' property value and note that the DateTimeOffset value has been truncated to remove 100 nanoseconds granularity.
Example: 637303659853204411 -> 637303659853200000

## Expected Experience ##
Expected to have consistent DateTimeOffset value maintained for and entity property when property is not updated manually.

## Actual Experience ##
Inconsistent DateTimeOffset value maintained for and entity property when property is not updated manually.

**Comment by JasonYeMSFT** [comment] 2020-07-15 19:20
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/3095.

**Closed** 2020-08-05 17:37 UTC
Labels: :heavy_check_mark: duplicate
