### ISSUE TITLE
The context menu of the new created file share shows incorrectly under one SAS storage account 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2641] opened 2020-02-18 09:37 UTC
**Storage Explorer Version:** 1.12.0
**Build**: [20200218.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3479076)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Select a storage account -> Use SAS to attach the storage account.
3. Expand Local & Attached -> Create a new file share under the sas storage account.
4. Check the context menu.

**Expect Experience:**
The context menu shows correctly.
![image](https://user-images.githubusercontent.com/54055206/74719445-ffd12c00-526e-11ea-938e-cec3d5fd9b1d.png)

**Actual Experience:**

1. An extra 'Detach' action shows in the context menu.
2. Miss '**Clone with New Name...**' & **'Delete'** & '**Get Shared Access Signatura...'** & '**Manage Access Policies...**' & '**Create Snapshot**' actions in the context menu.

![image](https://user-images.githubusercontent.com/54055206/74719274-b08afb80-526e-11ea-91b0-717822c0490e.png)

**More Info:**

1. This issue also reproduces for one new created queue/table.
2. This issue doesn't reproduce **after manually refresh.**
3. Related bug: [613](https://github.com/microsoft/AzureStorageExplorer/issues/613).

**Comment by v-limu** [comment] 2020-02-27 02:09
Verified on build [20200227.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3506444). The context menu of the new created file share has been fixed. **This issue still reproduces for one new created queue/table**.

**Comment by JasonYeMSFT** [comment] 2020-02-27 17:12
My fix was intended for File Share only. I am closing this issue and I have created another issue (#2676) to track the queue and table since the fix require fundamental refactoring instead of small local changes.

**Closed by JasonYeMSFT** 2020-02-27 17:12 UTC
Labels: :gear: files, :gear: queues, :gear: sas, :gear: tables, 🧪 testing
