### ISSUE TITLE
Failed to get properties for blob item when using Azurite

### ISSUE THREAD

**Issue by sterrius** [microsoft/AzureStorageExplorer#5310] opened 2022-01-04 16:17 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Regression From

No

### Architecture

i86

### Storage Explorer Build Number

20211020.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Storage explorer fails to display properties for any blob item when using Azurite for local development.

### Steps to Reproduce

1. Launch storage explorer
2. Select any blob item and right-click
3. Select 'properties' from the context menu

### Actual Experience

1. Activities pane displays message "Getting properties for '\<id\>'"
2. Times out after about a minute
3. Activities pane displays message "Failed to get properties for '\<id\>'"

### Expected Experience

Popup dialog showing properties for the selected blob item.

### Additional Context

This behaviour is exactly the same as described in ticket #5225, but that ticket has been closed due to lack of activity. The bug appears only when using Azurite, the older Storage Emulator brings up the blob properties as expected.

Following the recommended action from #5225, I found this entry in the Azure Storage Explorer log file:

[2022-01-04T15:51:50.298Z] (se-blob-extension_56440) <ERRO> API call for BlobPathClient.getProperties failed
HEAD http://127.0.0.1:10000/devstoreaccount1/name-of-blob - 500
Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
RequestId: c1cdd31e-73b7-47de-b89a-994b09d3993f, Date sent: Tue, 04 Jan 2022 15:51:50 GMT, ApiVersion: 2019-07-07, ProxySettings: undefined
ErrorCode: FeatureNotSupported

**Comment by matt-goldman** [comment] 2022-01-04 23:11
I have this same issue. However can confirm getting the metadata using CloudBlobClient in code works fine, and can also confirm issue did not occur with legacy storage emulator. So the issue seems to be to do with azurite + storage explorer.

**Comment by MRayermannMSFT** [comment] 2022-01-10 18:37
@sterrius @matt-goldman what version of Azurite are you using? @matt-goldman are you also on Windows, or a differentOS?

**Comment by sterrius** [comment] 2022-01-11 13:06
Hi @MRayermannMSFT,

I'm using the version that was installed with Visual Studio 2022. Doing a File -> Properties on the azurite.exe gives:

File version: 14.17.0.0
Product version: 3.14.1

**Comment by JasonYeMSFT** [comment] 2022-01-11 19:17
You can start azurite instance with the --loose option which should probably mitigate this issue. https://github.com/Azure/Azurite/issues/977

**Comment by matt-goldman** [comment] 2022-01-11 21:54
> @sterrius @matt-goldman what version of Azurite are you using? @matt-goldman are you also on Windows, or a differentOS?

Azurite version 3.15.0. Using on Windows, I will test on macOS and Linux too though and let you know the results.

**Comment by matt-goldman** [comment] 2022-01-13 11:33
Works as expected on macOS with no issue, with version 3.14.2. Will test Linux as soon as I can.

**Comment by JasonYeMSFT** [comment] 2022-01-19 23:54
Closing since the root cause of the issue is out of our control.

**Closed by JasonYeMSFT** 2022-01-19 23:54 UTC
Labels: :gear: emulator
