### ISSUE TITLE
Moving messages between queues

### ISSUE THREAD

**Issue by twoelfer** [microsoft/AzureStorageExplorer#1703] opened 2019-08-22 08:31 UTC
What i would like to see is a way to move messages from one queue to another. This is especially important for the "poison" queues - if the problem that made the msgs end up in a poison queue is resolved, it's not all that easy to move those msgs back to the "real" queue.

The "Cerebrata Cerulean" Software has such a feature.

**Comment by orofino** [comment] 2019-09-25 14:32
I'd like to see this as well.

The ability to 'get' and then 'move' or just 'move all' which would iteratively get and move all the queue items would be amazingly helpful.

As noted by OP, our worker process reads from a primary queue, if there is an issue, our worker puts the queue item into a 'poison' queue (which is really just a normal queue that no workers read from). Those items need to be moved back to the primary queue for processing once the issue is resolved. Sometimes this can be hundreds of messages and this is just generally not feasible to do today.

Happy to provide additional detail or clarification.

**Comment by MRayermannMSFT** [comment] 2020-01-27 18:56
Duplicate of #1064

**Closed by MRayermannMSFT** 2020-01-27 18:56 UTC
Labels: :bulb: feature request, :gear: queues
