### ISSUE TITLE
The total number of items is inconsistent with the number of items transferred for blob containers/file shares if cancelling the transfer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7970] opened 2024-05-30 08:48 UTC
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240530.2
**Branch**: main
**Platform/OS**: Windows 11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: x64/arm64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Try to upload more than 100 files.
3. Click 'Cancel' action next to the transfer activity.
4. After successfully cancelled -> Check the number of transferred items in the activity log.
5. Run 'Folder Statistics' for the blob explorer.
6. Check whether the total number of items is consistent with the number of items transferred.

## Expected Experience ##
The total number of items is consistent with the number of items transferred.

## Actual Experience ##
The total number of items is inconsistent with the number of items transferred.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/c9240b37-206a-4713-842a-55f54cfca501)

## Additional Context ##
This issue also reproduces for file shares.

**Comment by craxal** [comment] 2024-05-30 17:29
It's very common for cancellation in many apps to take time to fully kick in. The thing about cancelling is it's very possible that it may kick in after a successful transfer occurs but before the job has been able to update its numbers, meaning that a few items snuck out before cancellation could fully stop the process.

@RichardMSFT I would not consider this a high priority. Take a look at the code and see how these jobs are cancelling themselves (if it's like what I described above). If it looks like an easy fix, go for it. If not, you can move to another milestone.

**Comment by craxal** [comment] 2024-12-18 22:42
Won't fix unless customers are highly impacted.

**Closed by craxal** 2024-12-18 22:42 UTC
Labels: 🧪 testing, :gear: blobs, :gear: files

**Comment by v-lilyli8** [comment] 2025-03-21 06:27
Update:
This issue also reproduces when deleting a lot of files and then cancelling.
