### ISSUE TITLE
Subscriptions cannot be loaded

### ISSUE THREAD

**Issue by svelupula** [Microsoft/AzureStorageExplorer#336] opened 2018-06-21 15:51 UTC
**Storage Explorer Version**: 1.2.0

**Platform/OS Version**: windows 7 sp1
**Architecture**: x64
**Regression From**: N/A

#### Steps to Reproduce: ####
1. Just installed.

#### Actual Experience: ####
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 7f786e85-2b61-4bbe-a796-71e91e5e7e38, Error: {"code":"SELF_SIGNED_CERT_IN_CHAIN"}

**Comment by bplaats** [comment] 2018-06-21 18:16
I also submitted this same issue earlier today

**Comment by craxal** [comment] 2018-06-22 16:19
Duplicate of #335.

**Closed by craxal** 2018-06-22 16:19 UTC
Labels: :white_check_mark: duplicate

**Comment by PeterParker1234** [comment] 2018-06-24 07:02
This is a serious issue that a lot of people are experiencing. It make the AzureStorageExplorer unreliable. There are many people logging the same issue, where it is just marked duplicate and then closed, without any insight given as to whether any progress is made. Are you able to recreate the issue? Do you need more information? What is the status of this problem?
