### ISSUE TITLE
Don't allow people to rename/clone blobs with "." at the end of the name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3363] opened 2020-08-06 10:20 UTC
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200806.6
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob containers.
2. Create a blob container -> Upload one blob (make sure in the root directory).
3. Clone the blob with name '.' -> Check the result.

**Expect Experience:**
Fail to execute the action.

**Actual Experience:**
1. Show a successful activity log.
2. The original blob disappears. 

**More Info:**
1. This issue doesn't reproduce for one folder.
2. This issue doesn't reproduce for blobs under one folder.

**Comment by MRayermannMSFT** [comment] 2020-11-06 19:39
Duplicate of #3361

**Closed by MRayermannMSFT** 2020-11-06 19:39 UTC
Labels: :gear: adls gen2, :gear: azcopy, :gear: blobs, 🧪 testing
