### ISSUE TITLE
Quick Access does not work when tables with the same name are added from different storage account.

### ISSUE THREAD

**Issue by mibouhy** [microsoft/AzureStorageExplorer#493] opened 2018-07-25 19:51 UTC
Version 1.3.1
Windows 10 PC
ia32
I don't know if it is a regression.

#### Steps to Reproduce: ####
Create two storage accounts.
Create a table name TableX in both storage accounts - storageAccount1, storageAccount2.
Add entity1 to TableX in storageAccount1, Add entity2 to TableX in storageAccount2
Add those two tables TableX to quick access.
In quick access, you will see two TableX, but table from only one storage account is shown, so storageAccount1 or storageAccount2.

#### Expected Experience: ####
I would like to see a prefix before the table name, so I know from which storage account it is related.

**Comment by JasonYeMSFT** [comment] 2018-07-26 21:13
Thanks for reporting this to us. For now, you can use 'open new tab' instead of open/double click if you really want to have two tables with the same name in the editor at the same time.

**Comment by craxal** [comment] 2018-07-27 20:36
This is actually a duplicate of #189. We will be fixing this in a future release.

**Closed by craxal** 2018-07-27 20:36 UTC
Labels: :white_check_mark: duplicate
