### ISSUE TITLE
Export only selected storage table rows

### ISSUE THREAD

**Issue by ppsa-stephan** [microsoft/AzureStorageExplorer#4313] opened 2021-04-10 19:06 UTC
It is possible to query a storage table and export only the rows that result from the query.  That is great.

However, you can also select rows in the storage table, but when you export, you are still forced to export the entire table.

It would be great to be able to export only rows that are selected.

**Comment by MRayermannMSFT** [comment] 2021-08-23 17:39
Duplicate of #4802

**Closed by MRayermannMSFT** 2021-08-23 17:39 UTC
Labels: :bulb: feature request, :gear: tables
