### ISSUE TITLE
.azDownload file when using Azure Storage Explorer

### ISSUE THREAD

**Issue by CornAndBerry** [microsoft/AzureStorageExplorer#4495] opened 2021-05-27 06:57 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Platform

Windows

### OS Version

Windows Server 2019

### Architecture

i86

### Build Number

20210425.1

### Regression From

1.18.0

### Bug Description

When I use the Microsoft Azure Storage Explorer to restore some archived files I get these files when they are restored. I can't open them. What could be the problem here? Also when downloading the whole map, Microsoft Azure Storage Explorer crashes.

The file names looks like this: .azDownload-a744fea2-6d1b-5040-46ef-2003d8add10a-Stockphotos II.zip

### Steps to Reproduce

1. Open archive
2. Right mouse click on map
3. Download
4. Then the download is stuck at some point or the Azure File explorer crashes

### Actual Experience

The Azure File explorer crashes when downloading a map. Or is stuck at 8%. When wee look in the download map some files have weird names and can't open them.

**Comment by CornAndBerry** [comment] 2021-05-27 09:43
![image](https://user-images.githubusercontent.com/84896713/119804446-a4193800-bee0-11eb-9e85-90384820a94f.png)

When the Azure file explorer Crashes I get this error

**Comment by CornAndBerry** [comment] 2021-05-28 11:55
Rebooting the server fixed the problem

**Comment by JasonYeMSFT** [comment] 2021-06-03 17:29
Since this is mitigated, we are going to close the issue. We don't know for sure what is the root cause of this error. Please let us know if you run into this problem again or you somehow figured out what goes wrong.

**Closed by JasonYeMSFT** 2021-06-03 17:29 UTC
Labels: :heavy_check_mark: mitigated
