### ISSUE TITLE
Blob Container sort by date not working

### ISSUE THREAD

**Issue by ygeelen-tb** [microsoft/AzureStorageExplorer#4692] opened 2021-07-19 09:40 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Architecture

x64

### Storage Explorer Build Number

20210425.1

### Platform

Windows

### OS Version

10

### Bug Description

When clicking the grid header column "Last Modified", the sorting is only applied to the entries that have already been fetched / cached. When you have many entries, you first need to click "Load more" many, many times depending on how much data there is before the sorting is applied on all entries.

It would save us A LOT of time if you would sort the entries (newest first) automatically on opening the screen and if you would make the sort work.

### Steps to Reproduce

1. Launch Storage Explorer
2. Open Blob Container
3. Click on "Last Modified" column

### Actual Experience

Only the fetched entries are sorted, so you don't see the most recent entries on top.

### Expected Experience

- Show the most recent entries on top initially by default.
- Sorting takes into account all items instead of only the already fetched/cached items.

**Comment by MRayermannMSFT** [comment] 2021-07-19 17:01
Closing as duplicate of #134

**Closed by MRayermannMSFT** 2021-07-19 17:01 UTC
