### ISSUE TITLE
Search breaks when last character on string is "X"

### ISSUE THREAD

**Issue by wahedkhan** [microsoft/AzureStorageExplorer#3790] opened 2020-11-18 14:17 UTC
Issue:
1. Launch Azure Storage Explorer windows application
2. Connect to storage
3. Navigate to any table
4. Open Query Builder
5. Try searching any string field that ends with "X"
6. Observe...

Expected: Search completes and relevant details displayed
Actual: Throws exception as "Length cannot be less than zero. Parameter name: length RequestID:5e9d6530-29a8-11eb-afd1-b3843c308bc6"
![Screenshot 2020-11-18 194504](https://user-images.githubusercontent.com/2097559/99541360-c0d72f00-29d6-11eb-91df-b3ab46ace1b5.png)
![Screenshot 2020-11-18 194504](https://user-images.githubusercontent.com/2097559/99541425-d0ef0e80-29d6-11eb-9d8b-7a2a5b786c75.png)

**Comment by MRayermannMSFT** [comment] 2020-11-23 19:07
@wahedkhan do you have a space before the X? Can you try removing the space? Or do you have PartitionKeys with spaces in them...?

**Comment by MRayermannMSFT** [comment] 2020-11-23 19:08
Or are you just using PartitionKey as an example?

**Comment by MRayermannMSFT** [comment] 2020-11-23 19:09
What version of Storage Explorer are you using?

**Comment by wahedkhan** [comment] 2020-11-23 19:25
I'm on latest version of storage explorer. Partition key is just an example, you can repro it on any table column. It breaks in SDK too, I tried querying through code and that breaks with same error. Will post code snip during my work hours if needed.

**Comment by MRayermannMSFT** [comment] 2020-11-30 19:11
@wahedkhan can you post your code snippet?

**Comment by MRayermannMSFT** [comment] 2020-12-07 19:06
@wahedkhan ?

**Comment by wahedkhan** [comment] 2020-12-08 17:58
@MRayermannMSFT sorry, I was away for a while...

Assembly Microsoft.WindowsAzure.Storage, Version=9.3.2.0
Code Snip
`var storageAccount = CloudStorageAccount.Parse(<connection string>);
var tableClient = storageAccount.CreateCloudTableClient();
var table = tableClient.GetTableReference(<table name>);
var query = table.CreateQuery<dummyContract>()
                .Where(r => r.<property>.Equals("ABC X"))
                .Take(100)
                .AsTableQuery();
var queryResult = await query.ExecuteSegmentedAsync(<continuationToken>, <cancellationToken>);`

Error On ExecuteSegmentedAsync:
`$exception	{"The remote server returned an error: (500) Internal Server Error."}	Microsoft.WindowsAzure.Storage.StorageException
Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
		HResult	-2146233088	int
		HelpLink	null	string
InnerException	{"The remote server returned an error: (500) Internal Server Error."}	System.Exception {System.Net.WebException}
		Message	"The remote server returned an error: (500) Internal Server Error."	string
RequestInformation	{Microsoft.WindowsAzure.Storage.RequestResult}	Microsoft.WindowsAzure.Storage.RequestResult
		Source	"Microsoft.WindowsAzure.Storage"	string
		StackTrace	"   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)\r\n   at Microsoft.WindowsAzure.Storage.Table.TableQuery`1.EndExecuteSegmented(IAsyncResult asyncResult)\r\n   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass2`1.<CreateCallback>b__0(IAsyncResult ar)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at TableOperations.TableQueryExtensions.<ExecuteAsyncAll>d__1`1.MoveNext() in C:\\Users\\...\\Program.cs:line 246"	string
TargetSite	{T EndExecuteAsync[T](System.IAsyncResult)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
Static members		
Non-Public members`

**Comment by MRayermannMSFT** [comment] 2020-12-14 18:52
@wahedkhan are you working against an emulator and if so, which one (.NET emulator vs Azurite) and which version?

**Comment by wahedkhan** [comment] 2020-12-16 07:04
@MRayermannMSFT no emulator used

**Comment by craxal** [comment] 2021-02-23 19:59
@wahedkhan I tried the exact same thing and could not reproduce the issue. Judging by the errors, it sounds like the problem may be in your table or table service.

Have you tried running your query again? If the issue still occurs, I would suggest taking note of the request ID and opening an [Azure service request](https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request).

**Comment by JasonYeMSFT** [comment] 2021-04-05 18:34
Closing due to unable to reproduce. If you still have this problem, please open another issue then.

**Closed by JasonYeMSFT** 2021-04-05 18:34 UTC
Labels: :gear: tables, :grey_question: external, :grey_question: investigate
