### ISSUE TITLE
Metadata key names change when copying between containers

### ISSUE THREAD

**Issue by ericthomas1** [microsoft/AzureStorageExplorer#8083] opened 2024-07-25 23:24 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Regression From

?

### Architecture

x64

### Storage Explorer Build Number

20240523.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

When I copy a blob that has metadata associated with it, from one blob container to another, the keys of all metadata are suddenly capitalized. To use metadata programmatically, post-copy, requires additional handling. Would be awesome if this was addressed.

### Steps to Reproduce

1. Create a blob
2. Apply lower-case metadata to the blob
3. Copy the blob to a different Container
4. Right click on both blobs and view Properties

You will see that the new blob has the first char of all metadata keys capitalized...

### Actual Experience

1. Create a blob
2. Apply lower-case metadata to the blob
3. Copy the blob to a different Container
4. Right click on both blobs and view Properties

You will see that the new blob has the first char of all metadata keys capitalized...

### Expected Experience

Metadata is not affected by copying a blob.

**Comment by MRayermannMSFT** [comment] 2024-07-29 18:46
@ericthomas1 an initial quick reply I can give you is that you should be reading/treating blob metadata keys case insensitively. I know with AzCopy there have been reports in the past of transfers causing changes to the casing of metadata keys. I can try to double check on where those reports landed, but at the end of the day, my original guidance is what should be heeded.

See here for more info: https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#:~:text=but%20are%20case%2Dinsensitive%20when%20set%20or%20read

**Comment by ericthomas1** [comment] 2024-07-29 19:18
Thank you for the response. I wonder if the doc should be updated as `Note that metadata names preserve the case with which they were created` is not accurate. I created the metadata names in lower-case. Upon copying, they were automatically sentence-cased (First character upper-cased).

**Comment by craxal** [comment] 2024-08-05 19:02
@RichardMSFT Let's first investigate to pinpoint which component may be modifying the casing. Then let's work on a fix if possible.

**Comment by JasonYeMSFT** [comment] 2024-08-08 00:13
@ericthomas1 Blob copy uses AzCopy which has this issue for a long time. According to that discussion, the root cause seems to be somewhere in their Go SDK. Feel free to make a comment in the AzCopy issue or maybe create a new issue to bring their attention. We'll do our best to communicate this issue to them in our internal channel. 

https://github.com/Azure/azure-storage-azcopy/issues/113

**Comment by JasonYeMSFT** [comment] 2024-08-30 21:53
@ericthomas1 This is due to an underlying issue in the Go standard library which cannot be addressed by us anytime soon. Could you try to find a work around using other tools for now? I am sorry but I need to close this issue for now because there is nothing we can do.
https://github.com/golang/go/issues/37834

**Closed by JasonYeMSFT** 2024-08-30 21:53 UTC
Labels: :grey_question: external, :gear: azcopy
