### ISSUE TITLE
Show incorrect contents in the first opened 'Shared Access Signature' dialog after restarting Storage Explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6692] opened 2023-03-21 10:03 UTC
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230320.5
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: exploratory testing
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Restart Storage Explorer.
2. Right click one storage account -> Click 'Get Shared Access Signature...'.
3. A dialog pops up.
4. Check whether shows correct contents in the dialog.

## Expected Experience ##
Show correct contents in the dialog.
![image](https://user-images.githubusercontent.com/41351993/226570818-f4e8468f-9502-48f3-b7a3-a2c4459c84bf.png)

## Actual Experience ##
Show incorrect contents in the dialog.
![image](https://user-images.githubusercontent.com/41351993/226570637-c6ac021d-3d1a-42bf-b949-3b27274117a3.png)

## Additional Context ##
This issue doesn't reproduce on Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro).

**Comment by MRayermannMSFT** [comment] 2023-03-27 18:10
Root cause is duplicate of #6689

**Closed by MRayermannMSFT** 2023-03-27 18:10 UTC
Labels: 🧪 testing, :beetle: regression, :computer: windows
