### ISSUE TITLE
Blob Metadata Browser/Viewer

### ISSUE THREAD

**Issue by jtlz2** [microsoft/AzureStorageExplorer#1436] opened 2019-06-04 09:28 UTC
**Is your feature request related to a problem? Please describe.**

I am always frustrated when I try to quickly view blob metadata for a large number of different blobs. Right now I have to right click -> Properties and fire up a (blocking) window for each blob in turn.

**Describe the solution you'd like**

I would like the Properties window to persist and be non-blocking. I don't mind latency but being able to simply browse metadata relatively rapidly would be an enormous help.

**Describe alternatives you've considered**

Being patient / slowing down the pace of life (inefficient as it is).

**Additional context**

None

Thanks

**Comment by maskati** [comment] 2019-09-27 04:52
Alternatively being able to add custom blob metadata as columns similarly to how you can configure table columns.

**Comment by MRayermannMSFT** [comment] 2020-04-13 18:54
Duplicate of #2101

**Closed by MRayermannMSFT** 2020-04-13 18:54 UTC
Labels: :bulb: feature request
