### ISSUE TITLE
The activity log is always in progress if soft deleting one rehydrate ADLS Gen2 blob then clicking 'Folder Statistics'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7588] opened 2023-12-14 09:54 UTC
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231214.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1.2 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Change the blob access tier to 'Archive' -> Then change the archive blob access tier to 'Hot'.
4. Soft delete the rehydrate blob -> Click 'Folder Statistics'.
5. Check whether the activity log can be completed.

## Expected Experience ##
The activity log can be completed.

## Actual Experience ##
The activity log is always in progress.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/1cac1d26-4b10-4c11-8807-289f63eba468)

**Comment by craxal** [comment] 2023-12-14 17:30
@JasonYeMSFT Sounds like it could be an edge case. Can you find out if there's an easy fix?

**Comment by JasonYeMSFT** [comment] 2023-12-14 18:04
This is a duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/6870.

**Closed** 2023-12-14 18:05 UTC
Labels: :white_check_mark: duplicate, 🧪 testing, :gear: adls gen2
