### ISSUE TITLE
Error when opening File Shares of a Azure Storage Account

### ISSUE THREAD

**Issue by brevi77** [microsoft/AzureStorageExplorer#6732] opened 2023-04-02 10:07 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Architecture

i86

### Storage Explorer Build Number

20230309.1

### Platform

All

### OS Version

Windows 10

### Bug Description

Trying to navigate the Files in an Azure Storage account I receive the error: "Unable to retrieve child resources."

### Steps to Reproduce

1. Launch Storage explorer
2. Navigate to the Storage Account
3. Try to expand the File Shares node

### Actual Experience

The system return the error attached in the section Additional Context

### Additional Context

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "request to https://azprblobstorageiqvia.file.core.windows.net/?comp=list failed, reason: getaddrinfo ENOTFOUND azprblobstorageiqvia.file.core.windows.net",
  "stack": "RestError: request to https://azprblobstorageiqvia.file.core.windows.net/?comp=list failed, reason: getaddrinfo ENOTFOUND azprblobstorageiqvia.file.core.windows.net\n    at NodeFetchHttpClient.sendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:124991)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async CoreHttpLogHttpClient.sendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:478986)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:349786)\n    at async StorageClientContext.sendOperationRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:170891)\n    at async ShareServiceClient.listSharesSegment (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:417886)",

[..]

**Comment by JasonYeMSFT** [comment] 2023-04-03 17:06
@brevi77 The error indicates your file share endpoint cannot be resolved by DNS service. You can try manually resolving the endpoint "azprblobstorageiqvia.file.core.windows.net" to see if it gives you anything. If you are using a proxy, if possible, try disabling it to see if that's the cause.

**Comment by JasonYeMSFT** [comment] 2023-05-08 17:41
Closing due to lack of response. Please try the steps we recommended and open a new issue if you still have this problem.

**Closed by JasonYeMSFT** 2023-05-08 17:41 UTC
