### ISSUE TITLE
Unable to import, update or delete any table data using emulator

### ISSUE THREAD

**Issue by lmulligan27** [microsoft/AzureStorageExplorer#5369] opened 2022-01-25 16:28 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Unable to import tables, or edit/ update existing tables

### Steps to Reproduce

Import table (excel table on desktop) under local storage account 

### Actual Experience

N/A

**Comment by MRayermannMSFT** [comment] 2022-01-25 21:47
@lmulligan27 a couple of things:
- We're in the middle of releasing a hotfix for 1.22.0. Can you please try again with that hotfix? You can find it here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.22.1
- Would you be willing to share the full .csv you are trying to import to Azurite? If you do not wish to post it here, we can give you an e maiil address to send it to.

**Comment by lmulligan27** [comment] 2022-01-26 17:49
Thanks for the prompt reply! I tried the updated version no luck unfortunately.
I don't think the data is the issue however as the error is reproduceable with any table. 
In addition I could not update any data in an existing table. However I downloaded version the previous version before 1.22.0 and it worked. 
Thanks for your help!

**Comment by craxal** [comment] 2022-01-26 18:21
@lmulligan27 We made a few fixes for importing and exporting in 1.22.1, so it's concerning that it doesn't work for you. How large is the table you are exporting? How large is the file you're importing? What's the general structure of the data in the table (number of properties, data types, characters used, etc.)? Would you be willing to provide a sample CSV file we could try importing?

**Comment by craxal** [comment] 2022-02-03 23:34
@lmulligan27 When you import data into a table, are the target tables empty, or do they have existing entities in them that are also in the CSV file you're importing?

Possibly related to #5387.

**Comment by bojned** [comment] 2022-02-22 16:31
This happens to me as well. Version I have is 1.22.1, and when I try to import CSV file with 30.000+ entries to a table, nothing happens.

I've tried both on existing and new/empty tables and behavior is the same.

**Comment by craxal** [comment] 2022-02-23 18:39
@lmulligan27 @bojned I just noticed this issue mentions importing to a _local_ storage account. I assume that means you are using an emulator. If that's the case, are you using Azurite? If so, this is already a known issue which should be resolved in an Azurite update (see #5299, #5307).

**Comment by bojned** [comment] 2022-02-23 19:23
> @lmulligan27 @bojned I just noticed this issue mentions importing to a _local_ storage account. I assume that means you are using an emulator. If that's the case, are you using Azurite? There are known problems related to Boolean or Int32 data which should be resolved in an Azurite update (see #5299, #5307).

No, I am not using emulated storage, I am facing this issue when uploading to the actual storage account.

**Comment by craxal** [comment] 2022-02-23 19:53
@bojned Since you're not on an emulator, this may be a separate issue. Could you open a new issue and provide:
* All appropriate information, including the platform and app version you're using.
* The error message you're receiving.
* Any relevant logs
* A description of the data you're trying to import or a sample of import data that reproduces the error.

**Comment by EmilAlipiev** [comment] 2022-02-25 01:47
I think the problem is with the data, not the tool. Tool has only problem that not showing exact error message. 
my problem was related to Datime format,
it has to be exactly[ ISO 8601](https://docs.microsoft.com/en-us/rest/api/storageservices/formatting-datetime-values) formatted if you are trying to import Datetime Column. Otherwise this error message is returned.

**Comment by bojned** [comment] 2022-02-25 11:10
> I think the problem is with the data, not the tool. Tool has only problem that not showing exact error message. my problem was related to Datime format, it has to be exactly[ ISO 8601](https://docs.microsoft.com/en-us/rest/api/storageservices/formatting-datetime-values) formatted if you are trying to import Datetime Column. Otherwise this error message is returned.

Not for me I'm afraid, as even data exported using this tool is misbehaving. I've opened a new issue here:
https://github.com/microsoft/AzureStorageExplorer/issues/5469

**Comment by EmilAlipiev** [comment] 2022-02-25 13:15
@bojned  have you tried "try and fail"? i have tried like this
- leave only 1 row and try to import, if it fails, remove each column 1 by 1 to see if any of the column causing the issue. At least you may know what is the root of the issue

**Comment by craxal** [comment] 2022-03-22 22:57
@lmulligan27 @bojned @EmilAlipiev We released version 1.23.0 not too long ago. Do you still experience issues with that version?

**Comment by bojned** [comment] 2022-04-04 10:57
> @lmulligan27 @bojned @EmilAlipiev We released version 1.23.0 not too long ago. Do you still experience issues with that version?

Hi, my apologies for not coming back sooner on this issue, as I was preoccupied with other things. 

I am still facing this import problem even with version 1.23. Version 1.21.3 works ok and I will continue to use it. 

Unfortunately, I cannot share my data due to sensitivity of the information stored there, but I would gladly show you examples if you want to directly get in touch with me.

**Comment by craxal** [comment] 2022-04-04 21:24
@bojned Are you using an emulator? If so, which one and what version? Have you tried updating to the latest?

If you are not using an emulator, please open a separate issue, as this issue is concerned with importing to an emulator table.

**Comment by craxal** [comment] 2022-04-13 23:16
Everyone, we just put out a new version, 1.23.1, which contains more table fixes. Please update to this version and try again. If you're still having problems, please open a new issue.

**Comment by craxal** [comment] 2022-06-10 21:36
Closing due to lack of further activity.

**Closed by craxal** 2022-06-10 21:36 UTC
Labels: :grey_question: more info, :gear: tables, :gear: emulator
