### ISSUE TITLE
Set content-type to text-javascript for JavaScript files

### ISSUE THREAD

**Issue by curia-damiano** [microsoft/AzureStorageExplorer#2789] opened 2020-04-03 09:41 UTC
**Is your feature request related to a problem? Please describe.**
It's very frustrating publishing static websites to Azure Storage, because after uploading the files, I must manually update all content-types for JavaScript files

**Describe the solution you'd like**
The content-type is set up accordingly, like for other file types

**Describe alternatives you've considered**
Manual work...

**Additional context**
Nothing

**Comment by JasonYeMSFT** [comment] 2020-04-06 19:22
Duplicate of #2267. The original issue contains the instructions to tell AzCopy what content type to set for each file extension. By the way, we have been aware of the fact multiple users have reported the similar issues against the content-type of javascript/json files. We are prioritizing it with the AzCopy team and considering giving these files default content types.

**Closed by JasonYeMSFT** 2020-04-06 19:22 UTC

**Comment by curia-damiano** [comment] 2020-04-07 07:22
Yes please!
Also it would be nice if you could make it evident in the Storage Explorer UI, at least give instructions to customize these content types (even for not common content-types, but this is what happens in my case too: I have other file types, other than the JavaScript files)
