### ISSUE TITLE
Showing the Properties of a Blob does not display it's ContentMD5 value

### ISSUE THREAD

**Issue by Shidell** [microsoft/AzureStorageExplorer#6098] opened 2022-09-15 22:46 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Regression From

It was working previously, I don't know when it stopped working

### Architecture

x64

### Storage Explorer Build Number

20220809.7

### Platform

Windows

### OS Version

Windows 11 10.0.22000.978

### Bug Description

When viewing the Properties of a Blob, the **ContentMD5** field is empty, when I expect it to show the MD5 hash of the selected blob as a Base64 string.

### Steps to Reproduce

1. View any blob's Properties and inspect the **ContentMD5** field.

### Actual Experience

The **ContentMD5** field is not being populated when inspecting a blob's Properties.

### Expected Experience

The **ContentMD5** field should be populated when inspecting a blob's Properties.

### Additional Context

Recently I started having problems where blob(s) I'm working with appear to not have a ContentMD5 Property. Upon troubleshooting, I discovered that I could upload a new blob via ASE, inspect it's Properties, and the ContentMD5 field is empty. 

Inspecting the same blob via the Azure web portal (Chrome), viewing it's Properties displays it's ContentMD5 field as expected (as a Base64 string.)

Using The Azure SDK v12 (C#), accessing the same blob's Properties as a BlobClient or BlobItem will also produce the correct MD5 Hash (as a Byte array.)

**I suspect that, somehow, an earlier build of ASE was not preserving the Content-MD5 Hash of (some?) blobs uploaded with it.** I suspect this because I have a limited selection of blobs in our environment that were uploaded manually with (recent, but out of date) versions of ASE, and there is no Content-MD5 hash present. I'm not sure what to attest this to, as I expected the Azure service to populate the Content-MD5 field automatically when blobs are pushed up (unless pushed as block(s)), which is the only explanation I can come up with as to how ASE might've pushed some blob(s) and never received a Content-MD5 hash for them.

The latest version of ASE does not appear to "prevent" or stop an uploaded blob from receiving a ContentMD5 hash, but it does not display the ContentMD5 hash as the Azure web portal (or C# SDK) do.

**EDIT:** It also appears that editing (adding or deleting) metadata using ASE will cause some Properties to be cleared on the Azure service; ContentType and ContentMD5 being two that I can confirm are lost.

Finally, is it expected behavior that uploading a blob and replacing an existing blob with it does not cause the Azure service to auto-generate an MD5? For example, if I upload a blob via the web or Azure SDK, the Azure service automatically generates and stores the Content-MD5 hash—but if you overwite an existing blob, it appears to clear the Content-MD5 and does not update it. Is that expected?

**Comment by JasonYeMSFT** [comment] 2022-09-19 17:18
@Shidell We use AzCopy for the blob upload. It **should** compute and set the Content-MD5 on the blobs we uploaded. Do you have system proxy enabled? We discovered a bug recently where some of the headers aren't parsed correctly because of their casing and as a result we may fail to show some properties. If you do, you can try disabling it and see if you can then get all the property values of your blob.

**Comment by Shidell** [comment] 2022-09-19 19:01
@JasonYeMSFT Thanks, I reviewed my settings, and do in fact have System Proxy enabled. I disabled it ("Do not use proxy"), and it fixed the issues I reported above.

I ran some additional tests to confirm, with "Use system proxy (preview)" enabled:

1. Upload a text file (.txt) to a blob container via ASE 1.25.1
2. View Properties via ASE, no ContentType nor ContentMD5
3. View Properties via Chrome, Content-Type is present ("text/plain") as is Content-MD5

4. Add Metadata to text file via ASE, Key="a", Value="b"
5. View Properties in ASE, no ContentType nor ContentMD5
6. View Properties in Chrome, Content-Type is empty, Content-MD5 is also empty (Deleted!)

7. Re-upload text file via ASE, replacing existing file
2. View Properties via ASE, no ContentType nor ContentMD5
3. View Properties via Chrome, Content-Type is present ("text/plain") as is Content-MD5

I then deleted the blob, set Proxy to "Do not use proxy", and repeated the above tests, and ASE reported the correct information (and did not delete Properties!) as it appeared to whilst using the System Proxy preview—so it appears the HTTP header issue you mentioned is also somehow clearing the ContentType and ContentMD5 Properties.

**Comment by JasonYeMSFT** [comment] 2022-09-20 00:01
@Shidell Thanks for verifying this for us. I can reproduce the same bug on my end. We have already merged a fix for this issue and it will be released soon in 1.26.0.

**Comment by MRayermannMSFT** [comment] 2022-09-21 17:28
Yes, the fix we checked in does address this issue.

**Closed** 2022-09-22 17:27 UTC
Labels: :heavy_check_mark: merged
