### ISSUE TITLE
Unable to Export data to csv in Azure Storage Explorer

### ISSUE THREAD

**Issue by praveenbontala** [microsoft/AzureStorageExplorer#5332] opened 2022-01-14 07:57 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Regression From

1.18

### Architecture

x64

### Storage Explorer Build Number

20211211.10

### Platform

Windows

### OS Version

Windows 10 Enterprise

### Bug Description

When trying to export data to csv from Azure storage table for queried entities i have observed it is exporting all data but not the result of queried entities and some columns missing in exported data. Also it is taking so much time to give the report.
All these issues observed after i have upgraded my azure storage explorer to new latest version.

### Steps to Reproduce

1. Launch Azure Storage Explorer
2. Expand storage accounts and .
3. Select the storage account and expand tables.
4.  Select the table and on Query builder select Fields and values to filter data.
5. Click on Execute Query(F5) and results are displayed.
6. Click on Export to generate the report in CSV.
7. Open the CSV and verify that Timestamp column is not present in the report and also some other columns are missing.
8. Verify that the CSV does not gets the Queried report instead gets the full data in storage table.

### Actual Experience

It is taking so much time to generate the report and also generated report does not gets queried results, missing Columns in the report. Experience is very bad and with older version we were able to get correct data, after upgrading to new version new issues appeared.

### Expected Experience

When Exporting data on Queried results we need to get only Queried data no all the data and no columns should be missing in exported data. 
When a new version is released it should not include new bugs and enough testing should be done on performance of the product. UI improvements does not be necessary but the performance of the product should be taken care on high priority.

**Comment by craxal** [comment] 2022-01-14 19:29
@praveenbontala This is a known issue and has been addressed. A fix will be out in the next release.

Duplicate of #5320.

**Closed by craxal** 2022-01-14 19:29 UTC
