### ISSUE TITLE
An error occurs when removing one account from which added via Azure and Custom environment with MSAL enabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3247] opened 2020-07-16 08:39 UTC
**Storage Explorer Version:** 1.14.2
**Build**: 20200715.2
**Branch**: hotfix/1.14.2
**Platform/OS:** Windows 10/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer (Make sure setting 'MSAL' is applied).
2. Sign in with one azure account via Azure environment.
3. Sign in with the same account via Custom environment (ARM endpoint: https://management.azure.com).
4. Remove one account -> Check the result.

**Expect Experience:**
Succeed to remove the selected account.
 
**Actual Experience:**
1. The two accounts are removed.
2. An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/87642791-93eee300-c77c-11ea-94b8-a1908f481a57.png)

**More Info:**
1. This issue doesn't reproduce when the MSAL is disabled.
2. Similar bug: [3175](https://github.com/microsoft/AzureStorageExplorer/issues/3175), [2746](https://github.com/microsoft/AzureStorageExplorer/issues/2746)
3. On Linux, the two accounts are removed & no error dialog pops up.

**Comment by MRayermannMSFT** [comment] 2020-10-21 17:16
Fix merged into main. @v-xianya please confirm this bug was fixed. Thanks!

**Comment by v-xianya** [comment] 2020-10-22 03:14
@MRayermannMSFT Verified this issue on build main/20201022.3. Reproduce.

The current behaviors: 
1. The two accounts are removed when trying to remove one account.
2. No error dialog pops up.

**Comment by MRayermannMSFT** [comment] 2020-10-22 17:05
@v-xianya I've been told for now that in this specific case, the removing of both accounts is expected. To the auth library we are using, the accounts are identical due to the fact they are the same user from public azure. If you'd like to keep testing this scenario you could try:

- sign in with two accounts from different Azure environments (e.g. public Azure and Azure China)
- sign in with an account from public Azure, create a custom environment using https://management.azure.com/ and sign in with a **different** account

If you find issues with those, please open a new bug and specify if the unexpected behavior and if there were any error dialogs. The goal for me with this issue was to get rid of the error.

**Closed by MRayermannMSFT** 2020-10-22 17:05 UTC
Labels: :gear: sign-in, :heavy_check_mark: merged, 🧪 testing
