### ISSUE TITLE
Explore ADLS Gen2 Container Auth and Access with Deep link

### ISSUE THREAD

**Issue by TaquiM** [microsoft/AzureStorageExplorer#4477] opened 2021-05-20 06:18 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

We need to share the newly create containers with other teams, this require users to login twice first Subscription then ADLS Gen 2 container. For non-technical team this difficult auth flow.

### Desired Solution

Need to access storage explorer like direct link with only one auth.

### Alternatives and Workarounds

None

### Additional Context

None

**Comment by MRayermannMSFT** [comment] 2021-05-24 17:05
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/4459

**Closed by MRayermannMSFT** 2021-05-24 17:05 UTC
Labels: :white_check_mark: duplicate
