### ISSUE TITLE
Error copying managed disk, large disk, (access token expiry)

### ISSUE THREAD

**Issue by marckean** [microsoft/AzureStorageExplorer#2048] opened 2019-10-11 02:17 UTC
Storage Explorer was unable to revoke access to a disk.
The disks involved in this operation may still be in an 'Active SAS' state. You may need to return the disks to an 'Unattached' state before retrying this operation, or before performing new operations on the disks.

```json
{
  "name": "Error",
  "message": "The access token expiry UTC time '10/11/2019 1:31:23 AM' is earlier than current UTC time '10/11/2019 2:09:17 AM'.",
  "stack": "Error: The access token expiry UTC time '10/11/2019 1:31:23 AM' is earlier than current UTC time '10/11/2019 2:09:17 AM'.\n    at new RestError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:2400:28)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:3544:37\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
  "code": "ExpiredAuthenticationToken",
  "statusCode": 401,
  "request": {
    "streamResponseBody": false,
    "url": "https://management.azure.com/subscriptions/6bb00255-5486-4db1-96ca-5baefc18b0b2/resourceGroups/Hyper-V-2016/providers/Microsoft.Compute/disks/Hyper-V-2016_DataDisk_0/endGetAccess?api-version=2019-03-01",
    "method": "POST",
    "headers": {
      "_headersMap": {
        "content-type": {
          "name": "content-type",
          "value": "application/json; charset=utf-8"
        },
        "accept-language": {
          "name": "accept-language",
          "value": "en-US"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "713934a9-6e84-4253-87a0-60071cb416c7"
        },
        "user-agent": {
          "name": "user-agent",
          "value": "@azure/arm-compute/11.0.0 ms-rest-azure-js/2.0.1 ms-rest-js/2.0.4 Node/v10.11.0 OS/(ia32-Windows_NT-10.0.14393)"
        },
        "cookie": {
          "name": "cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "operationSpec": {
      ...
    }
  }
}

**Comment by blozza** [comment] 2019-10-15 11:18
hi, did you find a solution, I'm having the same issue with a large disk?

Ta

**Comment by marckean** [comment] 2019-10-16 03:33
No, I am having the same issue again today, I'm using a 32GB disk (not large at all), using AzCopy to copy the disk from within a VM in Azure, same region, so it should be the fastest internet for the copy process, however I get the same error - ExpiredAuthenticationToken

**Comment by MRayermannMSFT** [comment] 2019-10-16 16:25
Hey y'all, I believe I have an understanding for what the root cause of this issue is. What I'd like to do is write up a fix, and then if y'all are willing, have y'all insert the fix to your own machine. That way we can confirm that things are working both on my end and yours'.

**Comment by blozza** [comment] 2019-10-16 16:56
Sure, I’d be happy to give it a test for you.

**Comment by MRayermannMSFT** [comment] 2019-10-16 21:45
Ok so here's a fix you can insert: 
[DiskCopy.zip](https://github.com/microsoft/AzureStorageExplorer/files/3736511/DiskCopy.zip)

That zip contains a folder called `DiskCopy`. Take that folder and put it/replace the existing one at at `C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\se-managed-disks-extension\dist\src\StateMachines`. A couple notes to read before you do that though:

- If you installed in a non standard location, you will need to translate my path to your location. Let me know if you need help with that.
- Before moving the `DiskCopy` folder from the zip to that location, I recommend renaming the existing `DiskCopy` folder to something like `DiskCopy_original`, just in case this doesn't work out and you want to quickly switch back to the original code.
- Although I believe there is nothing in my modification that could cause a bad thing to happen (now we're getting a fresh auth token for every API call), I recommend exercising caution while using it. I just made the change this morning, and it hasn't gone through any extended testing.

Anyway, good luck! Let me know if it fixes things (my fingers are crossed). 😀

**Comment by marckean** [comment] 2019-10-16 23:35
Thanks, testing it now. One thing to add to the above, I watched it several times yesterday, the copy of the disk managess to get to 100%, the folder where the disk is copying to I can see the disk there, however, at the 100% mark, the disk magically disappears from the folder, then seconds later Azure Storage Exporer reports a failed download.

**Comment by marckean** [comment] 2019-10-17 00:28
Same thing, it failed at the very end, got to 100%, but then the freshly downloaded file disappeared: 

AzCopy failed to complete the transfer.

AzCopy error message: Transfer of https://md-ssd-qzgld31wfvd5.blob.core.windows.net/rsqqlm2vfxr0/abcd to D:/nVidia-02_OsDisk_1_c8ee171ef3ff40da856c6a8e3d522516.vhd failed: Status: Failed, Error code: 0

AzCopy log file can be found at C:\Users\marc.kean.DXC/.azcopy/b118c6ee-072d-874c-65b5-fc07938605dd.log   

Link to the log file is here https://msmarcsg.blob.core.windows.net/mess/b118c6ee-072d-874c-65b5-fc07938605dd.log

**Comment by MRayermannMSFT** [comment] 2019-10-17 20:58
Hey @marckean , first, thank you for sharing the log!!!! It's so refreshing to have someone just share it right off the bat. You have truly made my day (not sarcasm, truly 110% serious). 😎

Anyway it looks like AzCopy's MD5 verification failed. Basically this means that the AzCopy thinks the file was corrupted during transit or at some other time. Since this is a managed disk, I'm not sure how to look into the MD5 hash being wrong/that is definitely concerning. For the purposes of getting your download to finish though, we currently don't expose a way to disable that, but I can walk you through editing the code to disable it. Here's what you can do:

1. Run a text editor as admin (if you use VS Code, you can run it as normal, though you'll be prompted later when you try to save the file
2. Go to where you coped the patch folder and then look for/open the file `DiskCopy/States/StartAzCopyState.js`
3. Add `checkMd5: "NoCheck"` below line 36, and a comma at the end of line 36:
![image](https://user-images.githubusercontent.com/21112697/67046752-bb2d5c80-f0e5-11e9-995f-4bf9ff801f74.png)
4. Save the file. If you're using VS Code, you'll be prompted to save as admin.: 
![image](https://user-images.githubusercontent.com/21112697/67046791-cd0eff80-f0e5-11e9-8510-6a049b5ce882.png)
If you aren't using VS code, then it should just save (assuming you ran the editor as admin)
5. Try the download again

**Comment by MRayermannMSFT** [comment] 2019-10-25 17:16
Another person in #2128 reported that this fix worked. I'm going to ahead and close this. The fix will officially ship in 1.11.0.

**Closed by MRayermannMSFT** 2019-10-25 17:16 UTC
Labels: :beetle: bug, :gear: disks, :heavy_check_mark: merged
