### ISSUE TITLE
Search not working, when you have multiple pages and have a file that start with G, search does not find any files with G, you need to go to the pages that have files beginning with G to find the file

### ISSUE THREAD

**Issue by DiptiChauhan** [microsoft/AzureStorageExplorer#3700] opened 2020-10-21 11:41 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JasonYeMSFT** [comment] 2020-10-21 17:01
Closed since this is a duplicate of #3699

**Closed by JasonYeMSFT** 2020-10-21 17:01 UTC
Labels: :heavy_check_mark: duplicate
