### ISSUE TITLE
Unable to load blob containers from Emulator - after upgrade to latest version

### ISSUE THREAD

**Issue by robinstauntoncollins** [microsoft/AzureStorageExplorer#6043] opened 2022-08-22 12:15 UTC
## Preflight Checklist
 
- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X]  I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

## Storage Explorer Version
1.25.1

## Regression From
No response

## Architecture
x64

## Storage Explorer Build Number
20220809.7

## Platform
Windows

## OS Version
Windows 10

## Bug Description
Attempting to load blob containers from Storage Emulator results in error. Loading storage queues is successful. Can create new (previously not created) containers but after refreshing they disappear. They do exist because attempting to create a new container with the same name as an existing container fails with message:
```
Failed to create blob container 'testcontainer': The specified container already exists.
RequestId:add098d9-a848-4825-af7d-04195793ab1e
Time:2022-08-22T12:23:59.4860113Z
```

However the existing containers with names like: `incontainer`, `outcontainer` and `testcontainer` cannot be displayed in the list. These are the only containers within the emulator and they should match the naming requirements.

## Details:
```
{
  "name": "RestError",
  "message": "The specifed resource name contains invalid characters.\nRequestId:85606b01-2b74-4c47-9486-dd07d81bb340\nTime:2022-08-22T12:00:14.6254668Z",
  "stack": "RestError: The specifed resource name contains invalid characters.\nRequestId:85606b01-2b74-4c47-9486-dd07d81bb340\nTime:2022-08-22T12:00:14.6254668Z\n    at handleErrorResponse 
   ...
  "code": "InvalidResourceName",
  "statusCode": 400,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "http://127.0.0.1:10000/devstoreaccount1/%24blobchangefeed?restype=container",
    "method": "GET",
      ...
  "details": {
    "errorCode": "InvalidResourceName",
    "Content-Length": "243",
    "Content-Type": "application/xml",
    "Server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "85606b01-2b74-4c47-9486-dd07d81bb340",
    "x-ms-version": "2019-07-07",
    "Date": "Mon, 22 Aug 2022 12:00:14 GMT",
    "message": "The specifed resource name contains invalid characters.\nRequestId:85606b01-2b74-4c47-9486-dd07d81bb340\nTime:2022-08-22T12:00:14.6254668Z",
    "code": "InvalidResourceName"
  }
}
```

## Steps to Reproduce
Upgrade to 1.25.1 - attempt to connect to running Storage Emulator and display the list of Blob containers

## Actual Experience
<img width="594" alt="AttemptingToRefreshCausesError" src="https://user-images.githubusercontent.com/25299948/185921049-7bf3a1aa-8c6d-47f1-996b-d59d44342d4f.PNG">

Attempting to connect manually to Storage Emulator using normal flow results in same issue.

## Expected Experience
The list of containers are displayed in Storage Explorer for the Storage Emulator
## Additional Context
No response

**Comment by robinstauntoncollins** [comment] 2022-08-22 12:43
After a quick look, appears to be same issue as #6030

**Comment by robinstauntoncollins** [comment] 2022-08-22 13:12
Issue doesn't seem to appear with Azurite but with only Storage Emulator

**Comment by MRayermannMSFT** [comment] 2022-08-22 17:13
Closing as dupe of #6030. Thanks for including all the extra helpful on this issue by the way. Makes a big difference when we know an issue is specific to emulator vs live Azure.

**Closed by MRayermannMSFT** 2022-08-22 17:13 UTC
