### ISSUE TITLE
Display duplicate folder name in the display name of one blob directory that attached via OAuth

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8053] opened 2024-07-11 06:44 UTC
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240711.2
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.34.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one folder.
3. Attach the folder via OAuth -> Go to the attached folder -> Observe the display name.
4. Check whether no duplicate folder name.

## Expected Experience ##
No duplicate folder name.

## Actual Experience ##
It contains duplicate folder name.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/59962865-2a87-4467-aacf-dd25308242de)

## Additional Context ##
Below is the screenshot for previous version.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/bed3e5e5-becf-47e3-bca2-4a7d36c39062)

**Comment by richardMSFT** [comment] 2024-07-11 17:47
@v-xianya The path/folder name being in the display name within the parentheses portion is as intended. We recently decided that it would be beneficial to include the path for attached and quick access nodes that open to a directory.

However, I'm not sure why the name of the attached container is also the path. Can you share a video showing attaching the the folder via OAuth? When I do so, the default name for the attached container is just the container name and then a numerical suffix.

**Comment by v-xianya** [comment] 2024-07-12 02:13
@richardMSFT Sorry to not point out that we attached the directory by using 'Copy Direct Link' action.
![0712](https://github.com/user-attachments/assets/05bb222f-9870-4a56-9dda-01522687f6fb)

**Comment by richardMSFT** [comment] 2024-09-19 19:49
Closing this issue because having the path in the display status is by designl

**Closed by richardMSFT** 2024-09-19 19:49 UTC
Labels: 🧪 testing, :gear: blobs, :white_check_mark: by design, :beetle: regression, :gear: adls gen2
