### ISSUE TITLE
Edits to Blob Shared Access Policy expiry date does not save

### ISSUE THREAD

**Issue by georgestevens99** [microsoft/AzureStorageExplorer#161] opened 2018-05-09 17:14 UTC
**Storage Explorer Version**:  1.0.0

**Platform**: Windows

**Architecture**: ia32

**Build Number**: 20180415.2

**Commit**: 5d603051

**Regression From**: Don't know.

#### Steps to Reproduce: ####

1. 
2. 
Create a blob container and a shared access policy programatically, having start and expiry dates and times.
Log into Storage explorer and open the container. Click Shared Access Policies and edit the above Shared Access policy.  Set the exiry time to a later time.  SAVE.

Look in the portal at the Shared Access Policy or access it programatically and you will find that the changes made in the storage explorer are not persisted.  This happens even when pressing the storage explorer refresh button numerous times.

#### Expected Experience: ####

When I edit something and press save I expect it to be saved promptly.

#### Actual Experience: ####

Edits are not saved.

**Comment by MRayermannMSFT** [comment] 2018-05-10 16:40
Hi @georgestevens99 , thank you for the bug report! This bug was recently fixed in version 1.1.0. Please check for updates and download/install 1.1.0 to get the latest version.

Duplicate of: #50

**Closed by MRayermannMSFT** 2018-05-10 16:40 UTC
Labels: :white_check_mark: duplicate
