### ISSUE TITLE
Storage explorer throws error when opening - can't enumerate child objects

### ISSUE THREAD

**Issue by jasonmoye** [microsoft/AzureStorageExplorer#4044] opened 2021-02-02 20:11 UTC
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201211.10
**Platform/OS**: windows 10
**Architecture**: 
**Regression From**:  It was working in the same version

## Bug Description ##
Unable to retrieve child resources.

Details:
{
  "name": "Error",
  "message": "connect ENOENT \\\\?\\pipe\\8d5810bb5e834685940a951322658045",
  "__zone_symbol__error": {
    "originalStack": "Error: connect ENOENT \\\\?\\pipe\\8d5810bb5e834685940a951322658045",
    "zoneAwareStack": "Error: connect ENOENT \\\\?\\pipe\\8d5810bb5e834685940a951322658045"
  },
  "stack": "Error: connect ENOENT \\\\?\\pipe\\8d5810bb5e834685940a951322658045",
  "originalStack": "Error: connect ENOENT \\\\?\\pipe\\8d5810bb5e834685940a951322658045",
  "zoneAwareStack": "Error: connect ENOENT \\\\?\\pipe\\8d5810bb5e834685940a951322658045",
  "__zone_symbol__stack": "Error: connect ENOENT \\\\?\\pipe\\8d5810bb5e834685940a951322658045",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "connect ENOENT \\\\?\\pipe\\8d5810bb5e834685940a951322658045",
  "__zone_symbol__originalStack": "Error: connect ENOENT \\\\?\\pipe\\8d5810bb5e834685940a951322658045",
  "__zone_symbol__zoneAwareStack": "Error: connect ENOENT \\\\?\\pipe\\8d5810bb5e834685940a951322658045",
  "errno": "ENOENT",
  "code": "ENOENT",
  "syscall": "connect",
  "address": "\\\\?\\pipe\\8d5810bb5e834685940a951322658045"
}

## Steps to Reproduce ##
Open ASE

## Expected Experience ##
It reads child nodes

## Actual Experience ##
throws the above error

**Comment by ruffCode** [comment] 2021-02-02 22:32
I was having the same issue a few hours ago, just restarted the app and everything is working as expected. I'm attaching the bug report just in case it can be helpful.

**Storage Explorer Version**: 1.17.0
**Build Number**: 20201211.10
**Platform/OS**: Linux
**Architecture**:  x64

## Bug Description ##
`Unable to retrieve child resources.

Details:
{
  "name": "Error",
  "message": "Hub Controller process exited prematurely with signal 'SIGABRT'.",
  "__zone_symbol__error": {
    "originalStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/snap/storage-explorer/19/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
    "zoneAwareStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/snap/storage-explorer/19/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)"
  },
  "stack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at ControllerConnection.onControllerProcessExited (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)\nFrom previous event:\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at defer (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:582:19)\n    at Promise.then (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:828:20)\n    at ControllerConnection.connectImpl (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:48:14)\n    at Function.ControllerConnection.connect (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:31:27)\n    at HubLookup.getLocationService (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/hubLookup.js:20:80)\n    at HubClient.requestServiceWithRetries (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/hubClient.js:74:21)\n    at /snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/hubClient.js:94:54\n    at _fulfilled (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:834:54)\n    at /snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:863:30\n    at Promise.promise.promiseDispatch (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:796:13)\n    at /snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:604:44\n    at runSingle (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:137:13)\n    at flush (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:125:13)",
  "originalStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/snap/storage-explorer/19/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
  "zoneAwareStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/snap/storage-explorer/19/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
  "__zone_symbol__stack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at ControllerConnection.onControllerProcessExited (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)\nFrom previous event:\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at defer (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:582:19)\n    at Promise.then (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:828:20)\n    at ControllerConnection.connectImpl (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:48:14)\n    at Function.ControllerConnection.connect (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:31:27)\n    at HubLookup.getLocationService (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/hubLookup.js:20:80)\n    at HubClient.requestServiceWithRetries (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/hubClient.js:74:21)\n    at /snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/hubClient.js:94:54\n    at _fulfilled (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:834:54)\n    at /snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:863:30\n    at Promise.promise.promiseDispatch (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:796:13)\n    at /snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:604:44\n    at runSingle (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:137:13)\n    at flush (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:125:13)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "Hub Controller process exited prematurely with signal 'SIGABRT'.",
  "__zone_symbol__originalStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/snap/storage-explorer/19/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
  "__zone_symbol__zoneAwareStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/snap/storage-explorer/19/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/snap/storage-explorer/19/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/snap/storage-explorer/19/resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
  "signal": "SIGABRT"
}`

**Comment by jasonmoye** [comment] 2021-02-02 22:34
I did the same thing and it is working now. Thanks!

**Comment by MRayermannMSFT** [comment] 2021-02-08 18:12
Can all of y'all do the following:
1. Start Storage Explorer
2. Go to settings (gear on the left) -> Application -> Sign-In and enable Verbose Authentication Logging
3. Close Storage Explorer
4. Delete everything in `C:\Users\username\AppData\Local\Temp\servicehub\logs` directory
5. Start Storage Explorer
6. Reproduce the your issue your facing/get to the point you see an error
7. Close Storage Explorer
8. Zip up the contents of `C:\Users\username\AppData\Local\Temp\servicehub\logs` and then attach that zip to this issue

(**Some files in the log dir might have your email address or other PII, if you don't want that out in the open, then either check the files and redact it, or let me know that you'd rather share the zip another way and we can figure something out**)

**Comment by MRayermannMSFT** [comment] 2021-04-26 17:10
Closing due to lack of reply. Please open a new issue if you are still encountering this problem.

**Closed by MRayermannMSFT** 2021-04-26 17:10 UTC
Labels: servicehub
