### ISSUE TITLE
Explorer - Hide or Unhide Subscriptions

### ISSUE THREAD

**Issue by InathiM** [microsoft/AzureStorageExplorer#6742] opened 2023-04-04 18:49 UTC
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I am unable to hide or unhide subscriptions in the explore pane

### Desired Solution

I would like to have support to hide or unhide list of subscriptions I've connected to on my storage explorer

**Comment by JasonYeMSFT** [comment] 2023-04-06 21:05
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/5774. It will be available in 1.29.0

**Closed** 2023-04-06 21:05 UTC
Labels: :heavy_check_mark: duplicate
