### ISSUE TITLE
Changing container Access Policies sets Public Access Level to "Private"

### ISSUE THREAD

**Issue by dagood** [Microsoft/AzureStorageExplorer#317] opened 2018-06-18 21:34 UTC
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: Unknown (I have not used this feature before)
Build Number: 20180605.1
Commit: f8373d5a

#### Steps to Reproduce: ####
1. Set up a storage account with a blob container at "Public read access for blobs only" access.
   * "Public read access for containers and blobs" also reproduces the bug.
2. Right click on the container => 'Manage Access Policies...'
3. Add or modify an access policy.
   * For example, extend an expiration date.
4. Click 'Save'

#### Expected Experience: ####
The access policy is changed, and nothing else is changed about the container.

#### Actual Experience: ####
The access policy is changed, **and the container public access level is set to 'private'.**
 * There is no indication in the UI that this change will happen.
 * In the Azure Portal, you can change access policies without changing the public access level, suggesting the change is incorrect (even if the UI did tell me about it).
 * Note: in ASE you have to refresh the node to see the Public Access Policy change, perhaps sharing a root cause with https://github.com/Microsoft/AzureStorageExplorer/issues/214.

**Comment by craxal** [comment] 2018-06-19 16:03
Duplicate of #197.

**Closed by craxal** 2018-06-19 16:03 UTC

**Comment by dagood** [comment] 2018-06-19 16:19
Thanks, didn't see that.
