### ISSUE TITLE
Add option to uncompress GZIP encoded content during download

### ISSUE THREAD

**Issue by icnatejackson** [microsoft/AzureStorageExplorer#758] opened 2018-10-12 11:10 UTC
**Storage Explorer Version**: 1.4.3
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: possibly new feature request

#### Steps to Reproduce: ####
1. Place a BLOB in BLOB storage that is gzip compressed
2. Ensure that the content-encoding property on the BLOB says gzip

#### Expected Experience: ####
When I download gzip content encoded content, I'd like to be given the option to automatically gzip uncompress the payload before writing the file to local disk.

#### Actual Experience: ####
There are no such options available to uncompress encoded BLOB content.

**Comment by MRayermannMSFT** [comment] 2018-10-12 19:21
@icnatejackson , if there was the ability for you to extend download (e.g., write an extension for Storage Explorer) that allowed you to add this behavior, would you be interested in writing it?

**Comment by MRayermannMSFT** [comment] 2020-02-03 19:01
Closing due to lack of reply. Please open a new issue if you still have problems.

**Comment by nbevans** [comment] 2020-03-18 12:55
Really need this feature. `Content-Encoding` using things like `gzip`, `br`, `deflate` etc is a pretty common way to store things in blob storage. It seems there are no tools (Az Storage Explorer included) that actually support decompressing things on the fly during download. I also tried the CloudBerry tool - nope.

Moreover, I think this should be standard functionality - not an extension. Building out an ability to write extensions for the tool seems like a massive effort and over-complication for what is actually quite a small and innocuous feature request. We will probably be waiting months or years for it.

All it needs is to support some basic common compression algos like gzip, br, deflate. Then change the Download toolbar button into the drop-down kind (like the Undelete toolbar button) with a menu option called "Download and honour content encoding".

**Comment by MRayermannMSFT** [comment] 2020-04-14 23:49
Closing as dupe of #2359 

Apparently AzCopy already has an option to do this. We'll expose turning that option on in 1.14!

**Closed by MRayermannMSFT** 2020-04-14 23:49 UTC
Labels: :bulb: feature request
