### ISSUE TITLE
Labels in Properties dialog are inconsistent with platform terminology

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2853] opened 2020-04-21 05:58 UTC
**Storage Explorer Version:** 1.13.0
**Build:** [20200418.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3654085&view=results)
**Branch:** rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.12.0)

**Steps to reproduce:**
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create one blob container -> Upload one blob.
3. Right click the blob -> Select 'Properties...' -> Check the properties dialog.

**Expect Experience:**
The properties dialog shows like below;
![image](https://user-images.githubusercontent.com/41351993/79830088-45c58000-83d7-11ea-87b5-1ebfd43d9ec2.png)

**Actual Experience:**
The properties dialog shows like below:
![image](https://user-images.githubusercontent.com/41351993/79830079-40683580-83d7-11ea-837f-6126d36474b2.png)

**Comment by craxal** [comment] 2020-04-21 19:27
This is by design. HNS enabled accounts use the same strings, so this was likely changed to make the two consistent. We may want to change the strings back, but in any case, this is not a regression.

**Comment by jinglouMSFT** [comment] 2020-04-21 20:57
Labels should be consistent to the APIs as Matthew said below:

"The API specifically refers to the key value pairs in the bottom as metadata and the top as properties (granted, we add on some of our own properties, but minus those). 

https://docs.microsoft.com/en-us/rest/api/storageservices/setting-and-retrieving-properties-and-metadata-for-blob-resources

I think we should go with their naming scheme."

**Comment by MRayermannMSFT** [comment] 2020-05-20 01:12
Fix merged into master.

**Comment by v-xianya** [comment] 2020-05-20 03:34
Verified on build master/[20200520.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3742543&view=results). Reproduce. So re-open it.

**Comment by MRayermannMSFT** [comment] 2020-05-20 16:39
Please verify against build 20200520.5 or later.

**Comment by v-xianya** [comment] 2020-05-21 01:56
Hi @MRayermannMSFT Verified on build master/[20200521.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3746638&view=results).The current properties dialog as below.
![image](https://user-images.githubusercontent.com/41351993/82514862-62c1b000-9b49-11ea-91e8-4ad4ef10e208.png)

**Comment by v-xianya** [comment] 2020-05-29 02:26
Hi @MRayermannMSFT 
Re-open this issue just in case we miss it.😉

**Comment by craxal** [comment] 2020-05-29 17:49
@v-xianya I'm closing this issue again until it can be reproduced. Only reopen the bug if you've definitely reproduced and we need to take a look.

**Closed by craxal** 2020-05-29 17:49 UTC
Labels: :gear: blobs, :heavy_check_mark: merged, 🧪 testing
