### ISSUE TITLE
File filter / search

### ISSUE THREAD

**Issue by JERisBRISK** [microsoft/AzureStorageExplorer#3083] opened 2020-06-05 14:11 UTC
The web Storage Explorer (for Gen1 only) provides a way to filter file results at a given directory node. Please (at a minimum) add this feature to the Azure Storage Explorer for both Gen1 AND Gen2 (we're primarily in need of this for Gen2, but you might as well wire it up for both to help people selectively migrate files to and from Gen1).

Even better would be a way to do a recursive search, but for starters, just letting us scope down to just the files we're interested within a given view of a folder would be *hugely* helpful.

**Describe the solution you'd like**
For Gen2 and Gen1, a "Search for files" box similar to the "Search for resources" box. Recursive would be great, but we can start with just filtering the current view.  Allowing for literal string, wildcard match, and regex would be ideal.

**Describe alternatives you've considered**
Writing my own for Gen2.
Just using the web version of the Explorer for Gen1 filtering (it's not perfect, but it's better than nothing).

**Comment by MRayermannMSFT** [comment] 2020-06-08 18:22
@JERisBRISK unfortunately with the APIs available to us today, this is not feasible.

**Comment by MRayermannMSFT** [comment] 2020-06-08 18:23
Duplicate of #1667

**Closed by MRayermannMSFT** 2020-06-08 18:23 UTC
Labels: :bulb: feature request, :heavy_check_mark: duplicate
