### ISSUE TITLE
Show tenant name along with/in place of subscription ID

### ISSUE THREAD

**Issue by LarsKemmann** [microsoft/AzureStorageExplorer#2127] opened 2019-10-24 01:15 UTC
As a consultant, I work with a _lot_ of Azure subscriptions. It becomes very difficult to separate the different subscription names and find the ones I'm actively working with. It would be very helpful if the Manage Accounts view would show the Azure AD tenant names (e.g. "Contoso Ltd.") along with the subscription names and subscription IDs.

**Comment by craxal** [comment] 2019-11-05 21:47
Duplicate of #1326.

**Closed by craxal** 2019-11-05 21:47 UTC
Labels: :bulb: feature request, :heavy_check_mark: duplicate
