### ISSUE TITLE
The upload dialog doesn't pop up when uploading files/folder to a folder whose name is '\' in one blob container

### ISSUE THREAD

**Issue by v-sunnysun** [microsoft/AzureStorageExplorer#5625] opened 2022-04-14 09:05 UTC
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220414.17
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.2.1(MacBook Air M1, 2020)
**Architecture:** ia32\x64
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Click 'New Folder' -> Type '\\' as the folder name -> Click 'OK'.
3. Click 'Upload' -> 'Upload Folder/Files...'.
4. Check whether the upload dialog pops up.

## Expected Experience ##
The upload dialog pops up.

## Actual Experience ##
The upload dialog doesn't pop up.

**Comment by v-xianya** [comment] 2022-04-18 06:40
@JasonYeMSFT 
Verified this issue on the build 20220418.1. This issue is fixed. 
If uploading a blob to the new folder named '\', , there are 10 `<no name>` on the address bar.
**Could you help to take a look?**

Here is the record:
![0418](https://user-images.githubusercontent.com/41351993/163766411-35a706f0-4fa0-40e6-8bbb-4caa634b46dc.gif)

**Comment by JasonYeMSFT** [comment] 2022-04-19 20:53
I created a regression which breaks blob listing, that's why there is endless no name directories. But there is another problem where the blob service interprets the backslash character as a forward slash and puts the blob there. For example, upload to "blob02/\\/file" will result in blob "blob02///file" being created. 

I will make a fix to the listing problem while leaving the \ to / conversion issue open for now. There is nothing we can do since the service converts \ to /.

**Comment by v-xianya** [comment] 2022-04-20 06:11
@JasonYeMSFT The listing problem has been fixed on the new build 20220420.3. We are going to close this issue.

BTW, do we need to log a bug for the mentioned issue 'blob service interprets the backslash character as a forward slash'?

**Closed by v-xianya** 2022-04-20 06:11 UTC
Labels: 🧪 testing, :gear: blobs, :beetle: regression
